#ifndef CLUSAPI_H
#define CLUSAPI_H

#IFDEF LINKFILES
	#dynamiclinkfile Clusapi.dll
#ENDIF

/* Microsoft Cluster Server definitions */

#define CLUSAPI_VERSION  0x0500

#define MAX_CLUSTERNAME_LENGTH  MAX_COMPUTERNAME_LENGTH

#define CLUSTER_VERSION_FLAG_MIXED_MODE  0x00000001

#define NT4_MAJOR_VERSION  1
#define NT4SP4_MAJOR_VERSION  2
#define NT5_MAJOR_VERSION  3

#define CLUSTER_VERSION_UNKNOWN  0xFFFFFFFF

#define CLUSTER_INSTALLED  0x00000001
#define CLUSTER_CONFIGURED  0x00000002
#define CLUSTER_RUNNING  0x00000010

#define CLUSAPI_READ_ACCESS  0x00000001
#define CLUSAPI_CHANGE_ACCESS  0x00000002
#define CLUSAPI_NO_ACCESS  0x00000004
#define CLUSAPI_ALL_ACCESS (CLUSAPI_READ_ACCESS|CLUSAPI_CHANGE_ACCESS)

#define CLUS_ACCESS_ANY  0
#define CLUS_ACCESS_READ  0x01
#define CLUS_ACCESS_WRITE  0x02

#define CLUS_NO_MODIFY  0
#define CLUS_MODIFY  0x01

#define CLUS_NOT_GLOBAL  0
#define CLUS_GLOBAL  0x01

#define CLUSCTL_ACCESS_SHIFT  0
#define CLUSCTL_FUNCTION_SHIFT  2
#define CLCTL_INTERNAL_SHIFT  20
#define CLCTL_USER_SHIFT  21
#define CLCTL_MODIFY_SHIFT  22
#define CLCTL_GLOBAL_SHIFT  23
#define CLUSCTL_OBJECT_SHIFT  24

#define CLCTL_INTERNAL_MASK  (1<<CLCTL_INTERNAL_SHIFT)
#define CLCTL_USER_MASK  (1<<CLCTL_USER_SHIFT)
#define CLCTL_MODIFY_MASK  (1<<CLCTL_MODIFY_SHIFT)
#define CLCTL_GLOBAL_MASK  (1<<CLCTL_GLOBAL_SHIFT)
#define CLUSCTL_CONTROL_CODE_MASK  0x3FFFFF
#define CLUSCTL_OBJECT_MASK  0xFF
#define CLUSCTL_ACCESS_MODE_MASK  0x03

#define CLCTL_CLUSTER_BASE  0
#define CLCTL_USER_BASE  (1<<CLCTL_USER_SHIFT)

OperationalQuorum = 0
ModifyQuorum = 1

CLUSTERVERSIONINFO_NT4 STRUCT
	dwVersionInfoSize DD
	MajorVersion DW
	MinorVersion DW
	BuildNumber DW
	szVendorId DW 64 DUP (?)
	szCSDVersion DW 64 DUP (?)
ENDS

CLUSTERVERSIONINFO STRUCT
	dwVersionInfoSize DD
	MajorVersion DW
	MinorVersion DW
	BuildNumber DW
	szVendorId DW 64 DUP (?)
	szCSDVersion DW 64 DUP (?)
	dwClusterHighestVersion DD
	dwClusterLowestVersion DD
	dwFlags DD
	dwReserved DD
ENDS

CLUS_STARTING_PARAMS STRUCT
	dwSize DD
	bForm DD
	bFirst DD
ENDS

ClusterStateNotInstalled = 0x00000000
ClusterStateNotConfigured = CLUSTER_INSTALLED
ClusterStateNotRunning = CLUSTER_INSTALLED|CLUSTER_CONFIGURED
ClusterStateRunning = CLUSTER_INSTALLED|CLUSTER_CONFIGURED|CLUSTER_RUNNING

CLUSTER_CHANGE_NODE_STATE = 0x00000001
CLUSTER_CHANGE_NODE_DELETED = 0x00000002
CLUSTER_CHANGE_NODE_ADDED = 0x00000004
CLUSTER_CHANGE_NODE_PROPERTY = 0x00000008
CLUSTER_CHANGE_REGISTRY_NAME = 0x00000010
CLUSTER_CHANGE_REGISTRY_ATTRIBUTES = 0x00000020
CLUSTER_CHANGE_REGISTRY_VALUE = 0x00000040
CLUSTER_CHANGE_REGISTRY_SUBTREE = 0x00000080
CLUSTER_CHANGE_RESOURCE_STATE = 0x00000100
CLUSTER_CHANGE_RESOURCE_DELETED = 0x00000200
CLUSTER_CHANGE_RESOURCE_ADDED = 0x00000400
CLUSTER_CHANGE_RESOURCE_PROPERTY = 0x00000800
CLUSTER_CHANGE_GROUP_STATE = 0x00001000
CLUSTER_CHANGE_GROUP_DELETED = 0x00002000
CLUSTER_CHANGE_GROUP_ADDED = 0x00004000
CLUSTER_CHANGE_GROUP_PROPERTY = 0x00008000
CLUSTER_CHANGE_RESOURCE_TYPE_DELETED = 0x00010000
CLUSTER_CHANGE_RESOURCE_TYPE_ADDED = 0x00020000
CLUSTER_CHANGE_RESOURCE_TYPE_PROPERTY = 0x00040000
CLUSTER_CHANGE_NETWORK_STATE = 0x00100000
CLUSTER_CHANGE_NETWORK_DELETED = 0x00200000
CLUSTER_CHANGE_NETWORK_ADDED = 0x00400000
CLUSTER_CHANGE_NETWORK_PROPERTY = 0x00800000
CLUSTER_CHANGE_NETINTERFACE_STATE = 0x01000000
CLUSTER_CHANGE_NETINTERFACE_DELETED = 0x02000000
CLUSTER_CHANGE_NETINTERFACE_ADDED = 0x04000000
CLUSTER_CHANGE_NETINTERFACE_PROPERTY = 0x08000000
CLUSTER_CHANGE_QUORUM_STATE = 0x10000000
CLUSTER_CHANGE_CLUSTER_STATE = 0x20000000
CLUSTER_CHANGE_CLUSTER_PROPERTY = 0x40000000
CLUSTER_CHANGE_HANDLE_CLOSE = 0x80000000
CLUSTER_CHANGE_ALL = (CLUSTER_CHANGE_NODE_STATE|CLUSTER_CHANGE_NODE_DELETED|CLUSTER_CHANGE_NODE_ADDED|CLUSTER_CHANGE_NODE_PROPERTY|CLUSTER_CHANGE_REGISTRY_NAME|CLUSTER_CHANGE_REGISTRY_ATTRIBUTES|CLUSTER_CHANGE_REGISTRY_VALUE|CLUSTER_CHANGE_REGISTRY_SUBTREE|CLUSTER_CHANGE_RESOURCE_STATE|CLUSTER_CHANGE_RESOURCE_DELETED|CLUSTER_CHANGE_RESOURCE_ADDED|CLUSTER_CHANGE_RESOURCE_PROPERTY|CLUSTER_CHANGE_GROUP_STATE|CLUSTER_CHANGE_GROUP_DELETED|CLUSTER_CHANGE_GROUP_ADDED|CLUSTER_CHANGE_GROUP_PROPERTY|CLUSTER_CHANGE_RESOURCE_TYPE_DELETED|CLUSTER_CHANGE_RESOURCE_TYPE_ADDED|CLUSTER_CHANGE_RESOURCE_TYPE_PROPERTY|CLUSTER_CHANGE_NETWORK_STATE|CLUSTER_CHANGE_NETWORK_DELETED|CLUSTER_CHANGE_NETWORK_ADDED|CLUSTER_CHANGE_NETWORK_PROPERTY|CLUSTER_CHANGE_NETINTERFACE_STATE|CLUSTER_CHANGE_NETINTERFACE_DELETED|CLUSTER_CHANGE_NETINTERFACE_ADDED|CLUSTER_CHANGE_NETINTERFACE_PROPERTY|CLUSTER_CHANGE_QUORUM_STATE|CLUSTER_CHANGE_CLUSTER_STATE|CLUSTER_CHANGE_CLUSTER_PROPERTY|CLUSTER_CHANGE_HANDLE_CLOSE)

CLUSTER_ENUM_NODE = 0x00000001
CLUSTER_ENUM_RESTYPE = 0x00000002
CLUSTER_ENUM_RESOURCE = 0x00000004
CLUSTER_ENUM_GROUP = 0x00000008
CLUSTER_ENUM_NETWORK = 0x00000010
CLUSTER_ENUM_NETINTERFACE = 0x00000020
CLUSTER_ENUM_INTERNAL_NETWORK = 0x80000000
CLUSTER_ENUM_ALL = (CLUSTER_ENUM_NODE|CLUSTER_ENUM_RESTYPE|CLUSTER_ENUM_RESOURCE|CLUSTER_ENUM_GROUP|CLUSTER_ENUM_NETWORK|CLUSTER_ENUM_NETINTERFACE)

CLUSTER_NODE_ENUM_NETINTERFACES = 0x00000001
CLUSTER_NODE_ENUM_ALL = CLUSTER_NODE_ENUM_NETINTERFACES

ClusterNodeStateUnknown = -1
ClusterNodeUp = 0
ClusterNodeDown = 1
ClusterNodePaused = 2
ClusterNodeJoining = 3

CLUSTER_GROUP_ENUM_CONTAINS = 0x00000001
CLUSTER_GROUP_ENUM_NODES = 0x00000002
CLUSTER_GROUP_ENUM_ALL = CLUSTER_GROUP_ENUM_CONTAINS|CLUSTER_GROUP_ENUM_NODES

ClusterGroupStateUnknown = -1
ClusterGroupOnline = 0
ClusterGroupOffline = 1
ClusterGroupFailed = 2
ClusterGroupPartialOnline = 3
ClusterGroupPending = 4

ClusterGroupPreventFailback = 0
ClusterGroupAllowFailback = 1
ClusterGroupFailbackTypeCount = 2

ClusterResourceStateUnknown = -1
ClusterResourceInherited = 0
ClusterResourceInitializing = 1
ClusterResourceOnline = 2
ClusterResourceOffline = 3
ClusterResourceFailed = 4
ClusterResourcePending = 128
ClusterResourceOnlinePending = 129
ClusterResourceOfflinePending = 130

ClusterResourceDontRestart = 0
ClusterResourceRestartNoNotify = 1
ClusterResourceRestartNotify = 2
ClusterResourceRestartActionCount = 3

CLUSTER_RESOURCE_DEFAULT_MONITOR = 0
CLUSTER_RESOURCE_SEPARATE_MONITOR = 1
CLUSTER_RESOURCE_VALID_FLAGS = CLUSTER_RESOURCE_SEPARATE_MONITOR

CLUSPROP_TYPE_UNKNOWN = -1
CLUSPROP_TYPE_ENDMARK = 0
CLUSPROP_TYPE_LIST_VALUE = 1
CLUSPROP_TYPE_RESCLASS = 2
CLUSPROP_TYPE_RESERVED1 = 3
CLUSPROP_TYPE_NAME = 4
CLUSPROP_TYPE_SIGNATURE = 5
CLUSPROP_TYPE_SCSI_ADDRESS = 6
CLUSPROP_TYPE_DISK_NUMBER = 7
CLUSPROP_TYPE_PARTITION_INFO = 8
CLUSPROP_TYPE_FTSET_INFO = 9
CLUSPROP_TYPE_USER = 32768

CLUSPROP_FORMAT_UNKNOWN = 0
CLUSPROP_FORMAT_BINARY = 1
CLUSPROP_FORMAT_DWORD = 2
CLUSPROP_FORMAT_SZ = 3
CLUSPROP_FORMAT_EXPAND_SZ = 4
CLUSPROP_FORMAT_MULTI_SZ = 5
CLUSPROP_FORMAT_ULARGE_INTEGER = 6
CLUSPROP_FORMAT_LONG = 7
CLUSPROP_FORMAT_EXPANDED_SZ = 8
CLUSPROP_FORMAT_SECURITY_DESCRIPTOR = 9
CLUSPROP_FORMAT_LARGE_INTEGER = 10
CLUSPROP_FORMAT_USER = 32768

CLUS_RESCLASS_UNKNOWN = 0
CLUS_RESCLASS_STORAGE = 1
CLUS_RESCLASS_USER = 32768

CLUS_RESSUBCLASS_SHARED = 0x80000000

CLUS_CHAR_UNKNOWN = 0x00000000
CLUS_CHAR_QUORUM = 0x00000001
CLUS_CHAR_DELETE_REQUIRES_ALL_NODES = 0x00000002

CLUS_FLAG_CORE = 0x00000001

;_CLUSPROP_SYNTAX STRUCT
;	wFormat DW
;	wType DW
;ENDS

CLUSPROP_SYNTAX STRUCT
	UNION
		dw DD
		STRUCT
	    	wFormat DW
			wType DW
		ENDS
	ENDUNION
ENDS

CLUSPROP_VALUE STRUCT
	Syntax CLUSPROP_SYNTAX
	cbLength DW
ENDS

CLUSPROP_BINARY STRUCT
	rgb DB
ENDS

CLUSPROP_DWORD STRUCT
	Syntax CLUSPROP_SYNTAX
	cbLength DD
	dw DD
ENDS

CLUSPROP_LONG STRUCT
	Syntax CLUSPROP_SYNTAX
	cbLength DD
    LONG l DW
ENDS

CLUSPROP_SZ STRUCT
	Syntax CLUSPROP_SYNTAX
	cbLength DD
	sz DW
ENDS

CLUSPROP_ULARGE_INTEGER STRUCT
	Syntax CLUSPROP_SYNTAX
	cbLength DD
	li DQ
ENDS

CLUSPROP_LARGE_INTEGER STRUCT
	Syntax CLUSPROP_SYNTAX
	cbLength DD
	li DQ
ENDS

CLUSPROP_SECURITY_DESCRIPTOR STRUCT
	UNION
		sd DD
		rgbSecurityDescriptor DB
	ENDUNION
ENDS

CLUSPROP_PIFLAG_STICKY = 0x00000001
CLUSPROP_PIFLAG_REMOVABLE = 0x00000002
CLUSPROP_PIFLAG_USABLE = 0x00000004

CLUS_PARTITION_INFO STRUCT
	dwFlags DD
	szDeviceName DW MAX_PATH DUP (?)
	szVolumeLabel DW MAX_PATH DUP (?)
	dwSerialNumber DD
	rgdwMaximumComponentLength DD
	dwFileSystemFlags DD
	szFileSystem DW 32 DUP (?)
ENDS

CLUS_SCSI_ADDRESS STRUCT
	UNION
	STRUCT
		PortNumber DB
		PathId DB
		TargetId DB
		Lun DB
	ENDS
	dw DD
	ENDUNION
ENDS

CLUSPROP_PROPERTY_NAME STRUCT   
	Syntax CLUSPROP_SYNTAX
	cbLength DD
	sz DW
ENDS

CLUSPROP_LIST STRUCT
	nPropertyCount DD
	PropertyName CLUSPROP_PROPERTY_NAME
ENDS

CLUSPROP_BUFFER_HELPER STRUCT
	UNION
		pb PTR
		pw PTR
		pdw PTR
		pl PTR
		psz PTR
		pList PTR
		pSyntax PTR
		pName PTR
		pValue PTR
		pBinaryValue PTR
		pDwordValue PTR
		pLongValue PTR
		pULargeIntegerValue PTR
		pLargeIntegerValue PTR
		pStringValue PTR
		pMultiSzValue PTR
		pSecurityDescriptor PTR
		pResourceClassValue PTR
		pResourceClassInfoValue PTR
		pDiskSignatureValue PTR
		pScsiAddressValue PTR
		pDiskNumberValue PTR
		pPartitionInfoValue PTR
		pRequiredDependencyValue PTR
	ENDUNION
ENDS

CLUSTER_RESOURCE_ENUM_DEPENDS = 0x00000001
CLUSTER_RESOURCE_ENUM_PROVIDES = 0x00000002
CLUSTER_RESOURCE_ENUM_NODES = 0x00000004
CLUSTER_RESOURCE_ENUM_ALL = CLUSTER_RESOURCE_ENUM_DEPENDS|CLUSTER_RESOURCE_ENUM_PROVIDES|CLUSTER_RESOURCE_ENUM_NODES

CLUSTER_RESOURCE_TYPE_ENUM_NODES = 0x00000001
CLUSTER_RESOURCE_TYPE_ENUM_ALL = CLUSTER_RESOURCE_TYPE_ENUM_NODES

CLUSTER_NETWORK_ENUM_NETINTERFACES = 0x00000001
CLUSTER_NETWORK_ENUM_ALL = CLUSTER_NETWORK_ENUM_NETINTERFACES

ClusterNetworkStateUnknown = -1
ClusterNetworkUnavailable = 0
ClusterNetworkDown = 1
ClusterNetworkPartitioned = 2
ClusterNetworkUp = 3

ClusterNetworkRoleNone = 0
ClusterNetworkRoleInternalUse = 0x00000001
ClusterNetworkRoleClientAccess = 0x00000002
ClusterNetworkRoleInternalAndClient = 0x00000003

ClusterNetInterfaceStateUnknown = -1
ClusterNetInterfaceUnavailable = 0
ClusterNetInterfaceFailed = 1
ClusterNetInterfaceUnreachable = 2
ClusterNetInterfaceUp = 3

#endif /* _CLUSAPI_H */
