#ifndef DOCOBJ_H
#define DOCOBJ_H

#IFNDEF RPC_H
	#include "rpc.h"
#ENDIF

#IFNDEF RPCNDR_H
	#include "rpcndr.h"
#ENDIF

#ifndef COM_NO_WINDOWS_H
	#IFNDEF WINDOWS_H
		#include "windows.h"
	#ENDIF
	#IFNDEF OLE2_H
		#include "ole2.h"
	#ENDIF
#endif /*COM_NO_WINDOWS_H*/

/* header files for imported files */
#IFNDEF OCIDL_H
	#include "ocidl.h"
#ENDIF

#IFNDEF BASECOM_H
	#include "BaseCOM.h"
#ENDIF

DOCMISC_CANCREATEMULTIPLEVIEWS	= 1
DOCMISC_SUPPORTCOMPLEXRECTANGLES	= 2
DOCMISC_CANTOPENEDIT	= 4
DOCMISC_NOFILESUPPORT	= 8

#DEFINE GUID_IID_IOleDocument <0xb722bcc5,0x4e68,0x101b,<0xa2,0xbc,0x00,0xaa,0x00,0x40,0x47,0x70>>

IOleDocument STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	CreateView PTR
	GetDocMiscStatus PTR
	EnumViews PTR
ENDS


#DEFINE GUID_IID_IOleDocumentSite <0xb722bcc7,0x4e68,0x101b,<0xa2,0xbc,0x00,0xaa,0x00,0x40,0x47,0x70>>

IOleDocumentSite STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	ActivateMe PTR
ENDS

#DEFINE GUID_IID_IOleDocumentView <0xb722bcc6,0x4e68,0x101b,<0xa2,0xbc,0x00,0xaa,0x00,0x40,0x47,0x70>>

IOleDocumentView STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	SetInPlaceSite PTR
	GetInPlaceSite PTR
	GetDocument PTR
	SetRect PTR
	GetRect PTR
	SetRectComplex PTR
	Show PTR
	UIActivate PTR
	Open PTR
	CloseView PTR
	SaveViewState PTR
	ApplyViewState PTR
	Clone PTR
ENDS

#DEFINE GUID_IID_IEnumOleDocumentViews <0xb722bcc8,0x4e68,0x101b,<0xa2,0xbc,0x00,0xaa,0x00,0x40,0x47,0x70>>

IEnumOleDocumentViews STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Next PTR
	Skip PTR
	Reset PTR
	Clone PTR
ENDS

#DEFINE GUID_IID_IContinueCallback <0xb722bcca,0x4e68,0x101b,<0xa2,0xbc,0x00,0xaa,0x00,0x40,0x47,0x70>>

IContinueCallback STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	FContinue PTR
	FContinuePrinting PTR
ENDS

PRINTFLAG_MAYBOTHERUSER	= 1
PRINTFLAG_PROMPTUSER	= 2
PRINTFLAG_USERMAYCHANGEPRINTER	= 4
PRINTFLAG_RECOMPOSETODEVICE	= 8
PRINTFLAG_DONTACTUALLYPRINT	= 16
PRINTFLAG_FORCEPROPERTIES	= 32
PRINTFLAG_PRINTTOFILE	= 64

PAGERANGE STRUCT
	nFromPage DD
	nToPage DD
ENDS

PAGESET STRUCT
	cbStruct DD
	fOddPages DD
	fEvenPages DD
	cPageRange DD
	rgPages PAGERANGE
ENDS

#define PAGESET_TOLASTPAGE -1

#DEFINE GUID_IID_IPrint <0xb722bcc9,0x4e68,0x101b,<0xa2,0xbc,0x00,0xaa,0x00,0x40,0x47,0x70>>

IPrint STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	SetInitialPageNum PTR
	GetPageInfo PTR
	Print PTR
ENDS

OLECMDF_SUPPORTED	= 0x1
OLECMDF_ENABLED	= 0x2
OLECMDF_LATCHED	= 0x4
OLECMDF_NINCHED	= 0x8
OLECMDF_INVISIBLE	= 0x10
OLECMDF_DEFHIDEONCTXTMENU	= 0x20

OLECMD STRUCT
	cmdID DD
	cmdf DD
ENDS

OLECMDTEXT STRUCT
	cmdtextf DD
	cwActual DD
	cwBuf DD
	rgwz DW
ENDS

OLECMDTEXTF_NONE	= 0
OLECMDTEXTF_NAME	= 1
OLECMDTEXTF_STATUS	= 2

OLECMDEXECOPT_DODEFAULT	= 0
OLECMDEXECOPT_PROMPTUSER	= 1
OLECMDEXECOPT_DONTPROMPTUSER	= 2
OLECMDEXECOPT_SHOWHELP	= 3

OLECMDID_OPEN	= 1
OLECMDID_NEW	= 2
OLECMDID_SAVE	= 3
OLECMDID_SAVEAS	= 4
OLECMDID_SAVECOPYAS	= 5
OLECMDID_PRINT	= 6
OLECMDID_PRINTPREVIEW	= 7
OLECMDID_PAGESETUP	= 8
OLECMDID_SPELL	= 9
OLECMDID_PROPERTIES	= 10
OLECMDID_CUT	= 11
OLECMDID_COPY	= 12
OLECMDID_PASTE	= 13
OLECMDID_PASTESPECIAL	= 14
OLECMDID_UNDO	= 15
OLECMDID_REDO	= 16
OLECMDID_SELECTALL	= 17
OLECMDID_CLEARSELECTION	= 18
OLECMDID_ZOOM	= 19
OLECMDID_GETZOOMRANGE	= 20
OLECMDID_UPDATECOMMANDS	= 21
OLECMDID_REFRESH	= 22
OLECMDID_STOP	= 23
OLECMDID_HIDETOOLBARS	= 24
OLECMDID_SETPROGRESSMAX	= 25
OLECMDID_SETPROGRESSPOS	= 26
OLECMDID_SETPROGRESSTEXT	= 27
OLECMDID_SETTITLE	= 28
OLECMDID_SETDOWNLOADSTATE	= 29
OLECMDID_STOPDOWNLOAD	= 30
OLECMDID_ONTOOLBARACTIVATED	= 31
OLECMDID_FIND	= 32
OLECMDID_DELETE	= 33
OLECMDID_HTTPEQUIV	= 34
OLECMDID_HTTPEQUIV_DONE	= 35
OLECMDID_ENABLE_INTERACTION	= 36
OLECMDID_ONUNLOAD	= 37
OLECMDID_PROPERTYBAG2	= 38
OLECMDID_PREREFRESH	= 39
OLECMDID_SHOWSCRIPTERROR	= 40
OLECMDID_SHOWMESSAGE	= 41
OLECMDID_SHOWFIND	= 42
OLECMDID_SHOWPAGESETUP	= 43
OLECMDID_SHOWPRINT	= 44
OLECMDID_CLOSE	= 45
OLECMDID_ALLOWUILESSSAVEAS	= 46
OLECMDID_DONTDOWNLOADCSS	= 47
OLECMDID_UPDATEPAGESTATUS	= 48
OLECMDID_PRINT2	= 49
OLECMDID_PRINTPREVIEW2	= 50
OLECMDID_SETPRINTTEMPLATE	= 51
OLECMDID_GETPRINTTEMPLATE	= 52
OLECMDID_PAGEACTIONBLOCKED	= 55
OLECMDID_PAGEACTIONUIQUERY	= 56
OLECMDID_FOCUSVIEWCONTROLS	= 57
OLECMDID_FOCUSVIEWCONTROLSQUERY	= 58
OLECMDID_SHOWPAGEACTIONMENU	= 59
OLECMDID_ADDTRAVELENTRY	= 60
OLECMDID_UPDATETRAVELENTRY	= 61
OLECMDID_UPDATEBACKFORWARDSTATE	= 62
OLECMDID_OPTICAL_ZOOM	= 63
OLECMDID_OPTICAL_GETZOOMRANGE	= 64
OLECMDID_WINDOWSTATECHANGED	= 65

#define OLECMDERR_E_FIRST            (OLE_E_LAST+1)
#define OLECMDERR_E_NOTSUPPORTED     (OLECMDERR_E_FIRST)
#define OLECMDERR_E_DISABLED         (OLECMDERR_E_FIRST+1)
#define OLECMDERR_E_NOHELP           (OLECMDERR_E_FIRST+2)
#define OLECMDERR_E_CANCELED         (OLECMDERR_E_FIRST+3)
#define OLECMDERR_E_UNKNOWNGROUP     (OLECMDERR_E_FIRST+4)
#define MSOCMDERR_E_FIRST            OLECMDERR_E_FIRST
#define MSOCMDERR_E_NOTSUPPORTED     OLECMDERR_E_NOTSUPPORTED
#define MSOCMDERR_E_DISABLED         OLECMDERR_E_DISABLED
#define MSOCMDERR_E_NOHELP           OLECMDERR_E_NOHELP
#define MSOCMDERR_E_CANCELED         OLECMDERR_E_CANCELED

#define OLECMDARGINDEX_SHOWPAGEACTIONMENU_HWND     0
#define OLECMDARGINDEX_SHOWPAGEACTIONMENU_X        1
#define OLECMDARGINDEX_SHOWPAGEACTIONMENU_Y        2
#define OLECMDARGINDEX_ACTIVEXINSTALL_PUBLISHER    0
#define OLECMDARGINDEX_ACTIVEXINSTALL_DISPLAYNAME  1

IGNOREMIME_PROMPT	= 0x1
IGNOREMIME_TEXT	= 0x2

WPCSETTING_LOGGING_ENABLED	= 0x1
WPCSETTING_FILEDOWNLOAD_BLOCKED	= 0x2


#DEFINE GUID_IID_IOleCommandTarget <0xb722bccb,0x4e68,0x101b,<0xa2,0xbc,0x00,0xaa,0x00,0x40,0x47,0x70>>

IOleCommandTarget STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	QueryStatus PTR
	Exec PTR
ENDS

OLECMDIDF_REFRESH_NORMAL          = 0
OLECMDIDF_REFRESH_IFEXPIRED       = 1
OLECMDIDF_REFRESH_CONTINUE        = 2
OLECMDIDF_REFRESH_COMPLETELY      = 3
OLECMDIDF_REFRESH_NO_CACHE        = 4
OLECMDIDF_REFRESH_RELOAD          = 5
OLECMDIDF_REFRESH_LEVELMASK       = 0x00FF
OLECMDIDF_REFRESH_CLEARUSERINPUT  = 0x1000

OLECMDIDF_REFRESH_PROMPTIFOFFLINE = 0x2000
OLECMDIDF_REFRESH_THROUGHSCRIPT   = 0x4000
OLECMDIDF_REFRESH_PAGEACTION_ACTIVEXINSTALL = 0x00010000
OLECMDIDF_REFRESH_PAGEACTION_FILEDOWNLOAD   = 0x00020000
OLECMDIDF_REFRESH_PAGEACTION_LOCALMACHINE   = 0x00040000
OLECMDIDF_REFRESH_PAGEACTION_POPUPWINDOW    = 0x00080000
OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNLOCALMACHINE  = 0x00100000
OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNTRUSTED       = 0x00200000
OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTRANET      = 0x00400000
OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTERNET      = 0x00800000
OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNRESTRICTED    = 0x01000000

OLECMDIDF_REFRESH_PROMPTIFOFFLINE = 0x2000
OLECMDIDF_REFRESH_THROUGHSCRIPT   = 0x4000

OLECMDIDF_REFRESH_PROMPTIFOFFLINE = 0x2000

OLECMDIDF_REFRESH_PAGEACTION_MIXEDCONTENT              = 0x02000000
OLECMDIDF_REFRESH_PAGEACTION_INVALID_CERT              = 0x04000000



OLECMDIDF_PAGEACTION_FILEDOWNLOAD                       = 0x00000001
OLECMDIDF_PAGEACTION_ACTIVEXINSTALL                     = 0x00000002
OLECMDIDF_PAGEACTION_ACTIVEXTRUSTFAIL                   = 0x00000004
OLECMDIDF_PAGEACTION_ACTIVEXUSERDISABLE                 = 0x00000008
OLECMDIDF_PAGEACTION_ACTIVEXDISALLOW                    = 0x00000010
OLECMDIDF_PAGEACTION_ACTIVEXUNSAFE                      = 0x00000020
OLECMDIDF_PAGEACTION_POPUPWINDOW                        = 0x00000040
OLECMDIDF_PAGEACTION_LOCALMACHINE                       = 0x00000080
OLECMDIDF_PAGEACTION_MIMETEXTPLAIN                      = 0x00000100
OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE                     = 0x00000200
OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXINSTALL      = 0x00000200
OLECMDIDF_PAGEACTION_PROTLOCKDOWNLOCALMACHINE           = 0x00000400
OLECMDIDF_PAGEACTION_PROTLOCKDOWNTRUSTED                = 0x00000800
OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTRANET               = 0x00001000
OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTERNET               = 0x00002000
OLECMDIDF_PAGEACTION_PROTLOCKDOWNRESTRICTED             = 0x00004000
OLECMDIDF_PAGEACTION_PROTLOCKDOWNDENY                   = 0x00008000
OLECMDIDF_PAGEACTION_POPUPALLOWED                       = 0x00010000
OLECMDIDF_PAGEACTION_SCRIPTPROMPT                       = 0x00020000
OLECMDIDF_PAGEACTION_ACTIVEXUSERAPPROVAL                = 0x00040000
OLECMDIDF_PAGEACTION_MIXEDCONTENT                       = 0x00080000
OLECMDIDF_PAGEACTION_INVALID_CERT                       = 0x00100000
OLECMDIDF_PAGEACTION_INTRANETZONEREQUEST                = 0x00200000
OLECMDIDF_PAGEACTION_SPOOFABLEIDNHOST                   = 0x00800000
OLECMDIDF_PAGEACTION_LOWRIGHTSIE                        = 0x01000000
OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXUSERAPPROVAL = 0x02000000
OLECMDIDF_PAGEACTION_WPCBLOCKED                         = 0x04000000
OLECMDIDF_PAGEACTION_WPCBLOCKED_ACTIVEX                 = 0x08000000
OLECMDIDF_PAGEACTION_EXTENSION_COMPAT_BLOCKED           = 0x10000000
OLECMDIDF_PAGEACTION_NORESETACTIVEX                     = 0x20000000
OLECMDIDF_PAGEACTION_GENERIC_STATE                      = 0x40000000
OLECMDIDF_PAGEACTION_RESET                              = 0x80000000

OLECMDIDF_BROWSERSTATE_EXTENSIONSOFF                      = 0x00000001
OLECMDIDF_BROWSERSTATE_IESECURITY                         = 0x00000002
OLECMDIDF_BROWSERSTATE_PROTECTEDMODE_OFF                  = 0x00000004
OLECMDIDF_BROWSERSTATE_RESET                              = 0x00000008

PAGEACTION_UI_DEFAULT     = 0
PAGEACTION_UI_MODAL       = 1
PAGEACTION_UI_MODELESS    = 2
PAGEACTION_UI_SILENT      = 3

OLECMDIDF_WINDOWSTATE_USERVISIBLE        = 0x00000001
OLECMDIDF_WINDOWSTATE_ENABLED            = 0x00000002
OLECMDIDF_WINDOWSTATE_USERVISIBLE_VALID  = 0x00010000
OLECMDIDF_WINDOWSTATE_ENABLED_VALID      = 0x00020000

////////////////////////////////////////////////////////////////////////////
//  Aliases to original office-compatible names
#define IMsoDocument             IOleDocument
#define IMsoDocumentSite         IOleDocumentSite
#define IMsoView                 IOleDocumentView
#define IEnumMsoView             IEnumOleDocumentViews
#define IMsoCommandTarget        IOleCommandTarget
#define LPMSODOCUMENT            LPOLEDOCUMENT
#define LPMSODOCUMENTSITE        LPOLEDOCUMENTSITE
#define LPMSOVIEW                LPOLEDOCUMENTVIEW
#define LPENUMMSOVIEW            LPENUMOLEDOCUMENTVIEWS
#define LPMSOCOMMANDTARGET       LPOLECOMMANDTARGET
#define MSOCMD                   OLECMD
#define MSOCMDTEXT               OLECMDTEXT
#define IID_IMsoDocument         IID_IOleDocument
#define IID_IMsoDocumentSite     IID_IOleDocumentSite
#define IID_IMsoView             IID_IOleDocumentView
#define IID_IEnumMsoView         IID_IEnumOleDocumentViews
#define IID_IMsoCommandTarget    IID_IOleCommandTarget

#define MSOCMDF_SUPPORTED OLECMDF_SUPPORTED
#define MSOCMDF_ENABLED OLECMDF_ENABLED
#define MSOCMDF_LATCHED OLECMDF_LATCHED
#define MSOCMDF_NINCHED OLECMDF_NINCHED
#define MSOCMDTEXTF_NONE OLECMDTEXTF_NONE
#define MSOCMDTEXTF_NAME OLECMDTEXTF_NAME
#define MSOCMDTEXTF_STATUS OLECMDTEXTF_STATUS
#define MSOCMDEXECOPT_DODEFAULT OLECMDEXECOPT_DODEFAULT
#define MSOCMDEXECOPT_PROMPTUSER OLECMDEXECOPT_PROMPTUSER
#define MSOCMDEXECOPT_DONTPROMPTUSER OLECMDEXECOPT_DONTPROMPTUSER
#define MSOCMDEXECOPT_SHOWHELP OLECMDEXECOPT_SHOWHELP
#define MSOCMDID_OPEN OLECMDID_OPEN
#define MSOCMDID_NEW OLECMDID_NEW
#define MSOCMDID_SAVE OLECMDID_SAVE
#define MSOCMDID_SAVEAS OLECMDID_SAVEAS
#define MSOCMDID_SAVECOPYAS OLECMDID_SAVECOPYAS
#define MSOCMDID_PRINT OLECMDID_PRINT
#define MSOCMDID_PRINTPREVIEW OLECMDID_PRINTPREVIEW
#define MSOCMDID_PAGESETUP OLECMDID_PAGESETUP
#define MSOCMDID_SPELL OLECMDID_SPELL
#define MSOCMDID_PROPERTIES OLECMDID_PROPERTIES
#define MSOCMDID_CUT OLECMDID_CUT
#define MSOCMDID_COPY OLECMDID_COPY
#define MSOCMDID_PASTE OLECMDID_PASTE
#define MSOCMDID_PASTESPECIAL OLECMDID_PASTESPECIAL
#define MSOCMDID_UNDO OLECMDID_UNDO
#define MSOCMDID_REDO OLECMDID_REDO
#define MSOCMDID_SELECTALL OLECMDID_SELECTALL
#define MSOCMDID_CLEARSELECTION OLECMDID_CLEARSELECTION
#define MSOCMDID_ZOOM OLECMDID_ZOOM
#define MSOCMDID_GETZOOMRANGE OLECMDID_GETZOOMRANGE

#DEFINE GUID_IID_IZoomEvents <0x41B68150,0x904C,0x4e17,<0xA0,0xBA,0xA4,0x38,0x18,0x2E,0x35,0x9D>>

IZoomEvents STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	OnZoomPercentChanged PTR
ENDS

#DEFINE GUID_IID_IProtectFocus <0xd81f90a3,0x8156,0x44f7,<0xad,0x28,0x5a,0xbb,0x87,0x00,0x32,0x74>>

IProtectFocus STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	AllowFocusChange PTR
ENDS

#define SID_SProtectFocus  IID_IProtectFocus

#DEFINE GUID_IID_IProtectedModeMenuServices <0x73c105ee,0x9dff,0x4a07,<0xb8,0x3c,0x7e,0xff,0x29,0x0c,0x26,0x6e>>

IProtectedModeMenuServices STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	CreateMenu PTR
	LoadMenu PTR
	LoadMenuID PTR
ENDS

#endif



