#ifndef HTMLHELP_H
#define HTMLHELP_H

/* Windows HTMLHelp definitions */

#define HH_DISPLAY_TOPIC  0x0000
#define HH_HELP_FINDER  0x0000
#define HH_DISPLAY_TOC  0x0001
#define HH_DISPLAY_INDEX  0x0002
#define HH_DISPLAY_SEARCH  0x0003
#define HH_SET_WIN_TYPE  0x0004
#define HH_GET_WIN_TYPE  0x0005
#define HH_GET_WIN_HANDLE  0x0006
#define HH_ENUM_INFO_TYPE  0x0007
#define HH_SET_INFO_TYPE  0x0008
#define HH_SYNC  0x0009
#define HH_RESERVED1  0x000A
#define HH_RESERVED2  0x000B
#define HH_RESERVED3  0x000C
#define HH_KEYWORD_LOOKUP  0x000D
#define HH_DISPLAY_TEXT_POPUP  0x000E
#define HH_HELP_CONTEXT  0x000F
#define HH_TP_HELP_CONTEXTMENU  0x0010
#define HH_TP_HELP_WM_HELP  0x0011
#define HH_CLOSE_ALL  0x0012
#define HH_ALINK_LOOKUP  0x0013
#define HH_GET_LAST_ERROR  0x0014
#define HH_ENUM_CATEGORY  0x0015
#define HH_ENUM_CATEGORY_IT  0x0016
#define HH_RESET_IT_FILTER  0x0017
#define HH_SET_INCLUSIVE_FILTER 0x0018
#define HH_SET_EXCLUSIVE_FILTER 0x0019
#define HH_INITIALIZE  0x001C
#define HH_UNINITIALIZE  0x001D
#define HH_PRETRANSLATEMESSAGE  0x00fd
#define HH_SET_GLOBAL_PROPERTY  0x00fc

#define HHWIN_PROP_TAB_AUTOHIDESHOW  (1<<0)
#define HHWIN_PROP_ONTOP  (1<<1)
#define HHWIN_PROP_NOTITLEBAR  (1<<2)
#define HHWIN_PROP_NODEF_STYLES  (1<<3)
#define HHWIN_PROP_NODEF_EXSTYLES  (1<<4)
#define HHWIN_PROP_TRI_PANE  (1<<5)
#define HHWIN_PROP_NOTB_TEXT  (1<<6)
#define HHWIN_PROP_POST_QUIT  (1<<7)
#define HHWIN_PROP_AUTO_SYNC  (1<<8)
#define HHWIN_PROP_TRACKING  (1<<9)
#define HHWIN_PROP_TAB_SEARCH  (1<<10)
#define HHWIN_PROP_TAB_HISTORY  (1<<11)
#define HHWIN_PROP_TAB_FAVORITES  (1<<12)
#define HHWIN_PROP_CHANGE_TITLE  (1<<13)
#define HHWIN_PROP_NAV_ONLY_WIN  (1<<14)
#define HHWIN_PROP_NO_TOOLBAR  (1<<15)
#define HHWIN_PROP_MENU  (1<<16)
#define HHWIN_PROP_TAB_ADVSEARCH  (1<<17)
#define HHWIN_PROP_USER_POS  (1<<18)
#define HHWIN_PROP_TAB_CUSTOM1  (1<<19)
#define HHWIN_PROP_TAB_CUSTOM2  (1<<20)
#define HHWIN_PROP_TAB_CUSTOM3  (1<<21)
#define HHWIN_PROP_TAB_CUSTOM4  (1<<22)
#define HHWIN_PROP_TAB_CUSTOM5  (1<<23)
#define HHWIN_PROP_TAB_CUSTOM6  (1<<24)
#define HHWIN_PROP_TAB_CUSTOM7  (1<<25)
#define HHWIN_PROP_TAB_CUSTOM8  (1<<26)
#define HHWIN_PROP_TAB_CUSTOM9  (1<<27)
#define HHWIN_TB_MARGIN  (1<<28)

#define HHWIN_PARAM_PROPERTIES  (1<<1)
#define HHWIN_PARAM_STYLES  (1<<2)
#define HHWIN_PARAM_EXSTYLES  (1<<3)
#define HHWIN_PARAM_RECT  (1<<4)
#define HHWIN_PARAM_NAV_WIDTH  (1<<5)
#define HHWIN_PARAM_SHOWSTATE  (1<<6)
#define HHWIN_PARAM_INFOTYPES  (1<<7)
#define HHWIN_PARAM_TB_FLAGS  (1<<8)
#define HHWIN_PARAM_EXPANSION  (1<<9)
#define HHWIN_PARAM_TABPOS  (1<<10)
#define HHWIN_PARAM_TABORDER  (1<<11)
#define HHWIN_PARAM_HISTORY_COUNT  (1<<12)
#define HHWIN_PARAM_CUR_TAB  (1<<13)

#define HHWIN_BUTTON_EXPAND  (1<<1)
#define HHWIN_BUTTON_BACK  (1<<2)
#define HHWIN_BUTTON_FORWARD  (1<<3)
#define HHWIN_BUTTON_STOP  (1<<4)
#define HHWIN_BUTTON_REFRESH  (1<<5)
#define HHWIN_BUTTON_HOME  (1<<6)
#define HHWIN_BUTTON_BROWSE_FWD  (1<<7)
#define HHWIN_BUTTON_BROWSE_BCK  (1<<8)
#define HHWIN_BUTTON_NOTES  (1<<9)
#define HHWIN_BUTTON_CONTENTS  (1<<10)
#define HHWIN_BUTTON_SYNC  (1<<11)
#define HHWIN_BUTTON_OPTIONS  (1<<12)
#define HHWIN_BUTTON_PRINT  (1<<13)
#define HHWIN_BUTTON_INDEX  (1<<14)
#define HHWIN_BUTTON_SEARCH  (1<<15)
#define HHWIN_BUTTON_HISTORY  (1<<16)
#define HHWIN_BUTTON_FAVORITES  (1<<17)
#define HHWIN_BUTTON_JUMP1  (1<<18)
#define HHWIN_BUTTON_JUMP2  (1<<19)
#define HHWIN_BUTTON_ZOOM  (1<<20)
#define HHWIN_BUTTON_TOC_NEXT  (1<<21)
#define HHWIN_BUTTON_TOC_PREV  (1<<22)

#define HHWIN_DEF_BUTTONS  (HHWIN_BUTTON_EXPAND|HHWIN_BUTTON_BACK|HHWIN_BUTTON_OPTIONS|HHWIN_BUTTON_PRINT)

#define IDTB_EXPAND  200
#define IDTB_CONTRACT  201
#define IDTB_STOP  202
#define IDTB_REFRESH  203
#define IDTB_BACK  204
#define IDTB_HOME  205
#define IDTB_SYNC  206
#define IDTB_PRINT  207
#define IDTB_OPTIONS  208
#define IDTB_FORWARD  209
#define IDTB_NOTES  210
#define IDTB_BROWSE_FWD  211
#define IDTB_BROWSE_BACK  212
#define IDTB_CONTENTS  213
#define IDTB_INDEX  214
#define IDTB_SEARCH  215
#define IDTB_HISTORY  216
#define IDTB_FAVORITES  217
#define IDTB_JUMP1  218
#define IDTB_JUMP2  219
#define IDTB_CUSTOMIZE  221
#define IDTB_ZOOM  222
#define IDTB_TOC_NEXT  223
#define IDTB_TOC_PREV  224

#define HHN_FIRST -860
#define HHN_LAST -879

#define HHN_NAVCOMPLETE  (HHN_FIRST-0)
#define HHN_TRACK  (HHN_FIRST-1)
#define HHN_WINDOW_CREATE (HHN_FIRST-2)

#define HH_MAX_TABS  19

#define ATOM_HTMLHELP_API_ANSI  14
#define ATOM_HTMLHELP_API_UNICODE  15

HHN_NOTIFY STRUCT
	hdr NMHDR
	pszUrl PTR
ENDS

HH_POPUP STRUCT
	cbStruct DD
	hinst HANDLE
	idString DD
	pszText PTR
	pt POINT
	clrForeground DD
	clrBackground DD
	rcMargins RECT
	pszFont PTR
ENDS

HH_AKLINK STRUCT
	cbStruct DD
	fReserved DD
	pszKeywords PTR
	pszUrl PTR
	pszMsgText PTR
	pszMsgTitle PTR
	pszWindow PTR
	fIndexOnFail DD
ENDS

HHWIN_NAVTYPE_TOC = 0
HHWIN_NAVTYPE_INDEX = 1
HHWIN_NAVTYPE_SEARCH = 2
HHWIN_NAVTYPE_FAVORITES = 3
HHWIN_NAVTYPE_HISTORY = 4
HHWIN_NAVTYPE_AUTHOR = 5
HHWIN_NAVTYPE_CUSTOM_FIRST = 11

IT_INCLUSIVE = 0
IT_EXCLUSIVE = 1
IT_HIDDEN = 2

HH_ENUM_IT STRUCT
	cbStruct DD
	iType DD
	pszCatName PTR
	pszITName PTR
	pszITDescription PTR
ENDS

HH_ENUM_CAT STRUCT
	cbStruct DD
	pszCatName PTR
	pszCatDescription PTR
ENDS

HH_SET_INFOTYPE STRUCT
	cbStruct DD
	pszCatName PTR
	pszInfoTypeName PTR
ENDS

HHWIN_NAVTAB_TOP = 0
HHWIN_NAVTAB_LEFT = 1
HHWIN_NAVTAB_BOTTOM = 2

HH_TAB_CONTENTS = 0
HH_TAB_INDEX = 1
HH_TAB_SEARCH = 2
HH_TAB_FAVORITES = 3
HH_TAB_HISTORY = 4
HH_TAB_AUTHOR = 5
HH_TAB_CUSTOM_FIRST = 11
HH_TAB_CUSTOM_LAST = HH_MAX_TABS

#define HH_MAX_TABS_CUSTOM (HH_TAB_CUSTOM_LAST-HH_TAB_CUSTOM_FIRST+1)
#define HH_FTS_DEFAULT_PROXIMITY -1

HH_FTS_QUERY STRUCT
	cbStruct DD
	fUniCodeStrings DD
	pszSearchQuery PTR
	iProximity DD
	fStemmedSearch DD
	fTitleOnly DD
	fExecute DD
	pszWindow PTR
ENDS

HH_WINTYPE STRUCT
	cbStruct DD
	fUniCodeStrings DD
	pszType PTR
	fsValidMembers DD
	fsWinProperties DD
	pszCaption PTR
	dwStyles DD
	dwExStyles DD
	rcWindowPos RECT
	nShowState DD
	hwndHelp HANDLE
	hwndCaller HANDLE
	paInfoTypes PTR
	hwndToolBar HANDLE
	hwndNavigation HANDLE
	hwndHTML HANDLE
	iNavWidth DD
	rcHTML RECT
	pszToc PTR
	pszIndex PTR
	pszFile PTR
	pszHome PTR
	fsToolBarFlags DD
	fNotExpanded DD
	curNavType DD
	tabpos DD
	idNotify DD
	tabOrder DB HH_MAX_TABS+1 DUP
	cHistory DD
	pszJump1 PTR
	pszJump2 PTR
	pszUrlJump1 PTR
	pszUrlJump2 PTR
;	rcMinSize RECT
;	cbInfoTypes DD
;	pszCustomTabs PTR
ENDS

HHACT_TAB_CONTENTS = 0
HHACT_TAB_INDEX = 1
HHACT_TAB_SEARCH = 2
HHACT_TAB_HISTORY = 3
HHACT_TAB_FAVORITES = 4
HHACT_EXPAND = 5
HHACT_CONTRACT = 6
HHACT_BACK = 7
HHACT_FORWARD = 8
HHACT_STOP = 9
HHACT_REFRESH = 10
HHACT_HOME = 11
HHACT_SYNC = 12
HHACT_OPTIONS = 13
HHACT_PRINT = 14
HHACT_HIGHLIGHT = 15
HHACT_CUSTOMIZE = 16
HHACT_JUMP1 = 17
HHACT_JUMP2 = 18
HHACT_ZOOM = 19
HHACT_TOC_NEXT = 20
HHACT_TOC_PREV = 21
HHACT_NOTES = 22
HHACT_LAST_ENUM = 23

HHNTRACK STRUCT
	hdr NMHDR
	pszCurUrl PTR
	idAction DD
	phhWinType PTR
ENDS

#IFNDEF HELPLIB
	// Default lib file path
	#DEFINE HELPLIB "C:\Program Files\HTML Help Workshop\Lib\Htmlhelp.lib"
#ENDIF

#IFDEF UNICODE
	#define HtmlHelp HELPLIB:HtmlHelpW
#else
	#define HtmlHelp HELPLIB:HtmlHelpA
#endif

HH_GPROPID_SINGLETHREAD = 1
HH_GPROPID_TOOLBAR_MARGIN = 2
HH_GPROPID_UI_LANGUAGE = 3
HH_GPROPID_CURRENT_SUBSET = 4
HH_GPROPID_CONTENT_LANGUAGE = 5

HH_GLOBAL_PROPERTY STRUCT
	id DD
	var VARIANT
ENDS

#endif /* HTMLHELP_H */
