#ifndef LMSERVER_H
#define LMSERVER_H

/* NetServer API definitions */

#IFNDEF WINSVC_H
	#include winsvc.h
#ENDIF

#IFNDEF LMCONS_H
	#include lmcons.h
#ENDIF

#define SV_PLATFORM_ID_OS2  400
#define SV_PLATFORM_ID_NT  500

#define MAJOR_VERSION_MASK  0x0F

#define SV_TYPE_WORKSTATION  0x00000001
#define SV_TYPE_SERVER  0x00000002
#define SV_TYPE_SQLSERVER  0x00000004
#define SV_TYPE_DOMAIN_CTRL  0x00000008
#define SV_TYPE_DOMAIN_BAKCTRL  0x00000010
#define SV_TYPE_TIME_SOURCE  0x00000020
#define SV_TYPE_AFP  0x00000040
#define SV_TYPE_NOVELL  0x00000080
#define SV_TYPE_DOMAIN_MEMBER  0x00000100
#define SV_TYPE_PRINTQ_SERVER  0x00000200
#define SV_TYPE_DIALIN_SERVER  0x00000400
#define SV_TYPE_XENIX_SERVER  0x00000800
#define SV_TYPE_SERVER_UNIX  SV_TYPE_XENIX_SERVER
#define SV_TYPE_NT  0x00001000
#define SV_TYPE_WFW  0x00002000
#define SV_TYPE_SERVER_MFPN  0x00004000
#define SV_TYPE_SERVER_NT  0x00008000
#define SV_TYPE_POTENTIAL_BROWSER  0x00010000
#define SV_TYPE_BACKUP_BROWSER  0x00020000
#define SV_TYPE_MASTER_BROWSER  0x00040000
#define SV_TYPE_DOMAIN_MASTER  0x00080000
#define SV_TYPE_SERVER_OSF  0x00100000
#define SV_TYPE_SERVER_VMS  0x00200000
#define SV_TYPE_WINDOWS  0x00400000
#define SV_TYPE_DFS  0x00800000
#define SV_TYPE_CLUSTER_NT  0x01000000
#define SV_TYPE_TERMINALSERVER  0x02000000
#define SV_TYPE_DCE  0x10000000
#define SV_TYPE_ALTERNATE_XPORT  0x20000000
#define SV_TYPE_LOCAL_LIST_ONLY  0x40000000
#define SV_TYPE_DOMAIN_ENUM  0x80000000
#define SV_TYPE_ALL  0xFFFFFFFF

#define SV_NODISC -1

#define SV_USERSECURITY  1
#define SV_SHARESECURITY  0

#define SV_HIDDEN  1
#define SV_VISIBLE  0

#define SV_PLATFORM_ID_PARMNUM  101
#define SV_NAME_PARMNUM  102
#define SV_VERSION_MAJOR_PARMNUM  103
#define SV_VERSION_MINOR_PARMNUM  104
#define SV_TYPE_PARMNUM  105
#define SV_COMMENT_PARMNUM  5
#define SV_USERS_PARMNUM  107
#define SV_DISC_PARMNUM  10
#define SV_HIDDEN_PARMNUM  16
#define SV_ANNOUNCE_PARMNUM  17
#define SV_ANNDELTA_PARMNUM  18
#define SV_USERPATH_PARMNUM  112

#define SV_ULIST_MTIME_PARMNUM  401
#define SV_GLIST_MTIME_PARMNUM  402
#define SV_ALIST_MTIME_PARMNUM  403
#define SV_ALERTS_PARMNUM  11
#define SV_SECURITY_PARMNUM  405
#define SV_NUMADMIN_PARMNUM  406
#define SV_LANMASK_PARMNUM  407
#define SV_GUESTACC_PARMNUM  408
#define SV_CHDEVQ_PARMNUM  410
#define SV_CHDEVJOBS_PARMNUM  411
#define SV_CONNECTIONS_PARMNUM  412
#define SV_SHARES_PARMNUM  413
#define SV_OPENFILES_PARMNUM  414
#define SV_SESSREQS_PARMNUM  417
#define SV_ACTIVELOCKS_PARMNUM  419
#define SV_NUMREQBUF_PARMNUM  420
#define SV_NUMBIGBUF_PARMNUM  422
#define SV_NUMFILETASKS_PARMNUM  423
#define SV_ALERTSCHED_PARMNUM  37
#define SV_ERRORALERT_PARMNUM  38
#define SV_LOGONALERT_PARMNUM  39
#define SV_ACCESSALERT_PARMNUM  40
#define SV_DISKALERT_PARMNUM  41
#define SV_NETIOALERT_PARMNUM  42
#define SV_MAXAUDITSZ_PARMNUM  43
#define SV_SRVHEURISTICS_PARMNUM  431

#define SV_SESSOPENS_PARMNUM  501
#define SV_SESSVCS_PARMNUM  502
#define SV_OPENSEARCH_PARMNUM  503
#define SV_SIZREQBUF_PARMNUM  504
#define SV_INITWORKITEMS_PARMNUM  505
#define SV_MAXWORKITEMS_PARMNUM  506
#define SV_RAWWORKITEMS_PARMNUM  507
#define SV_IRPSTACKSIZE_PARMNUM  508
#define SV_MAXRAWBUFLEN_PARMNUM  509
#define SV_SESSUSERS_PARMNUM  510
#define SV_SESSCONNS_PARMNUM  511
#define SV_MAXNONPAGEDMEMORYUSAGE_PARMNUM  512
#define SV_MAXPAGEDMEMORYUSAGE_PARMNUM  513
#define SV_ENABLESOFTCOMPAT_PARMNUM  514
#define SV_ENABLEFORCEDLOGOFF_PARMNUM  515
#define SV_TIMESOURCE_PARMNUM  516
#define SV_ACCEPTDOWNLEVELAPIS_PARMNUM  517
#define SV_LMANNOUNCE_PARMNUM  518
#define SV_DOMAIN_PARMNUM  519
#define SV_MAXCOPYREADLEN_PARMNUM  520
#define SV_MAXCOPYWRITELEN_PARMNUM  521
#define SV_MINKEEPSEARCH_PARMNUM  522
#define SV_MAXKEEPSEARCH_PARMNUM  523
#define SV_MINKEEPCOMPLSEARCH_PARMNUM  524
#define SV_MAXKEEPCOMPLSEARCH_PARMNUM  525
#define SV_THREADCOUNTADD_PARMNUM  526
#define SV_NUMBLOCKTHREADS_PARMNUM  527
#define SV_SCAVTIMEOUT_PARMNUM  528
#define SV_MINRCVQUEUE_PARMNUM  529
#define SV_MINFREEWORKITEMS_PARMNUM  530
#define SV_XACTMEMSIZE_PARMNUM  531
#define SV_THREADPRIORITY_PARMNUM  532
#define SV_MAXMPXCT_PARMNUM  533
#define SV_OPLOCKBREAKWAIT_PARMNUM  534
#define SV_OPLOCKBREAKRESPONSEWAIT_PARMNUM  535
#define SV_ENABLEOPLOCKS_PARMNUM  536
#define SV_ENABLEOPLOCKFORCECLOSE_PARMNUM  537
#define SV_ENABLEFCBOPENS_PARMNUM  538
#define SV_ENABLERAW_PARMNUM  539
#define SV_ENABLESHAREDNETDRIVES_PARMNUM  540
#define SV_MINFREECONNECTIONS_PARMNUM  541
#define SV_MAXFREECONNECTIONS_PARMNUM  542
#define SV_INITSESSTABLE_PARMNUM  543
#define SV_INITCONNTABLE_PARMNUM  544
#define SV_INITFILETABLE_PARMNUM  545
#define SV_INITSEARCHTABLE_PARMNUM  546
#define SV_ALERTSCHEDULE_PARMNUM  547
#define SV_ERRORTHRESHOLD_PARMNUM  548
#define SV_NETWORKERRORTHRESHOLD_PARMNUM  549
#define SV_DISKSPACETHRESHOLD_PARMNUM  550
#define SV_MAXLINKDELAY_PARMNUM  552
#define SV_MINLINKTHROUGHPUT_PARMNUM  553
#define SV_LINKINFOVALIDTIME_PARMNUM  554
#define SV_SCAVQOSINFOUPDATETIME_PARMNUM  555
#define SV_MAXWORKITEMIDLETIME_PARMNUM  556
#define SV_MAXRAWWORKITEMS_PARMNUM  557
#define SV_PRODUCTTYPE_PARMNUM  560
#define SV_SERVERSIZE_PARMNUM  561
#define SV_CONNECTIONLESSAUTODISC_PARMNUM  562
#define SV_SHARINGVIOLATIONRETRIES_PARMNUM  563
#define SV_SHARINGVIOLATIONDELAY_PARMNUM  564
#define SV_MAXGLOBALOPENSEARCH_PARMNUM  565
#define SV_REMOVEDUPLICATESEARCHES_PARMNUM  566
#define SV_LOCKVIOLATIONRETRIES_PARMNUM  567
#define SV_LOCKVIOLATIONOFFSET_PARMNUM  568
#define SV_LOCKVIOLATIONDELAY_PARMNUM  569
#define SV_MDLREADSWITCHOVER_PARMNUM  570
#define SV_CACHEDOPENLIMIT_PARMNUM  571
#define SV_CRITICALTHREADS_PARMNUM  572
#define SV_RESTRICTNULLSESSACCESS_PARMNUM  573
#define SV_ENABLEWFW311DIRECTIPX_PARMNUM  574
#define SV_OTHERQUEUEAFFINITY_PARMNUM  575
#define SV_QUEUESAMPLESECS_PARMNUM  576
#define SV_BALANCECOUNT_PARMNUM  577
#define SV_PREFERREDAFFINITY_PARMNUM  578
#define SV_MAXFREERFCBS_PARMNUM  579
#define SV_MAXFREEMFCBS_PARMNUM  580
#define SV_MAXFREELFCBS_PARMNUM  581
#define SV_MAXFREEPAGEDPOOLCHUNKS_PARMNUM  582
#define SV_MINPAGEDPOOLCHUNKSIZE_PARMNUM  583
#define SV_MAXPAGEDPOOLCHUNKSIZE_PARMNUM  584
#define SV_SENDSFROMPREFERREDPROCESSOR_PARMNUM  585
#define SV_MAXTHREADSPERQUEUE_PARMNUM  586
#define SV_CACHEDDIRECTORYLIMIT_PARMNUM  587
#define SV_MAXCOPYLENGTH_PARMNUM  588
#define SV_ENABLECOMPRESSION_PARMNUM  590
#define SV_AUTOSHAREWKS_PARMNUM  591
#define SV_AUTOSHARESERVER_PARMNUM  592
#define SV_ENABLESECURITYSIGNATURE_PARMNUM  593
#define SV_REQUIRESECURITYSIGNATURE_PARMNUM  594
#define SV_MINCLIENTBUFFERSIZE_PARMNUM  595
#define SV_CONNECTIONNOSESSIONSTIMEOUT_PARMNUM  596
#define SV_IDLETHREADTIMEOUT_PARMNUM  597
#define SV_ENABLEW9XSECURITYSIGNATURE_PARMNUM  598

#define SV_COMMENT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_COMMENT_PARMNUM)
#define SV_USERS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_USERS_PARMNUM)
#define SV_DISC_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_DISC_PARMNUM)
#define SV_HIDDEN_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_HIDDEN_PARMNUM)
#define SV_ANNOUNCE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ANNOUNCE_PARMNUM)
#define SV_ANNDELTA_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ANNDELTA_PARMNUM)
#define SV_SESSOPENS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SESSOPENS_PARMNUM)
#define SV_SESSVCS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SESSVCS_PARMNUM)
#define SV_OPENSEARCH_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_OPENSEARCH_PARMNUM)
#define SV_MAXWORKITEMS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXWORKITEMS_PARMNUM)
#define SV_MAXRAWBUFLEN_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXRAWBUFLEN_PARMNUM)
#define SV_SESSUSERS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SESSUSERS_PARMNUM)
#define SV_SESSCONNS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SESSCONNS_PARMNUM)
#define SV_MAXNONPAGEDMEMORYUSAGE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXNONPAGEDMEMORYUSAGE_PARMNUM)
#define SV_MAXPAGEDMEMORYUSAGE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXPAGEDMEMORYUSAGE_PARMNUM)
#define SV_ENABLESOFTCOMPAT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLESOFTCOMPAT_PARMNUM)
#define SV_ENABLEFORCEDLOGOFF_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLEFORCEDLOGOFF_PARMNUM)
#define SV_TIMESOURCE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_TIMESOURCE_PARMNUM)
#define SV_LMANNOUNCE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_LMANNOUNCE_PARMNUM)
#define SV_MAXCOPYREADLEN_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXCOPYREADLEN_PARMNUM)
#define SV_MAXCOPYWRITELEN_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXCOPYWRITELEN_PARMNUM)
#define SV_MINKEEPSEARCH_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MINKEEPSEARCH_PARMNUM)
#define SV_MAXKEEPSEARCH_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXKEEPSEARCH_PARMNUM)
#define SV_MINKEEPCOMPLSEARCH_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MINKEEPCOMPLSEARCH_PARMNUM)
#define SV_MAXKEEPCOMPLSEARCH_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXKEEPCOMPLSEARCH_PARMNUM)
#define SV_SCAVTIMEOUT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SCAVTIMEOUT_PARMNUM)
#define SV_MINRCVQUEUE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MINRCVQUEUE_PARMNUM)
#define SV_MINFREEWORKITEMS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MINFREEWORKITEMS_PARMNUM)
#define SV_MAXMPXCT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXMPXCT_PARMNUM)
#define SV_OPLOCKBREAKWAIT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_OPLOCKBREAKWAIT_PARMNUM)
#define SV_OPLOCKBREAKRESPONSEWAIT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_OPLOCKBREAKRESPONSEWAIT_PARMNUM)
#define SV_ENABLEOPLOCKS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLEOPLOCKS_PARMNUM)
#define SV_ENABLEOPLOCKFORCECLOSE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLEOPLOCKFORCECLOSE_PARMNUM)
#define SV_ENABLEFCBOPENS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLEFCBOPENS_PARMNUM)
#define SV_ENABLERAW_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLERAW_PARMNUM)
#define SV_ENABLESHAREDNETDRIVES_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLESHAREDNETDRIVES_PARMNUM)
#define SV_MINFREECONNECTIONS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MINFREECONNECTIONS_PARMNUM)
#define SV_MAXFREECONNECTIONS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXFREECONNECTIONS_PARMNUM)
#define SV_INITSESSTABLE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_INITSESSTABLE_PARMNUM)
#define SV_INITCONNTABLE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_INITCONNTABLE_PARMNUM)
#define SV_INITFILETABLE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_INITFILETABLE_PARMNUM)
#define SV_INITSEARCHTABLE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_INITSEARCHTABLE_PARMNUM)
#define SV_ALERTSCHEDULE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ALERTSCHEDULE_PARMNUM)
#define SV_ERRORTHRESHOLD_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ERRORTHRESHOLD_PARMNUM)
#define SV_NETWORKERRORTHRESHOLD_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_NETWORKERRORTHRESHOLD_PARMNUM)
#define SV_DISKSPACETHRESHOLD_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_DISKSPACETHRESHOLD_PARMNUM)
#define SV_MAXLINKDELAY_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXLINKDELAY_PARMNUM)
#define SV_MINLINKTHROUGHPUT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MINLINKTHROUGHPUT_PARMNUM)
#define SV_LINKINFOVALIDTIME_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_LINKINFOVALIDTIME_PARMNUM)
#define SV_SCAVQOSINFOUPDATETIME_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SCAVQOSINFOUPDATETIME_PARMNUM)
#define SV_MAXWORKITEMIDLETIME_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXWORKITEMIDLETIME_PARMNUM)
#define SV_MAXRAWWORKITEMS_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXRAWWORKITEMS_PARMNUM)
#define SV_PRODUCTTYPE_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_PRODUCTTYPE_PARMNUM)
#define SV_SERVERSIZE_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SERVERSIZE_PARMNUM)
#define SV_CONNECTIONLESSAUTODISC_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_CONNECTIONLESSAUTODISC_PARMNUM)
#define SV_SHARINGVIOLATIONRETRIES_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SHARINGVIOLATIONRETRIES_PARMNUM)
#define SV_SHARINGVIOLATIONDELAY_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SHARINGVIOLATIONDELAY_PARMNUM)
#define SV_MAXGLOBALOPENSEARCH_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXGLOBALOPENSEARCH_PARMNUM)
#define SV_REMOVEDUPLICATESEARCHES_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_REMOVEDUPLICATESEARCHES_PARMNUM)
#define SV_LOCKVIOLATIONRETRIES_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_LOCKVIOLATIONRETRIES_PARMNUM)
#define SV_LOCKVIOLATIONOFFSET_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_LOCKVIOLATIONOFFSET_PARMNUM)
#define SV_LOCKVIOLATIONDELAY_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_LOCKVIOLATIONDELAY_PARMNUM)
#define SV_MDLREADSWITCHOVER_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MDLREADSWITCHOVER_PARMNUM)
#define SV_CACHEDOPENLIMIT_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_CACHEDOPENLIMIT_PARMNUM)
#define SV_CRITICALTHREADS_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_CRITICALTHREADS_PARMNUM)
#define SV_RESTRICTNULLSESSACCESS_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_RESTRICTNULLSESSACCESS_PARMNUM)
#define SV_ENABLEWFW311DIRECTIPX_INFOLOEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLEWFW311DIRECTIPX_PARMNUM)
#define SV_OTHERQUEUEAFFINITY_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_OTHERQUEUEAFFINITY_PARMNUM)
#define SV_QUEUESAMPLESECS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_QUEUESAMPLESECS_PARMNUM)
#define SV_BALANCECOUNT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_BALANCECOUNT_PARMNUM)
#define SV_PREFERREDAFFINITY_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_PREFERREDAFFINITY_PARMNUM)
#define SV_MAXFREERFCBS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXFREERFCBS_PARMNUM)
#define SV_MAXFREEMFCBS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXFREEMFCBS_PARMNUM)
#define SV_MAXFREELFCBS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXFREELFCBS_PARMNUM)
#define SV_MAXFREEPAGEDPOOLCHUNKS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXFREEPAGEDPOOLCHUNKS_PARMNUM)
#define SV_MINPAGEDPOOLCHUNKSIZE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MINPAGEDPOOLCHUNKSIZE_PARMNUM)
#define SV_MAXPAGEDPOOLCHUNKSIZE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXPAGEDPOOLCHUNKSIZE_PARMNUM)
#define SV_SENDSFROMPREFERREDPROCESSOR_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_SENDSFROMPREFERREDPROCESSOR_PARMNUM)
#define SV_MAXTHREADSPERQUEUE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXTHREADSPERQUEUE_PARMNUM)
#define SV_CACHEDDIRECTORYLIMIT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_CACHEDDIRECTORYLIMIT_PARMNUM)
#define SV_MAXCOPYLENGTH_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MAXCOPYLENGTH_PARMNUM)
#define SV_ENABLECOMPRESSION_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLECOMPRESSION_PARMNUM)
#define SV_AUTOSHAREWKS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_AUTOSHAREWKS_PARMNUM)
#define SV_AUTOSHARESERVER_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_AUTOSHARESERVER_PARMNUM)
#define SV_ENABLESECURITYSIGNATURE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLESECURITYSIGNATURE_PARMNUM)
#define SV_REQUIRESECURITYSIGNATURE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_REQUIRESECURITYSIGNATURE_PARMNUM)
#define SV_MINCLIENTBUFFERSIZE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_MINCLIENTBUFFERSIZE_PARMNUM)
#define SV_CONNECTIONNOSESSIONSTIMEOUT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_CONNECTIONNOSESSIONSTIMEOUT_PARMNUM)
#define SV_IDLETHREADTIMEOUT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_IDLETHREADTIMEOUT_PARMNUM)
#define SV_ENABLEW9XSECURITYSIGNATURE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+SV_ENABLEW9XSECURITYSIGNATURE_PARMNUM)

#define SVI1_NUM_ELEMENTS  5
#define SVI2_NUM_ELEMENTS  40
#define SVI3_NUM_ELEMENTS  44

#define SV_MAX_CMD_LEN  PATHLEN
#define SV_MAX_SRV_HEUR_LEN  32
#define SV_USERS_PER_LICENSE  5

#define SW_AUTOPROF_LOAD_MASK  0x1
#define SW_AUTOPROF_SAVE_MASK  0x2

#define SVTI2_REMAP_PIPE_NAMES  0x2

SERVER_INFO_100 STRUCT
	sv100_platform_id DD
	sv100_name PTR
ENDS

SERVER_INFO_101 STRUCT
	sv101_platform_id DD
	sv101_name PTR
	sv101_version_major DD
	sv101_version_minor DD
	sv101_type DD
	sv101_comment PTR
ENDS

SERVER_INFO_102 STRUCT
 	sv102_platform_id DD
 	sv102_name PTR
 	sv102_version_major DD
 	sv102_version_minor DD
 	sv102_type DD
 	sv102_comment PTR
 	sv102_users DD
	sv102_disc DD
 	sv102_hidden DD
 	sv102_announce DD
 	sv102_anndelta DD
 	sv102_licenses DD
 	sv102_userpath PTR
ENDS

SERVER_INFO_402 STRUCT
 	sv402_ulist_mtime DD
 	sv402_glist_mtime DD
 	sv402_alist_mtime DD
 	sv402_alerts PTR
 	sv402_security DD
 	sv402_numadmin DD
 	sv402_lanmask DD
 	sv402_guestacct PTR
 	sv402_chdevs DD
 	sv402_chdevq DD
 	sv402_chdevjobs DD
 	sv402_connections DD
 	sv402_shares DD
 	sv402_openfiles DD
 	sv402_sessopens DD
 	sv402_sessvcs DD
 	sv402_sessreqs DD
 	sv402_opensearch DD
 	sv402_activelocks DD
 	sv402_numreqbuf DD
 	sv402_sizreqbuf DD
 	sv402_numbigbuf DD
 	sv402_numfiletasks DD
 	sv402_alertsched DD
 	sv402_erroralert DD
 	sv402_logonalert DD
 	sv402_accessalert DD
 	sv402_diskalert DD
 	sv402_netioalert DD
 	sv402_maxauditsz DD
 	sv402_srvheuristics PTR
ENDS

SERVER_INFO_403 STRUCT
 	sv403_ulist_mtime DD
 	sv403_glist_mtime DD
 	sv403_alist_mtime DD
 	sv403_alerts PTR
 	sv403_security DD
 	sv403_numadmin DD
 	sv403_lanmask DD
 	sv403_guestacct PTR
 	sv403_chdevs DD
 	sv403_chdevq DD
 	sv403_chdevjobs DD
 	sv403_connections DD
 	sv403_shares DD
 	sv403_openfiles DD
 	sv403_sessopens DD
 	sv403_sessvcs DD
 	sv403_sessreqs DD
 	sv403_opensearch DD
 	sv403_activelocks DD
 	sv403_numreqbuf DD
 	sv403_sizreqbuf DD
 	sv403_numbigbuf DD
 	sv403_numfiletasks DD
 	sv403_alertsched DD
 	sv403_erroralert DD
 	sv403_logonalert DD
 	sv403_accessalert DD
 	sv403_diskalert DD
 	sv403_netioalert DD
 	sv403_maxauditsz DD
 	sv403_srvheuristics PTR
 	sv403_auditedevents DD
 	sv403_autoprofile DD
 	sv403_autopath DD
ENDS

SERVER_INFO_502 STRUCT
	sv502_sessopens DD
	sv502_sessvcs DD
	sv502_opensearch DD
	sv502_sizreqbuf DD
	sv502_initworkitems DD
	sv502_maxworkitems DD
	sv502_rawworkitems DD
	sv502_irpstacksize DD
	sv502_maxrawbuflen DD
	sv502_sessusers DD
	sv502_sessconns DD
	sv502_maxpagedmemoryusage DD
	sv502_maxnonpagedmemoryusage DD
	sv502_enablesoftcompat DD
	sv502_enableforcedlogoff DD
	sv502_timesource DD
	sv502_acceptdownlevelapis DD
	sv502_lmannounce DD
ENDS

SERVER_INFO_503 STRUCT
	sv503_sessopens DD
	sv503_sessvcs DD
	sv503_opensearch DD
	sv503_sizreqbuf DD
	sv503_initworkitems DD
	sv503_maxworkitems DD
	sv503_rawworkitems DD
	sv503_irpstacksize DD
	sv503_maxrawbuflen DD
	sv503_sessusers DD
	sv503_sessconns DD
	sv503_maxpagedmemoryusage DD
	sv503_maxnonpagedmemoryusage DD
	sv503_enablesoftcompat DD
	sv503_enableforcedlogoff DD
	sv503_timesource DD
	sv503_acceptdownlevelapis DD
	sv503_lmannounce DD
	sv503_domain PTR
	sv503_maxcopyreadlen DD
	sv503_maxcopywritelen DD
	sv503_minkeepsearch DD
	sv503_maxkeepsearch DD
	sv503_minkeepcomplsearch DD
	sv503_maxkeepcomplsearch DD
	sv503_threadcountadd DD
	sv503_numblockthreads DD
	sv503_scavtimeout DD
	sv503_minrcvqueue DD
	sv503_minfreeworkitems DD
	sv503_xactmemsize DD
	sv503_threadpriority DD
	sv503_maxmpxct DD
	sv503_oplockbreakwait DD
	sv503_oplockbreakresponsewait DD
	sv503_enableoplocks DD
	sv503_enableoplockforceclose DD
	sv503_enablefcbopens DD
	sv503_enableraw DD
	sv503_enablesharednetdrives DD
	sv503_minfreeconnections DD
	sv503_maxfreeconnections DD
ENDS

SERVER_INFO_599 STRUCT
	sv599_sessopens DD
	sv599_sessvcs DD
	sv599_opensearch DD
	sv599_sizreqbuf DD
	sv599_initworkitems DD
	sv599_maxworkitems DD
	sv599_rawworkitems DD
	sv599_irpstacksize DD
	sv599_maxrawbuflen DD
	sv599_sessusers DD
	sv599_sessconns DD
	sv599_maxpagedmemoryusage DD
	sv599_maxnonpagedmemoryusage DD
	sv599_enablesoftcompat DD
	sv599_enableforcedlogoff DD
	sv599_timesource DD
	sv599_acceptdownlevelapis DD
	sv599_lmannounce DD
	sv599_domain PTR
	sv599_maxcopyreadlen DD
	sv599_maxcopywritelen DD
	sv599_minkeepsearch DD
	sv599_maxkeepsearch DD
	sv599_minkeepcomplsearch DD
	sv599_maxkeepcomplsearch DD
	sv599_threadcountadd DD
	sv599_numblockthreads DD
	sv599_scavtimeout DD
	sv599_minrcvqueue DD
	sv599_minfreeworkitems DD
	sv599_xactmemsize DD
	sv599_threadpriority DD
	sv599_maxmpxct DD
	sv599_oplockbreakwait DD
	sv599_oplockbreakresponsewait DD
	sv599_enableoplocks DD
	sv599_enableoplockforceclose DD
	sv599_enablefcbopens DD
	sv599_enableraw DD
	sv599_enablesharednetdrives DD
	sv599_minfreeconnections DD
	sv599_maxfreeconnections DD
	sv599_initsesstable DD
	sv599_initconntable DD
	sv599_initfiletable DD
	sv599_initsearchtable DD
	sv599_alertschedule DD
	sv599_errorthreshold DD
	sv599_networkerrorthreshold DD
	sv599_diskspacethreshold DD
	sv599_reserved DD
	sv599_maxlinkdelay DD
	sv599_minlinkthroughput DD
	sv599_linkinfovalidtime DD
	sv599_scavqosinfoupdatetime DD
	sv599_maxworkitemidletime DD
ENDS

SERVER_INFO_598 STRUCT
	sv598_maxrawworkitems DD
	sv598_maxthreadsperqueue DD
	sv598_producttype DD
	sv598_serversize DD
	sv598_connectionlessautodisc DD
	sv598_sharingviolationretries DD
	sv598_sharingviolationdelay DD
	sv598_maxglobalopensearch DD
	sv598_removeduplicatesearches DD
	sv598_lockviolationoffset DD
	sv598_lockviolationdelay DD
	sv598_mdlreadswitchover DD
	sv598_cachedopenlimit DD
	sv598_otherqueueaffinity DD
	sv598_restrictnullsessaccess DD
	sv598_enablewfw311directipx DD
	sv598_queuesamplesecs DD
	sv598_balancecount DD
	sv598_preferredaffinity DD
	sv598_maxfreerfcbs DD
	sv598_maxfreemfcbs DD
	sv598_maxfreelfcbs DD
	sv598_maxfreepagedpoolchunks DD
	sv598_minpagedpoolchunksize DD
	sv598_maxpagedpoolchunksize DD
	sv598_sendsfrompreferredprocessor DD
	sv598_cacheddirectorylimit DD
	sv598_maxcopylength DD
	sv598_enablecompression DD
	sv598_autosharewks DD
	sv598_autoshareserver DD
	sv598_enablesecuritysignature DD
	sv598_requiresecuritysignature DD
	sv598_minclientbuffersize DD
	sv598_serverguid GUID
	sv598_ConnectionNoSessionsTimeout DD
	sv598_IdleThreadTimeOut DD
	sv598_enableW9xsecuritysignature DD
ENDS

SERVER_INFO_1005 STRUCT
	sv1005_comment PTR
ENDS

SERVER_INFO_1107 STRUCT
	sv1107_users DD
ENDS

SERVER_INFO_1010 STRUCT
	sv1010_disc DD
ENDS

SERVER_INFO_1016 STRUCT
	sv1016_hidden DD
ENDS

SERVER_INFO_1017 STRUCT
	sv1017_announce DD
ENDS

SERVER_INFO_1018 STRUCT
	sv1018_anndelta DD
ENDS

SERVER_INFO_1501 STRUCT
	sv1501_sessopens DD
ENDS

SERVER_INFO_1502 STRUCT
	sv1502_sessvcs DD
ENDS

SERVER_INFO_1503 STRUCT
	sv1503_opensearch DD
ENDS

SERVER_INFO_1506 STRUCT
	sv1506_maxworkitems DD
ENDS

SERVER_INFO_1509 STRUCT
	sv1509_maxrawbuflen DD
ENDS

SERVER_INFO_1510 STRUCT
	sv1510_sessusers DD
ENDS

SERVER_INFO_1511 STRUCT
	sv1511_sessconns DD
ENDS

SERVER_INFO_1512 STRUCT
	sv1512_maxnonpagedmemoryusage DD
ENDS

SERVER_INFO_1513 STRUCT
	sv1513_maxpagedmemoryusage DD
ENDS

SERVER_INFO_1514 STRUCT
	sv1514_enablesoftcompat DD
ENDS

SERVER_INFO_1515 STRUCT
	sv1515_enableforcedlogoff DD
ENDS

SERVER_INFO_1516 STRUCT
	sv1516_timesource DD
ENDS

SERVER_INFO_1518 STRUCT
	sv1518_lmannounce DD
ENDS

SERVER_INFO_1520 STRUCT
	sv1520_maxcopyreadlen DD
ENDS

SERVER_INFO_1521 STRUCT
	sv1521_maxcopywritelen DD
ENDS

SERVER_INFO_1522 STRUCT
	sv1522_minkeepsearch DD
ENDS

SERVER_INFO_1523 STRUCT
	sv1523_maxkeepsearch DD
ENDS

SERVER_INFO_1524 STRUCT
	sv1524_minkeepcomplsearch DD
ENDS

SERVER_INFO_1525 STRUCT
	sv1525_maxkeepcomplsearch DD
ENDS

SERVER_INFO_1528 STRUCT
	sv1528_scavtimeout DD
ENDS

SERVER_INFO_1529 STRUCT
	sv1529_minrcvqueue DD
ENDS

SERVER_INFO_1530 STRUCT
	sv1530_minfreeworkitems DD
ENDS

SERVER_INFO_1533 STRUCT
	sv1533_maxmpxct DD
ENDS

SERVER_INFO_1534 STRUCT
	sv1534_oplockbreakwait DD
ENDS

SERVER_INFO_1535 STRUCT
	sv1535_oplockbreakresponsewait DD
ENDS

SERVER_INFO_1536 STRUCT
	sv1536_enableoplocks DD
ENDS

SERVER_INFO_1537 STRUCT
	sv1537_enableoplockforceclose DD
ENDS

SERVER_INFO_1538 STRUCT
	sv1538_enablefcbopens DD
ENDS

SERVER_INFO_1539 STRUCT
	sv1539_enableraw DD
ENDS

SERVER_INFO_1540 STRUCT
	sv1540_enablesharednetdrives DD
ENDS

SERVER_INFO_1541 STRUCT
	sv1541_minfreeconnections DD
ENDS

SERVER_INFO_1542 STRUCT
	sv1542_maxfreeconnections DD
ENDS

SERVER_INFO_1543 STRUCT
	sv1543_initsesstable DD
ENDS

SERVER_INFO_1544 STRUCT
	sv1544_initconntable DD
ENDS

SERVER_INFO_1545 STRUCT
	sv1545_initfiletable DD
ENDS

SERVER_INFO_1546 STRUCT
	sv1546_initsearchtable DD
ENDS

SERVER_INFO_1547 STRUCT
	sv1547_alertschedule DD
ENDS

SERVER_INFO_1548 STRUCT
	sv1548_errorthreshold DD
ENDS

SERVER_INFO_1549 STRUCT
	sv1549_networkerrorthreshold DD
ENDS

SERVER_INFO_1550 STRUCT
	sv1550_diskspacethreshold DD
ENDS

SERVER_INFO_1552 STRUCT
	sv1552_maxlinkdelay DD
ENDS

SERVER_INFO_1553 STRUCT
	sv1553_minlinkthroughput DD
ENDS

SERVER_INFO_1554 STRUCT
	sv1554_linkinfovalidtime DD
ENDS

SERVER_INFO_1555 STRUCT
	sv1555_scavqosinfoupdatetime DD
ENDS

SERVER_INFO_1556 STRUCT
	sv1556_maxworkitemidletime DD
ENDS

SERVER_INFO_1557 STRUCT
	sv1557_maxrawworkitems DD
ENDS

SERVER_INFO_1560 STRUCT
	sv1560_producttype DD
ENDS

SERVER_INFO_1561 STRUCT
	sv1561_serversize DD
ENDS

SERVER_INFO_1562 STRUCT
	sv1562_connectionlessautodisc DD
ENDS

SERVER_INFO_1563 STRUCT
	sv1563_sharingviolationretries DD
ENDS

SERVER_INFO_1564 STRUCT
	sv1564_sharingviolationdelay DD
ENDS

SERVER_INFO_1565 STRUCT
	sv1565_maxglobalopensearch DD
ENDS

SERVER_INFO_1566 STRUCT
	sv1566_removeduplicatesearches DD
ENDS

SERVER_INFO_1567 STRUCT
	sv1567_lockviolationretries DD
ENDS

SERVER_INFO_1568 STRUCT
	sv1568_lockviolationoffset DD
ENDS

SERVER_INFO_1569 STRUCT
	sv1569_lockviolationdelay DD
ENDS

SERVER_INFO_1570 STRUCT
	sv1570_mdlreadswitchover DD
ENDS

SERVER_INFO_1571 STRUCT
	sv1571_cachedopenlimit DD
ENDS

SERVER_INFO_1572 STRUCT
	sv1572_criticalthreads DD
ENDS

SERVER_INFO_1573 STRUCT
	sv1573_restrictnullsessaccess DD
ENDS

SERVER_INFO_1574 STRUCT
	sv1574_enablewfw311directipx DD
ENDS

SERVER_INFO_1575 STRUCT
	sv1575_otherqueueaffinity DD
ENDS

SERVER_INFO_1576 STRUCT
	sv1576_queuesamplesecs DD
ENDS

SERVER_INFO_1577 STRUCT
	sv1577_balancecount DD
ENDS

SERVER_INFO_1578 STRUCT
	sv1578_preferredaffinity DD
ENDS

SERVER_INFO_1579 STRUCT
	sv1579_maxfreerfcbs DD
ENDS

SERVER_INFO_1580 STRUCT
	sv1580_maxfreemfcbs DD
ENDS

SERVER_INFO_1581 STRUCT
	sv1581_maxfreemlcbs DD
ENDS

SERVER_INFO_1582 STRUCT
	sv1582_maxfreepagedpoolchunks DD
ENDS

SERVER_INFO_1583 STRUCT
	sv1583_minpagedpoolchunksize DD
ENDS

SERVER_INFO_1584 STRUCT
	sv1584_maxpagedpoolchunksize DD
ENDS

SERVER_INFO_1585 STRUCT
	sv1585_sendsfrompreferredprocessor DD
ENDS

SERVER_INFO_1586 STRUCT
	sv1586_maxthreadsperqueue DD
ENDS

SERVER_INFO_1587 STRUCT
	sv1587_cacheddirectorylimit DD
ENDS

SERVER_INFO_1588 STRUCT
	sv1588_maxcopylength DD
ENDS

SERVER_INFO_1590 STRUCT
	sv1590_enablecompression DD
ENDS

SERVER_INFO_1591 STRUCT
	sv1591_autosharewks DD
ENDS

SERVER_INFO_1592 STRUCT
	sv1592_autosharewks DD
ENDS

SERVER_INFO_1593 STRUCT
	sv1593_enablesecuritysignature DD
ENDS

SERVER_INFO_1594 STRUCT
	sv1594_requiresecuritysignature DD
ENDS

SERVER_INFO_1595 STRUCT
	sv1595_minclientbuffersize DD
ENDS

SERVER_INFO_1596 STRUCT
	sv1596_ConnectionNoSessionsTimeout DD
ENDS

SERVER_INFO_1597 STRUCT
	sv1597_IdleThreadTimeOut DD
ENDS

SERVER_INFO_1598 STRUCT
	sv1598_enableW9xsecuritysignature DD
ENDS

SERVER_TRANSPORT_INFO_0 STRUCT
	svti0_numberofvcs DD
	svti0_transportname DD
	svti0_transportaddress DD
	svti0_transportaddresslength DD
	svti0_networkaddress DD
ENDS

SERVER_TRANSPORT_INFO_1 STRUCT
	svti1_numberofvcs DD
	svti1_transportname DD
	svti1_transportaddress DD
	svti1_transportaddresslength DD
	svti1_networkaddress DD
	svti1_domain DD
ENDS

SERVER_TRANSPORT_INFO_2 STRUCT
	svti2_numberofvcs DD
	svti2_transportname DD
	svti2_transportaddress DD
	svti2_transportaddresslength DD
	svti2_networkaddress DD
	svti2_domain DD
	svti2_flags DD
ENDS

SERVER_TRANSPORT_INFO_3 STRUCT
	svti3_numberofvcs DD
	svti3_transportname DD
	svti3_transportaddress DD
	svti3_transportaddresslength DD
	svti3_networkaddress DD
	svti3_domain DD
	svti3_flags DD
	svti3_passwordlength DD
	svti3_password DB 256 DUP (?)
ENDS

#endif /* _LMSERVER_H */

