#ifndef LMSNAME_H
#define LMSNAME_H

/* Standard LAN Manager service names */

#define WORKSTATION_DISPLAY_NAME  "Workstation"
#define SERVER_DISPLAY_NAME  "Server"
#define NWSAP_DISPLAY_NAME  "NW Sap Agent"

#define SERVICE_WORKSTATION  "LanmanWorkstation"
#define SERVICE_SERVER  "LanmanServer"
#define SERVICE_BROWSER  "BROWSER"
#define SERVICE_MESSENGER  "MESSENGER"
#define SERVICE_NETRUN  "NETRUN"
#define SERVICE_SPOOLER  "SPOOLER"
#define SERVICE_ALERTER  "ALERTER"
#define SERVICE_NETLOGON  "NETLOGON"
#define SERVICE_NETPOPUP  "NETPOPUP"
#define SERVICE_SQLSERVER  "SQLSERVER"
#define SERVICE_REPL  "REPLICATOR"
#define SERVICE_RIPL  "REMOTEBOOT"
#define SERVICE_TIMESOURCE  "TIMESOURCE"
#define SERVICE_AFP  "AFP"
#define SERVICE_UPS  "UPS"
#define SERVICE_XACTSRV  "XACTSRV"
#define SERVICE_TCPIP  "TCPIP"
#define SERVICE_NBT  "NBT"
#define SERVICE_LMHOSTS  "LMHOSTS"
#define SERVICE_TELNET  "Telnet"
#define SERVICE_SCHEDULE  "Schedule"
#define SERVICE_NTLMSSP  "NtLmSsp"
#define SERVICE_DHCP  "DHCP"
#define SERVICE_NWSAP  "NwSapAgent"
#define SERVICE_NWCS  "NWCWorkstation"
#define SERVICE_DNS_CACHE  "DnsCache"
#define SERVICE_W32TIME  "w32time"
#define SERVICE_KDC  "kdc"
#define SERVICE_RPCLOCATOR  "RPCLOCATOR"
#define SERVICE_TRKSVR  "TrkSvr"
#define SERVICE_TRKWKS  "TrkWks"

#define SERVICE_LM20_WORKSTATION  "WORKSTATION"
#define SERVICE_LM20_SERVER  "SERVER"
#define SERVICE_LM20_BROWSER  SERVICE_BROWSER
#define SERVICE_LM20_MESSENGER  SERVICE_MESSENGER
#define SERVICE_LM20_NETRUN  SERVICE_NETRUN
#define SERVICE_LM20_SPOOLER  SERVICE_SPOOLER
#define SERVICE_LM20_ALERTER  SERVICE_ALERTER
#define SERVICE_LM20_NETLOGON  SERVICE_NETLOGON
#define SERVICE_LM20_NETPOPUP  SERVICE_NETPOPUP
#define SERVICE_LM20_SQLSERVER  SERVICE_SQLSERVER
#define SERVICE_LM20_REPL  SERVICE_REPL
#define SERVICE_LM20_RIPL  SERVICE_RIPL
#define SERVICE_LM20_TIMESOURCE  SERVICE_TIMESOURCE
#define SERVICE_LM20_AFP  SERVICE_AFP
#define SERVICE_LM20_UPS  SERVICE_UPS
#define SERVICE_LM20_XACTSRV  SERVICE_XACTSRV
#define SERVICE_LM20_TCPIP  SERVICE_TCPIP
#define SERVICE_LM20_NBT  SERVICE_NBT
#define SERVICE_LM20_LMHOSTS  SERVICE_LMHOSTS
#define SERVICE_LM20_TELNET  SERVICE_TELNET
#define SERVICE_LM20_SCHEDULE  SERVICE_SCHEDULE
#define SERVICE_LM20_DHCP  SERVICE_DHCP
#define SERVICE_LM20_NWSAP  SERVICE_NWSAP
#define SERVICE_LM20_W32TIME  SERVICE_W32TIME
#define SERVICE_LM20_KDC  SERVICE_KDC
#define SERVICE_LM20_RPCLOCATOR  SERVICE_RPCLOCATOR
#define SERVICE_LM20_TRKSVR  SERVICE_TRKSVR
#define SERVICE_LM20_TRKWKS  SERVICE_TRKWKS

#endif /* _LMSNAME_H */
