#ifndef NMEXPERT_H
#define NMEXPERT_H

/* Microsoft Network Monitor Experts definitions */

#define EXPERTSTRINGLENGTH  MAX_PATH
#define EXPERTGROUPNAMELENGTH  25

#define EXPERTENTRY_REGISTER  "Register"
#define EXPERTENTRY_CONFIGURE  "Configure"
#define EXPERTENTRY_RUN  "Run"

#define EXPERT_ENUM_FLAG_CONFIGURABLE  0x0001
#define EXPERT_ENUM_FLAG_VIEWER_PRIVATE  0x0002
#define EXPERT_ENUM_FLAG_NO_VIEWER  0x0004
#define EXPERT_ENUM_FLAG_ADD_ME_TO_RMC_IN_SUMMARY  0x0010
#define EXPERT_ENUM_FLAG_ADD_ME_TO_RMC_IN_DETAIL  0x0020

#define GET_SPECIFIED_FRAME  0
#define GET_FRAME_NEXT_FORWARD  1
#define GET_FRAME_NEXT_BACKWARD  2

#define FLAGS_DEFER_TO_UI_FILTER  0x1
#define FLAGS_ATTACH_PROPERTIES  0x2

#define EXPERTSUBSTATUS_ABORTED_USER  0x0001
#define EXPERTSUBSTATUS_ABORTED_LOAD_FAIL  0x0002
#define EXPERTSUBSTATUS_ABORTED_THREAD_FAIL  0x0004
#define EXPERTSUBSTATUS_ABORTED_BAD_ENTRY  0x0008

#define EXPERT_STARTUP_FLAG_USE_STARTUP_DATA_OVER_CONFIG_DATA  0x00000001

EXPERTENUMINFO STRUCT
	szName DB EXPERTSTRINGLENGTH DUP
	szVendor DB EXPERTSTRINGLENGTH DUP
	szDescription DB EXPERTSTRINGLENGTH DUP
	Version DD
	Flags DD
	szDllName DB MAX_PATH DUP
	hExpert HANDLE
	hModule HANDLE
	pRegisterProc PTR
	pConfigProc PTR
	pRunProc PTR
ENDS

GROUPINFO STRUCT
	szGroupName DB EXPERTGROUPNAMELENGTH+1 DUP
	hGroup HANDLE
ENDS

EXPERTSTARTUPINFO STRUCT
	Flags DD
	hCapture HANDLE
	szCaptureFile DB MAX_PATH DUP
	dwFrameNumber DD
	hProtocol HANDLE
	lpPropertyInst PTR
    sBitfield STRUCT
		BitNumber DB
		bOn DB
    ENDS
ENDS

EXPERTCONFIG STRUCT
	RawConfigLength DD
	RawConfigData DB
ENDS

CONFIGUREDEXPERT STRUCT
	hExpert HANDLE
	StartupFlags DD
	pConfig PTR
ENDS

EXPERTFRAMEDESCRIPTOR STRUCT
	FrameNumber DD
	hFrame HANDLE
	pFrame PTR
	lpRecognizeDataTable PTR
	lpPropertyTable PTR
ENDS

EXPERTSTATUS_INACTIVE = 0
EXPERTSTATUS_STARTING = 1
EXPERTSTATUS_RUNNING = 2
EXPERTSTATUS_PROBLEM = 3
EXPERTSTATUS_ABORTED = 4
EXPERTSTATUS_DONE = 5

EXPERTSTATUS STRUCT
	Status DD
	SubStatus DD
	PercentDone DD
	Frame DD
	szStatusText DB EXPERTSTRINGLENGTH DUP
ENDS

#endif /* _NMEXPERT_H */
