#ifndef PRSHT_H
#define PRSHT_H

#DEFINE PRSHT_H_REQVER 100

/* Windows Property Sheet definitions */

#IFDEF LINKFILES
	#dynamiclinkfile comctl32.dll
#ENDIF

/*
Switches
WIN32_IE5 (IE >= 5.00)
*/

#IFNDEF NMHDR
	NMHDR STRUCT
		hwndFrom HANDLE
		idFrom UINT_PTR
		code DD
	ENDS
#ENDIF

#define MAXPROPPAGES  100

#define PSH_DEFAULT  0x00000000
#define PSH_PROPTITLE  0x00000001
#define PSH_USEHICON  0x00000002
#define PSH_USEICONID  0x00000004
#define PSH_PROPSHEETPAGE  0x00000008
#define PSH_WIZARDHASFINISH  0x00000010
#define PSH_WIZARD  0x00000020
#define PSH_USEPSTARTPAGE  0x00000040
#define PSH_NOAPPLYNOW  0x00000080
#define PSH_USECALLBACK  0x00000100
#define PSH_HASHELP  0x00000200
#define PSH_MODELESS  0x00000400
#define PSH_RTLREADING  0x00000800
#define PSH_WIZARDCONTEXTHELP  0x00001000

#ifndef WIN32_IE5
	#define PSH_WIZARD97  0x00002000
#else
	#define PSH_WIZARD97  0x01000000
#endif

#define PSH_WATERMARK  0x00008000
#define PSH_USEHBMWATERMARK  0x00010000
#define PSH_USEHPLWATERMARK  0x00020000
#define PSH_STRETCHWATERMARK  0x00040000
#define PSH_HEADER  0x00080000
#define PSH_USEHBMHEADER  0x00100000
#define PSH_USEPAGELANG  0x00200000
#define PSH_WIZARD_LITE  0x00400000
#define PSH_NOCONTEXTHELP  0x02000000

#define PSP_DEFAULT  0x00000000
#define PSP_DLGINDIRECT  0x00000001
#define PSP_USEHICON  0x00000002
#define PSP_USEICONID  0x00000004
#define PSP_USETITLE  0x00000008
#define PSP_RTLREADING  0x00000010
#define PSP_HASHELP  0x00000020
#define PSP_USEREFPARENT  0x00000040
#define PSP_USECALLBACK  0x00000080
#define PSP_PREMATURE  0x00000400
#define PSP_HIDEHEADER  0x00000800
#define PSP_USEHEADERTITLE  0x00001000
#define PSP_USEHEADERSUBTITLE  0x00002000
#define PSPCB_ADDREF  0
#define PSPCB_RELEASE  1
#define PSPCB_CREATE  2

#define PSCB_INITIALIZED  1
#define PSCB_PRECREATE  2

#define PSN_FIRST  -200
#define PSN_LAST  -299

#define PSN_SETACTIVE  (PSN_FIRST-0)
#define PSN_KILLACTIVE  (PSN_FIRST-1)
#define PSN_APPLY  (PSN_FIRST-2)
#define PSN_RESET  (PSN_FIRST-3)
#define PSN_HELP  (PSN_FIRST-5)
#define PSN_WIZBACK  (PSN_FIRST-6)
#define PSN_WIZNEXT  (PSN_FIRST-7)
#define PSN_WIZFINISH  (PSN_FIRST-8)
#define PSN_QUERYCANCEL  (PSN_FIRST-9)
#define PSN_GETOBJECT  (PSN_FIRST-10)
#define PSN_TRANSLATEACCELERATOR  (PSN_FIRST-12)
#define PSN_QUERYINITIALFOCUS  (PSN_FIRST-13)

#define PSNRET_NOERROR  0
#define PSNRET_INVALID  1
#define PSNRET_INVALID_NOCHANGEPAGE  2
#define PSNRET_MESSAGEHANDLED  3

#define PSM_SETCURSEL  (WM_USER+101)
#define PSM_REMOVEPAGE  (WM_USER+102)
#define PSM_ADDPAGE  (WM_USER+103)
#define PSM_CHANGED  (WM_USER+104)
#define PSM_RESTARTWINDOWS  (WM_USER+105)
#define PSM_REBOOTSYSTEM  (WM_USER+106)
#define PSM_CANCELTOCLOSE  (WM_USER+107)
#define PSM_QUERYSIBLINGS  (WM_USER+108)
#define PSM_UNCHANGED  (WM_USER+109)
#define PSM_APPLY  (WM_USER+110)
#define PSM_SETTITLEA  (WM_USER+111)
#define PSM_SETTITLEW  (WM_USER+120)
#define PSM_SETWIZBUTTONS  (WM_USER+112)
#define PSM_PRESSBUTTON  (WM_USER+113)
#define PSM_SETCURSELID  (WM_USER+114)
#define PSM_SETFINISHTEXTA  (WM_USER+115)
#define PSM_SETFINISHTEXTW  (WM_USER+121)
#define PSM_GETTABCONTROL  (WM_USER+116)
#define PSM_ISDIALOGMESSAGE  (WM_USER+117)
#define PSM_GETCURRENTPAGEHWND  (WM_USER+118)
#define PSM_INSERTPAGE  (WM_USER+119)
#define PSM_SETHEADERTITLEA  (WM_USER+125)
#define PSM_SETHEADERTITLEW  (WM_USER+126)
#define PSM_SETHEADERSUBTITLEA  (WM_USER+127)
#define PSM_SETHEADERSUBTITLEW  (WM_USER+128)
#define PSM_HWNDTOINDEX  (WM_USER+129)
#define PSM_INDEXTOHWND  (WM_USER+130)
#define PSM_PAGETOINDEX  (WM_USER+131)
#define PSM_INDEXTOPAGE  (WM_USER+132)
#define PSM_IDTOINDEX  (WM_USER+133)
#define PSM_INDEXTOID  (WM_USER+134)
#define PSM_GETRESULT  (WM_USER+135)
#define PSM_RECALCPAGESIZES  (WM_USER+136)

#define PSWIZB_BACK  0x00000001
#define PSWIZB_NEXT  0x00000002
#define PSWIZB_FINISH  0x00000004
#define PSWIZB_DISABLEDFINISH  0x00000008

#define PSBTN_BACK  0
#define PSBTN_NEXT  1
#define PSBTN_FINISH  2
#define PSBTN_OK  3
#define PSBTN_APPLYNOW  4
#define PSBTN_CANCEL  5
#define PSBTN_HELP  6
#define PSBTN_MAX  6

#define ID_PSRESTARTWINDOWS  0x2
#define ID_PSREBOOTSYSTEM  (ID_PSRESTARTWINDOWS|0x1)

#define WIZ_CXDLG  276
#define WIZ_CYDLG  140
#define WIZ_CXBMP  80
#define WIZ_BODYX  92
#define WIZ_BODYCX  184

#define PROP_SM_CXDLG  212
#define PROP_SM_CYDLG  188
#define PROP_MED_CXDLG  227
#define PROP_MED_CYDLG  215
#define PROP_LG_CXDLG  252
#define PROP_LG_CYDLG  218

PROPSHEETPAGEA STRUCT
	dwSize DD
	dwFlags DD
	hInstance HANDLE
    UNION
		pszTemplate PTR
		pResource PTR
    ENDUNION
    UNION
		hIcon HANDLE
		pszIcon PTR
    ENDUNION
	pszTitle PTR
	pfnDlgProc PTR
	lParam LPARAM
	pfnCallback PTR
	pcRefParent PTR
	pszHeaderTitle PTR
	pszHeaderSubTitle PTR
ENDS

PROPSHEETPAGEW STRUCT
	dwSize DD
	dwFlags DD
	hInstance HANDLE
    UNION
		pszTemplate PTR
		pResource PTR
    ENDUNION
    UNION
		hIcon HANDLE
		pszIcon PTR
    ENDUNION
	pszTitle PTR
	pfnDlgProc PTR
	lParam LPARAM
	pfnCallback PTR
	pcRefParent PTR
	pszHeaderTitle PTR
	pszHeaderSubTitle PTR
ENDS

PROPSHEETHEADERA STRUCT
	dwSize DD
	dwFlags DD
	hwndParent HANDLE
	hInstance HANDLE
    UNION
		hIcon HANDLE
		pszIcon PTR
    ENDUNION
	pszCaption PTR
	nPages DD
    UNION
		nStartPage DD
		pStartPage PTR
    ENDUNION
    UNION
		ppsp PTR
		phpage PTR
    ENDUNION
	pfnCallback PTR
    UNION
		hbmWatermark HANDLE
		pszbmWatermark PTR
    ENDUNION
	hplWatermark HANDLE
    UNION
		hbmHeader HANDLE
		pszbmHeader PTR
    ENDUNION
ENDS

PROPSHEETHEADERW STRUCT
	dwSize DD
	dwFlags DD
	hwndParent HANDLE
	hInstance HANDLE
    UNION
		hIcon HANDLE
		pszIcon PTR
    ENDUNION
	pszCaption PTR
	nPages DD
    UNION
		nStartPage DD
		pStartPage PTR
    ENDUNION
    UNION
		ppsp PTR
		phpage PTR
    ENDUNION
	pfnCallback PTR
    UNION
		hbmWatermark HANDLE
		pszbmWatermark PTR
    ENDUNION
	hplWatermark HANDLE
    UNION
		hbmHeader HANDLE
		pszbmHeader PTR
    ENDUNION
ENDS

PSHNOTIFY STRUCT
	hdr NMHDR <>
	lParam LPARAM
ENDS

#IFDEF UNICODE
	#define PROPSHEETPAGE PROPSHEETPAGEW
	#define PROPSHEETHEADER PROPSHEETHEADERW
	#define PROPSHEETHEADER_V1_SIZE PROPSHEETHEADERW_V1_SIZE
	#define CreatePropertySheetPage CreatePropertySheetPageW
	#define PropertySheet PropertySheetW
	#define PSM_SETTITLE PSM_SETTITLEW
	#define PSM_SETFINISHTEXT PSM_SETFINISHTEXTW
	#define PSM_SETHEADERTITLE PSM_SETHEADERTITLEW
	#define PSM_SETHEADERSUBTITLE PSM_SETHEADERSUBTITLEW
#else
	#define PROPSHEETPAGE PROPSHEETPAGEA
	#define PROPSHEETHEADER PROPSHEETHEADERA
	#define PROPSHEETHEADER_V1_SIZE PROPSHEETHEADERA_V1_SIZE
	#define CreatePropertySheetPage CreatePropertySheetPageA
	#define PropertySheet PropertySheetA
	#define PSM_SETTITLE PSM_SETTITLEA
	#define PSM_SETFINISHTEXT PSM_SETFINISHTEXTA
	#define PSM_SETHEADERTITLE PSM_SETHEADERTITLEA
	#define PSM_SETHEADERSUBTITLE PSM_SETHEADERSUBTITLEA
#endif /* UNICODE */

#endif /* _PRSHT_H */

