#ifndef VFW_H
#define VFW_H

/* Windows Video definitions */

#IFNDEF MMSYSTEM_H
	#include mmsystem.h
#ENDIF

#IFNDEF BASECOM_H
	#include "BaseCOM.h"
#ENDIF

#IFNDEF MAKEFOURCC
	MAKEFOURCC(%1,%2,%3,%4,%5) MACRO
		%1 equ  %2|(%3<<8)|(%4<<16)|(%5<<24)
	ENDM
#ENDIF

#define BI_1632  0x32333631

#IFNDEF aviTWOCC
	aviTWOCC(%1,%2,%3) MACRO
		%1 equ %2|(%3<<8)
	ENDM
#ENDIF

#ifndef ICTYPE_VIDEO
	#define ICTYPE_VIDEO  A'vidc'
	#define ICTYPE_AUDIO  A'audc'
#endif

#ifndef ICERR_OK
	#define ICERR_OK  0
	#define ICERR_DONTDRAW  1
	#define ICERR_NEWPALETTE  2
	#define ICERR_GOTOKEYFRAME  3
	#define ICERR_STOPDRAWING  4
	#define ICERR_UNSUPPORTED  -1
	#define ICERR_BADFORMAT  -2
	#define ICERR_MEMORY  -3
	#define ICERR_INTERNAL  -4
	#define ICERR_BADFLAGS  -5
	#define ICERR_BADPARAM  -6
	#define ICERR_BADSIZE  -7
	#define ICERR_BADHANDLE  -8
	#define ICERR_CANTUPDATE  -9
	#define ICERR_ABORT  -10
	#define ICERR_ERROR  -100
	#define ICERR_BADBITDEPTH  -200
	#define ICERR_BADIMAGESIZE  -201
	#define ICERR_CUSTOM  -400
#endif

#ifndef ICMODE_COMPRESS
	#define ICMODE_COMPRESS  1
	#define ICMODE_DECOMPRESS  2
	#define ICMODE_FASTDECOMPRESS  3
	#define ICMODE_QUERY  4
	#define ICMODE_FASTCOMPRESS  5
	#define ICMODE_DRAW  8
#endif

#define AVIIF_LIST  0x00000001
#define AVIIF_TWOCC  0x00000002
#define AVIIF_KEYFRAME  0x00000010
#define AVIIF_FIRSTPART  0x00000020
#define AVIIF_LASTPART  0x00000040
#define AVIIF_MIDPART  (AVIIF_LASTPART|AVIIF_FIRSTPART)
#define AVIIF_NOTIME  0x00000100
#define AVIIF_COMPUSE  0x0FFF0000

#define ICQUALITY_LOW  0
#define ICQUALITY_HIGH  10000
#define ICQUALITY_DEFAULT  -1

#define ICM_USER  (DRV_USER+0x0000)

#define ICM_RESERVED  ICM_RESERVED_LOW
#define ICM_RESERVED_LOW  (DRV_USER+0x1000)
#define ICM_RESERVED_HIGH (DRV_USER+0x2000)

#define ICM_GETSTATE  (ICM_RESERVED+0)
#define ICM_SETSTATE  (ICM_RESERVED+1)
#define ICM_GETINFO  (ICM_RESERVED+2)
#define ICM_CONFIGURE  (ICM_RESERVED+10)
#define ICM_ABOUT  (ICM_RESERVED+11)
#define ICM_GETERRORTEXT  (ICM_RESERVED+12)
#define ICM_GETFORMATNAME  (ICM_RESERVED+20)
#define ICM_ENUMFORMATS  (ICM_RESERVED+21)
#define ICM_GETDEFAULTQUALITY  (ICM_RESERVED+30)
#define ICM_GETQUALITY  (ICM_RESERVED+31)
#define ICM_SETQUALITY  (ICM_RESERVED+32)
#define ICM_SET  (ICM_RESERVED+40)
#define ICM_GET  (ICM_RESERVED+41)

#define ICM_FRAMERATE  A'FrmR'
#define ICM_KEYFRAMERATE  A'KeyR'

#define ICM_COMPRESS_GET_FORMAT  (ICM_USER+4)
#define ICM_COMPRESS_GET_SIZE  (ICM_USER+5)
#define ICM_COMPRESS_QUERY  (ICM_USER+6)
#define ICM_COMPRESS_BEGIN  (ICM_USER+7)
#define ICM_COMPRESS  (ICM_USER+8)
#define ICM_COMPRESS_END  (ICM_USER+9)
#define ICM_DECOMPRESS_GET_FORMAT  (ICM_USER+10)
#define ICM_DECOMPRESS_QUERY  (ICM_USER+11)
#define ICM_DECOMPRESS_BEGIN  (ICM_USER+12)
#define ICM_DECOMPRESS  (ICM_USER+13)
#define ICM_DECOMPRESS_END  (ICM_USER+14)
#define ICM_DECOMPRESS_SET_PALETTE  (ICM_USER+29)
#define ICM_DECOMPRESS_GET_PALETTE  (ICM_USER+30)
#define ICM_DRAW_QUERY  (ICM_USER+31)
#define ICM_DRAW_BEGIN  (ICM_USER+15)
#define ICM_DRAW_GET_PALETTE  (ICM_USER+16)
#define ICM_DRAW_UPDATE  (ICM_USER+17)
#define ICM_DRAW_START  (ICM_USER+18)
#define ICM_DRAW_STOP  (ICM_USER+19)
#define ICM_DRAW_BITS  (ICM_USER+20)
#define ICM_DRAW_END  (ICM_USER+21)
#define ICM_DRAW_GETTIME  (ICM_USER+32)
#define ICM_DRAW  (ICM_USER+33)
#define ICM_DRAW_WINDOW  (ICM_USER+34)
#define ICM_DRAW_SETTIME  (ICM_USER+35)
#define ICM_DRAW_REALIZE  (ICM_USER+36)
#define ICM_DRAW_FLUSH  (ICM_USER+37)
#define ICM_DRAW_RENDERBUFFER  (ICM_USER+38)
#define ICM_DRAW_START_PLAY  (ICM_USER+39)
#define ICM_DRAW_STOP_PLAY  (ICM_USER+40)
#define ICM_DRAW_SUGGESTFORMAT  (ICM_USER+50)
#define ICM_DRAW_CHANGEPALETTE  (ICM_USER+51)
#define ICM_DRAW_IDLE  (ICM_USER+52)
#define ICM_GETBUFFERSWANTED  (ICM_USER+41)
#define ICM_GETDEFAULTKEYFRAMERATE  (ICM_USER+42)
#define ICM_DECOMPRESSEX_BEGIN  (ICM_USER+60)
#define ICM_DECOMPRESSEX_QUERY  (ICM_USER+61)
#define ICM_DECOMPRESSEX  (ICM_USER+62)
#define ICM_DECOMPRESSEX_END  (ICM_USER+63)
#define ICM_COMPRESS_FRAMES_INFO  (ICM_USER+70)
#define ICM_COMPRESS_FRAMES  (ICM_USER+71)
#define ICM_SET_STATUS_PROC  (ICM_USER+72)

#define VIDCF_QUALITY  0x0001
#define VIDCF_CRUNCH  0x0002
#define VIDCF_TEMPORAL  0x0004
#define VIDCF_COMPRESSFRAMES 0x0008
#define VIDCF_DRAW  0x0010
#define VIDCF_FASTTEMPORALC  0x0020
#define VIDCF_FASTTEMPORALD  0x0080

#define ICCOMPRESS_KEYFRAME  0x00000001

#define ICCOMPRESSFRAMES_PADDING  0x00000001

#define ICSTATUS_START  0
#define ICSTATUS_STATUS  1
#define ICSTATUS_END  2
#define ICSTATUS_ERROR  3
#define ICSTATUS_YIELD  4

#define ICDECOMPRESS_HURRYUP  0x80000000
#define ICDECOMPRESS_UPDATE  0x40000000
#define ICDECOMPRESS_PREROLL  0x20000000
#define ICDECOMPRESS_NULLFRAME  0x10000000
#define ICDECOMPRESS_NOTKEYFRAME  0x08000000

#define ICDRAW_QUERY  0x00000001
#define ICDRAW_FULLSCREEN  0x00000002
#define ICDRAW_HDC  0x00000004
#define ICDRAW_ANIMATE  0x00000008
#define ICDRAW_CONTINUE  0x00000010
#define ICDRAW_MEMORYDC  0x00000020
#define ICDRAW_UPDATING  0x00000040
#define ICDRAW_RENDER  0x00000080
#define ICDRAW_BUFFER  0x00000100

#define ICDRAW_HURRYUP  0x80000000
#define ICDRAW_UPDATE  0x40000000
#define ICDRAW_PREROLL  0x20000000
#define ICDRAW_NULLFRAME  0x10000000
#define ICDRAW_NOTKEYFRAME  0x08000000

#define ICINSTALL_UNICODE  0x8000
#define ICINSTALL_FUNCTION  0x0001
#define ICINSTALL_DRIVER  0x0002
#define ICINSTALL_HDRV  0x0004
#define ICINSTALL_DRIVERW  0x8002

#define ICMF_CONFIGURE_QUERY  0x00000001
#define ICMF_ABOUT_QUERY  0x00000001

#define ICDECOMPRESS_HURRYUP  0x80000000

#define ICMF_COMPVARS_VALID  0x00000001

#define ICMF_CHOOSE_KEYFRAME  0x0001
#define ICMF_CHOOSE_DATARATE  0x0002
#define ICMF_CHOOSE_PREVIEW  0x0004
#define ICMF_CHOOSE_ALLCOMPRESSORS  0x0008

#define DDF_0001  0x0001
#define DDF_UPDATE  0x0002
#define DDF_SAME_HDC  0x0004
#define DDF_SAME_DRAW  0x0008
#define DDF_DONTDRAW  0x0010
#define DDF_ANIMATE  0x0020
#define DDF_BUFFER  0x0040
#define DDF_JUSTDRAWIT  0x0080
#define DDF_FULLSCREEN  0x0100
#define DDF_BACKGROUNDPAL  0x0200
#define DDF_NOTKEYFRAME  0x0400
#define DDF_HURRYUP  0x0800
#define DDF_HALFTONE  0x1000
#define DDF_2000  0x2000

#define DDF_PREROLL  DDF_DONTDRAW
#define DDF_SAME_DIB  DDF_SAME_DRAW
#define DDF_SAME_SIZE  DDF_SAME_DRAW

#define PD_CAN_DRAW_DIB  0x0001
#define PD_CAN_STRETCHDIB  0x0002
#define PD_STRETCHDIB_1_1_OK  0x0004
#define PD_STRETCHDIB_1_2_OK  0x0008
#define PD_STRETCHDIB_1_N_OK  0x0010


#define formtypeAVI  A'AVI '
#define listtypeAVIHEADER  A'hdrl'
#define ckidAVIMAINHDR  A'avih'
#define listtypeSTREAMHEADER  A'strl'
#define ckidSTREAMHEADER  A'strh'
#define ckidSTREAMFORMAT  A'strf'
#define ckidSTREAMHANDLERDATA  A'strd'
#define ckidSTREAMNAME  A'strn'

#define listtypeAVIMOVIE  A'movi'
#define listtypeAVIRECORD  A'rec '

#define ckidAVINEWINDEX  A'idx1'

#define streamtypeVIDEO  A'vids'
#define streamtypeAUDIO  A'auds'
#define streamtypeMIDI  A'mids'
#define streamtypeTEXT  A'txts'

#define cktypeDIBbits  A'db'
#define cktypeDIBcompressed  A'dc'
#define cktypePALchange  A'pc'
#define cktypeWAVEbytes  A'wb'

#define ckidAVIPADDING  A'JUNK'

#define AVIF_HASINDEX  0x00000010
#define AVIF_MUSTUSEINDEX  0x00000020
#define AVIF_ISINTERLEAVED  0x00000100
#define AVIF_WASCAPTUREFILE  0x00010000
#define AVIF_COPYRIGHTED  0x00020000

#define AVI_HEADERSIZE  2048

#define AVISF_DISABLED  0x00000001
#define AVISF_VIDEO_PALCHANGES  0x00010000

ICOPEN STRUCT
	dwSize DD
	fccType DD
	fccHandler DD
	dwVersion DD
	dwFlags DD
	dwError DD
	pV1Reserved PTR
	pV2Reserved PTR
	dnDevNode DD
ENDS

ICINFO STRUCT
	dwSize DD
	fccType DD
	fccHandler DD
	dwFlags DD
	dwVersion DD
	dwVersionICM DD
	szName DW 16 DUP
	szDescription DW 128 DUP
	szDriver DW 128 DUP
ENDS

ICCOMPRESS STRUCT
	dwFlags DD
	lpbiOutput PTR
	lpOutput PTR
	lpbiInput PTR
	lpInput PTR
	lpckid PTR
	lpdwFlags PTR
	lFrameNum DD
	dwFrameSize DD
	dwQuality DD
	lpbiPrev PTR
	lpPrev PTR
ENDS

ICCOMPRESSFRAMES STRUCT
	dwFlags DD
	lpbiOutput PTR
	lOutput LPARAM
	lpbiInput PTR
	lInput LPARAM
	lStartFrame DD
	lFrameCount DD
	lQuality DD
	lDataRate DD
	lKeyRate DD
	dwRate DD
	dwScale DD
	dwOverheadPerFrame DD
	dwReserved2 DD
	GetData PTR
	PutData PTR
ENDS

ICSETSTATUSPROC STRUCT
	dwFlags DD
	lParam LPARAM
	fpfnStatus PTR
ENDS

ICDECOMPRESS STRUCT
	dwFlags DD
	lpbiInput PTR
	lpInput PTR
	lpbiOutput PTR
	lpOutput PTR
	ckid DD
ENDS

ICDECOMPRESSEX STRUCT
	dwFlags DD
	lpbiSrc PTR
	lpSrc PTR
	lpbiDst PTR
	lpDst PTR
	xDst DD
	yDst DD
	dxDst DD
	dyDst DD
	xSrc DD
	ySrc DD
	dxSrc DD
	dySrc DD
ENDS

ICDRAWBEGIN STRUCT
	dwFlags DD
	hpal HANDLE
	hwnd HANDLE
	hdc HANDLE
	xDst DD
	yDst DD
	dxDst DD
	dyDst DD
	lpbi PTR
	xSrc DD
	ySrc DD
	dxSrc DD
	dySrc DD
	dwRate DD
	dwScale DD
ENDS

ICDRAW STRUCT
	dwFlags DD
	lpFormat PTR
	lpData PTR
	cbData DD
	lTime DD
ENDS

ICDRAWSUGGEST STRUCT
	lpbiIn PTR
	lpbiSuggest PTR
	dxSrc DD
	dySrc DD
	dxDst DD
	dyDst DD
	hicDecompressor HANDLE
ENDS

ICPALETTE STRUCT
	dwFlags DD
	iStart DD
	iLen DD
	lppe PTR
ENDS

COMPVARS STRUCT
	cbSize DD
	dwFlags DD
	hic HANDLE
	fccType DD
	fccHandler DD
	lpbiIn PTR
	lpbiOut PTR
	lpBitsOut PTR
	lpBitsPrev PTR
	lFrame DD
	lKey DD
	lDataRate DD
	lQ DD
	lKeyCount DD
	lpState PTR
	cbState DD
ENDS

DRAWDIBTIME STRUCT
	timeCount DD
	timeDraw DD
	timeDecompress DD
	timeDither DD
	timeStretch DD
	timeBlt DD
	timeSetDIBits DD
ENDS

MainAVIHeader STRUCT
	dwMicroSecPerFrame DD
	dwMaxBytesPerSec DD
	dwPaddingGranularity DD
	dwFlags DD
	dwTotalFrames DD
	dwInitialFrames DD
	dwStreams DD
	dwSuggestedBufferSize DD
	dwWidth DD
	dwHeight DD
	dwReserved DD 4 DUP
ENDS

AVIStreamHeader STRUCT
	fccType DD
	fccHandler DD
	dwFlags DD
	wPriority DW
	wLanguage DW
	dwInitialFrames DD
	dwScale DD
	dwRate DD
	dwStart DD
	dwLength DD
	dwSuggestedBufferSize DD
	dwQuality DD
	dwSampleSize DD
	rcFrame RECT
ENDS

AVIINDEXENTRY STRUCT
	ckid DD
	dwFlags DD
	dwChunkOffset DD
	dwChunkLength DD
ENDS

AVIPALCHANGE STRUCT
	bFirstEntry DB
	bNumEntries DB
	wFlags DW
	peNew PALETTEENTRY
ENDS

#define AVIGETFRAMEF_BESTDISPLAYFMT  1

#define AVISTREAMINFO_DISABLED  0x00000001
#define AVISTREAMINFO_FORMATCHANGES  0x00010000

#define AVIFILEINFO_HASINDEX  0x00000010
#define AVIFILEINFO_MUSTUSEINDEX  0x00000020
#define AVIFILEINFO_ISINTERLEAVED  0x00000100
#define AVIFILEINFO_WASCAPTUREFILE  0x00010000
#define AVIFILEINFO_COPYRIGHTED  0x00020000

#define AVIFILECAPS_CANREAD  0x00000001
#define AVIFILECAPS_CANWRITE  0x00000002
#define AVIFILECAPS_ALLKEYFRAMES  0x00000010
#define AVIFILECAPS_NOCOMPRESSION  0x00000020

#define AVICOMPRESSF_INTERLEAVE  0x00000001
#define AVICOMPRESSF_DATARATE  0x00000002
#define AVICOMPRESSF_KEYFRAMES  0x00000004
#define AVICOMPRESSF_VALID  0x00000008

AVISTREAMINFOW STRUCT
	fccType DD
	fccHandler DD
	dwFlags DD
	dwCaps DD
	wPriority DW
	wLanguage DW
	dwScale DD
	dwRate DD
	dwStart DD
	dwLength DD
	dwInitialFrames DD
	dwSuggestedBufferSize DD
	dwQuality DD
	dwSampleSize DD
	rcFrame RECT
	dwEditCount DD
	dwFormatChangeCount DD
	szName DW 64 DUP
ENDS

AVISTREAMINFOA STRUCT
	fccType DD
	fccHandler DD
	dwFlags DD
	dwCaps DD
	wPriority DW
	wLanguage DW
	dwScale DD
	dwRate DD
	dwStart DD
	dwLength DD
	dwInitialFrames DD
	dwSuggestedBufferSize DD
	dwQuality DD
	dwSampleSize DD
	rcFrame RECT
	dwEditCount DD
	dwFormatChangeCount DD
	szName DB 64 DUP
ENDS

AVIFILEINFOW STRUCT
	dwMaxBytesPerSec DD
	dwFlags DD
	dwCaps DD
	dwStreams DD
	dwSuggestedBufferSize DD
	dwWidth DD
	dwHeight DD
	dwScale DD
	dwRate DD
	dwLength DD
	dwEditCount DD
	szFileType DW 64 DUP
ENDS

AVIFILEINFOA STRUCT
	dwMaxBytesPerSec DD
	dwFlags DD
	dwCaps DD
	dwStreams DD
	dwSuggestedBufferSize DD
	dwWidth DD
	dwHeight DD
	dwScale DD
	dwRate DD
	dwLength DD
	dwEditCount DD
	szFileType DB 64 DUP
ENDS

AVICOMPRESSOPTIONS STRUCT
	fccType DD
	fccHandler DD
	dwKeyFrameEvery DD
	dwQuality DD
	dwBytesPerSecond DD
	dwFlags DD
	lpFormat PTR
	cbFormat DD
	lpParms PTR
	cbParms DD
	dwInterleaveEvery DD
ENDS

#IFDEF UNICODE
	#define AVISTREAMINFO AVISTREAMINFOW
	#define AVIFILEINFO AVIFILEINFOW
#else
	#define AVISTREAMINFO AVISTREAMINFOA
	#define AVIFILEINFO AVIFILEINFOA
#endif

#define GUID_IID_IAVIFile <0x00020020,0,0,<0xC0,0,0,0,0,0,0,0x46>>
#define GUID_IID_IAVIStream <0x00020021,0,0,<0xC0,0,0,0,0,0,0,0x46>>
#define GUID_IID_IAVIStreaming <0x00020022,0,0,<0xC0,0,0,0,0,0,0,0x46>>
#define GUID_IID_IGetFrame <0x00020023,0,0,<0xC0,0,0,0,0,0,0,0x46>>
#define GUID_IID_IAVIEditStream <0x00020024,0,0,<0xC0,0,0,0,0,0,0,0x46>>
#define GUID_CLSID_AVISimpleUnMarshal <0x00020009,0,0,<0xC0,0,0,0,0,0,0,0x46>>
#define GUID_CLSID_AVIFile <0x00020000,0,0,<0xC0,0,0,0,0,0,0,0x46>>

#define AVIFILEHANDLER_CANREAD  0x0001
#define AVIFILEHANDLER_CANWRITE  0x0002
#define AVIFILEHANDLER_CANACCEPTNONRGB  0x0004

#define AVISTREAMREAD_CONVENIENT -1

#define FIND_DIR  0x0000000F
#define FIND_NEXT  0x00000001
#define FIND_PREV  0x00000004
#define FIND_FROM_START 0x00000008

#define FIND_TYPE  0x000000F0
#define FIND_KEY  0x00000010
#define FIND_ANY  0x00000020
#define FIND_FORMAT  0x00000040

#define FIND_RET  0x0000F000
#define FIND_POS  0x00000000
#define FIND_LENGTH  0x00001000
#define FIND_OFFSET  0x00002000
#define FIND_SIZE  0x00003000
#define FIND_INDEX  0x00004000

#define SEARCH_NEAREST  FIND_PREV
#define SEARCH_BACKWARD FIND_PREV
#define SEARCH_FORWARD  FIND_NEXT
#define SEARCH_KEY  FIND_KEY
#define SEARCH_ANY  FIND_ANY

#ifndef AVIERR_OK
	#define AVIERR_OK  0
	#define AVIERR_UNSUPPORTED  (1<<31)|(4<<16)|(101)
	#define AVIERR_BADFORMAT  (1<<31)|(4<<16)|(102)
	#define AVIERR_MEMORY  (1<<31)|(4<<16)|(103)
	#define AVIERR_INTERNAL  (1<<31)|(4<<16)|(104)
	#define AVIERR_BADFLAGS  (1<<31)|(4<<16)|(105)
	#define AVIERR_BADPARAM  (1<<31)|(4<<16)|(106)
	#define AVIERR_BADSIZE  (1<<31)|(4<<16)|(107)
	#define AVIERR_BADHANDLE  (1<<31)|(4<<16)|(108)
	#define AVIERR_FILEREAD  (1<<31)|(4<<16)|(109)
	#define AVIERR_FILEWRITE  (1<<31)|(4<<16)|(110)
	#define AVIERR_FILEOPEN  (1<<31)|(4<<16)|(111)
	#define AVIERR_COMPRESSOR  (1<<31)|(4<<16)|(112)
	#define AVIERR_NOCOMPRESSOR  (1<<31)|(4<<16)|(113)
	#define AVIERR_READONLY  (1<<31)|(4<<16)|(114)
	#define AVIERR_NODATA  (1<<31)|(4<<16)|(115)
	#define AVIERR_BUFFERTOOSMALL  (1<<31)|(4<<16)|(116)
	#define AVIERR_CANTCOMPRESS  (1<<31)|(4<<16)|(117)
	#define AVIERR_USERABORT  (1<<31)|(4<<16)|(198)
	#define AVIERR_ERROR  (1<<31)|(4<<16)|(199)
#endif

IAVIStream STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Create PTR
	Info PTR
	FindSample PTR
	ReadFormat PTR
	SetFormat PTR
	Read PTR
	Write PTR
	Delete PTR
	ReadData PTR
	WriteData PTR
	SetInfo PTR
ENDS

IAVIStreaming STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Begin PTR
	End PTR
ENDS

IAVIEditStream STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Cut PTR
	Copy PTR
	Paste PTR
	Clone PTR
	SetInfo PTR
ENDS

IAVIFile STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Info PTR
	GetStream PTR
	CreateStream PTR
	WriteData PTR
	ReadData PTR
	EndRecord PTR
	DeleteStream PTR
ENDS

IGetFrame STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetFrame PTR
	Begin PTR
	End PTR
	SetFormat PTR
ENDS

#IFDEF UNICODE
	#define AVIFileOpen AVIFileOpenW
	#define AVIFileInfo AVIFileInfoW
	#define AVIFileCreateStream AVIFileCreateStreamW
	#define AVIStreamInfo AVIStreamInfoW
	#define AVIStreamOpenFromFile AVIStreamOpenFromFileW
	#define AVISave AVISaveW
	#define AVISaveV AVISaveVW
	#define AVIBuildFilter AVIBuildFilterW
	#define EditStreamSetInfo EditStreamSetInfoW
	#define EditStreamSetName EditStreamSetNameW
#else
	#define AVIFileOpen AVIFileOpenA
	#define AVIFileInfo AVIFileInfoA
	#define AVIFileCreateStream AVIFileCreateStreamA
	#define AVIStreamInfo AVIStreamInfoA
	#define AVIStreamOpenFromFile AVIStreamOpenFromFileA
	#define AVISave AVISaveA
	#define AVISaveV AVISaveVA
	#define AVIBuildFilter AVIBuildFilterA
	#define EditStreamSetInfo EditStreamSetInfoA
	#define EditStreamSetName EditStreamSetNameA
#endif

#define AVIStreamFindKeyFrame  AVIStreamFindSample
#define FindKeyFrame  FindSample

#define AVIStreamClose AVIStreamRelease
#define AVIFileClose  AVIFileRelease
#define AVIStreamInit  AVIFileInit
#define AVIStreamExit  AVIFileExit

#ifndef comptypeDIB
	#define comptypeDIB  A'DIB '
#endif

#define MCIWNDOPENF_NEW  0x0001

#define MCIWNDF_NOAUTOSIZEWINDOW  0x0001
#define MCIWNDF_NOPLAYBAR  0x0002
#define MCIWNDF_NOAUTOSIZEMOVIE  0x0004
#define MCIWNDF_NOMENU  0x0008
#define MCIWNDF_SHOWNAME  0x0010
#define MCIWNDF_SHOWPOS  0x0020
#define MCIWNDF_SHOWMODE  0x0040
#define MCIWNDF_SHOWALL  0x0070
#define MCIWNDF_NOTIFYMODE  0x0100
#define MCIWNDF_NOTIFYPOS  0x0200
#define MCIWNDF_NOTIFYSIZE  0x0400
#define MCIWNDF_NOTIFYERROR  0x1000
#define MCIWNDF_NOTIFYALL  0x1F00
#define MCIWNDF_NOTIFYANSI  0x0080
#define MCIWNDF_NOTIFYMEDIAA  0x0880
#define MCIWNDF_NOTIFYMEDIAW  0x0800
#define MCIWNDF_RECORD  0x2000
#define MCIWNDF_NOERRORDLG  0x4000
#define MCIWNDF_NOOPEN  0x8000

#define MCIWNDM_GETDEVICEID  (WM_USER+100)
#define MCIWNDM_GETSTART  (WM_USER+103)
#define MCIWNDM_GETLENGTH  (WM_USER+104)
#define MCIWNDM_GETEND  (WM_USER+105)
#define MCIWNDM_EJECT  (WM_USER+107)
#define MCIWNDM_SETZOOM  (WM_USER+108)
#define MCIWNDM_GETZOOM  (WM_USER+109)
#define MCIWNDM_SETVOLUME  (WM_USER+110)
#define MCIWNDM_GETVOLUME  (WM_USER+111)
#define MCIWNDM_SETSPEED  (WM_USER+112)
#define MCIWNDM_GETSPEED  (WM_USER+113)
#define MCIWNDM_SETREPEAT  (WM_USER+114)
#define MCIWNDM_GETREPEAT  (WM_USER+115)
#define MCIWNDM_REALIZE  (WM_USER+118)
#define MCIWNDM_VALIDATEMEDIA  (WM_USER+121)
#define MCIWNDM_PLAYFROM  (WM_USER+122)
#define MCIWNDM_PLAYTO  (WM_USER+123)
#define MCIWNDM_GETPALETTE  (WM_USER+126)
#define MCIWNDM_SETPALETTE  (WM_USER+127)
#define MCIWNDM_SETTIMERS  (WM_USER+129)
#define MCIWNDM_SETACTIVETIMER  (WM_USER+130)
#define MCIWNDM_SETINACTIVETIMER (WM_USER+131)
#define MCIWNDM_GETACTIVETIMER  (WM_USER+132)
#define MCIWNDM_GETINACTIVETIMER (WM_USER+133)
#define MCIWNDM_CHANGESTYLES  (WM_USER+135)
#define MCIWNDM_GETSTYLES  (WM_USER+136)
#define MCIWNDM_GETALIAS  (WM_USER+137)
#define MCIWNDM_PLAYREVERSE  (WM_USER+139)
#define MCIWNDM_GET_SOURCE  (WM_USER+140)
#define MCIWNDM_PUT_SOURCE  (WM_USER+141)
#define MCIWNDM_GET_DEST  (WM_USER+142)
#define MCIWNDM_PUT_DEST  (WM_USER+143)
#define MCIWNDM_CAN_PLAY  (WM_USER+144)
#define MCIWNDM_CAN_WINDOW  (WM_USER+145)
#define MCIWNDM_CAN_RECORD  (WM_USER+146)
#define MCIWNDM_CAN_SAVE  (WM_USER+147)
#define MCIWNDM_CAN_EJECT  (WM_USER+148)
#define MCIWNDM_CAN_CONFIG  (WM_USER+149)
#define MCIWNDM_PALETTEKICK  (WM_USER+150)
#define MCIWNDM_OPENINTERFACE  (WM_USER+151)
#define MCIWNDM_SETOWNER  (WM_USER+152)

#define MCIWNDM_SENDSTRINGA  (WM_USER+101)
#define MCIWNDM_GETPOSITIONA  (WM_USER+102)
#define MCIWNDM_GETMODEA  (WM_USER+106)
#define MCIWNDM_SETTIMEFORMATA  (WM_USER+119)
#define MCIWNDM_GETTIMEFORMATA  (WM_USER+120)
#define MCIWNDM_GETFILENAMEA  (WM_USER+124)
#define MCIWNDM_GETDEVICEA  (WM_USER+125)
#define MCIWNDM_GETERRORA  (WM_USER+128)
#define MCIWNDM_NEWA  (WM_USER+134)
#define MCIWNDM_RETURNSTRINGA  (WM_USER+138)
#define MCIWNDM_OPENA  (WM_USER+153)

#define MCIWNDM_SENDSTRINGW  (WM_USER+201)
#define MCIWNDM_GETPOSITIONW  (WM_USER+202)
#define MCIWNDM_GETMODEW  (WM_USER+206)
#define MCIWNDM_SETTIMEFORMATW  (WM_USER+219)
#define MCIWNDM_GETTIMEFORMATW  (WM_USER+220)
#define MCIWNDM_GETFILENAMEW  (WM_USER+224)
#define MCIWNDM_GETDEVICEW  (WM_USER+225)
#define MCIWNDM_GETERRORW  (WM_USER+228)
#define MCIWNDM_NEWW  (WM_USER+234)
#define MCIWNDM_RETURNSTRINGW  (WM_USER+238)
#define MCIWNDM_OPENW  (WM_USER+252)

#define MCIWNDM_NOTIFYMODE  (WM_USER+200)
#define MCIWNDM_NOTIFYPOS  (WM_USER+201)
#define MCIWNDM_NOTIFYSIZE  (WM_USER+202)
#define MCIWNDM_NOTIFYMEDIA  (WM_USER+203)
#define MCIWNDM_NOTIFYERROR  (WM_USER+205)

#define MCIWND_START  -1
#define MCIWND_END  -2

#ifndef MCI_PLAY
	#define MCI_CLOSE  0x0804
	#define MCI_PLAY  0x0806
	#define MCI_SEEK  0x0807
	#define MCI_STOP  0x0808
	#define MCI_PAUSE  0x0809
	#define MCI_STEP  0x080E
	#define MCI_RECORD  0x080F
	#define MCI_SAVE  0x0813
	#define MCI_CUT  0x0851
	#define MCI_COPY  0x0852
	#define MCI_PASTE  0x0853
	#define MCI_RESUME  0x0855
	#define MCI_DELETE  0x0856
#endif

#ifndef MCI_MODE_NOT_READY
	#define MCI_MODE_NOT_READY  524
	#define MCI_MODE_STOP  525
	#define MCI_MODE_PLAY  526
	#define MCI_MODE_RECORD  527
	#define MCI_MODE_SEEK  528
	#define MCI_MODE_PAUSE  529
	#define MCI_MODE_OPEN  530
#endif

#define MCIWND_WINDOW_CLASS "MCIWndClass"

#define DV_ERR_OK  0
#define DV_ERR_BASE  1
#define DV_ERR_NONSPECIFIC  (DV_ERR_BASE)
#define DV_ERR_BADFORMAT  (DV_ERR_BASE+1)
#define DV_ERR_STILLPLAYING  (DV_ERR_BASE+2)
#define DV_ERR_UNPREPARED  (DV_ERR_BASE+3)
#define DV_ERR_SYNC  (DV_ERR_BASE+4)
#define DV_ERR_TOOMANYCHANNELS  (DV_ERR_BASE+5)
#define DV_ERR_NOTDETECTED  (DV_ERR_BASE+6)
#define DV_ERR_BADINSTALL  (DV_ERR_BASE+7)
#define DV_ERR_CREATEPALETTE  (DV_ERR_BASE+8)
#define DV_ERR_SIZEFIELD  (DV_ERR_BASE+9)
#define DV_ERR_PARAM1  (DV_ERR_BASE+10)
#define DV_ERR_PARAM2  (DV_ERR_BASE+11)
#define DV_ERR_CONFIG1  (DV_ERR_BASE+12)
#define DV_ERR_CONFIG2  (DV_ERR_BASE+13)
#define DV_ERR_FLAGS  (DV_ERR_BASE+14)
#define DV_ERR_13  (DV_ERR_BASE+15)
#define DV_ERR_NOTSUPPORTED  (DV_ERR_BASE+16)
#define DV_ERR_NOMEM  (DV_ERR_BASE+17)
#define DV_ERR_ALLOCATED  (DV_ERR_BASE+18)
#define DV_ERR_BADDEVICEID  (DV_ERR_BASE+19)
#define DV_ERR_INVALHANDLE  (DV_ERR_BASE+20)
#define DV_ERR_BADERRNUM  (DV_ERR_BASE+21)
#define DV_ERR_NO_BUFFERS  (DV_ERR_BASE+22)
#define DV_ERR_MEM_CONFLICT  (DV_ERR_BASE+23)
#define DV_ERR_IO_CONFLICT  (DV_ERR_BASE+24)
#define DV_ERR_DMA_CONFLICT  (DV_ERR_BASE+25)
#define DV_ERR_INT_CONFLICT  (DV_ERR_BASE+26)
#define DV_ERR_PROTECT_ONLY  (DV_ERR_BASE+27)
#define DV_ERR_LASTERROR  (DV_ERR_BASE+27)
#define DV_ERR_USER_MSG  (DV_ERR_BASE+1000)

#ifndef MM_DRVM_OPEN
	#define MM_DRVM_OPEN  0x3D0
	#define MM_DRVM_CLOSE  0x3D1
	#define MM_DRVM_DATA  0x3D2
	#define MM_DRVM_ERROR  0x3D3
#endif

#define DV_VM_OPEN  MM_DRVM_OPEN
#define DV_VM_CLOSE  MM_DRVM_CLOSE
#define DV_VM_DATA  MM_DRVM_DATA
#define DV_VM_ERROR  MM_DRVM_ERROR

#define VHDR_DONE  0x00000001
#define VHDR_PREPARED  0x00000002
#define VHDR_INQUEUE  0x00000004
#define VHDR_KEYFRAME  0x00000008
#define VHDR_VALID  0x0000000F

#define VCAPS_OVERLAY  0x00000001
#define VCAPS_SRC_CAN_CLIP  0x00000002
#define VCAPS_DST_CAN_CLIP  0x00000004
#define VCAPS_CAN_SCALE  0x00000008

#define VIDEO_EXTERNALIN  0x0001
#define VIDEO_EXTERNALOUT  0x0002
#define VIDEO_IN  0x0004
#define VIDEO_OUT  0x0008

#define VIDEO_DLG_QUERY  0x0010

#define VIDEO_CONFIGURE_QUERY  0x8000
#define VIDEO_CONFIGURE_SET  0x1000
#define VIDEO_CONFIGURE_GET  0x2000
#define VIDEO_CONFIGURE_QUERYSIZE  0x0001
#define VIDEO_CONFIGURE_CURRENT  0x0010
#define VIDEO_CONFIGURE_NOMINAL  0x0020
#define VIDEO_CONFIGURE_MIN  0x0040
#define VIDEO_CONFIGURE_MAX  0x0080

#define DVM_USER  0X4000

#define DVM_CONFIGURE_START  0x1000
#define DVM_CONFIGURE_END  0x1FFF

#define DVM_PALETTE  (DVM_CONFIGURE_START+1)
#define DVM_FORMAT  (DVM_CONFIGURE_START+2)
#define DVM_PALETTERGB555  (DVM_CONFIGURE_START+3)
#define DVM_SRC_RECT  (DVM_CONFIGURE_START+4)
#define DVM_DST_RECT  (DVM_CONFIGURE_START+5)

#define WM_CAP_START  WM_USER
#define WM_CAP_UNICODE_START  (WM_USER+100)
#define WM_CAP_GET_CAPSTREAMPTR  (WM_CAP_START+1)
#define WM_CAP_SET_CALLBACK_ERRORW  (WM_CAP_UNICODE_START+2)
#define WM_CAP_SET_CALLBACK_STATUSW  (WM_CAP_UNICODE_START+3)
#define WM_CAP_SET_CALLBACK_ERRORA  (WM_CAP_START+2)
#define WM_CAP_SET_CALLBACK_STATUSA  (WM_CAP_START+3)
#define WM_CAP_SET_CALLBACK_YIELD  (WM_CAP_START+4)
#define WM_CAP_SET_CALLBACK_FRAME  (WM_CAP_START+5)
#define WM_CAP_SET_CALLBACK_VIDEOSTREAM (WM_CAP_START+6)
#define WM_CAP_SET_CALLBACK_WAVESTREAM  (WM_CAP_START+7)
#define WM_CAP_GET_USER_DATA  (WM_CAP_START+8)
#define WM_CAP_SET_USER_DATA  (WM_CAP_START+9)
#define WM_CAP_DRIVER_CONNECT  (WM_CAP_START+10)
#define WM_CAP_DRIVER_DISCONNECT  (WM_CAP_START+11)
#define WM_CAP_DRIVER_GET_NAMEA  (WM_CAP_START+12)
#define WM_CAP_DRIVER_GET_VERSIONA  (WM_CAP_START+13)
#define WM_CAP_DRIVER_GET_NAMEW  (WM_CAP_UNICODE_START+12)
#define WM_CAP_DRIVER_GET_VERSIONW  (WM_CAP_UNICODE_START+13)
#define WM_CAP_DRIVER_GET_CAPS  (WM_CAP_START+14)
#define WM_CAP_FILE_SET_CAPTURE_FILEA  (WM_CAP_START+20)
#define WM_CAP_FILE_GET_CAPTURE_FILEA  (WM_CAP_START+21)
#define WM_CAP_FILE_SAVEASA  (WM_CAP_START+23)
#define WM_CAP_FILE_SAVEDIBA  (WM_CAP_START+25)
#define WM_CAP_FILE_SET_CAPTURE_FILEW  (WM_CAP_UNICODE_START+20)
#define WM_CAP_FILE_GET_CAPTURE_FILEW  (WM_CAP_UNICODE_START+21)
#define WM_CAP_FILE_SAVEASW  (WM_CAP_UNICODE_START+23)
#define WM_CAP_FILE_SAVEDIBW  (WM_CAP_UNICODE_START+25)
#define WM_CAP_FILE_ALLOCATE  (WM_CAP_START+22)
#define WM_CAP_FILE_SET_INFOCHUNK  (WM_CAP_START+24)
#define WM_CAP_EDIT_COPY  (WM_CAP_START+30)
#define WM_CAP_SET_AUDIOFORMAT  (WM_CAP_START+35)
#define WM_CAP_GET_AUDIOFORMAT  (WM_CAP_START+36)
#define WM_CAP_DLG_VIDEOFORMAT  (WM_CAP_START+41)
#define WM_CAP_DLG_VIDEOSOURCE  (WM_CAP_START+42)
#define WM_CAP_DLG_VIDEODISPLAY  (WM_CAP_START+43)
#define WM_CAP_GET_VIDEOFORMAT  (WM_CAP_START+44)
#define WM_CAP_SET_VIDEOFORMAT  (WM_CAP_START+45)
#define WM_CAP_DLG_VIDEOCOMPRESSION  (WM_CAP_START+46)
#define WM_CAP_SET_PREVIEW  (WM_CAP_START+50)
#define WM_CAP_SET_OVERLAY  (WM_CAP_START+51)
#define WM_CAP_SET_PREVIEWRATE  (WM_CAP_START+52)
#define WM_CAP_SET_SCALE  (WM_CAP_START+53)
#define WM_CAP_GET_STATUS  (WM_CAP_START+54)
#define WM_CAP_SET_SCROLL  (WM_CAP_START+55)
#define WM_CAP_GRAB_FRAME  (WM_CAP_START+60)
#define WM_CAP_GRAB_FRAME_NOSTOP  (WM_CAP_START+61)
#define WM_CAP_SEQUENCE  (WM_CAP_START+62)
#define WM_CAP_SEQUENCE_NOFILE  (WM_CAP_START+63)
#define WM_CAP_SET_SEQUENCE_SETUP  (WM_CAP_START+64)
#define WM_CAP_GET_SEQUENCE_SETUP  (WM_CAP_START+65)
#define WM_CAP_SET_MCI_DEVICEA  (WM_CAP_START+66)
#define WM_CAP_GET_MCI_DEVICEA  (WM_CAP_START+67)
#define WM_CAP_SET_MCI_DEVICEW  (WM_CAP_UNICODE_START+66)
#define WM_CAP_GET_MCI_DEVICEW  (WM_CAP_UNICODE_START+67)
#define WM_CAP_STOP  (WM_CAP_START+68)
#define WM_CAP_ABORT  (WM_CAP_START+69)
#define WM_CAP_SINGLE_FRAME_OPEN  (WM_CAP_START+70)
#define WM_CAP_SINGLE_FRAME_CLOSE  (WM_CAP_START+71)
#define WM_CAP_SINGLE_FRAME  (WM_CAP_START+72)
#define WM_CAP_PAL_OPENA  (WM_CAP_START+80)
#define WM_CAP_PAL_SAVEA  (WM_CAP_START+81)
#define WM_CAP_PAL_OPENW  (WM_CAP_UNICODE_START+80)
#define WM_CAP_PAL_SAVEW  (WM_CAP_UNICODE_START+81)
#define WM_CAP_PAL_PASTE  (WM_CAP_START+82)
#define WM_CAP_PAL_AUTOCREATE  (WM_CAP_START+83)
#define WM_CAP_PAL_MANUALCREATE  (WM_CAP_START+84)
#define WM_CAP_SET_CALLBACK_CAPCONTROL  (WM_CAP_START+85)
#define WM_CAP_UNICODE_END  WM_CAP_PAL_SAVEW
#define WM_CAP_END  WM_CAP_UNICODE_END

#define AVSTREAMMASTER_AUDIO  0
#define AVSTREAMMASTER_NONE  1

#define CONTROLCALLBACK_PREROLL  1
#define CONTROLCALLBACK_CAPTURING  2

#define infotypeDIGITIZATION_TIME  A'IDIT'
#define infotypeSMPTE_TIME  A'ISMP'

#define IDS_CAP_BEGIN  300
#define IDS_CAP_END  301
#define IDS_CAP_INFO  401
#define IDS_CAP_OUTOFMEM  402
#define IDS_CAP_FILEEXISTS  403
#define IDS_CAP_ERRORPALOPEN  404
#define IDS_CAP_ERRORPALSAVE  405
#define IDS_CAP_ERRORDIBSAVE  406
#define IDS_CAP_DEFAVIEXT  407
#define IDS_CAP_DEFPALEXT  408
#define IDS_CAP_CANTOPEN  409
#define IDS_CAP_SEQ_MSGSTART  410
#define IDS_CAP_SEQ_MSGSTOP  411
#define IDS_CAP_VIDEDITERR  412
#define IDS_CAP_READONLYFILE  413
#define IDS_CAP_WRITEERROR  414
#define IDS_CAP_NODISKSPACE  415
#define IDS_CAP_SETFILESIZE  416
#define IDS_CAP_SAVEASPERCENT  417
#define IDS_CAP_DRIVER_ERROR  418
#define IDS_CAP_WAVE_OPEN_ERROR  419
#define IDS_CAP_WAVE_ALLOC_ERROR  420
#define IDS_CAP_WAVE_PREPARE_ERROR  421
#define IDS_CAP_WAVE_ADD_ERROR  422
#define IDS_CAP_WAVE_SIZE_ERROR  423
#define IDS_CAP_VIDEO_OPEN_ERROR  424
#define IDS_CAP_VIDEO_ALLOC_ERROR  425
#define IDS_CAP_VIDEO_PREPARE_ERROR 426
#define IDS_CAP_VIDEO_ADD_ERROR  427
#define IDS_CAP_VIDEO_SIZE_ERROR  428
#define IDS_CAP_FILE_OPEN_ERROR  429
#define IDS_CAP_FILE_WRITE_ERROR  430
#define IDS_CAP_RECORDING_ERROR  431
#define IDS_CAP_RECORDING_ERROR2  432
#define IDS_CAP_AVI_INIT_ERROR  433
#define IDS_CAP_NO_FRAME_CAP_ERROR  434
#define IDS_CAP_NO_PALETTE_WARN  435
#define IDS_CAP_MCI_CONTROL_ERROR  436
#define IDS_CAP_MCI_CANT_STEP_ERROR 437
#define IDS_CAP_NO_AUDIO_CAP_ERROR  438
#define IDS_CAP_AVI_DRAWDIB_ERROR  439
#define IDS_CAP_COMPRESSOR_ERROR  440
#define IDS_CAP_AUDIO_DROP_ERROR  441
#define IDS_CAP_AUDIO_DROP_COMPERROR 442
#define IDS_CAP_STAT_LIVE_MODE  500
#define IDS_CAP_STAT_OVERLAY_MODE  501
#define IDS_CAP_STAT_CAP_INIT  502
#define IDS_CAP_STAT_CAP_FINI  503
#define IDS_CAP_STAT_PALETTE_BUILD  504
#define IDS_CAP_STAT_OPTPAL_BUILD  505
#define IDS_CAP_STAT_I_FRAMES  506
#define IDS_CAP_STAT_L_FRAMES  507
#define IDS_CAP_STAT_CAP_L_FRAMES  508
#define IDS_CAP_STAT_CAP_AUDIO  509
#define IDS_CAP_STAT_VIDEOCURRENT  510
#define IDS_CAP_STAT_VIDEOAUDIO  511
#define IDS_CAP_STAT_VIDEOONLY  512
#define IDS_CAP_STAT_FRAMESDROPPED  513

VIDEOHDR STRUCT
	lpData PTR
	dwBufferLength DD
	dwBytesUsed DD
	dwTimeCaptured DD
	dwUser DD
	dwFlags DD
	dwReserved DWORD_PTR 4 DUP
ENDS

CHANNEL_CAPS STRUCT
	dwFlags DD
	dwSrcRectXMod DD
	dwSrcRectYMod DD
	dwSrcRectWidthMod DD
	dwSrcRectHeightMod DD
	dwDstRectXMod DD
	dwDstRectYMod DD
	dwDstRectWidthMod DD
	dwDstRectHeightMod DD
ENDS

CAPDRIVERCAPS STRUCT
	wDeviceIndex DD
	fHasOverlay DD
	fHasDlgVideoSource DD
	fHasDlgVideoFormat DD
	fHasDlgVideoDisplay DD
	fCaptureInitialized DD
	fDriverSuppliesPalettes DD
	hVideoIn HANDLE
	hVideoOut HANDLE
	hVideoExtIn HANDLE
	hVideoExtOut HANDLE
ENDS

CAPSTATUS STRUCT
	uiImageWidth DD
	uiImageHeight DD
	fLiveWindow DD
	fOverlayWindow DD
	fScale DD
	ptScroll POINT
	fUsingDefaultPalette DD
	fAudioHardware DD
	fCapFileExists DD
	dwCurrentVideoFrame DD
	dwCurrentVideoFramesDropped DD
	dwCurrentWaveSamples DD
	dwCurrentTimeElapsedMS DD
	hPalCurrent HANDLE
	fCapturingNow DD
	dwReturn DD
	wNumVideoAllocated DD
	wNumAudioAllocated DD
ENDS

CAPTUREPARMS STRUCT
	dwRequestMicroSecPerFrame DD
	fMakeUserHitOKToCapture DD
	wPercentDropForError DD
	fYield DD
	dwIndexSize DD
	wChunkGranularity DD
	fUsingDOSMemory DD
	wNumVideoRequested DD
	fCaptureAudio DD
	wNumAudioRequested DD
	vKeyAbort DD
	fAbortLeftMouse DD
	fAbortRightMouse DD
	fLimitEnabled DD
	wTimeLimit DD
	fMCIControl DD
	fStepMCIDevice DD
	dwMCIStartTime DD
	dwMCIStopTime DD
	fStepCaptureAt2x DD
	wStepCaptureAverageFrames DD
	dwAudioBufferSize DD
	fDisableWriteCache DD
	AVStreamMaster DD
ENDS

CAPINFOCHUNK STRUCT
	fccInfoID DD
	lpData PTR
	cbData DD
ENDS

#IFDEF UNICODE
	#define MCIWNDF_NOTIFYMEDIA MCIWNDF_NOTIFYMEDIAW
	#define MCIWNDM_SENDSTRING MCIWNDM_SENDSTRINGW
	#define MCIWNDM_GETPOSITION MCIWNDM_GETPOSITIONW
	#define MCIWNDM_GETMODE MCIWNDM_GETMODEW
	#define MCIWNDM_SETTIMEFORMAT MCIWNDM_SETTIMEFORMATW
	#define MCIWNDM_GETTIMEFORMAT MCIWNDM_GETTIMEFORMATW
	#define MCIWNDM_GETFILENAME MCIWNDM_GETFILENAMEW
	#define MCIWNDM_GETDEVICE MCIWNDM_GETDEVICEW
	#define MCIWNDM_GETERROR MCIWNDM_GETERRORW
	#define MCIWNDM_NEW MCIWNDM_NEWW
	#define MCIWNDM_RETURNSTRING MCIWNDM_RETURNSTRINGW
	#define MCIWNDM_OPEN MCIWNDM_OPENW
	#define WM_CAP_SET_CALLBACK_ERROR WM_CAP_SET_CALLBACK_ERRORW
	#define WM_CAP_SET_CALLBACK_STATUS WM_CAP_SET_CALLBACK_STATUSW
	#define WM_CAP_DRIVER_GET_NAME WM_CAP_DRIVER_GET_NAMEW
	#define WM_CAP_DRIVER_GET_VERSION WM_CAP_DRIVER_GET_VERSIONW
	#define WM_CAP_FILE_SET_CAPTURE_FILE WM_CAP_FILE_SET_CAPTURE_FILEW
	#define WM_CAP_FILE_GET_CAPTURE_FILE WM_CAP_FILE_GET_CAPTURE_FILEW
	#define WM_CAP_FILE_SAVEAS WM_CAP_FILE_SAVEASW
	#define WM_CAP_FILE_SAVEDIB WM_CAP_FILE_SAVEDIBW
	#define WM_CAP_SET_MCI_DEVICE WM_CAP_SET_MCI_DEVICEW
	#define WM_CAP_GET_MCI_DEVICE WM_CAP_GET_MCI_DEVICEW
	#define WM_CAP_PAL_OPEN WM_CAP_PAL_OPENW
	#define WM_CAP_PAL_SAVE WM_CAP_PAL_SAVEW
	#define MCIWndCreate MCIWndCreateW
	#define capCreateCaptureWindow capCreateCaptureWindowW
	#define capGetDriverDescription capGetDriverDescriptionW
#else
	#define MCIWNDF_NOTIFYMEDIA MCIWNDF_NOTIFYMEDIAA
	#define MCIWNDM_SENDSTRING MCIWNDM_SENDSTRINGA
	#define MCIWNDM_GETPOSITION MCIWNDM_GETPOSITIONA
	#define MCIWNDM_GETMODE MCIWNDM_GETMODEA
	#define MCIWNDM_SETTIMEFORMAT MCIWNDM_SETTIMEFORMATA
	#define MCIWNDM_GETTIMEFORMAT MCIWNDM_GETTIMEFORMATA
	#define MCIWNDM_GETFILENAME MCIWNDM_GETFILENAMEA
	#define MCIWNDM_GETDEVICE MCIWNDM_GETDEVICEA
	#define MCIWNDM_GETERROR MCIWNDM_GETERRORA
	#define MCIWNDM_NEW MCIWNDM_NEWA
	#define MCIWNDM_RETURNSTRING MCIWNDM_RETURNSTRINGA
	#define MCIWNDM_OPEN MCIWNDM_OPENA
	#define WM_CAP_SET_CALLBACK_ERROR WM_CAP_SET_CALLBACK_ERRORA
	#define WM_CAP_SET_CALLBACK_STATUS WM_CAP_SET_CALLBACK_STATUSA
	#define WM_CAP_DRIVER_GET_NAME WM_CAP_DRIVER_GET_NAMEA
	#define WM_CAP_DRIVER_GET_VERSION WM_CAP_DRIVER_GET_VERSIONA
	#define WM_CAP_FILE_SET_CAPTURE_FILE WM_CAP_FILE_SET_CAPTURE_FILEA
	#define WM_CAP_FILE_GET_CAPTURE_FILE WM_CAP_FILE_GET_CAPTURE_FILEA
	#define WM_CAP_FILE_SAVEAS WM_CAP_FILE_SAVEASA
	#define WM_CAP_FILE_SAVEDIB WM_CAP_FILE_SAVEDIBA
	#define WM_CAP_SET_MCI_DEVICE WM_CAP_SET_MCI_DEVICEA
	#define WM_CAP_GET_MCI_DEVICE WM_CAP_GET_MCI_DEVICEA
	#define WM_CAP_PAL_OPEN WM_CAP_PAL_OPENA
	#define WM_CAP_PAL_SAVE WM_CAP_PAL_SAVEA
	#define MCIWndCreate MCIWndCreateA
	#define capCreateCaptureWindow capCreateCaptureWindowA
	#define capGetDriverDescription capGetDriverDescriptionA
#endif

#IFDEF UNICODE
	#define GetOpenFileNamePreview GetOpenFileNamePreviewW
	#define GetSaveFileNamePreview GetSaveFileNamePreviewW
#else
	#define GetOpenFileNamePreview GetOpenFileNamePreviewA
	#define GetSaveFileNamePreview GetSaveFileNamePreviewA
#endif

#endif
