#ifndef WINGDI_H
#define WINGDI_H

#DEFINE WINGDI_H_REQVER 100

/* Windows GDI Module definitions */

/*
Switches used
WINNT4
WIN9X
*/

#IFDEF LINKFILES
	#dynamiclinkfile GDI32.dll
	#dynamiclinkfile opengl32.dll
	#dynamiclinkfile Msimg32.dll
#ENDIF

#IFNDEF POINT
	POINT STRUCT
		x DD
		y DD
	ENDS
#ENDIF

#IFNDEF SIZE
	SIZE STRUCT
		cx DD
		cy DD
	ENDS
#ENDIF

#IFNDEF RECT
	RECT STRUCT
		left DD
		top DD
		right DD
		bottom DD
	ENDS
#ENDIF

#IFNDEF SIZEL
	#define SIZEL SIZE
#ENDIF
#IFNDEF RECTL
	#define RECTL RECT
#ENDIF
#IFNDEF POINTL
	#define POINTL POINT
#ENDIF

#IFNDEF MAX_PATH
	#define MAX_PATH 260
#ENDIF

#IFNDEF POINTS
	POINTS STRUCT 
		x DW 
		y DW 
	ENDS
#ENDIF

#if WINVER >= NTDDI_VISTA
	#define MILCORE_TS_QUERYVER_RESULT_FALSE 0x0
	#define MILCORE_TS_QUERYVER_RESULT_TRUE 0x7FFFFFFF
#endif

#if WINVER >= NTDDI_WINXP
	#define FEATURESETTING_PRIVATE_BEGIN 0x1000
	#define FEATURESETTING_PRIVATE_END 0x1FFF
#endif

#define GDI_ERROR  -1
#define HGDI_ERROR  -1

#define R2_BLACK  1
#define R2_NOTMERGEPEN  2
#define R2_MASKNOTPEN  3
#define R2_NOTCOPYPEN  4
#define R2_MASKPENNOT  5
#define R2_NOT  6
#define R2_XORPEN  7
#define R2_NOTMASKPEN  8
#define R2_MASKPEN  9
#define R2_NOTXORPEN  10
#define R2_NOP  11
#define R2_MERGENOTPEN  12
#define R2_COPYPEN  13
#define R2_MERGEPENNOT  14
#define R2_MERGEPEN  15
#define R2_WHITE  16
#define R2_LAST  16

#define SRCCOPY  0x00CC0020
#define SRCPAINT  0x00EE0086
#define SRCAND  0x008800C6
#define SRCINVERT  0x00660046
#define SRCERASE  0x00440328
#define NOTSRCCOPY  0x00330008
#define NOTSRCERASE  0x001100A6
#define MERGECOPY  0x00C000CA
#define MERGEPAINT  0x00BB0226
#define PATCOPY  0x00F00021
#define PATPAINT  0x00FB0A09
#define PATINVERT  0x005A0049
#define DSTINVERT  0x00550009
#define BLACKNESS  0x00000042
#define WHITENESS  0x00FF0062
#define NOMIRRORBITMAP  0x80000000
#define CAPTUREBLT  0x40000000

/*
ROP codes for BitBlt
*/

#Define ROP_0 00000042h ; BLACKNESS
#Define ROP_DPSoon 00010289h
#Define ROP_DPSona 00020C89h
#Define ROP_PSon 000300AAh
#Define ROP_SDPona 00040C88h
#Define ROP_DPon 000500A9h
#Define ROP_PDSxnon 00060865h
#Define ROP_PDSaon 000702C5h
#Define ROP_SDPnaa 00080F08h
#Define ROP_PDSxon 00090245h
#Define ROP_DPna 000A0329h
#Define ROP_PSDnaon 000B0B2Ah
#Define ROP_SPna 000C0324h
#Define ROP_PDSnaon 000D0B25h
#Define ROP_PDSonon 000E08A5h
#Define ROP_Pn 000F0001h
#Define ROP_PDSona 00100C85h
#Define ROP_DSon 001100A6h  ; NOTSRCERASE
#Define ROP_SDPxnon 00120868h
#Define ROP_SDPaon 001302C8h
#Define ROP_DPSxnon 00140869h
#Define ROP_DPSaon 001502C9h
#Define ROP_PSDPSanaxx 00165CCAh
#Define ROP_SSPxDSxaxn 00171D54h
#Define ROP_SPxPDxa 00180D59h
#Define ROP_SDPSanaxn 00191CC8h
#Define ROP_PDSPaox 001A06C5h
#Define ROP_SDPSxaxn 001B0768h
#Define ROP_PSDPaox 001C06CAh
#Define ROP_DSPDxaxn 001D0766h
#Define ROP_PDSox 001E01A5h
#Define ROP_PDSoan 001F0385h
#Define ROP_DPSnaa 00200F09h
#Define ROP_SDPxon 00210248h
#Define ROP_DSna 00220326h
#Define ROP_SPDnaon 00230B24h
#Define ROP_SPxDSxa 00240D55h
#Define ROP_PDSPanaxn 00251CC5h
#Define ROP_SDPSaox 002606C8h
#Define ROP_SDPSxnox 00271868h
#Define ROP_DPSxa 00280369h
#Define ROP_PSDPSaoxxn 002916CAh
#Define ROP_DPSana 002A0CC9h
#Define ROP_SSPxPDxaxn 002B1D58h
#Define ROP_SPDSoax 002C0784h
#Define ROP_PSDnox 002D060Ah
#Define ROP_PSDPxox 002E064Ah
#Define ROP_PSDnoan 002F0E2Ah
#Define ROP_PSna 0030032Ah
#Define ROP_SDPnaon 00310B28h
#Define ROP_SDPSoox 00320688h
#Define ROP_Sn 00330008h  ; NOTSRCCOPY
#Define ROP_SPDSaox 003406C4h
#Define ROP_SPDSxnox 00351864h
#Define ROP_SDPox 003601A8h
#Define ROP_SDPoan 00370388h
#Define ROP_PSDPoax 0038078Ah
#Define ROP_SPDnox 00390604h
#Define ROP_SPDSxox 003A0644h
#Define ROP_SPDnoan 003B0E24h
#Define ROP_PSx 003C004Ah
#Define ROP_SPDSonox 003D18A4h
#Define ROP_SPDSnaox 003E1B24h
#Define ROP_PSan 003F00EAh
#Define ROP_PSDnaa 00400F0Ah
#Define ROP_DPSxon 00410249h
#Define ROP_SDxPDxa 00420D5Dh
#Define ROP_SPDSanaxn 00431CC4h
#Define ROP_SDna 00440328h  ; SRCERASE
#Define ROP_DPSnaon 00450B29h
#Define ROP_DSPDaox 004606C6h
#Define ROP_PSDPxaxn 0047076Ah
#Define ROP_SDPxa 00480368h
#Define ROP_PDSPDaoxxn 004916C5h
#Define ROP_DPSDoax 004A0789h
#Define ROP_PDSnox 004B0605h
#Define ROP_SDPana 004C0CC8h
#Define ROP_SSPxDSxoxn 004D1954h
#Define ROP_PDSPxox 004E0645h
#Define ROP_PDSnoan 004F0E25h
#Define ROP_PDna 00500325h
#Define ROP_DSPnaon 00510B26h
#Define ROP_DPSDaox 005206C9h
#Define ROP_SPDSxaxn 00530764h
#Define ROP_DPSonon 005408A9h
#Define ROP_Dn 00550009h  ; DSTINVERT
#Define ROP_DPSox 005601A9h
#Define ROP_DPSoan 00570389h
#Define ROP_PDSPoax 00580785h
#Define ROP_DPSnox 00590609h
#Define ROP_DPx 005A0049h ; PATINVERT
#Define ROP_DPSDonox 005B18A9h
#Define ROP_DPSDxox 005C0649h
#Define ROP_DPSnoan 005D0E29h
#Define ROP_DPSDnaox 005E1B29h
#Define ROP_DPan 005F00E9h
#Define ROP_PDSxa 00600365h
#Define ROP_DSPDSaoxxn 006116C6h
#Define ROP_DSPDoax 00620786h
#Define ROP_SDPnox 00630608h
#Define ROP_SDPSoax 00640788h
#Define ROP_DSPnox 00650606h
#Define ROP_DSx 00660046h ; SRCINVERT
#Define ROP_SDPSonox 006718A8h
#Define ROP_DSPDSonoxxn 006858A6h
#Define ROP_PDSxxn 00690145h
#Define ROP_DPSax 006A01E9h
#Define ROP_PSDPSoaxxn 006B178Ah
#Define ROP_SDPax 006C01E8h
#Define ROP_PDSPDoaxxn 006D1785h
#Define ROP_SDPSnoax 006E1E28h
#Define ROP_PDSxnan 006F0C65h
#Define ROP_PDSana 00700CC5h
#Define ROP_SSDxPDxaxn 00711D5Ch
#Define ROP_SDPSxox 00720648h
#Define ROP_SDPnoan 00730E28h
#Define ROP_DSPDxox 00740646h
#Define ROP_DSPnoan 00750E26h
#Define ROP_SDPSnaox 00761B28h
#Define ROP_DSan 007700E6h
#Define ROP_PDSax 007801E5h
#Define ROP_DSPDSoaxxn 00791786h
#Define ROP_DPSDnoax 007A1E29h
#Define ROP_SDPxnan 007B0C68h
#Define ROP_SPDSnoax 007C1E24h
#Define ROP_DPSxnan 007D0C69h
#Define ROP_SPxDSxo 007E0955h
#Define ROP_DPSaan 007F03C9h
#Define ROP_DPSaa 008003E9h
#Define ROP_SPxDSxon 00810975h
#Define ROP_DPSxna 00820C49h
#Define ROP_SPDSnoaxn 00831E04h
#Define ROP_SDPxna 00840C48h
#Define ROP_PDSPnoaxn 00851E05h
#Define ROP_DSPDSoaxx 008617A6h
#Define ROP_PDSaxn 008701C5h
#Define ROP_DSa 008800C6h ; SRCAND
#Define ROP_SDPSnaoxn 00891B08h
#Define ROP_DSPnoa 008A0E06h
#Define ROP_DSPDxoxn 008B0666h
#Define ROP_SDPnoa 008C0E08h
#Define ROP_SDPSxoxn 008D0668h
#Define ROP_SSDxPDxax 008E1D7Ch
#Define ROP_PDSanan 008F0CE5h
#Define ROP_PDSxna 00900C45h
#Define ROP_SDPSnoaxn 00911E08h
#Define ROP_DPSDPoaxx 009217A9h
#Define ROP_SPDaxn 009301C4h
#Define ROP_PSDPSoaxx 009417AAh
#Define ROP_DPSaxn 009501C9h
#Define ROP_DPSxx 00960169h
#Define ROP_PSDPSonoxx 0097588Ah
#Define ROP_SDPSonoxn 00981888h
#Define ROP_DSxn 00990066h
#Define ROP_DPSnax 009A0709h
#Define ROP_SDPSoaxn 009B07A8h
#Define ROP_SPDnax 009C0704h
#Define ROP_DSPDoaxn 009D07A6h
#Define ROP_DSPDSaoxx 009E16E6h
#Define ROP_PDSxan 009F0345h
#Define ROP_DPa 00A000C9h
#Define ROP_PDSPnaoxn 00A11B05h
#Define ROP_DPSnoa 00A20E09h
#Define ROP_DPSDxoxn 00A30669h
#Define ROP_PDSPonoxn 00A41885h
#Define ROP_PDxn 00A50065h
#Define ROP_DSPnax 00A60706h
#Define ROP_PDSPoaxn 00A707A5h
#Define ROP_DPSoa 00A803A9h
#Define ROP_DPSoxn 00A90189h
#Define ROP_D 00AA0029h
#Define ROP_DPSono 00AB0889h
#Define ROP_SPDSxax 00AC0744h
#Define ROP_DPSDaoxn 00AD06E9h
#Define ROP_DSPnao 00AE0B06h
#Define ROP_DPno 00AF0229h
#Define ROP_PDSnoa 00B00E05h
#Define ROP_PDSPxoxn 00B10665h
#Define ROP_SSPxDSxox 00B21974h
#Define ROP_SDPanan 00B30CE8h
#Define ROP_PSDnax 00B4070Ah
#Define ROP_DPSDoaxn 00B507A9h
#Define ROP_DPSDPaoxx 00B616E9h
#Define ROP_SDPxan 00B70348h
#Define ROP_PSDPxax 00B8074Ah
#Define ROP_DSPDaoxn 00B906E6h
#Define ROP_DPSnao 00BA0B09h
#Define ROP_DSno 00BB0226h ; MERGEPAINT
#Define ROP_SPDSanax 00BC1CE4h
#Define ROP_SDxPDxan 00BD0D7Dh
#Define ROP_DPSxo 00BE0269h
#Define ROP_DPSano 00BF08C9h
#Define ROP_PSa 00C000CAh ; MERGECOPY
#Define ROP_SPDSnaoxn 00C11B04h
#Define ROP_SPDSonoxn 00C21884h
#Define ROP_PSxn 00C3006Ah
#Define ROP_SPDnoa 00C40E04h
#Define ROP_SPDSxoxn 00C50664h
#Define ROP_SDPnax 00C60708h
#Define ROP_PSDPoaxn 00C707AAh
#Define ROP_SDPoa 00C803A8h
#Define ROP_SPDoxn 00C90184h
#Define ROP_DPSDxax 00CA0749h
#Define ROP_SPDSaoxn 00CB06E4h
#Define ROP_S 00CC0020h ; SRCCOPY
#Define ROP_SDPono 00CD0888h
#Define ROP_SDPnao 00CE0B08h
#Define ROP_SPno 00CF0224h
#Define ROP_PSDnoa 00D00E0Ah
#Define ROP_PSDPxoxn 00D1066Ah
#Define ROP_PDSnax 00D20705h
#Define ROP_SPDSoaxn 00D307A4h
#Define ROP_SSPxPDxax 00D41D78h
#Define ROP_DPSanan 00D50CE9h
#Define ROP_PSDPSaoxx 00D616EAh
#Define ROP_DPSxan 00D70349h
#Define ROP_PDSPxax 00D80745h
#Define ROP_SDPSaoxn 00D906E8h
#Define ROP_DPSDanax 00DA1CE9h
#Define ROP_SPxDSxan 00DB0D75h
#Define ROP_SPDnao 00DC0B04h
#Define ROP_SDno 00DD0228h
#Define ROP_SDPxo 00DE0268h
#Define ROP_SDPano 00DF08C8h
#Define ROP_PDSoa 00E003A5h
#Define ROP_PDSoxn 00E10185h
#Define ROP_DSPDxax 00E20746h
#Define ROP_PSDPaoxn 00E306EAh
#Define ROP_SDPSxax 00E40748h
#Define ROP_PDSPaoxn 00E506E5h
#Define ROP_SDPSanax 00E61CE8h
#Define ROP_SPxPDxan 00E70D79h
#Define ROP_SSPxDSxax 00E81D74h
#Define ROP_DSPDSanaxxn 00E95CE6h
#Define ROP_DPSao 00EA02E9h
#Define ROP_DPSxno 00EB0849h
#Define ROP_SDPao 00EC02E8h
#Define ROP_SDPxno 00ED0848h
#Define ROP_DSo 00EE0086h ; SRCPAINT
#Define ROP_SDPnoo 00EF0A08h
#Define ROP_P 00F00021h ; PATCOPY
#Define ROP_PDSono 00F10885h
#Define ROP_PDSnao 00F20B05h
#Define ROP_PSno 00F3022Ah
#Define ROP_PSDnao 00F40B0Ah
#Define ROP_PDno 00F50225h
#Define ROP_PDSxo 00F60265h
#Define ROP_PDSano 00F708C5h
#Define ROP_PDSao 00F802E5h
#Define ROP_PDSxno 00F90845h
#Define ROP_DPo 00FA0089h
#Define ROP_DPSnoo 00FB0A09h ; PATPAINT
#Define ROP_PSo 00FC008Ah
#Define ROP_PSDnoo 00FD0A0Ah
#Define ROP_DPSoo 00FE02A9h
#Define ROP_1 00FF0062h ; WHITENESS

#define ERROR  0
#define NULLREGION  1
#define SIMPLEREGION  2
#define COMPLEXREGION  3
#define RGN_ERROR  ERROR
#define RGN_AND  1
#define RGN_OR  2
#define RGN_XOR  3
#define RGN_DIFF  4
#define RGN_COPY  5
#define RGN_MIN  RGN_AND
#define RGN_MAX  RGN_COPY

#define BLACKONWHITE  1
#define WHITEONBLACK  2
#define COLORONCOLOR  3
#define HALFTONE  4
#define MAXSTRETCHBLTMODE  4

#define STRETCH_ANDSCANS  BLACKONWHITE
#define STRETCH_ORSCANS  WHITEONBLACK
#define STRETCH_DELETESCANS  COLORONCOLOR
#define STRETCH_HALFTONE  HALFTONE

#define ALTERNATE  1
#define WINDING  2
#define POLYFILL_LAST  2

#define LAYOUT_RTL  0x00000001
#define LAYOUT_BTT  0x00000002
#define LAYOUT_VBH  0x00000004
#define LAYOUT_ORIENTATIONMASK  (LAYOUT_RTL|LAYOUT_BTT|LAYOUT_VBH)
#define LAYOUT_BITMAPORIENTATIONPRESERVED  0x00000008

#define TA_NOUPDATECP  0
#define TA_UPDATECP  1
#define TA_LEFT  0
#define TA_RIGHT  2
#define TA_CENTER  6
#define TA_TOP  0
#define TA_BOTTOM  8
#define TA_BASELINE  24
#define TA_RTLREADING  256
#define TA_MASK  (TA_BASELINE+TA_CENTER+TA_UPDATECP+TA_RTLREADING)
#define VTA_BASELINE  TA_BASELINE
#define VTA_LEFT  TA_BOTTOM
#define VTA_RIGHT  TA_TOP
#define VTA_CENTER  TA_CENTER
#define VTA_BOTTOM  TA_RIGHT
#define VTA_TOP  TA_LEFT

#define ETO_OPAQUE  0x0002
#define ETO_CLIPPED  0x0004
#define ETO_GLYPH_INDEX  0x0010
#define ETO_RTLREADING  0x0080
#define ETO_NUMERICSLOCAL  0x0400
#define ETO_NUMERICSLATIN  0x0800
#define ETO_IGNORELANGUAGE  0x1000
#define ETO_PDY  0x2000
#define ETO_REVERSE_INDEX_MAP        0x10000

#define ASPECT_FILTERING  0x0001

#define DCB_RESET  0x0001
#define DCB_ACCUMULATE  0x0002
#define DCB_DIRTY  DCB_ACCUMULATE
#define DCB_SET  (DCB_RESET|DCB_ACCUMULATE)
#define DCB_ENABLE  0x0004
#define DCB_DISABLE  0x0008

#IFNDEF META_ENUMERATION
#DEFINE META_ENUMERATION
#define META_SETBKCOLOR  0x0201
#define META_SETBKMODE  0x0102
#define META_SETMAPMODE  0x0103
#define META_SETROP2  0x0104
#define META_SETRELABS  0x0105
#define META_SETPOLYFILLMODE  0x0106
#define META_SETSTRETCHBLTMODE  0x0107
#define META_SETTEXTCHAREXTRA  0x0108
#define META_SETTEXTCOLOR  0x0209
#define META_SETTEXTJUSTIFICATION  0x020A
#define META_SETWINDOWORG  0x020B
#define META_SETWINDOWEXT  0x020C
#define META_SETVIEWPORTORG  0x020D
#define META_SETVIEWPORTEXT  0x020E
#define META_OFFSETWINDOWORG  0x020F
#define META_SCALEWINDOWEXT  0x0410
#define META_OFFSETVIEWPORTORG  0x0211
#define META_SCALEVIEWPORTEXT  0x0412
#define META_LINETO  0x0213
#define META_MOVETO  0x0214
#define META_EXCLUDECLIPRECT  0x0415
#define META_INTERSECTCLIPRECT  0x0416
#define META_ARC  0x0817
#define META_ELLIPSE  0x0418
#define META_FLOODFILL  0x0419
#define META_PIE  0x081A
#define META_RECTANGLE  0x041B
#define META_ROUNDRECT  0x061C
#define META_PATBLT  0x061D
#define META_SAVEDC  0x001E
#define META_SETPIXEL  0x041F
#define META_OFFSETCLIPRGN  0x0220
#define META_TEXTOUT  0x0521
#define META_BITBLT  0x0922
#define META_STRETCHBLT  0x0B23
#define META_POLYGON  0x0324
#define META_POLYLINE  0x0325
#define META_ESCAPE  0x0626
#define META_RESTOREDC  0x0127
#define META_FILLREGION  0x0228
#define META_FRAMEREGION  0x0429
#define META_INVERTREGION  0x012A
#define META_PAINTREGION  0x012B
#define META_SELECTCLIPREGION  0x012C
#define META_SELECTOBJECT  0x012D
#define META_SETTEXTALIGN  0x012E
#define META_CHORD  0x0830
#define META_SETMAPPERFLAGS  0x0231
#define META_EXTTEXTOUT  0x0a32
#define META_SETDIBTODEV  0x0d33
#define META_SELECTPALETTE  0x0234
#define META_REALIZEPALETTE  0x0035
#define META_ANIMATEPALETTE  0x0436
#define META_SETPALENTRIES  0x0037
#define META_POLYPOLYGON  0x0538
#define META_RESIZEPALETTE  0x0139
#define META_DIBBITBLT  0x0940
#define META_DIBSTRETCHBLT  0x0b41
#define META_DIBCREATEPATTERNBRUSH  0x0142
#define META_STRETCHDIB  0x0f43
#define META_EXTFLOODFILL  0x0548
#define META_SETLAYOUT  0x0149
#define META_DELETEOBJECT  0x01f0
#define META_CREATEPALETTE  0x00f7
#define META_CREATEPATTERNBRUSH  0x01F9
#define META_CREATEPENINDIRECT  0x02FA
#define META_CREATEFONTINDIRECT  0x02FB
#define META_CREATEBRUSHINDIRECT  0x02FC
#define META_CREATEREGION  0x06FF
#ENDIF

#define NEWFRAME  1
#define ABORTDOC  2
#define NEXTBAND  3
#define SETCOLORTABLE  4
#define GETCOLORTABLE  5
#define FLUSHOUTPUT  6
#define DRAFTMODE  7
#define QUERYESCSUPPORT  8
#define SETABORTPROC  9
#define STARTDOC  10
#define ENDDOC  11
#define GETPHYSPAGESIZE  12
#define GETPRINTINGOFFSET  13
#define GETSCALINGFACTOR  14
#define MFCOMMENT  15
#define GETPENWIDTH  16
#define SETCOPYCOUNT  17
#define SELECTPAPERSOURCE  18
#define DEVICEDATA  19
#define PASSTHROUGH  19
#define GETTECHNOLGY  20
#define GETTECHNOLOGY  20
#define SETLINECAP  21
#define SETLINEJOIN  22
#define SETMITERLIMIT  23
#define BANDINFO  24
#define DRAWPATTERNRECT  25
#define GETVECTORPENSIZE  26
#define GETVECTORBRUSHSIZE  27
#define ENABLEDUPLEX  28
#define GETSETPAPERBINS  29
#define GETSETPRINTORIENT  30
#define ENUMPAPERBINS  31
#define SETDIBSCALING  32
#define EPSPRINTING  33
#define ENUMPAPERMETRICS  34
#define GETSETPAPERMETRICS  35
#define POSTSCRIPT_DATA  37
#define POSTSCRIPT_IGNORE  38
#define MOUSETRAILS  39
#define GETDEVICEUNITS  42
#define GETEXTENDEDTEXTMETRICS  256
#define GETEXTENTTABLE  257
#define GETPAIRKERNTABLE  258
#define GETTRACKKERNTABLE  259
#define EXTTEXTOUT  512
#define GETFACENAME  513
#define DOWNLOADFACE  514
#define ENABLERELATIVEWIDTHS  768
#define ENABLEPAIRKERNING  769
#define SETKERNTRACK  770
#define SETALLJUSTVALUES  771
#define SETCHARSET  772
#define STRETCHBLT  2048
#define METAFILE_DRIVER  2049
#define GETSETSCREENPARAMS  3072
#define QUERYDIBSUPPORT  3073
#define BEGIN_PATH  4096
#define CLIP_TO_PATH  4097
#define END_PATH  4098
#define EXT_DEVICE_CAPS  4099
#define RESTORE_CTM  4100
#define SAVE_CTM  4101
#define SET_ARC_DIRECTION  4102
#define SET_BACKGROUND_COLOR  4103
#define SET_POLY_MODE  4104
#define SET_SCREEN_ANGLE  4105
#define SET_SPREAD  4106
#define TRANSFORM_CTM  4107
#define SET_CLIP_BOX  4108
#define SET_BOUNDS  4109
#define SET_MIRROR_MODE  4110
#define OPENCHANNEL  4110
#define DOWNLOADHEADER  4111
#define CLOSECHANNEL  4112
#define POSTSCRIPT_PASSTHROUGH  4115
#define ENCAPSULATED_POSTSCRIPT  4116
#define POSTSCRIPT_IDENTIFY  4117
#define POSTSCRIPT_INJECTION  4118
#define CHECKJPEGFORMAT  4119
#define CHECKPNGFORMAT  4120
#define GET_PS_FEATURESETTING  4121
#define SPCLPASSTHROUGH2  4568

#define PSIDENT_GDICENTRIC  0
#define PSIDENT_PSCENTRIC  1

#define PSINJECT_BEGINSTREAM  1
#define PSINJECT_PSADOBE  2
#define PSINJECT_PAGESATEND  3
#define PSINJECT_PAGES  4
#define PSINJECT_DOCNEEDEDRES  5
#define PSINJECT_DOCSUPPLIEDRES  6
#define PSINJECT_PAGEORDER  7
#define PSINJECT_ORIENTATION  8
#define PSINJECT_BOUNDINGBOX  9
#define PSINJECT_DOCUMENTPROCESSCOLORS  10
#define PSINJECT_COMMENTS  11
#define PSINJECT_BEGINDEFAULTS  12
#define PSINJECT_ENDDEFAULTS  13
#define PSINJECT_BEGINPROLOG  14
#define PSINJECT_ENDPROLOG  15
#define PSINJECT_BEGINSETUP  16
#define PSINJECT_ENDSETUP  17
#define PSINJECT_TRAILER  18
#define PSINJECT_EOF  19
#define PSINJECT_ENDSTREAM  20
#define PSINJECT_DOCUMENTPROCESSCOLORSATEND  21
#define PSINJECT_PAGENUMBER  100
#define PSINJECT_BEGINPAGESETUP  101
#define PSINJECT_ENDPAGESETUP  102
#define PSINJECT_PAGETRAILER  103
#define PSINJECT_PLATECOLOR  104
#define PSINJECT_SHOWPAGE  105
#define PSINJECT_PAGEBBOX  106
#define PSINJECT_ENDPAGECOMMENTS  107
#define PSINJECT_VMSAVE  200
#define PSINJECT_VMRESTORE  201

#define FEATURESETTING_NUP  0
#define FEATURESETTING_OUTPUT  1
#define FEATURESETTING_PSLEVEL  2
#define FEATURESETTING_CUSTPAPER  3
#define FEATURESETTING_MIRROR  4
#define FEATURESETTING_NEGATIVE  5
#define FEATURESETTING_PROTOCOL  6

#define PSPROTOCOL_ASCII  0
#define PSPROTOCOL_BCP  1
#define PSPROTOCOL_TBCP  2
#define PSPROTOCOL_BINARY  3

#define QDI_SETDIBITS  1
#define QDI_GETDIBITS  2
#define QDI_DIBTOSCREEN  4
#define QDI_STRETCHDIB  8

#define SP_NOTREPORTED  0x4000
#define SP_ERROR  (-1)
#define SP_APPABORT  (-2)
#define SP_USERABORT  (-3)
#define SP_OUTOFDISK  (-4)
#define SP_OUTOFMEMORY  (-5)

#define PR_JOBSTATUS  0x0000

#define OBJ_PEN  1
#define OBJ_BRUSH  2
#define OBJ_DC  3
#define OBJ_METADC  4
#define OBJ_PAL  5
#define OBJ_FONT  6
#define OBJ_BITMAP  7
#define OBJ_REGION  8
#define OBJ_METAFILE  9
#define OBJ_MEMDC  10
#define OBJ_EXTPEN  11
#define OBJ_ENHMETADC  12
#define OBJ_ENHMETAFILE  13
#define OBJ_COLORSPACE  14

#define MWT_IDENTITY  1
#define MWT_LEFTMULTIPLY  2
#define MWT_RIGHTMULTIPLY  3
#define MWT_MIN  MWT_IDENTITY
#define MWT_MAX  MWT_RIGHTMULTIPLY

#define CS_ENABLE  0x00000001
#define CS_DISABLE  0x00000002
#define CS_DELETE_TRANSFORM  0x00000003

#define LCS_SIGNATURE  A'PSOC'
#define LCS_sRGB  A'sRGB'
#define LCS_WINDOWS_COLOR_SPACE  A'Win '
#define LCS_CALIBRATED_RGB  0x00000000
#define LCS_GM_BUSINESS  0x00000001
#define LCS_GM_GRAPHICS  0x00000002
#define LCS_GM_IMAGES  0x00000004
#define LCS_GM_ABS_COLORIMETRIC  0x00000008

#define CM_OUT_OF_GAMUT  255
#define CM_IN_GAMUT  0

#define ICM_ADDPROFILE  1
#define ICM_DELETEPROFILE  2
#define ICM_QUERYPROFILE  3
#define ICM_SETDEFAULTPROFILE  4
#define ICM_REGISTERICMATCHER  5
#define ICM_UNREGISTERICMATCHER  6
#define ICM_QUERYMATCH  7

#define PROFILE_LINKED  A'LINK'
#define PROFILE_EMBEDDED  A'MBED'

#define BI_RGB  0
#define BI_RLE8  1
#define BI_RLE4  2
#define BI_BITFIELDS  3
#define BI_JPEG  4
#define BI_PNG  5

#define TCI_SRCCHARSET  1
#define TCI_SRCCODEPAGE  2
#define TCI_SRCFONTSIG  3
#if WINVER >= NTDDI_WINXP
	#define TCI_SRCLOCALE   0x1000
#endif

#define TMPF_FIXED_PITCH  0x01
#define TMPF_VECTOR  0x02
#define TMPF_DEVICE  0x08
#define TMPF_TRUETYPE  0x04

#define NTM_REGULAR  0x00000040
#define NTM_BOLD  0x00000020
#define NTM_ITALIC  0x00000001
#define NTM_NONNEGATIVE_AC  0x00010000
#define NTM_PS_OPENTYPE  0x00020000
#define NTM_TT_OPENTYPE  0x00040000
#define NTM_MULTIPLEMASTER  0x00080000
#define NTM_TYPE1  0x00100000
#define NTM_DSIG  0x00200000

#define LF_FACESIZE  32
#define LF_FULLFACESIZE  64

#define OUT_DEFAULT_PRECIS  0
#define OUT_STRING_PRECIS  1
#define OUT_CHARACTER_PRECIS  2
#define OUT_STROKE_PRECIS  3
#define OUT_TT_PRECIS  4
#define OUT_DEVICE_PRECIS  5
#define OUT_RASTER_PRECIS  6
#define OUT_TT_ONLY_PRECIS  7
#define OUT_OUTLINE_PRECIS  8
#define OUT_SCREEN_OUTLINE_PRECIS  9
#define OUT_PS_ONLY_PRECIS  10

#define CLIP_DEFAULT_PRECIS  0
#define CLIP_CHARACTER_PRECIS  1
#define CLIP_STROKE_PRECIS  2
#define CLIP_MASK  0xF
#Define CLIP_LH_ANGLES 16
#Define CLIP_TT_ALWAYS 32
#Define CLIP_EMBEDDED 128
#if WINVER >= NTDDI_VISTA
	#define CLIP_DFA_DISABLE (4<<4)
#endif

#define DEFAULT_QUALITY  0
#define DRAFT_QUALITY  1
#define PROOF_QUALITY  2
#define NONANTIALIASED_QUALITY  3
#define ANTIALIASED_QUALITY  4
#if WINVER >= NTDDI_WINXP
	#define CLEARTYPE_QUALITY       5
	#define CLEARTYPE_NATURAL_QUALITY       6
#endif

#define DEFAULT_PITCH  0
#define FIXED_PITCH  1
#define VARIABLE_PITCH  2
#define MONO_FONT  8

#define ANSI_CHARSET  0
#define DEFAULT_CHARSET  1
#define SYMBOL_CHARSET  2
#define MAC_CHARSET  77
#define SHIFTJIS_CHARSET  128
#define HANGEUL_CHARSET  129
#define HANGUL_CHARSET  129
#define JOHAB_CHARSET  130
#define GB2312_CHARSET  134
#define CHINESEBIG5_CHARSET  136
#define GREEK_CHARSET  161
#define TURKISH_CHARSET  162
#define VIETNAMESE_CHARSET  163
#define HEBREW_CHARSET  177
#define ARABIC_CHARSET  178
#define BALTIC_CHARSET  186
#define RUSSIAN_CHARSET  204
#define THAI_CHARSET  222
#define EASTEUROPE_CHARSET  238
#define OEM_CHARSET  255

#define FS_LATIN1  0x00000001
#define FS_LATIN2  0x00000002
#define FS_CYRILLIC  0x00000004
#define FS_GREEK  0x00000008
#define FS_TURKISH  0x00000010
#define FS_HEBREW  0x00000020
#define FS_ARABIC  0x00000040
#define FS_BALTIC  0x00000080
#define FS_VIETNAMESE  0x00000100
#define FS_THAI  0x00010000
#define FS_JISJAPAN  0x00020000
#define FS_CHINESESIMP  0x00040000
#define FS_WANSUNG  0x00080000
#define FS_CHINESETRAD  0x00100000
#define FS_JOHAB  0x00200000
#define FS_SYMBOL  0x80000000

#Define FF_DONTCARE 0
#Define FF_ROMAN 16
#Define FF_SWISS 32
#Define FF_MODERN 48
#Define FF_SCRIPT 64
#Define FF_DECORATIVE 80

#define FW_DONTCARE  0
#define FW_THIN  100
#define FW_EXTRALIGHT  200
#define FW_LIGHT  300
#define FW_NORMAL  400
#define FW_MEDIUM  500
#define FW_SEMIBOLD  600
#define FW_BOLD  700
#define FW_EXTRABOLD  800
#define FW_HEAVY  900

#define FW_ULTRALIGHT  FW_EXTRALIGHT
#define FW_REGULAR  FW_NORMAL
#define FW_DEMIBOLD  FW_SEMIBOLD
#define FW_ULTRABOLD  FW_EXTRABOLD
#define FW_BLACK  FW_HEAVY

#define PANOSE_COUNT  10

#define PAN_FAMILYTYPE_INDEX  0
#define PAN_SERIFSTYLE_INDEX  1
#define PAN_WEIGHT_INDEX  2
#define PAN_PROPORTION_INDEX  3
#define PAN_CONTRAST_INDEX  4
#define PAN_STROKEVARIATION_INDEX  5
#define PAN_ARMSTYLE_INDEX  6
#define PAN_LETTERFORM_INDEX  7
#define PAN_MIDLINE_INDEX  8
#define PAN_XHEIGHT_INDEX  9
#define PAN_CULTURE_LATIN  0
#define PAN_ANY  0
#define PAN_NO_FIT  1
#define PAN_FAMILY_TEXT_DISPLAY  2
#define PAN_FAMILY_SCRIPT  3
#define PAN_FAMILY_DECORATIVE  4
#define PAN_FAMILY_PICTORIAL  5
#define PAN_SERIF_COVE  2
#define PAN_SERIF_OBTUSE_COVE  3
#define PAN_SERIF_SQUARE_COVE  4
#define PAN_SERIF_OBTUSE_SQUARE_COVE  5
#define PAN_SERIF_SQUARE  6
#define PAN_SERIF_THIN  7
#define PAN_SERIF_BONE  8
#define PAN_SERIF_EXAGGERATED  9
#define PAN_SERIF_TRIANGLE  10
#define PAN_SERIF_NORMAL_SANS  11
#define PAN_SERIF_OBTUSE_SANS  12
#define PAN_SERIF_PERP_SANS  13
#define PAN_SERIF_FLARED  14
#define PAN_SERIF_ROUNDED  15
#define PAN_WEIGHT_VERY_LIGHT  2
#define PAN_WEIGHT_LIGHT  3
#define PAN_WEIGHT_THIN  4
#define PAN_WEIGHT_BOOK  5
#define PAN_WEIGHT_MEDIUM  6
#define PAN_WEIGHT_DEMI  7
#define PAN_WEIGHT_BOLD  8
#define PAN_WEIGHT_HEAVY  9
#define PAN_WEIGHT_BLACK  10
#define PAN_WEIGHT_NORD  11
#define PAN_PROP_OLD_STYLE  2
#define PAN_PROP_MODERN  3
#define PAN_PROP_EVEN_WIDTH  4
#define PAN_PROP_EXPANDED  5
#define PAN_PROP_CONDENSED  6
#define PAN_PROP_VERY_EXPANDED  7
#define PAN_PROP_VERY_CONDENSED  8
#define PAN_PROP_MONOSPACED  9
#define PAN_CONTRAST_NONE  2
#define PAN_CONTRAST_VERY_LOW  3
#define PAN_CONTRAST_LOW  4
#define PAN_CONTRAST_MEDIUM_LOW  5
#define PAN_CONTRAST_MEDIUM  6
#define PAN_CONTRAST_MEDIUM_HIGH  7
#define PAN_CONTRAST_HIGH  8
#define PAN_CONTRAST_VERY_HIGH  9
#define PAN_STROKE_GRADUAL_DIAG  2
#define PAN_STROKE_GRADUAL_TRAN  3
#define PAN_STROKE_GRADUAL_VERT  4
#define PAN_STROKE_GRADUAL_HORZ  5
#define PAN_STROKE_RAPID_VERT  6
#define PAN_STROKE_RAPID_HORZ  7
#define PAN_STROKE_INSTANT_VERT  8
#define PAN_STRAIGHT_ARMS_HORZ  2
#define PAN_STRAIGHT_ARMS_WEDGE  3
#define PAN_STRAIGHT_ARMS_VERT  4
#define PAN_STRAIGHT_ARMS_SINGLE_SERIF  5
#define PAN_STRAIGHT_ARMS_DOUBLE_SERIF  6
#define PAN_BENT_ARMS_HORZ  7
#define PAN_BENT_ARMS_WEDGE  8
#define PAN_BENT_ARMS_VERT  9
#define PAN_BENT_ARMS_SINGLE_SERIF  10
#define PAN_BENT_ARMS_DOUBLE_SERIF  11
#define PAN_LETT_NORMAL_CONTACT  2
#define PAN_LETT_NORMAL_WEIGHTED  3
#define PAN_LETT_NORMAL_BOXED  4
#define PAN_LETT_NORMAL_FLATTENED  5
#define PAN_LETT_NORMAL_ROUNDED  6
#define PAN_LETT_NORMAL_OFF_CENTER  7
#define PAN_LETT_NORMAL_SQUARE  8
#define PAN_LETT_OBLIQUE_CONTACT  9
#define PAN_LETT_OBLIQUE_WEIGHTED  10
#define PAN_LETT_OBLIQUE_BOXED  11
#define PAN_LETT_OBLIQUE_FLATTENED  12
#define PAN_LETT_OBLIQUE_ROUNDED  13
#define PAN_LETT_OBLIQUE_OFF_CENTER  14
#define PAN_LETT_OBLIQUE_SQUARE  15
#define PAN_MIDLINE_STANDARD_TRIMMED  2
#define PAN_MIDLINE_STANDARD_POINTED  3
#define PAN_MIDLINE_STANDARD_SERIFED  4
#define PAN_MIDLINE_HIGH_TRIMMED  5
#define PAN_MIDLINE_HIGH_POINTED  6
#define PAN_MIDLINE_HIGH_SERIFED  7
#define PAN_MIDLINE_CONSTANT_TRIMMED  8
#define PAN_MIDLINE_CONSTANT_POINTED  9
#define PAN_MIDLINE_CONSTANT_SERIFED  10
#define PAN_MIDLINE_LOW_TRIMMED  11
#define PAN_MIDLINE_LOW_POINTED  12
#define PAN_MIDLINE_LOW_SERIFED  13
#define PAN_XHEIGHT_CONSTANT_SMALL  2
#define PAN_XHEIGHT_CONSTANT_STD  3
#define PAN_XHEIGHT_CONSTANT_LARGE  4
#define PAN_XHEIGHT_DUCKING_SMALL  5
#define PAN_XHEIGHT_DUCKING_STD  6
#define PAN_XHEIGHT_DUCKING_LARGE  7

#define ELF_VENDOR_SIZE  4
#define ELF_VERSION  0
#define ELF_CULTURE_LATIN  0

#define RASTER_FONTTYPE  0x0001
#define DEVICE_FONTTYPE  0x002
#define TRUETYPE_FONTTYPE  0x004

#define PC_RESERVED  0x01
#define PC_EXPLICIT  0x02
#define PC_NOCOLLAPSE  0x04

#define TRANSPARENT  1
#define OPAQUE  2
#define BKMODE_LAST  2

#define GM_COMPATIBLE  1
#define GM_ADVANCED  2
#define GM_LAST  2

#define PT_CLOSEFIGURE  0x01
#define PT_LINETO  0x02
#define PT_BEZIERTO  0x04
#define PT_MOVETO  0x06

#define MM_TEXT  1
#define MM_LOMETRIC  2
#define MM_HIMETRIC  3
#define MM_LOENGLISH  4
#define MM_HIENGLISH  5
#define MM_TWIPS  6
#define MM_ISOTROPIC  7
#define MM_ANISOTROPIC  8
#define MM_MIN  1
#define MM_MAX  8
#define MM_MAX_FIXEDSCALE  6

#define ABSOLUTE  1
#define RELATIVE  2

#define WHITE_BRUSH  0
#define LTGRAY_BRUSH  1
#define GRAY_BRUSH  2
#define DKGRAY_BRUSH  3
#define BLACK_BRUSH  4
#define NULL_BRUSH  5
#define HOLLOW_BRUSH  5
#define WHITE_PEN  6
#define BLACK_PEN  7
#define NULL_PEN  8
#define OEM_FIXED_FONT  10
#define ANSI_FIXED_FONT  11
#define ANSI_VAR_FONT  12
#define SYSTEM_FONT  13
#define DEVICE_DEFAULT_FONT  14
#define DEFAULT_PALETTE  15
#define SYSTEM_FIXED_FONT  16
#define DEFAULT_GUI_FONT  17

#define DC_BRUSH  18
#define DC_PEN  19

#IF WINVER = NTDDI_WINNT4
	#define STOCK_LAST  17
#ELSEIF WINVER = NTDDI_WIN9X
	#define STOCK_LAST  17
#ELSE
	#define STOCK_LAST  19
#endif

#define CLR_INVALID  0xFFFFFFFF

#define BS_SOLID  0
#define BS_NULL  1
#define BS_HOLLOW  BS_NULL
#define BS_HATCHED  2
#define BS_PATTERN  3
#define BS_INDEXED  4
#define BS_DIBPATTERN  5
#define BS_DIBPATTERNPT  6
#define BS_PATTERN8X8  7
#define BS_DIBPATTERN8X8  8
#define BS_MONOPATTERN  9

#define HS_HORIZONTAL  0
#define HS_VERTICAL  1
#define HS_FDIAGONAL  2
#define HS_BDIAGONAL  3
#define HS_CROSS  4
#define HS_DIAGCROSS  5

#define PS_SOLID  0
#define PS_DASH  1
#define PS_DOT  2
#define PS_DASHDOT  3
#define PS_DASHDOTDOT  4
#define PS_NULL  5
#define PS_INSIDEFRAME  6
#define PS_USERSTYLE  7
#define PS_ALTERNATE  8
#define PS_STYLE_MASK  0x0000000F

#define PS_ENDCAP_ROUND  0x00000000
#define PS_ENDCAP_SQUARE  0x00000100
#define PS_ENDCAP_FLAT  0x00000200
#define PS_ENDCAP_MASK  0x00000F00

#define PS_JOIN_ROUND  0x00000000
#define PS_JOIN_BEVEL  0x00001000
#define PS_JOIN_MITER  0x00002000
#define PS_JOIN_MASK  0x0000F000

#define PS_COSMETIC  0x00000000
#define PS_GEOMETRIC  0x00010000
#define PS_TYPE_MASK  0x000F0000

#define AD_COUNTERCLOCKWISE 1
#define AD_CLOCKWISE  2

#define DRIVERVERSION 0
#define TECHNOLOGY  2
#define HORZSIZE  4
#define VERTSIZE  6
#define HORZRES  8
#define VERTRES  10
#define BITSPIXEL  12
#define PLANES  14
#define NUMBRUSHES  16
#define NUMPENS  18
#define NUMMARKERS  20
#define NUMFONTS  22
#define NUMCOLORS  24
#define PDEVICESIZE  26
#define CURVECAPS  28
#define LINECAPS  30
#define POLYGONALCAPS 32
#define TEXTCAPS  34
#define CLIPCAPS  36
#define RASTERCAPS  38
#define ASPECTX  40
#define ASPECTY  42
#define ASPECTXY  44

#define LOGPIXELSX  88
#define LOGPIXELSY  90

#define SIZEPALETTE  104
#define NUMRESERVED  106
#define COLORRES  108

#define PHYSICALWIDTH  110
#define PHYSICALHEIGHT  111
#define PHYSICALOFFSETX 112
#define PHYSICALOFFSETY 113
#define SCALINGFACTORX  114
#define SCALINGFACTORY  115

#define VREFRESH  116
#define DESKTOPVERTRES  117
#define DESKTOPHORZRES  118
#define BLTALIGNMENT  119

#define SHADEBLENDCAPS  120
#define COLORMGMTCAPS  121

#define DT_PLOTTER  0
#define DT_RASDISPLAY  1
#define DT_RASPRINTER  2
#define DT_RASCAMERA  3
#define DT_CHARSTREAM  4
#define DT_METAFILE  5
#define DT_DISPFILE  6

#define CC_NONE  0
#define CC_CIRCLES  1
#define CC_PIE  2
#define CC_CHORD  4
#define CC_ELLIPSES  8
#define CC_WIDE  16
#define CC_STYLED  32
#define CC_WIDESTYLED  64
#define CC_INTERIORS  128
#define CC_ROUNDRECT  256

#define LC_NONE  0
#define LC_POLYLINE  2
#define LC_MARKER  4
#define LC_POLYMARKER  8
#define LC_WIDE  16
#define LC_STYLED  32
#define LC_WIDESTYLED  64
#define LC_INTERIORS  128

#define PC_NONE  0
#define PC_POLYGON  1
#define PC_RECTANGLE  2
#define PC_WINDPOLYGON  4
#define PC_TRAPEZOID  4
#define PC_SCANLINE  8
#define PC_WIDE  16
#define PC_STYLED  32
#define PC_WIDESTYLED  64
#define PC_INTERIORS  128
#define PC_POLYPOLYGON  256
#define PC_PATHS  512

#define CP_NONE  0
#define CP_RECTANGLE  1
#define CP_REGION  2

#define TC_OP_CHARACTER  0x00000001
#define TC_OP_STROKE  0x00000002
#define TC_CP_STROKE  0x00000004
#define TC_CR_90  0x00000008
#define TC_CR_ANY  0x00000010
#define TC_SF_X_YINDEP  0x00000020
#define TC_SA_DOUBLE  0x00000040
#define TC_SA_INTEGER  0x00000080
#define TC_SA_CONTIN  0x00000100
#define TC_EA_DOUBLE  0x00000200
#define TC_IA_ABLE  0x00000400
#define TC_UA_ABLE  0x00000800
#define TC_SO_ABLE  0x00001000
#define TC_RA_ABLE  0x00002000
#define TC_VA_ABLE  0x00004000
#define TC_RESERVED  0x00008000
#define TC_SCROLLBLT  0x00010000

#define RC_NONE
#define RC_BITBLT  1
#define RC_BANDING  2
#define RC_SCALING  4
#define RC_BITMAP64  8
#define RC_GDI20_OUTPUT  0x0010
#define RC_GDI20_STATE  0x0020
#define RC_SAVEBITMAP  0x0040
#define RC_DI_BITMAP  0x0080
#define RC_PALETTE  0x0100
#define RC_DIBTODEV  0x0200
#define RC_BIGFONT  0x0400
#define RC_STRETCHBLT  0x0800
#define RC_FLOODFILL  0x1000
#define RC_STRETCHDIB  0x2000
#define RC_OP_DX_OUTPUT  0x4000
#define RC_DEVBITS  0x8000

#define SB_NONE  0x00000000
#define SB_CONST_ALPHA  0x00000001
#define SB_PIXEL_ALPHA  0x00000002
#define SB_PREMULT_ALPHA  0x00000004
#define SB_GRAD_RECT  0x00000010
#define SB_GRAD_TRI  0x00000020

#define CM_NONE  0x00000000
#define CM_DEVICE_ICM  0x00000001
#define CM_GAMMA_RAMP  0x00000002
#define CM_CMYK_COLOR  0x00000004

#define DIB_RGB_COLORS  0
#define DIB_PAL_COLORS  1

#define SYSPAL_ERROR  0
#define SYSPAL_STATIC  1
#define SYSPAL_NOSTATIC  2
#define SYSPAL_NOSTATIC256  3

#define CBM_INIT  0x04L

#define  FLOODFILLBORDER   0
#define  FLOODFILLSURFACE  1

#define CCHDEVICENAME 32

#define CCHFORMNAME 32

#IF WINVER = NTDDI_WIN9X
	#define DM_SPECVERSION 0x0400
#ELSE
	#define DM_SPECVERSION 0x0401
#endif

#define DM_ORIENTATION  0x00000001
#define DM_PAPERSIZE  0x00000002
#define DM_PAPERLENGTH  0x00000004
#define DM_PAPERWIDTH  0x00000008
#define DM_SCALE  0x00000010
#define DM_POSITION  0x00000020
#define DM_NUP  0x00000040
#define DM_DISPLAYORIENTATION   0x00000080
#define DM_COPIES  0x00000100
#define DM_DEFAULTSOURCE  0x00000200
#define DM_PRINTQUALITY  0x00000400
#define DM_COLOR  0x00000800
#define DM_DUPLEX  0x00001000
#define DM_YRESOLUTION  0x00002000
#define DM_TTOPTION  0x00004000
#define DM_COLLATE  0x00008000
#define DM_FORMNAME  0x00010000
#define DM_LOGPIXELS  0x00020000
#define DM_BITSPERPEL  0x00040000
#define DM_PELSWIDTH  0x00080000
#define DM_PELSHEIGHT  0x00100000
#define DM_DISPLAYFLAGS  0x00200000
#define DM_DISPLAYFREQUENCY 0x00400000
#define DM_ICMMETHOD  0x00800000
#define DM_ICMINTENT  0x01000000
#define DM_MEDIATYPE  0x02000000
#define DM_DITHERTYPE  0x04000000
#define DM_PANNINGWIDTH  0x08000000
#define DM_PANNINGHEIGHT  0x10000000
#define DM_DISPLAYFIXEDOUTPUT   0x20000000

#define DMORIENT_PORTRAIT  1
#define DMORIENT_LANDSCAPE  2

#define DMPAPER_FIRST  1
#define DMPAPER_LETTER  1
#define DMPAPER_LETTERSMALL  2
#define DMPAPER_TABLOID  3
#define DMPAPER_LEDGER  4
#define DMPAPER_LEGAL  5
#define DMPAPER_STATEMENT  6
#define DMPAPER_EXECUTIVE  7
#define DMPAPER_A3  8
#define DMPAPER_A4  9
#define DMPAPER_A4SMALL  10
#define DMPAPER_A5  11
#define DMPAPER_B4  12
#define DMPAPER_B5  13
#define DMPAPER_FOLIO  14
#define DMPAPER_QUARTO  15
#define DMPAPER_10X14  16
#define DMPAPER_11X17  17
#define DMPAPER_NOTE  18
#define DMPAPER_ENV_9  19
#define DMPAPER_ENV_10  20
#define DMPAPER_ENV_11  21
#define DMPAPER_ENV_12  22
#define DMPAPER_ENV_14  23
#define DMPAPER_CSHEET  24
#define DMPAPER_DSHEET  25
#define DMPAPER_ESHEET  26
#define DMPAPER_ENV_DL  27
#define DMPAPER_ENV_C5  28
#define DMPAPER_ENV_C3  29
#define DMPAPER_ENV_C4  30
#define DMPAPER_ENV_C6  31
#define DMPAPER_ENV_C65  32
#define DMPAPER_ENV_B4  33
#define DMPAPER_ENV_B5  34
#define DMPAPER_ENV_B6  35
#define DMPAPER_ENV_ITALY  36
#define DMPAPER_ENV_MONARCH  37
#define DMPAPER_ENV_PERSONAL  38
#define DMPAPER_FANFOLD_US  39
#define DMPAPER_FANFOLD_STD_GERMAN  40
#define DMPAPER_FANFOLD_LGL_GERMAN  41
#define DMPAPER_ISO_B4  42
#define DMPAPER_JAPANESE_POSTCARD  43
#define DMPAPER_9X11  44
#define DMPAPER_10X11  45
#define DMPAPER_15X11  46
#define DMPAPER_ENV_INVITE  47
#define DMPAPER_RESERVED_48  48
#define DMPAPER_RESERVED_49  49
#define DMPAPER_LETTER_EXTRA  50
#define DMPAPER_LEGAL_EXTRA  51
#define DMPAPER_TABLOID_EXTRA  52
#define DMPAPER_A4_EXTRA  53
#define DMPAPER_LETTER_TRANSVERSE  54
#define DMPAPER_A4_TRANSVERSE  55
#define DMPAPER_LETTER_EXTRA_TRANSVERSE 56
#define DMPAPER_A_PLUS  57
#define DMPAPER_B_PLUS  58
#define DMPAPER_LETTER_PLUS  59
#define DMPAPER_A4_PLUS  60
#define DMPAPER_A5_TRANSVERSE  61
#define DMPAPER_B5_TRANSVERSE  62
#define DMPAPER_A3_EXTRA  63
#define DMPAPER_A5_EXTRA  64
#define DMPAPER_B5_EXTRA  65
#define DMPAPER_A2  66
#define DMPAPER_A3_TRANSVERSE  67
#define DMPAPER_A3_EXTRA_TRANSVERSE 68
#define DMPAPER_DBL_JAPANESE_POSTCARD 69
#define DMPAPER_A6  70
#define DMPAPER_JENV_KAKU2  71
#define DMPAPER_JENV_KAKU3  72
#define DMPAPER_JENV_CHOU3  73
#define DMPAPER_JENV_CHOU4  74
#define DMPAPER_LETTER_ROTATED  75
#define DMPAPER_A3_ROTATED  76
#define DMPAPER_A4_ROTATED  77
#define DMPAPER_A5_ROTATED  78
#define DMPAPER_B4_JIS_ROTATED  79
#define DMPAPER_B5_JIS_ROTATED  80
#define DMPAPER_JAPANESE_POSTCARD_ROTATED 81
#define DMPAPER_DBL_JAPANESE_POSTCARD_ROTATED 82
#define DMPAPER_A6_ROTATED  83
#define DMPAPER_JENV_KAKU2_ROTATED  84
#define DMPAPER_JENV_KAKU3_ROTATED  85
#define DMPAPER_JENV_CHOU3_ROTATED  86
#define DMPAPER_JENV_CHOU4_ROTATED  87
#define DMPAPER_B6_JIS  88
#define DMPAPER_B6_JIS_ROTATED  89
#define DMPAPER_12X11  90
#define DMPAPER_JENV_YOU4  91
#define DMPAPER_JENV_YOU4_ROTATED  92
#define DMPAPER_P16K  93
#define DMPAPER_P32K  94
#define DMPAPER_P32KBIG  95
#define DMPAPER_PENV_1  96
#define DMPAPER_PENV_2  97
#define DMPAPER_PENV_3  98
#define DMPAPER_PENV_4  99
#define DMPAPER_PENV_5  100
#define DMPAPER_PENV_6  101
#define DMPAPER_PENV_7  102
#define DMPAPER_PENV_8  103
#define DMPAPER_PENV_9  104
#define DMPAPER_PENV_10  105
#define DMPAPER_P16K_ROTATED  106
#define DMPAPER_P32K_ROTATED  107
#define DMPAPER_P32KBIG_ROTATED  108
#define DMPAPER_PENV_1_ROTATED  109
#define DMPAPER_PENV_2_ROTATED  110
#define DMPAPER_PENV_3_ROTATED  111
#define DMPAPER_PENV_4_ROTATED  112
#define DMPAPER_PENV_5_ROTATED  113
#define DMPAPER_PENV_6_ROTATED  114
#define DMPAPER_PENV_7_ROTATED  115
#define DMPAPER_PENV_8_ROTATED  116
#define DMPAPER_PENV_9_ROTATED  117
#define DMPAPER_PENV_10_ROTATED  118

#IF WINVER >= NTDDI_WINNT4
	#define DMPAPER_LAST DMPAPER_PENV_10_ROTATED
#ELSE
	#define DMPAPER_LAST DMPAPER_A3_EXTRA_TRANSVERSE
#ENDIF

#if WINVER >= NTDDI_WINXP
	/* DEVMODE dmDisplayOrientation specifiations */
	#define DMDO_DEFAULT    0
	#define DMDO_90         1
	#define DMDO_180        2
	#define DMDO_270        3
	/* DEVMODE dmDisplayFixedOutput specifiations */
	#define DMDFO_DEFAULT   0
	#define DMDFO_STRETCH   1
	#define DMDFO_CENTER    2
#endif 

#define DMPAPER_USER  256

#define DMBIN_FIRST  1
#define DMBIN_UPPER  1
#define DMBIN_ONLYONE  1
#define DMBIN_LOWER  2
#define DMBIN_MIDDLE  3
#define DMBIN_MANUAL  4
#define DMBIN_ENVELOPE  5
#define DMBIN_ENVMANUAL  6
#define DMBIN_AUTO  7
#define DMBIN_TRACTOR  8
#define DMBIN_SMALLFMT  9
#define DMBIN_LARGEFMT  10
#define DMBIN_LARGECAPACITY 11
#define DMBIN_CASSETTE  14
#define DMBIN_FORMSOURCE  15
#define DMBIN_LAST  15
#define DMBIN_USER  256

#define DMRES_DRAFT  (-1)
#define DMRES_LOW  (-2)
#define DMRES_MEDIUM  (-3)
#define DMRES_HIGH  (-4)

#define DMCOLOR_MONOCHROME  1
#define DMCOLOR_COLOR  2

#define DMDUP_SIMPLEX  1
#define DMDUP_VERTICAL  2
#define DMDUP_HORIZONTAL 3

#define DMTT_BITMAP  1
#define DMTT_DOWNLOAD  2
#define DMTT_SUBDEV  3
#define DMTT_DOWNLOAD_OUTLINE 4

#define DMCOLLATE_FALSE  0
#define DMCOLLATE_TRUE  1

#define DMDISPLAYFLAGS_TEXTMODE  0x00000004

#define DMNUP_SYSTEM  1
#define DMNUP_ONEUP  2

#define DMICMMETHOD_NONE  1
#define DMICMMETHOD_SYSTEM  2
#define DMICMMETHOD_DRIVER  3
#define DMICMMETHOD_DEVICE  4
#define DMICMMETHOD_USER  256

#define DMICM_SATURATE  1
#define DMICM_CONTRAST  2
#define DMICM_COLORIMETRIC  3
#define DMICM_ABS_COLORIMETRIC  4
#define DMICM_USER  256

#define DMMEDIA_STANDARD  1
#define DMMEDIA_TRANSPARENCY  2
#define DMMEDIA_GLOSSY  3
#define DMMEDIA_USER  256

#define DMDITHER_NONE  1
#define DMDITHER_COARSE  2
#define DMDITHER_FINE  3
#define DMDITHER_LINEART  4
#define DMDITHER_ERRORDIFFUSION 5
#define DMDITHER_RESERVED6  6
#define DMDITHER_RESERVED7  7
#define DMDITHER_RESERVED8  8
#define DMDITHER_RESERVED9  9
#define DMDITHER_GRAYSCALE  10
#define DMDITHER_USER  256

#define DISPLAY_DEVICE_ATTACHED_TO_DESKTOP 0x00000001
#define DISPLAY_DEVICE_MULTI_DRIVER  0x00000002
#define DISPLAY_DEVICE_PRIMARY_DEVICE  0x00000004
#define DISPLAY_DEVICE_MIRRORING_DRIVER  0x00000008
#define DISPLAY_DEVICE_VGA_COMPATIBLE  0x00000010
#define DISPLAY_DEVICE_MODESPRUNED  0x08000000
#if WINVER >= NTDDI_WIN2K
	#define DISPLAY_DEVICE_REMOVABLE           0x00000020
	#define DISPLAY_DEVICE_REMOTE              0x04000000
	#define DISPLAY_DEVICE_DISCONNECT          0x02000000
#endif
#define DISPLAY_DEVICE_TS_COMPATIBLE       0x00200000
#if WINVER >= NTDDI_VISTA
	#define DISPLAY_DEVICE_UNSAFE_MODES_ON     0x00080000
#endif

#if WINVER >= NTDDI_WIN2K
	#define DISPLAY_DEVICE_ACTIVE              0x00000001
	#define DISPLAY_DEVICE_ATTACHED            0x00000002
#endif

#define RDH_RECTANGLES  1

#define SYSRGN  4

#define GGO_METRICS  0
#define GGO_BITMAP  1
#define GGO_NATIVE  2
#define GGO_BEZIER  3

#define GGO_GRAY2_BITMAP  4
#define GGO_GRAY4_BITMAP  5
#define GGO_GRAY8_BITMAP  6
#define GGO_GLYPH_INDEX  0x0080
#define GGO_UNHINTED  0x0100

#define TT_POLYGON_TYPE  24

#define TT_PRIM_LINE  1
#define TT_PRIM_QSPLINE  2
#define TT_PRIM_CSPLINE  3

#define GCP_DBCS  0x0001
#define GCP_REORDER  0x0002
#define GCP_USEKERNING  0x0008
#define GCP_GLYPHSHAPE  0x0010
#define GCP_LIGATE  0x0020
#define GCP_DIACRITIC  0x0100
#define GCP_KASHIDA  0x0400
#define GCP_ERROR  0x8000
#define FLI_MASK  0x103B

#define GCP_JUSTIFY  0x00010000L
#define FLI_GLYPHS  0x00040000L
#define GCP_CLASSIN  0x00080000L
#define GCP_MAXEXTENT  0x00100000L
#define GCP_JUSTIFYIN  0x00200000L
#define GCP_DISPLAYZWG  0x00400000L
#define GCP_SYMSWAPOFF  0x00800000L
#define GCP_NUMERICOVERRIDE 0x01000000L
#define GCP_NEUTRALOVERRIDE 0x02000000L
#define GCP_NUMERICSLATIN  0x04000000L
#define GCP_NUMERICSLOCAL  0x08000000L

#define GCPCLASS_LATIN  1
#define GCPCLASS_HEBREW  2
#define GCPCLASS_ARABIC  2
#define GCPCLASS_NEUTRAL  3
#define GCPCLASS_LOCALNUMBER  4
#define GCPCLASS_LATINNUMBER  5
#define GCPCLASS_LATINNUMERICTERMINATOR 6
#define GCPCLASS_LATINNUMERICSEPARATOR  7
#define GCPCLASS_NUMERICSEPARATOR  8
#define GCPCLASS_PREBOUNDLTR  0x80
#define GCPCLASS_PREBOUNDRTL  0x40
#define GCPCLASS_POSTBOUNDLTR  0x20
#define GCPCLASS_POSTBOUNDRTL  0x10

#define GCPGLYPH_LINKBEFORE  0x8000




#define GCPGLYPH_LINKAFTER  0x4000

#define TT_AVAILABLE  0x0001
#define TT_ENABLED  0x0002

#define PFD_TYPE_RGBA  0
#define PFD_TYPE_COLORINDEX  1

#define PFD_MAIN_PLANE  0
#define PFD_OVERLAY_PLANE  1
#define PFD_UNDERLAY_PLANE  (-1)

#define PFD_DOUBLEBUFFER  0x00000001
#define PFD_STEREO  0x00000002
#define PFD_DRAW_TO_WINDOW  0x00000004
#define PFD_DRAW_TO_BITMAP  0x00000008
#define PFD_SUPPORT_GDI  0x00000010
#define PFD_SUPPORT_OPENGL  0x00000020
#define PFD_GENERIC_FORMAT  0x00000040
#define PFD_NEED_PALETTE  0x00000080
#define PFD_NEED_SYSTEM_PALETTE  0x00000100
#define PFD_SWAP_EXCHANGE  0x00000200
#define PFD_SWAP_COPY  0x00000400
#define PFD_SWAP_LAYER_BUFFERS  0x00000800
#define PFD_GENERIC_ACCELERATED  0x00001000
#define PFD_SUPPORT_DIRECTDRAW  0x00002000
#define PFD_DEPTH_DONTCARE  0x20000000
#define PFD_DOUBLEBUFFER_DONTCARE  0x40000000
#define PFD_STEREO_DONTCARE  0x80000000

#define DM_UPDATE  1
#define DM_COPY  2
#define DM_PROMPT  4
#define DM_MODIFY  8

#define DM_IN_BUFFER  DM_MODIFY
#define DM_IN_PROMPT  DM_PROMPT
#define DM_OUT_BUFFER  DM_COPY
#define DM_OUT_DEFAULT  DM_UPDATE

#define DC_FIELDS  1
#define DC_PAPERS  2
#define DC_PAPERSIZE  3
#define DC_MINEXTENT  4
#define DC_MAXEXTENT  5
#define DC_BINS  6
#define DC_DUPLEX  7
#define DC_SIZE  8
#define DC_EXTRA  9
#define DC_VERSION  10
#define DC_DRIVER  11
#define DC_BINNAMES  12
#define DC_ENUMRESOLUTIONS  13
#define DC_FILEDEPENDENCIES 14
#define DC_TRUETYPE  15
#define DC_PAPERNAMES  16
#define DC_ORIENTATION  17
#define DC_COPIES  18
#define DC_BINADJUST  19
#define DC_EMF_COMPLIANT  20
#define DC_DATATYPE_PRODUCED  21
#define DC_COLLATE  22
#define DC_MANUFACTURER  23
#define DC_MODEL  24

#define DC_PERSONALITY  25
#define DC_PRINTRATE  26
#define DC_PRINTRATEUNIT  27
#define PRINTRATEUNIT_PPM     1
#define PRINTRATEUNIT_CPS     2
#define PRINTRATEUNIT_LPM     3
#define PRINTRATEUNIT_IPM     4
#define DC_PRINTERMEM  28
#define DC_MEDIAREADY  29
#define DC_STAPLE  30
#define DC_PRINTRATEPPM  31
#define DC_COLORDEVICE  32
#define DC_NUP  33

#if WINVER >= NTDDI_WIN2K
	#define DC_MEDIATYPENAMES       34
	#define DC_MEDIATYPES           35
#endif

#define DCTT_BITMAP  0x0000001
#define DCTT_DOWNLOAD  0x0000002
#define DCTT_SUBDEV  0x0000004
#define DCTT_DOWNLOAD_OUTLINE  0x0000008

#define DCBA_FACEUPNONE  0x0000
#define DCBA_FACEUPCENTER  0x0001
#define DCBA_FACEUPLEFT  0x0002
#define DCBA_FACEUPRIGHT  0x0003
#define DCBA_FACEDOWNNONE  0x0100
#define DCBA_FACEDOWNCENTER  0x0101
#define DCBA_FACEDOWNLEFT  0x0102
#define DCBA_FACEDOWNRIGHT  0x0103

#define GS_8BIT_INDICES  0x00000001
#define GGI_MARK_NONEXISTING_GLYPHS  0X0001

#define STAMP_DESIGNVECTOR  (0x8000000 + 64H + 07600h)
#define STAMP_AXESLIST  (0x8000000 + 61H + 03100h)
#define MM_MAX_NUMAXES  16

#define FR_PRIVATE  0x10
#define FR_NOT_ENUM  0x20

#define MM_MAX_AXES_NAMELEN 16

#define AC_SRC_OVER  0x00
#define AC_SRC_ALPHA  0x01

#define GRADIENT_FILL_RECT_H  0x00000000
#define GRADIENT_FILL_RECT_V  0x00000001
#define GRADIENT_FILL_TRIANGLE  0x00000002
#define GRADIENT_FILL_OP_FLAG  0x000000ff

#define CA_NEGATIVE  0x0001
#define CA_LOG_FILTER  0x0002

#define ILLUMINANT_DEVICE_DEFAULT  0
#define ILLUMINANT_A  1
#define ILLUMINANT_B  2
#define ILLUMINANT_C  3
#define ILLUMINANT_D50  4
#define ILLUMINANT_D55  5
#define ILLUMINANT_D65  6
#define ILLUMINANT_D75  7
#define ILLUMINANT_F2  8
#define ILLUMINANT_MAX_INDEX  ILLUMINANT_F2
#define ILLUMINANT_TUNGSTEN  ILLUMINANT_A
#define ILLUMINANT_DAYLIGHT  ILLUMINANT_C
#define ILLUMINANT_FLUORESCENT  ILLUMINANT_F2
#define ILLUMINANT_NTSC  ILLUMINANT_C

#define RGB_GAMMA_MIN  02500
#define RGB_GAMMA_MAX  65000

#define REFERENCE_WHITE_MIN  6000
#define REFERENCE_WHITE_MAX  10000
#define REFERENCE_BLACK_MIN  0
#define REFERENCE_BLACK_MAX  4000

#define COLOR_ADJ_MIN  -100
#define COLOR_ADJ_MAX  100

#define DI_APPBANDING  0x00000001
#define DI_ROPS_READ_DESTINATION  0x00000002

#define FONTMAPPER_MAX 10

#define ICM_OFF  1
#define ICM_ON  2
#define ICM_QUERY  3
#define ICM_DONE_OUTSIDEDC  4

#define ENHMETA_SIGNATURE  0x464D4520
#define ENHMETA_STOCK_OBJECT  0x80000000

#IFNDEF EMR_ENUMERATION
#DEFINE EMR_ENUMERATION
#define EMR_HEADER  1
#define EMR_POLYBEZIER  2
#define EMR_POLYGON  3
#define EMR_POLYLINE  4
#define EMR_POLYBEZIERTO  5
#define EMR_POLYLINETO  6
#define EMR_POLYPOLYLINE  7
#define EMR_POLYPOLYGON  8
#define EMR_SETWINDOWEXTEX  9
#define EMR_SETWINDOWORGEX  10
#define EMR_SETVIEWPORTEXTEX  11
#define EMR_SETVIEWPORTORGEX  12
#define EMR_SETBRUSHORGEX  13
#define EMR_EOF  14
#define EMR_SETPIXELV  15
#define EMR_SETMAPPERFLAGS  16
#define EMR_SETMAPMODE  17
#define EMR_SETBKMODE  18
#define EMR_SETPOLYFILLMODE  19
#define EMR_SETROP2  20
#define EMR_SETSTRETCHBLTMODE  21
#define EMR_SETTEXTALIGN  22
#define EMR_SETCOLORADJUSTMENT  23
#define EMR_SETTEXTCOLOR  24
#define EMR_SETBKCOLOR  25
#define EMR_OFFSETCLIPRGN  26
#define EMR_MOVETOEX  27
#define EMR_SETMETARGN  28
#define EMR_EXCLUDECLIPRECT  29
#define EMR_INTERSECTCLIPRECT  30
#define EMR_SCALEVIEWPORTEXTEX  31
#define EMR_SCALEWINDOWEXTEX  32
#define EMR_SAVEDC  33
#define EMR_RESTOREDC  34
#define EMR_SETWORLDTRANSFORM  35
#define EMR_MODIFYWORLDTRANSFORM  36
#define EMR_SELECTOBJECT  37
#define EMR_CREATEPEN  38
#define EMR_CREATEBRUSHINDIRECT  39
#define EMR_DELETEOBJECT  40
#define EMR_ANGLEARC  41
#define EMR_ELLIPSE  42
#define EMR_RECTANGLE  43
#define EMR_ROUNDRECT  44
#define EMR_ARC  45
#define EMR_CHORD  46
#define EMR_PIE  47
#define EMR_SELECTPALETTE  48
#define EMR_CREATEPALETTE  49
#define EMR_SETPALETTEENTRIES  50
#define EMR_RESIZEPALETTE  51
#define EMR_REALIZEPALETTE  52
#define EMR_EXTFLOODFILL  53
#define EMR_LINETO  54
#define EMR_ARCTO  55
#define EMR_POLYDRAW  56
#define EMR_SETARCDIRECTION  57
#define EMR_SETMITERLIMIT  58
#define EMR_BEGINPATH  59
#define EMR_ENDPATH  60
#define EMR_CLOSEFIGURE  61
#define EMR_FILLPATH  62
#define EMR_STROKEANDFILLPATH  63
#define EMR_STROKEPATH  64
#define EMR_FLATTENPATH  65
#define EMR_WIDENPATH  66
#define EMR_SELECTCLIPPATH  67
#define EMR_ABORTPATH  68
#define EMR_GDICOMMENT  70
#define EMR_FILLRGN  71
#define EMR_FRAMERGN  72
#define EMR_INVERTRGN  73
#define EMR_PAINTRGN  74
#define EMR_EXTSELECTCLIPRGN  75
#define EMR_BITBLT  76
#define EMR_STRETCHBLT  77
#define EMR_MASKBLT  78
#define EMR_PLGBLT  79
#define EMR_SETDIBITSTODEVICE  80
#define EMR_STRETCHDIBITS  81
#define EMR_EXTCREATEFONTINDIRECTW  82
#define EMR_EXTTEXTOUTA  83
#define EMR_EXTTEXTOUTW  84
#define EMR_POLYBEZIER16  85
#define EMR_POLYGON16  86
#define EMR_POLYLINE16  87
#define EMR_POLYBEZIERTO16  88
#define EMR_POLYLINETO16  89
#define EMR_POLYPOLYLINE16  90
#define EMR_POLYPOLYGON16  91
#define EMR_POLYDRAW16  92
#define EMR_CREATEMONOBRUSH  93
#define EMR_CREATEDIBPATTERNBRUSHPT  94
#define EMR_EXTCREATEPEN  95
#define EMR_POLYTEXTOUTA  96
#define EMR_POLYTEXTOUTW  97
#define EMR_SETICMMODE  98
#define EMR_CREATECOLORSPACE  99
#define EMR_SETCOLORSPACE  100
#define EMR_DELETECOLORSPACE  101
#define EMR_GLSRECORD  102
#define EMR_GLSBOUNDEDRECORD  103
#define EMR_PIXELFORMAT  104
#define EMR_RESERVED_105  105
#define EMR_RESERVED_106  106
#define EMR_RESERVED_107  107
#define EMR_RESERVED_108  108
#define EMR_RESERVED_109  109
#define EMR_RESERVED_110  110
#define EMR_COLORCORRECTPALETTE  111
#define EMR_SETICMPROFILEA  112
#define EMR_SETICMPROFILEW  113
#define EMR_ALPHABLEND  114
#define EMR_SETLAYOUT  115
#define EMR_TRANSPARENTBLT  116
#define EMR_RESERVED_117 117
#define EMR_GRADIENTFILL  118
#define EMR_RESERVED_119  119
#define EMR_RESERVED_120  120
#define EMR_COLORMATCHTOTARGETW  121
#define EMR_CREATECOLORSPACEW  122

#define EMR_MIN  1
#define EMR_MAX  122
#ENDIF

#define SETICMPROFILE_EMBEDED  0x00000001
#define CREATECOLORSPACE_EMBEDED  0x00000001
#define COLORMATCHTOTARGET_EMBEDED  0x00000001

#define GDICOMMENT_IDENTIFIER  0x43494447
#define GDICOMMENT_WINDOWS_METAFILE  0x80000001
#define GDICOMMENT_BEGINGROUP  0x00000002
#define GDICOMMENT_ENDGROUP  0x00000003
#define GDICOMMENT_MULTIFORMATS  0x40000004
#define EPS_SIGNATURE  0x46535045
#define GDICOMMENT_UNICODE_STRING  0x00000040
#define GDICOMMENT_UNICODE_END  0x00000080

#define WGL_FONT_LINES  0
#define WGL_FONT_POLYGONS  1

#define LPD_DOUBLEBUFFER  0x00000001
#define LPD_STEREO  0x00000002
#define LPD_SUPPORT_GDI  0x00000010
#define LPD_SUPPORT_OPENGL  0x00000020
#define LPD_SHARE_DEPTH  0x00000040
#define LPD_SHARE_STENCIL  0x00000080
#define LPD_SHARE_ACCUM  0x00000100
#define LPD_SWAP_EXCHANGE  0x00000200
#define LPD_SWAP_COPY  0x00000400
#define LPD_TRANSPARENT  0x00001000

#define LPD_TYPE_RGBA  0
#define LPD_TYPE_COLORINDEX  1

#define WGL_SWAP_MAIN_PLANE  0x00000001
#define WGL_SWAP_OVERLAY1  0x00000002
#define WGL_SWAP_OVERLAY2  0x00000004
#define WGL_SWAP_OVERLAY3  0x00000008
#define WGL_SWAP_OVERLAY4  0x00000010
#define WGL_SWAP_OVERLAY5  0x00000020
#define WGL_SWAP_OVERLAY6  0x00000040
#define WGL_SWAP_OVERLAY7  0x00000080
#define WGL_SWAP_OVERLAY8  0x00000100
#define WGL_SWAP_OVERLAY9  0x00000200
#define WGL_SWAP_OVERLAY10  0x00000400
#define WGL_SWAP_OVERLAY11  0x00000800
#define WGL_SWAP_OVERLAY12  0x00001000
#define WGL_SWAP_OVERLAY13  0x00002000
#define WGL_SWAP_OVERLAY14  0x00004000
#define WGL_SWAP_OVERLAY15  0x00008000
#define WGL_SWAP_UNDERLAY1  0x00010000
#define WGL_SWAP_UNDERLAY2  0x00020000
#define WGL_SWAP_UNDERLAY3  0x00040000
#define WGL_SWAP_UNDERLAY4  0x00080000
#define WGL_SWAP_UNDERLAY5  0x00100000
#define WGL_SWAP_UNDERLAY6  0x00200000
#define WGL_SWAP_UNDERLAY7  0x00400000
#define WGL_SWAP_UNDERLAY8  0x00800000
#define WGL_SWAP_UNDERLAY9  0x01000000
#define WGL_SWAP_UNDERLAY10  0x02000000
#define WGL_SWAP_UNDERLAY11  0x04000000
#define WGL_SWAP_UNDERLAY12  0x08000000
#define WGL_SWAP_UNDERLAY13  0x10000000
#define WGL_SWAP_UNDERLAY14  0x20000000
#define WGL_SWAP_UNDERLAY15  0x40000000

#define WGL_SWAPMULTIPLE_MAX 16

DRAWPATRECT STRUCT
	ptPosition POINT
	ptSize POINT
	wStyle DW
	wPattern DW
ENDS

PSINJECTDATA STRUCT
	DataBytes DD
	InjectionPoint DW
	PageNumber DW
ENDS

PSFEATURE_OUTPUT STRUCT
	bPageIndependent DD
	bSetPageDevice DD
ENDS

PSFEATURE_CUSTPAPER STRUCT
	lOrientation DD
	lWidth DD
	lHeight DD
	lWidthOffset DD
	lHeightOffset DD
ENDS

XFORM STRUCT
	eM11 FLOAT
	eM12 FLOAT
	eM21 FLOAT
	eM22 FLOAT
	eDx FLOAT
	eDy FLOAT
ENDS

BITMAP STRUCT
	bmType DD
	bmWidth DD
	bmHeight DD
	bmWidthBytes DD
	bmPlanes DW
	bmBitsPixel DW
	bmBits PTR
ENDS

RGBTRIPLE STRUCT
	rgbtBlue DB
	rgbtGreen DB
	rgbtRed DB
ENDS

RGBQUAD STRUCT
	rgbBlue DB
	rgbGreen DB
	rgbRed DB
	rgbReserved DB
ENDS


CIEXYZ STRUCT
	ciexyzX FXPT2DOT30
	ciexyzY FXPT2DOT30
	ciexyzZ FXPT2DOT30
ENDS

CEXYZTRIPLE STRUCT
	ciexyzRed DD
	ciexyzGreen DD
	ciexyzBlue DD
ENDS

LOGCOLORSPACEA STRUCT
	lcsSignature DD
	lcsVersion DD
	lcsSize DD
	lcsCSType DD
	lcsIntent DD
	lcsEndpoints CEXYZTRIPLE
	lcsGammaRed DD
	lcsGammaGreen DD
	lcsGammaBlue DD
	lcsFilename DB MAX_PATH DUP
ENDS

LOGCOLORSPACEW STRUCT
	lcsSignature DD
	lcsVersion DD
	lcsSize DD
	lcsCSType DD
	lcsIntent DD
	lcsEndpoints CEXYZTRIPLE
	lcsGammaRed DD
	lcsGammaGreen DD
	lcsGammaBlue DD
	lcsFilename DW MAX_PATH DUP
ENDS

BITMAPCOREHEADER STRUCT
	bcSize DD
	bcWidth DW
	bcHeight DW
	bcPlanes DW
	bcBitCount DW
ENDS

BITMAPINFOHEADER STRUCT
	biSize DD
	biWidth DD
	biHeight DD
	biPlanes DW
	biBitCount DW
	biCompression DD
	biSizeImage DD
	biXPelsPerMeter DD
	biYPelsPerMeter DD
	biClrUsed DD
	biClrImportant DD
ENDS

BITMAPV4HEADER STRUCT
	bV4Size DD
	bV4Width DD
	bV4Height DD
	bV4Planes DW
	bV4BitCount DW
	bV4V4Compression DD
	bV4SizeImage DD
	bV4XPelsPerMeter DD
	bV4YPelsPerMeter DD
	bV4ClrUsed DD
	bV4ClrImportant DD
	bV4RedMask DD
	bV4GreenMask DD
	bV4BlueMask DD
	bV4AlphaMask DD
	bV4CSType DD
	bV4Endpoints CIEXYZTRIPLE
	bV4GammaRed DD
	bV4GammaGreen DD
	bV4GammaBlue DD
ENDS

BITMAPV5HEADER STRUCT
	bV5Size DD
	bV5Width DD
	bV5Height DD
	bV5Planes DW
	bV5BitCount DW
	bV5Compression DD
	bV5SizeImage DD
	bV5XPelsPerMeter DD
	bV5YPelsPerMeter DD
	bV5ClrUsed DD
	bV5ClrImportant DD
	bV5RedMask DD
	bV5GreenMask DD
	bV5BlueMask DD
	bV5AlphaMask DD
	bV5CSType DD
	bV5Endpoints CIEXYZTRIPLE
	bV5GammaRed DD
	bV5GammaGreen DD
	bV5GammaBlue DD
	bV5Intent DD
	bV5ProfileData DD
	bV5ProfileSize DD
	bV5Reserved DD
ENDS

BITMAPINFO STRUCT
	bmiHeader BITMAPINFOHEADER
	bmiColors RGBQUAD
ENDS

BITMAPCOREINFO STRUCT
	bmciHeader BITMAPCOREHEADER
	bmciColors RGBTRIPLE
ENDS

BITMAPFILEHEADER STRUCT
	bfType DW
	bfSize DD
	bfReserved1 DW
	bfReserved2 DW
	bfOffBits DD
ENDS

FONTSIGNATURE STRUCT
	fsUsb DD 4 DUP
	fsCsb DD 2 DUP
ENDS

CHARSETINFO STRUCT
	ciCharset DD
	ciACP DD
	fs FONTSIGNATURE
ENDS

LOCALESIGNATURE STRUCT
	lsUsb DD 4 DUP
	lsCsbDefault DD 2 DUP
	lsCsbSupported DD 2 DUP
ENDS

HANDLETABLE STRUCT
	objectHandle HANDLE
ENDS

METARECORD STRUCT
	rdSize DD
	rdFunction DW
	rdParm DW
ENDS

METAFILEPICT STRUCT
	mm DD
	xExt DD
	yExt DD
	hMF HANDLE
ENDS

METAHEADER STRUCT
	mtType DW
	mtHeaderSize DW
	mtVersion DW
	mtSize DD
	mtNoObjects DW
	mtMaxRecord DD
	mtNoParameters DW
ENDS

ENHMETARECORD STRUCT
	iType DD
	nSize DD
	dParm DD
ENDS

ENHMETAHEADER STRUCT
	iType DD
	nSize DD
	rclBounds RECTL
	rclFrame RECTL
	dSignature DD
	nVersion DD
	nBytes DD
	nRecords DD
	nHandles DW
	sReserved DW
	nDescription DD
	offDescription DD
	nPalEntries DD
	szlDevice SIZEL
	szlMillimeters SIZEL
#IF WINVER >= NTDDI_WINNT4
	cbPixelFormat DD
	offPixelFormat DD
	bOpenGL DD
#ENDIF
#IF WINVER >= NTDDI_WIN2K
	szlMicrometers SIZEL
#ENDIF
ENDS

ENHMETAHEADER3 STRUCT
	iType DD
	nSize DD
	rclBounds RECTL
	rclFrame RECTL
	dSignature DD
	nVersion DD
	nBytes DD
	nRecords DD
	nHandles DW
	sReserved DW
	nDescription DD
	offDescription DD
	nPalEntries DD
	szlDevice SIZEL
	szlMillimeters SIZEL
ENDS

TEXTMETRICA STRUCT
	tmHeight DD
	tmAscent DD
	tmDescent DD
	tmInternalLeading DD
	tmExternalLeading DD
	tmAveCharWidth DD
	tmMaxCharWidth DD
	tmWeight DD
	tmOverhang DD
	tmDigitizedAspectX DD
	tmDigitizedAspectY DD
	tmFirstChar DB
	tmLastChar DB
	tmDefaultChar DB
	tmBreakChar DB
	tmItalic DB
	tmUnderlined DB
	tmStruckOut DB
	tmPitchAndFamily DB
	tmCharSet DB
ENDS

TEXTMETRICW STRUCT
	tmHeight DD
	tmAscent DD
	tmDescent DD
	tmInternalLeading DD
	tmExternalLeading DD
	tmAveCharWidth DD
	tmMaxCharWidth DD
	tmWeight DD
	tmOverhang DD
	tmDigitizedAspectX DD
	tmDigitizedAspectY DD
	tmFirstChar DW
	tmLastChar DW
	tmDefaultChar DW
	tmBreakChar DW
	tmItalic DB
	tmUnderlined DB
	tmStruckOut DB
	tmPitchAndFamily DB
	tmCharSet DB
ENDS

NEWTEXTMETRICA STRUCT
	tmHeight DD
	tmAscent DD
	tmDescent DD
	tmInternalLeading DD
	tmExternalLeading DD
	tmAveCharWidth DD
	tmMaxCharWidth DD
	tmWeight DD
	tmOverhang DD
	tmDigitizedAspectX DD
	tmDigitizedAspectY DD
	tmFirstChar DB
	tmLastChar DB
	tmDefaultChar DB
	tmBreakChar DB
	tmItalic DB
	tmUnderlined DB
	tmStruckOut DB
	tmPitchAndFamily DB
	tmCharSet DB
	ntmFlags DD
	ntmSizeEM DD
	ntmCellHeight DD
	ntmAvgWidth DD
ENDS

NEWTEXTMETRICW STRUCT
	tmHeight DD
	tmAscent DD
	tmDescent DD
	tmInternalLeading DD
	tmExternalLeading DD
	tmAveCharWidth DD
	tmMaxCharWidth DD
	tmWeight DD
	tmOverhang DD
	tmDigitizedAspectX DD
	tmDigitizedAspectY DD
	tmFirstChar DW
	tmLastChar DW
	tmDefaultChar DW
	tmBreakChar DW
	tmItalic DB
	tmUnderlined DB
	tmStruckOut DB
	tmPitchAndFamily DB
	tmCharSet DB
	ntmFlags DD
	ntmSizeEM DD
	ntmCellHeight DD
	ntmAvgWidth DD
ENDS

NEWTEXTMETRICEXA STRUCT
	ntmTm NEWTEXTMETRICA
	ntmFontSig FONTSIGNATURE
ENDS

NEWTEXTMETRICEXW STRUCT
	ntmTm NEWTEXTMETRICW
	ntmFontSig FONTSIGNATURE
ENDS

PELARRAY STRUCT
	paXCount DD
	paYCount DD
	paXExt DD
	paYExt DD
	paRGBs DB
ENDS

LOGBRUSH STRUCT
	lbStyle DD
	lbColor DD
	lbHatch ULONG_PTR
ENDS

LOGBRUSH32 STRUCT
	lbStyle DD
	lbColor DD
	lbHatch DD
ENDS

LOGPEN STRUCT
	lopnStyle DD
	lopnWidth POINT
	lopnColor DD
ENDS

EXTLOGPEN STRUCT
	elpPenStyle DD
	elpWidth DD
	elpBrushStyle DD
	elpColor DD
	elpHatch ULONG_PTR
	elpNumEntries DD
	elpStyleEntry DD
ENDS

PALETTEENTRY STRUCT
	peRed DB
	peGreen DB
	peBlue DB
	peFlags DB
ENDS

LOGPALETTE STRUCT
	palVersion DW
	palNumEntries DW
	palPalEntry PALETTEENTRY
ENDS

#IFNDEF LOGFONTA
LOGFONTA STRUCT
	lfHeight DD
	lfWidth DD
	lfEscapement DD
	lfOrientation DD
	lfWeight DD
	lfItalic DB
	lfUnderline DB
	lfStrikeOut DB
	lfCharSet DB
	lfOutPrecision DB
	lfClipPrecision DB
	lfQuality DB
	lfPitchAndFamily DB
	lfFaceName DB LF_FACESIZE DUP
ENDS
#ENDIF

#IFNDEF LOGFONTW
LOGFONTW STRUCT
	lfHeight DD
	lfWidth DD
	lfEscapement DD
	lfOrientation DD
	lfWeight DD
	lfItalic DB
	lfUnderline DB
	lfStrikeOut DB
	lfCharSet DB
	lfOutPrecision DB
	lfClipPrecision DB
	lfQuality DB
	lfPitchAndFamily DB
	lfFaceName DW LF_FACESIZE DUP
ENDS
#ENDIF

ENUMLOGFONTA STRUCT
	elfLogFont LOGFONTA
	elfFullName DB LF_FULLFACESIZE DUP
	elfStyle DB LF_FACESIZE DUP
ENDS

ENUMLOGFONTW STRUCT
	elfLogFont LOGFONTW
	elfFullName DW LF_FULLFACESIZE DUP
	elfStyle DW LF_FACESIZE DUP
ENDS

ENUMLOGFONTEXA STRUCT
	elfLogFont LOGFONTA
	elfFullName DB LF_FULLFACESIZE DUP
	elfStyle DB LF_FACESIZE DUP
	elfScript DB LF_FACESIZE DUP
ENDS

ENUMLOGFONTEXW STRUCT
	elfLogFont LOGFONTW
	elfFullName DW LF_FULLFACESIZE DUP
	elfStyle DW LF_FACESIZE DUP
	elfScript DW LF_FACESIZE DUP
ENDS

PANOSE STRUCT
	bFamilyType DB
	bSerifStyle DB
	bWeight DB
	bProportion DB
	bContrast DB
	bStrokeVariation DB
	bArmStyle DB
	bLetterform DB
	bMidline DB
	bXHeight DB
ENDS

EXTLOGFONTA STRUCT
	elfLogFont LOGFONTA
	elfFullName DB LF_FULLFACESIZE DUP
	elfStyle DB LF_FACESIZE DUP
	elfVersion DD
	elfStyleSize DD
	elfMatch DD
	elfReserved DD
	elfVendorId DB ELF_VENDOR_SIZE DUP
	elfCulture DD
	elfPanose PANOSE
ENDS

EXTLOGFONTW STRUCT
	elfLogFont LOGFONTW
	elfFullName DW LF_FULLFACESIZE DUP
	elfStyle DW LF_FACESIZE DUP
	elfVersion DD
	elfStyleSize DD
	elfMatch DD
	elfReserved DD
	elfVendorId DB ELF_VENDOR_SIZE DUP
	elfCulture DD
	elfPanose PANOSE
ENDS

DEVMODEA STRUCT
	dmDeviceName DB CCHDEVICENAME DUP
	dmSpecVersion DW
	dmDriverVersion DW
	dmSize DW
	dmDriverExtra DW
	dmFields DD
	UNION
		STRUCT
			dmOrientation DW
			dmPaperSize DW
			dmPaperLength DW
			dmPaperWidth DW
			dmScale DW
			dmCopies DW
			dmDefaultSource DW 
			dmPrintQuality DW
		ENDS
		dmPosition POINTL
		dmDisplayOrientation DD
		dmDisplayFixedOutput DD
    ENDUNION
	dmScale DW
	dmCopies DW
	dmDefaultSource DW
	dmPrintQuality DW
	dmColor DW
	dmDuplex DW
	dmYResolution DW
	dmTTOption DW
	dmCollate DW
	dmFormName DB CCHFORMNAME DUP
	dmLogPixels DW
	dmBitsPerPel DD
	dmPelsWidth DD
	dmPelsHeight DD
	UNION
		dmDisplayFlags DD
		dmNup DD
    ENDUNION
	dmDisplayFrequency DD
	dmICMMethod DD
	dmICMIntent DD
	dmMediaType DD
	dmDitherType DD
	dmReserved1 DD
	dmReserved2 DD
#IF WINVER >= NTDDI_WINNT4
	dmPanningWidth DD
	dmPanningHeight DD
#ENDIF
ENDS

DEVMODEW STRUCT
	dmDeviceName DW CCHDEVICENAME DUP
	dmSpecVersion DW
	dmDriverVersion DW
	dmSize DW
	dmDriverExtra DW
	dmFields DD
	UNION
		STRUCT
			dmOrientation DW
			dmPaperSize DW
			dmPaperLength DW
			dmPaperWidth DW
			dmScale DW
			dmCopies DW
			dmDefaultSource DW 
			dmPrintQuality DW
		ENDS
		dmPosition POINTL
		dmDisplayOrientation DD
		dmDisplayFixedOutput DD
    ENDUNION
	dmScale DW
	dmCopies DW
	dmDefaultSource DW
	dmPrintQuality DW
	dmColor DW
	dmDuplex DW
	dmYResolution DW
	dmTTOption DW
	dmCollate DW
	dmFormName DW CCHFORMNAME DUP
	dmLogPixels DW
	dmBitsPerPel DD
	dmPelsWidth DD
	dmPelsHeight DD
	UNION
		dmDisplayFlags DD
		dmNup DD
    ENDUNION
	dmDisplayFrequency DD
	dmICMMethod DD
	dmICMIntent DD
	dmMediaType DD
	dmDitherType DD
	dmReserved1 DD
	dmReserved2 DD
#IF WINVER >= NTDDI_WINNT4
	dmPanningWidth DD
	dmPanningHeight DD
#ENDIF
ENDS

DISPLAY_DEVICEA STRUCT
	cb DD
	DeviceName DB 32 DUP
	DeviceString DB 128 DUP
	StateFlags DD
	DeviceID DB 128 DUP
	DeviceKey DB 128 DUP
ENDS

DISPLAY_DEVICEW STRUCT
	cb DD
	DeviceName DW 32 DUP
	DeviceString DW 128 DUP
	StateFlags DD
	DeviceID DW 128 DUP
	DeviceKey DW 128 DUP
ENDS

RGNDATAHEADER STRUCT
	dwSize DD
	iType DD
	nCount DD
	nRgnSize DD
	rcBound RECT
ENDS

RGNDATA STRUCT
    rdh RGNDATAHEADER
	Buffer DB
ENDS

ABC STRUCT
	abcA DD
	abcB DD
	abcC DD
ENDS

ABCFLOAT STRUCT
	abcfA FLOAT
	abcfB FLOAT
	abcfC FLOAT
ENDS

OUTLINETEXTMETRICA STRUCT
	otmSize DD
	otmTextMetrics TEXTMETRICA
	otmFiller DB
	otmPanoseNumber PANOSE
	otmfsSelection DD
	otmfsType DD
	otmsCharSlopeRise DD
	otmsCharSlopeRun DD
	otmItalicAngle DD
	otmEMSquare DD
	otmAscent DD
	otmDescent DD
	otmLineGap DD
	otmsCapEmHeight DD
	otmsXHeight DD
	otmrcFontBox RECT
	otmMacAscent DD
	otmMacDescent DD
	otmMacLineGap DD
	otmusMinimumPPEM DD
	otmptSubscriptSize POINT
	otmptSubscriptOffset POINT
	otmptSuperscriptSize POINT
	otmptSuperscriptOffset POINT
	otmsStrikeoutSize DD
	otmsStrikeoutPosition DD
	otmsUnderscoreSize DD
	otmsUnderscorePosition DD
	otmpFamilyName PTR
	otmpFaceName PTR
	otmpStyleName PTR
	otmpFullName PTR
ENDS

OUTLINETEXTMETRICW STRUCT
	otmSize DD
	otmTextMetrics TEXTMETRICW
	otmFiller DB
	otmPanoseNumber PANOSE
	otmfsSelection DD
	otmfsType DD
	otmsCharSlopeRise DD
	otmsCharSlopeRun DD
	otmItalicAngle DD
	otmEMSquare DD
	otmAscent DD
	otmDescent DD
	otmLineGap DD
	otmsCapEmHeight DD
	otmsXHeight DD
	otmrcFontBox RECT
	otmMacAscent DD
	otmMacDescent DD
	otmMacLineGap DD
	otmusMinimumPPEM DD
	otmptSubscriptSize POINT
	otmptSubscriptOffset POINT
	otmptSuperscriptSize POINT
	otmptSuperscriptOffset POINT
	otmsStrikeoutSize DD
	otmsStrikeoutPosition DD
	otmsUnderscoreSize DD
	otmsUnderscorePosition DD
	otmpFamilyName PTR
	otmpFaceName PTR
	otmpStyleName PTR
	otmpFullName PTR
ENDS

POLYTEXTA STRUCT
	x DD
	y DD
	n DD
	lpstr PTR
	uiFlags DD
	rcl RECT
	pdx PTR
ENDS

POLYTEXTW STRUCT
	x DD
	y DD
	n DD
	lpstr PTR
	uiFlags DD
	rcl RECT
	pdx PTR
ENDS

FIXED STRUCT
	fract DW
	value DW
ENDS

MAT2 STRUCT
	eM11 FIXED
	eM12 FIXED
	eM21 FIXED
	eM22 FIXED
ENDS

GLYPHMETRICS STRUCT
	gmBlackBoxX DD
	gmBlackBoxY DD
	gmptGlyphOrigin POINT
	gmCellIncX DW
	gmCellIncY DW
ENDS

POINTFX STRUCT
	x FIXED
	y FIXED
ENDS

TTPOLYCURVE STRUCT
	wType DW
	cpfx DW
	apfx POINTFX
ENDS

TTPOLYGONHEADER STRUCT
	cb DD
	dwType DD
	pfxStart POINTFX
ENDS

GCP_RESULTSA STRUCT
	lStructSize DD
	lpOutString PTR
	lpOrder PTR
	lpDx PTR
	lpCaretPos PTR
	lpClass PTR
	lpGlyphs PTR
	nGlyphs DD
	nMaxFit DD
ENDS

GCP_RESULTSW STRUCT
	lStructSize DD
	lpOutString PTR
	lpOrder PTR
	lpDx PTR
	lpCaretPos PTR
	lpClass PTR
	lpGlyphs PTR
	nGlyphs DD
	nMaxFit DD
ENDS

RASTERIZER_STATUS STRUCT
	nSize DW
	wFlags DW
	nLanguageID DW
ENDS

PIXELFORMATDESCRIPTOR STRUCT
	nSize DW
	nVersion DW
	dwFlags DD
	iPixelType DB
	cColorBits DB
	cRedBits DB
	cRedShift DB
	cGreenBits DB
	cGreenShift DB
	cBlueBits DB
	cBlueShift DB
	cAlphaBits DB
	cAlphaShift DB
	cAccumBits DB
	cAccumRedBits DB
	cAccumGreenBits DB
	cAccumBlueBits DB
	cAccumAlphaBits DB
	cDepthBits DB
	cStencilBits DB
	cAuxBuffers DB
	iLayerType DB
	bReserved DB
	dwLayerMask DD
	dwVisibleMask DD
	dwDamageMask DD
ENDS

WCRANGE STRUCT
	wcLow DW
	cGlyphs DW
ENDS

GLYPHSET STRUCT
	cbThis DD
	flAccel DD
	cGlyphsSupported DD
	cRanges DD
	ranges WCRANGE
ENDS

DESIGNVECTOR STRUCT
	dvReserved DD
	dvNumAxes DD
	dvValues DD MM_MAX_NUMAXES DUP
ENDS

AXISINFOA STRUCT
	axMinValue DD
	axMaxValue DD
	axAxisName DB MM_MAX_AXES_NAMELEN DUP
ENDS

AXISINFOW STRUCT
	axMinValue DD
	axMaxValue DD
	axAxisName DW MM_MAX_AXES_NAMELEN DUP
ENDS

AXESLISTA STRUCT
	axlReserved DD
	axlNumAxes DD
	axlAxisInfo AXISINFOA MM_MAX_NUMAXES DUP
ENDS

AXESLISTW STRUCT
	axlReserved DD
	axlNumAxes DD
	axlAxisInfo AXISINFOW MM_MAX_NUMAXES DUP
ENDS

ENUMLOGFONTEXDVA STRUCT
	elfEnumLogfontEx ENUMLOGFONTEXA
	elfDesignVector DESIGNVECTOR
ENDS

ENUMLOGFONTEXDVW STRUCT
	elfEnumLogfontEx ENUMLOGFONTEXW
	elfDesignVector DESIGNVECTOR
ENDS

ENUMTEXTMETRICA STRUCT
	etmNewTextMetricEx NEWTEXTMETRICEXA
	etmAxesList AXESLISTA
ENDS

ENUMTEXTMETRICW STRUCT
	etmNewTextMetricEx NEWTEXTMETRICEXW
	etmAxesList AXESLISTW
ENDS

TRIVERTEX STRUCT
	x DD
	y DD
	Red DW
	Green DW
	Blue DW
	Alpha DW
ENDS

GRADIENT_TRIANGLE STRUCT
	Vertex1 DD
	Vertex2 DD
	Vertex3 DD
ENDS

GRADIENT_RECT STRUCT
	UpperLeft DD
	LowerRight DD
ENDS

BLENDFUNCTION STRUCT
	BlendOp DB
	BlendFlags DB
	SourceConstantAlpha DB
	AlphaFormat DB
ENDS

DIBSECTION STRUCT
	dsBm BITMAP
	dsBmih BITMAPINFOHEADER
	dsBitfields DD 3 DUP
	dshSection HANDLE
	dsOffset DD
ENDS

COLORADJUSTMENT STRUCT
	caSize DW
	caFlags DW
	caIlluminantIndex DW
	caRedGamma DW
	caGreenGamma DW
	caBlueGamma DW
	caReferenceBlack DW
	caReferenceWhite DW
	caContrast DW
	caBrightness DW
	caColorfulness DW
	caRedGreenTint DW
ENDS

DOCINFOA STRUCT
	cbSize DD
	lpszDocName PTR
	lpszOutput PTR
#IF WINVER >= NTDDI_WINNT4
	lpszDatatype PTR
	fwType DD
#ENDIF
ENDS

DOCINFOW STRUCT
	cbSize DD
	lpszDocName PTR
	lpszOutput PTR
#IF WINVER >= NTDDI_WINNT4
	lpszDatatype PTR
	fwType DD
#ENDIF
ENDS

KERNINGPAIR STRUCT
	wFirst DW
	wSecond DW
	iKernAmount DD
ENDS

EMR STRUCT
	iType DD
	nSize DD
ENDS

EMRTEXT STRUCT
	ptlReference POINTL
	nChars DD
	offString DD
	fOptions DD
	rcl RECTL
	offDx DD
ENDS

ABORTPATH STRUCT
	emr EMR
ENDS

EMRSELECTCLIPPATH STRUCT
	emr EMR
	iMode DD
ENDS

EMRSETMITERLIMIT STRUCT
	emr EMR
	eMiterLimit DD
ENDS

EMRRESTOREDC STRUCT
	emr EMR
	iRelative DD
ENDS

EMRSETARCDIRECTION STRUCT
	emr EMR
	iArcDirection DD
ENDS

EMRSETMAPPERFLAGS STRUCT
	emr EMR
	dwFlags DD
ENDS

EMRSETTEXTCOLOR STRUCT
	emr EMR
	crColor DD
ENDS

EMRSELECTOBJECT STRUCT
	emr EMR
	ihObject DD
ENDS

EMRSELECTPALETTE STRUCT
	emr EMR
	ihPal DD
ENDS

EMRRESIZEPALETTE STRUCT
	emr EMR
	ihPal DD
	cEntries DD
ENDS

EMRSETPALETTEENTRIES STRUCT
	emr EMR
	ihPal DD
	iStart DD
	cEntries DD
	aPalEntries PALETTEENTRY
ENDS

EMRSETCOLORADJUSTMENT STRUCT
	emr EMR
	ColorAdjustment COLORADJUSTMENT
ENDS

EMRGDICOMMENT STRUCT
	emr EMR
	cbData DD
	Data DB
ENDS

EMREOF STRUCT
	emr EMR
	nPalEntries DD
	offPalEntries DD
	nSizeLast DD
ENDS

EMRLINETO STRUCT
	emr EMR
	ptl POINTL
ENDS

EMROFFSETCLIPRGN STRUCT
	emr EMR
	ptlOffset POINTL
ENDS

EMRFILLPATH STRUCT
	emr EMR
	rclBounds RECTL
ENDS

EMREXCLUDECLIPRECT STRUCT
	emr EMR
	rclClip RECTL
ENDS

EMRSETVIEWPORTORGEX STRUCT
	emr EMR
	ptlOrigin POINTL
ENDS

EMRSETVIEWPORTEXTEX STRUCT
	emr EMR
	szlExtent SIZEL
ENDS

EMRSCALEVIEWPORTEXTEX STRUCT
	emr EMR
	xNum DD
	xDenom DD
	yNum DD
	yDenom DD
ENDS

EMRSETWORLDTRANSFORM STRUCT
	emr EMR
	xform XFORM
ENDS

EMRMODIFYWORLDTRANSFORM STRUCT
	emr EMR
	xform XFORM
	iMode DD
ENDS

EMRSETPIXELV STRUCT
	emr EMR
	ptlPixel POINTL
	crColor DD
ENDS

EMREXTFLOODFILL STRUCT
	emr EMR
	ptlStart POINTL
	crColor DD
	iMode DD
ENDS

EMRELLIPSE STRUCT
	emr EMR
	rclBox RECTL
ENDS

EMRROUNDRECT STRUCT
	emr EMR
	rclBox RECTL
	szlCorner SIZEL
ENDS

EMRARC STRUCT
	emr EMR
	rclBox RECTL
	ptlStart POINTL
	ptlEnd POINTL
ENDS

EMRANGLEARC STRUCT
	emr EMR
	ptlCenter POINTL
	nRadius DD
	eStartAngle FLOAT
	eSweepAngle FLOAT
ENDS

EMRPOLYLINE STRUCT
	emr EMR
	rclBounds RECTL
	cptl DD
	aptl POINTL
ENDS

EMRPOLYLINE16 STRUCT
	emr EMR
	rclBounds RECTL
	cpts DD
	apts POINTS
ENDS

EMRPOLYDRAW STRUCT
	emr EMR
	rclBounds RECTL
	cptl DD
	aptl POINTL
	abTypes DB
ENDS

EMRPOLYDRAW16 STRUCT
	emr EMR
	rclBounds RECTL
	cpts DD
	apts POINTS
	abTypes DB
ENDS

EMRPOLYPOLYLINE STRUCT
	emr EMR
	rclBounds RECTL
	nPolys DD
	cptl DD
	aPolyCounts DD
	aptl POINTL
ENDS

EMRPOLYPOLYLINE16 STRUCT
	emr EMR
	rclBounds RECTL
	nPolys DD
	cpts DD
	aPolyCounts DD
	apts POINTS
ENDS

EMRINVERTRGN STRUCT
	emr EMR
	rclBounds RECTL
	cbRgnData DD
	RgnData DB
ENDS

EMRFILLRGN STRUCT
	emr EMR
	rclBounds RECTL
	cbRgnData DD
	ihBrush DD
	RgnData DB
ENDS

EMRFRAMERGN STRUCT
	emr EMR
	rclBounds RECTL
	cbRgnData DD
	ihBrush DD
	szlStroke SIZEL
	RgnData DB
ENDS

EMREXTSELECTCLIPRGN STRUCT
	emr EMR
	cbRgnData DD
	iMode DD
	RgnData DB
ENDS

EMREXTTEXTOUTA STRUCT
	emr EMR
	rclBounds RECTL
	iGraphicsMode DD
	exScale FLOAT
	eyScale FLOAT
	emrtext EMRTEXT
ENDS

EMRPOLYTEXTOUTA STRUCT
	emr EMR
	rclBounds RECTL
	iGraphicsMode DD
	exScale FLOAT
	eyScale FLOAT
	cStrings DD
	aemrtext EMRTEXT
ENDS

EMRBITBLT STRUCT
	emr EMR
	rclBounds RECTL
	xDest DD
	yDest DD
	cxDest DD
	cyDest DD
	dwRop DD
	xSrc DD
	ySrc DD
	xformSrc XFORM
	crBkColorSrc DD
	iUsageSrc DD
	offBmiSrc DD
	cbBmiSrc DD
	offBitsSrc DD
	cbBitsSrc DD
ENDS

EMRSTRETCHBLT STRUCT
	emr EMR
	rclBounds RECTL
	xDest DD
	yDest DD
	cxDest DD
	cyDest DD
	dwRop DD
	xSrc DD
	ySrc DD
	xformSrc XFORM
	crBkColorSrc DD
	iUsageSrc DD
	offBmiSrc DD
	cbBmiSrc DD
	offBitsSrc DD
	cbBitsSrc DD
	cxSrc DD
	cySrc DD
ENDS

EMRMASKBLT STRUCT
	emr EMR
	rclBounds RECTL
	xDest DD
	yDest DD
	cxDest DD
	cyDest DD
	dwRop DD
	xSrc DD
	ySrc DD
	xformSrc XFORM
	crBkColorSrc DD
	iUsageSrc DD
	offBmiSrc DD
	cbBmiSrc DD
	offBitsSrc DD
	cbBitsSrc DD
	xMask DD
	yMask DD
	iUsageMask DD
	offBmiMask DD
	cbBmiMask DD
	offBitsMask DD
	cbBitsMask DD
ENDS

EMRPLGBLT STRUCT
	emr EMR
	rclBounds RECTL
	aptlDest POINTL 3 DUP
	xSrc DD
	ySrc DD
	cxSrc DD
	cySrc DD
	xformSrc XFORM
	crBkColorSrc DD
	iUsageSrc DD
	offBmiSrc DD
	cbBmiSrc DD
	offBitsSrc DD
	cbBitsSrc DD
	xMask DD
	yMask DD
	iUsageMask DD
	offBmiMask DD
	cbBmiMask DD
	offBitsMask DD
	cbBitsMask DD
ENDS

EMRSETDIBITSTODEVICE STRUCT
	emr EMR
	rclBounds RECTL
	xDest DD
	yDest DD
	xSrc DD
	ySrc DD
	cxSrc DD
	cySrc DD
	offBmiSrc DD
	cbBmiSrc DD
	offBitsSrc DD
	cbBitsSrc DD
	iUsageSrc DD
	iStartScan DD
	cScans DD
ENDS

EMRSTRETCHDIBITS STRUCT
	emr EMR
	rclBounds RECTL
	xDest DD
	yDest DD
	xSrc DD
	ySrc DD
	cxSrc DD
	cySrc DD
	offBmiSrc DD
	cbBmiSrc DD
	offBitsSrc DD
	cbBitsSrc DD
	iUsageSrc DD
	dwRop DD
	cxDest DD
	cyDest DD
ENDS

EMREXTCREATEFONTINDIRECTW STRUCT
	emr EMR
	ihFont DD
	elfw EXTLOGFONTW
ENDS

EMRCREATEPALETTE STRUCT
	emr EMR
	ihPal DD
	lgpl LOGPALETTE
ENDS

EMRCREATEPEN STRUCT
	emr EMR
	ihPen DD
	lopn LOGPEN
ENDS

EMREXTCREATEPEN STRUCT
	emr EMR
	ihPen DD
	offBmi DD
	cbBmi DD
	offBits DD
	cbBits DD
	elp EXTLOGPEN
ENDS

EMRCREATEBRUSHINDIRECT STRUCT
	emr EMR
	ihBrush DD
	lb LOGBRUSH32
ENDS

EMRCREATEMONOBRUSH STRUCT
	emr EMR
	ihBrush DD
	iUsage DD
	offBmi DD
	cbBmi DD
	offBits DD
	cbBits DD
ENDS

EMRCREATEDIBPATTERNBRUSHPT STRUCT
	emr EMR
	ihBrush DD
	iUsage DD
	offBmi PTR
	cbBmi DD
	offBits PTR
	cbBits DD
ENDS

EMRFORMAT STRUCT
	dSignature DD
	nVersion DD
	cbData DD
	offData PTR
ENDS

EMRGLSRECORD STRUCT
	emr EMR
	cbData DD
	Data DB
ENDS

EMRGLSBOUNDEDRECORD STRUCT
	emr EMR
	rclBounds RECTL
	cbData DD
	Data DB
ENDS

EMRPIXELFORMAT STRUCT
	emr EMR
	pfd PIXELFORMATDESCRIPTOR
ENDS

EMRCREATECOLORSPACE STRUCT
	emr EMR
	ihCS DD
	lcs LOGCOLORSPACEA
ENDS

EMRSETCOLORSPACE STRUCT
	emr EMR
	ihCS DD
ENDS

EMREXTESCAPE STRUCT
	emr EMR
	iEscape DD
	cbEscData DD
	EscData DB
ENDS

EMRNAMEDESCAPE STRUCT
	emr EMR
	iEscape DD
	cbDriver DD
	cbEscData DD
	EscData DB
ENDS

EMRSETICMPROFILE STRUCT
	emr EMR
	dwFlags DD
	cbName DD
	cbData DD
	Data DB
ENDS

EMRCREATECOLORSPACEW STRUCT
	emr EMR
	ihCS DD
	lcs LOGCOLORSPACEW
	dwFlags DD
	cbData DD
	Data DB
ENDS

COLORMATCHTOTARGET STRUCT
	emr EMR
	dwAction DD
	dwFlags DD
	cbName DD
	cbData DD
	Data DB
ENDS

COLORCORRECTPALETTE STRUCT
	emr EMR
	ihPalette DD
	nFirstEntry DD
	nPalEntries DD
	nReserved DD
ENDS

EMRALPHABLEND STRUCT
	emr EMR
	rclBounds RECTL
	xDest DD
	yDest DD
	cxDest DD
	cyDest DD
	dwRop DD
	xSrc DD
	ySrc DD
	xformSrc XFORM
	crBkColorSrc DD
	iUsageSrc DD
	offBmiSrc DD
	cbBmiSrc DD
	offBitsSrc DD
	cbBitsSrc DD
	cxSrc DD
	cySrc DD
ENDS

EMRGRADIENTFILL STRUCT
	emr EMR
	rclBounds RECTL
	nVer DD
	nTri DD
	ulMode DD
	Ver TRIVERTEX
ENDS

EMRTRANSPARENTBLT STRUCT
	emr EMR
	rclBounds RECTL
	xDest DD
	yDest DD
	cxDest DD
	cyDest DD
	dwRop DD
	xSrc DD
	ySrc DD
	xformSrc XFORM
	crBkColorSrc DD
	iUsageSrc DD
	offBmiSrc DD
	cbBmiSrc DD
	offBitsSrc DD
	cbBitsSrc DD
	cxSrc DD
	cySrc DD
ENDS

POINTFLOAT STRUCT
	x FLOAT
	y FLOAT
ENDS

GLYPHMETRICSFLOAT STRUCT
	gmfBlackBoxX FLOAT
	gmfBlackBoxY FLOAT
	gmfptGlyphOrigin POINTFLOAT
	gmfCellIncX FLOAT
	gmfCellIncY FLOAT
ENDS

LAYERPLANEDESCRIPTOR STRUCT
	nSize DW
	nVersion DW
	dwFlags DD
	iPixelType DB
	cColorBits DB
	cRedBits DB
	cRedShift DB
	cGreenBits DB
	cGreenShift DB
	cBlueBits DB
	cBlueShift DB
	cAlphaBits DB
	cAlphaShift DB
	cAccumBits DB
	cAccumRedBits DB
	cAccumGreenBits DB
	cAccumBlueBits DB
	cAccumAlphaBits DB
	cDepthBits DB
	cStencilBits DB
	cAuxBuffers DB
	iLayerPlane DB
	bReserved DB
	crTransparent DD
ENDS

WGLSWAP STRUCT
	hdc HANDLE
	uiFlags DD
ENDS

#IF WINVER >= NTDDI_VISTA

#define GDIREGISTERDDRAWPACKETVERSION   0x1

GDIREGISTERDDRAWPACKET STRUCT
	dwSize DD
	dwVersion DD
	pfnDdMarshal PTR
	pfnDdUnmarshal PTR
	pfnDdRelease PTR
ENDS

#ENDIF

#define DISPLAYCONFIG_MAXPATH 1024        // Maximum display path in system.
                                          // Max adapter (16) * Max source (16) *
                                          // Max clone pre source (4)

DISPLAYCONFIG_RATIONAL STRUCT
	Numerator DD
	Denominator DD
ENDS

DISPLAYCONFIG_OUTPUT_TECHNOLOGY_OTHER                   = -1
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HD15                    =  0
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SVIDEO                  =  1
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_COMPOSITE_VIDEO         =  2
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_COMPONENT_VIDEO         =  3
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DVI                     =  4
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI                    =  5
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_LVDS                    =  6
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_D_JPN                   =  8
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SDI                     =  9
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL    = 10
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED    = 11
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_UDI_EXTERNAL            = 12
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_UDI_EMBEDDED            = 13
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SDTVDONGLE              = 14
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL                = 0x80000000
DISPLAYCONFIG_OUTPUT_TECHNOLOGY_FORCE_UINT32            = 0xFFFFFFFF

DISPLAYCONFIG_SCANLINE_ORDERING_UNSPECIFIED                 = 0
DISPLAYCONFIG_SCANLINE_ORDERING_PROGRESSIVE                 = 1
DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED                  = 2
DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_UPPERFIELDFIRST  = DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED
DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_LOWERFIELDFIRST  = 3
DISPLAYCONFIG_SCANLINE_ORDERING_FORCE_UINT32                = 0xFFFFFFFF

DISPLAYCONFIG_2DREGION STRUCT
	cx DD
	cy DD
ENDS

DISPLAYCONFIG_VIDEO_SIGNAL_INFO STRUCT
	pixelRate DWORD64
	hSyncFreq DISPLAYCONFIG_RATIONAL
	vSyncFreq DISPLAYCONFIG_RATIONAL
	activeSize DISPLAYCONFIG_2DREGION
	totalSize DISPLAYCONFIG_2DREGION
	videoStandard DWORD32
	scanLineOrdering DD
ENDS

DISPLAYCONFIG_SCALING_IDENTITY                  = 1
DISPLAYCONFIG_SCALING_CENTERED                  = 2
DISPLAYCONFIG_SCALING_STRETCHED                 = 3
DISPLAYCONFIG_SCALING_ASPECTRATIOCENTEREDMAX    = 4
DISPLAYCONFIG_SCALING_CUSTOM                    = 5
DISPLAYCONFIG_SCALING_PREFERRED                 = 128
DISPLAYCONFIG_SCALING_FORCE_UINT32              = 0xFFFFFFFF

DISPLAYCONFIG_ROTATION_IDENTITY     = 1
DISPLAYCONFIG_ROTATION_ROTATE90     = 2
DISPLAYCONFIG_ROTATION_ROTATE180    = 3
DISPLAYCONFIG_ROTATION_ROTATE270    = 4
DISPLAYCONFIG_ROTATION_FORCE_UINT32 = 0xFFFFFFFF

DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE = 1
DISPLAYCONFIG_MODE_INFO_TYPE_TARGET = 2
DISPLAYCONFIG_MODE_INFO_TYPE_FORCE_UINT32 = 0xFFFFFFFF

DISPLAYCONFIG_PIXELFORMAT_8BPP          = 1
DISPLAYCONFIG_PIXELFORMAT_16BPP         = 2
DISPLAYCONFIG_PIXELFORMAT_24BPP         = 3
DISPLAYCONFIG_PIXELFORMAT_32BPP         = 4
DISPLAYCONFIG_PIXELFORMAT_NONGDI        = 5
DISPLAYCONFIG_PIXELFORMAT_FORCE_UINT32  = 0xffffffff

DISPLAYCONFIG_SOURCE_MODE STRUCT
	width DD
	height DD
	pixelFormat DD
	position POINTL
ENDS

DISPLAYCONFIG_TARGET_MODE STRUCT
	targetVideoSignalInfo DISPLAYCONFIG_VIDEO_SIGNAL_INFO
ENDS

DISPLAYCONFIG_MODE_INFO STRUCT
	infoType DD
	id DD
	adapterId LUID
	union
		targetMode DISPLAYCONFIG_TARGET_MODE
		sourceMode DISPLAYCONFIG_SOURCE_MODE
	endunion
ENDS

#define DISPLAYCONFIG_PATH_MODE_IDX_INVALID     0xffffffff

DISPLAYCONFIG_PATH_SOURCE_INFO STRUCT
	adapterId LUID
	id DD
	modeInfoIdx DD
	statusFlags DD
ENDS

//
// Flags for source info structure (from OS to application through QDC)
//

#define DISPLAYCONFIG_SOURCE_IN_USE     0x00000001

DISPLAYCONFIG_PATH_TARGET_INFO STRUCT
	adapterId LUID
	id DD
	modeInfoIdx DD
	outputTechnology DD
	rotation DD
	scaling DD
	refreshRate DISPLAYCONFIG_RATIONAL
	scanLineOrdering DD
	targetAvailable BOOL
	statusFlags DD
ENDS

//
// Status flags for target info structure (from OS to application through QDC)
//
#define DISPLAYCONFIG_TARGET_IN_USE                         0x00000001
#define DISPLAYCONFIG_TARGET_FORCIBLE                       0x00000002
#define DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_BOOT       0x00000004
#define DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_PATH       0x00000008
#define DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_SYSTEM     0x00000010

DISPLAYCONFIG_PATH_INFO STRUCT
	sourceInfo DISPLAYCONFIG_PATH_SOURCE_INFO
	targetInfo DISPLAYCONFIG_PATH_SOURCE_INFO
	flags DD
ENDS

//
// Flags for path info structure (from OS to application through QDC)
//

#define DISPLAYCONFIG_PATH_ACTIVE       0x00000001

DISPLAYCONFIG_TOPOLOGY_INTERNAL       = 0x00000001
DISPLAYCONFIG_TOPOLOGY_CLONE          = 0x00000002
DISPLAYCONFIG_TOPOLOGY_EXTEND         = 0x00000004
DISPLAYCONFIG_TOPOLOGY_EXTERNAL       = 0x00000008
DISPLAYCONFIG_TOPOLOGY_FORCE_UINT32   = 0xFFFFFFFF

DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME             = 1
DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME             = 2
DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE   = 3
DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME            = 4
DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE      = 5
DISPLAYCONFIG_DEVICE_INFO_FORCE_UINT32                = 0xFFFFFFFF

DISPLAYCONFIG_DEVICE_INFO_HEADER STRUCT
	type DD
	size DD
	adapterId LUID
	id DD
ENDS

DISPLAYCONFIG_SOURCE_DEVICE_NAME STRUCT
	header DISPLAYCONFIG_DEVICE_INFO_HEADER
	viewGdiDeviceName WCHAR CCHDEVICENAME DUP
ENDS

DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS UNION
        STRUCT
			friendlyNameFromEdid DD
			friendlyNameForced DD
			edidIdsValid DD
			reserved DD
		ENDS
		value DD
ENDUNION

DISPLAYCONFIG_TARGET_DEVICE_NAME STRUCT
	header DISPLAYCONFIG_DEVICE_INFO_HEADER
	flags DD
	outputTechnology DD
	edidManufactureId DW
	edidProductCodeId DW
	connectorInstance DD
	monitorFriendlyDeviceName WCHAR 64 DUP
	monitorDevicePath WCHAR 128 DUP
ENDS

DISPLAYCONFIG_TARGET_PREFERRED_MODE STRUCT
	header DISPLAYCONFIG_DEVICE_INFO_HEADER
	width DD
	height DD
	targetMode DD
ENDS

DISPLAYCONFIG_ADAPTER_NAME STRUCT
	header DISPLAYCONFIG_DEVICE_INFO_HEADER
	adapterDevicePath WCHAR 128 DUP
ENDS

DISPLAYCONFIG_SET_TARGET_PERSISTENCE STRUCT
	header DISPLAYCONFIG_DEVICE_INFO_HEADER
	union
		STRUCT
			bootPersistenceOn   DWORD32
			reserved DWORD32
		ENDS
		value DWORD32
	endunion
ENDS

//
// Definitions to be used by GetDisplayConfigBufferSizes and QueryDisplayConfig.
//

#define QDC_ALL_PATHS                   0x00000001
#define QDC_ONLY_ACTIVE_PATHS           0x00000002
#define QDC_DATABASE_CURRENT            0x00000004

//
// Definitions used by SetDisplayConfig.
//

#define SDC_TOPOLOGY_INTERNAL           0x00000001
#define SDC_TOPOLOGY_CLONE              0x00000002
#define SDC_TOPOLOGY_EXTEND             0x00000004
#define SDC_TOPOLOGY_EXTERNAL           0x00000008
#define SDC_TOPOLOGY_SUPPLIED           0x00000010
#define SDC_USE_DATABASE_CURRENT        (SDC_TOPOLOGY_INTERNAL | SDC_TOPOLOGY_CLONE | SDC_TOPOLOGY_EXTEND | SDC_TOPOLOGY_EXTERNAL)

#define SDC_USE_SUPPLIED_DISPLAY_CONFIG 0x00000020
#define SDC_VALIDATE                    0x00000040
#define SDC_APPLY                       0x00000080
#define SDC_NO_OPTIMIZATION             0x00000100
#define SDC_SAVE_TO_DATABASE            0x00000200
#define SDC_ALLOW_CHANGES               0x00000400
#define SDC_PATH_PERSIST_IF_REQUIRED    0x00000800
#define SDC_FORCE_MODE_ENUMERATION      0x00001000
#define SDC_ALLOW_PATH_ORDER_CHANGES    0x00002000


#IFDEF UNICODE
	#define TEXTMETRIC TEXTMETRICW
	#define LOGCOLORSPACE LOGCOLORSPACEW
	#define NEWTEXTMETRIC NEWTEXTMETRICW
	#define NEWTEXTMETRICEX NEWTEXTMETRICEXW
	#define LOGFONT LOGFONTW
	#define ENUMLOGFONT ENUMLOGFONTW
	#define ENUMLOGFONTEX ENUMLOGFONTEXW
	#define EXTLOGFONT EXTLOGFONTW
	#define DEVMODE DEVMODEW
	#define DISPLAY_DEVICE DISPLAY_DEVICEW
	#define OUTLINETEXTMETRIC OUTLINETEXTMETRICW
	#define POLYTEXT POLYTEXTW
	#define GCP_RESULTS GCP_RESULTSW
	#define DOCINFO DOCINFOW
	#define AXISINFO AXISINFOW
	#define AXESLIST AXESLISTW
	#define ENUMLOGFONTEXDV ENUMLOGFONTEXDVW
	#define ENUMTEXTMETRIC ENUMTEXTMETRICW
	#define AddFontResource AddFontResourceW
	#define CopyMetaFile CopyMetaFileW
	#define CreateDC CreateDCW
	#define CreateFontIndirect CreateFontIndirectW
	#define CreateFont CreateFontW
	#define CreateIC CreateICW
	#define CreateMetaFile CreateMetaFileW
	#define CreateScalableFontResource CreateScalableFontResourceW
	#define DeviceCapabilities DeviceCapabilitiesW
	#define EnumFontFamiliesEx EnumFontFamiliesExW
	#define EnumFontFamilies EnumFontFamiliesW
	#define EnumFonts EnumFontsW
	#define GetCharWidth GetCharWidthW
	#define GetCharWidth32 GetCharWidth32W
	#define GetCharWidthFloat GetCharWidthFloatW
	#define GetCharABCWidths GetCharABCWidthsW
	#define GetCharABCWidthsFloat GetCharABCWidthsFloatW
	#define GetGlyphOutline GetGlyphOutlineW
	#define GetMetaFile GetMetaFileW
	#define GetOutlineTextMetrics GetOutlineTextMetricsW
	#define GetTextExtentPoint GetTextExtentPointW
	#define GetTextExtentPoint32 GetTextExtentPoint32W
	#define GetTextExtentExPoint GetTextExtentExPointW
	#define GetCharacterPlacement GetCharacterPlacementW
	#define GetGlyphIndices GetGlyphIndicesW
	#IF WINVER > NTDDI_WIN9X
		#define AddFontResourceEx AddFontResourceExW
		#define RemoveFontResourceEx RemoveFontResourceExW
		#define CreateFontIndirectEx CreateFontIndirectExW
	#ENDIF
	#define ResetDC ResetDCW
	#define RemoveFontResource RemoveFontResourceW
	#define CopyEnhMetaFile CopyEnhMetaFileW
	#define CreateEnhMetaFile CreateEnhMetaFileW
	#define GetEnhMetaFile GetEnhMetaFileW
	#define GetEnhMetaFileDescription GetEnhMetaFileDescriptionW
	#define GetTextMetrics GetTextMetricsW
	#define StartDoc StartDocW
	#define GetObject GetObjectW
	#define TextOut TextOutW
	#define ExtTextOut ExtTextOutW
	#define PolyTextOut PolyTextOutW
	#define GetTextFace GetTextFaceW
	#define GetKerningPairs GetKerningPairsW
	#define GetLogColorSpace GetLogColorSpaceW
	#define CreateColorSpace CreateColorSpaceW
	#define GetICMProfile GetICMProfileW
	#define SetICMProfile SetICMProfileW
	#define EnumICMProfiles EnumICMProfilesW
	#define UpdateICMRegKey UpdateICMRegKeyW
	#define wglUseFontBitmaps wglUseFontBitmapsW
	#define wglUseFontOutlines wglUseFontOutlinesW
#else
	#define TEXTMETRIC TEXTMETRICA
	#define LOGCOLORSPACE LOGCOLORSPACEA
	#define NEWTEXTMETRIC NEWTEXTMETRICA
	#define NEWTEXTMETRICEX NEWTEXTMETRICEXA
	#define LOGFONT LOGFONTA
	#define ENUMLOGFONT ENUMLOGFONTA
	#define ENUMLOGFONTEX ENUMLOGFONTEXA
	#define EXTLOGFONT EXTLOGFONTA
	#define DEVMODE DEVMODEA
	#define DISPLAY_DEVICE DISPLAY_DEVICEA
	#define OUTLINETEXTMETRIC OUTLINETEXTMETRICA
	#define POLYTEXT POLYTEXTA
	#define GCP_RESULTS GCP_RESULTSA
	#define DOCINFO DOCINFOA
	#define AXISINFO AXISINFOA
	#define AXESLIST AXESLISTA
	#define ENUMLOGFONTEXDV ENUMLOGFONTEXDVA
	#define ENUMTEXTMETRIC ENUMTEXTMETRICA
	#define AddFontResource AddFontResourceA
	#define CopyMetaFile CopyMetaFileA
	#define CreateDC CreateDCA
	#define CreateFontIndirect CreateFontIndirectA
	#define CreateFont CreateFontA
	#define CreateIC CreateICA
	#define CreateMetaFile CreateMetaFileA
	#define CreateScalableFontResource CreateScalableFontResourceA
	#define DeviceCapabilities DeviceCapabilitiesA
	#define EnumFontFamiliesEx EnumFontFamiliesExA
	#define EnumFontFamilies EnumFontFamiliesA
	#define EnumFonts EnumFontsA
	#define GetCharWidth GetCharWidthA
	#define GetCharWidth32 GetCharWidth32A
	#define GetCharWidthFloat GetCharWidthFloatA
	#define GetCharABCWidths GetCharABCWidthsA
	#define GetCharABCWidthsFloat GetCharABCWidthsFloatA
	#define GetGlyphOutline GetGlyphOutlineA
	#define GetMetaFile GetMetaFileA
	#define GetOutlineTextMetrics GetOutlineTextMetricsA
	#define GetTextExtentPoint GetTextExtentPointA
	#define GetTextExtentPoint32 GetTextExtentPoint32A
	#define GetTextExtentExPoint GetTextExtentExPointA
	#define GetCharacterPlacement GetCharacterPlacementA
	#define GetGlyphIndices GetGlyphIndicesA
	#IF WINVER > NTDDI_WIN9X
		#define AddFontResourceEx AddFontResourceExA
		#define RemoveFontResourceEx RemoveFontResourceExA
		#define CreateFontIndirectEx CreateFontIndirectExA
	#ENDIF
	#define ResetDC ResetDCA
	#define RemoveFontResource RemoveFontResourceA
	#define CopyEnhMetaFile CopyEnhMetaFileA
	#define CreateEnhMetaFile CreateEnhMetaFileA
	#define GetEnhMetaFile GetEnhMetaFileA
	#define GetEnhMetaFileDescription GetEnhMetaFileDescriptionA
	#define GetTextMetrics GetTextMetricsA
	#define StartDoc StartDocA
	#define GetObject GetObjectA
	#define TextOut TextOutA
	#define ExtTextOut ExtTextOutA
	#define PolyTextOut PolyTextOutA
	#define GetTextFace GetTextFaceA
	#define GetKerningPairs GetKerningPairsA
	#define GetLogColorSpace GetLogColorSpaceA
	#define CreateColorSpace CreateColorSpaceA
	#define GetICMProfile GetICMProfileA
	#define SetICMProfile SetICMProfileA
	#define EnumICMProfiles EnumICMProfilesA
	#define UpdateICMRegKey UpdateICMRegKeyA
	#define wglUseFontBitmaps wglUseFontBitmapsA
	#define wglUseFontOutlines wglUseFontOutlinesA
#endif

#endif /* _WINGDI_H */
