#IFNDEF WINSXS_H
#DEFINE WINSXS_H

#IFDEF LINKFILES
	#dynamiclinkfile sxs.dll
#ENDIF

#IFNDEF RPC_H
	#include "rpc.h"
#ENDIF

#IFNDEF RPCNDR_H
	#include "rpcndr.h"
#ENDIF

#ifndef COM_NO_WINDOWS_H
	#IFNDEF WINDOWS_H
		#include "windows.h"
	#ENDIF
	#IFNDEF OLE2_H
		#include "ole2.h"
	#ENDIF
#endif /*COM_NO_WINDOWS_H*/


#IFNDEF OBJIDL_H
	#include "objidl.h"
#ENDIF

#ifndef OLEIDL_H
	#include "oleidl.h"
#ENDIF

//=--------------------------------------------------------------------------=
// winsxs.h
//=--------------------------------------------------------------------------=
// (C) Copyright 1995-1998 Microsoft Corporation.  All Rights Reserved.
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//=--------------------------------------------------------------------------=

//---------------------------------------------------------------------------=
// Fusion Interfaces for sxs assemblies.

#define STREAM_FORMAT_COMPLIB_MODULE    0
#define STREAM_FORMAT_COMPLIB_MANIFEST  1
#define STREAM_FORMAT_WIN32_MODULE      2
#define STREAM_FORMAT_WIN32_MANIFEST    4


#define IASSEMBLYCACHEITEM_COMMIT_FLAG_REFRESH 0x00000001
#define QUERYASMINFO_FLAG_VALIDATE             0x1
#define ASSEMBLYINFO_FLAG_INSTALLED 0x00000001
#define ASSEMBLYINFO_FLAG_PAYLOADRESIDENT 0x00000002

ASSEMBLY_INFO STRUCT
	cbAssemblyInfo LONG
	dwAssemblyFlags DD
	uliAssemblySizeInKB LARGE_INTEGER
	pszCurrentAssemblyPathBuf PTR
	cchBuf LONG
ENDS

#define IASSEMBLYCACHE_UNINSTALL_DISPOSITION_UNINSTALLED 1
#define IASSEMBLYCACHE_UNINSTALL_DISPOSITION_STILL_IN_USE 2
#define IASSEMBLYCACHE_UNINSTALL_DISPOSITION_ALREADY_UNINSTALLED 3
#define IASSEMBLYCACHE_UNINSTALL_DISPOSITION_DELETE_PENDING 4
#define IASSEMBLYCACHEITEM_COMMIT_DISPOSITION_INSTALLED 1
#define IASSEMBLYCACHEITEM_COMMIT_DISPOSITION_REFRESHED 2
#define IASSEMBLYCACHEITEM_COMMIT_DISPOSITION_ALREADY_INSTALLED 3

// {8cedc215-ac4b-488b-93c0-a50a49cb2fb8}
#DEFINE GUID_FUSION_REFCOUNT_UNINSTALL_SUBKEY_GUID <0x8cedc215, 0xac4b, 0x488b, <0x93, 0xc0, 0xa5, 0x0a, 0x49, 0xcb, 0x2f, 0xb8>>

// {b02f9d65-fb77-4f7a-afa5-b391309f11c9}
#DEFINE GUID_FUSION_REFCOUNT_FILEPATH_GUID <0xb02f9d65, 0xfb77, 0x4f7a, <0xaf, 0xa5, 0xb3, 0x91, 0x30, 0x9f, 0x11, 0xc9>>

// {2ec93463-b0c3-45e1-8364-327e96aea856}
#DEFINE GUID_FUSION_REFCOUNT_OPAQUE_STRING_GUID <0x2ec93463, 0xb0c3, 0x45e1, <0x83, 0x64, 0x32, 0x7e, 0x96, 0xae, 0xa8, 0x56>>

FUSION_INSTALL_REFERENCE STRUCT
	cbSize DD
	dwFlags DD
	guidScheme GUID
	szIdentifier PTR
	szNonCannonicalData PTR
ENDS

ASM_NAME_PUBLIC_KEY	= 0
ASM_NAME_PUBLIC_KEY_TOKEN	= 1
ASM_NAME_HASH_VALUE	= 2
ASM_NAME_NAME	= 3
ASM_NAME_MAJOR_VERSION	= 4
ASM_NAME_MINOR_VERSION	= 5
ASM_NAME_BUILD_NUMBER	= 6
ASM_NAME_REVISION_NUMBER	= 7
ASM_NAME_CULTURE	= 8
ASM_NAME_PROCESSOR_ID_ARRAY	= 9
ASM_NAME_OSINFO_ARRAY	= 10
ASM_NAME_HASH_ALGID	= 11
ASM_NAME_ALIAS	= 12
ASM_NAME_CODEBASE_URL	= 13
ASM_NAME_CODEBASE_LASTMOD	= 14
ASM_NAME_NULL_PUBLIC_KEY	= 15
ASM_NAME_NULL_PUBLIC_KEY_TOKEN	= 16
ASM_NAME_CUSTOM	= 17
ASM_NAME_NULL_CUSTOM	= 18
ASM_NAME_MVID	= 19
ASM_NAME_MAX_PARAMS	= 21

ASM_BINDF_FORCE_CACHE_INSTALL	= 0x1
ASM_BINDF_RFS_INTEGRITY_CHECK	= 0x2
ASM_BINDF_RFS_MODULE_CHECK	= 0x4
ASM_BINDF_BINPATH_PROBE_ONLY	= 0x8
ASM_BINDF_SHARED_BINPATH_HINT	= 0x10
ASM_BINDF_PARENT_ASM_HINT	= 0x20

ASM_DISPLAYF_VERSION	= 0x1
ASM_DISPLAYF_CULTURE	= 0x2
ASM_DISPLAYF_PUBLIC_KEY_TOKEN	= 0x4
ASM_DISPLAYF_PUBLIC_KEY	= 0x8
ASM_DISPLAYF_CUSTOM	= 0x10
ASM_DISPLAYF_PROCESSORARCHITECTURE	= 0x20
ASM_DISPLAYF_LANGUAGEID	= 0x40

ASM_CMPF_NAME	= 0x1
ASM_CMPF_MAJOR_VERSION	= 0x2
ASM_CMPF_MINOR_VERSION	= 0x4
ASM_CMPF_BUILD_NUMBER	= 0x8
ASM_CMPF_REVISION_NUMBER	= 0x10
ASM_CMPF_PUBLIC_KEY_TOKEN	= 0x20
ASM_CMPF_CULTURE	= 0x40
ASM_CMPF_CUSTOM	= 0x80
ASM_CMPF_ALL	= 0xFF
ASM_CMPF_DEFAULT	= 0x100

#DEFINE GUID_IID_IAssemblyName <0xCD193BC0,0xB4BC,0x11d2,<0x98,0x33,0x00,0xC0,0x4F,0xC3,0x1D,0x2E>>

IAssemblyName STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	SetProperty PTR
	GetProperty PTR
	Finalize PTR
	GetDisplayName PTR
	Reserved PTR
	GetName PTR
	GetVersion PTR
	IsEqual PTR
	Clone PTR
ENDS

#DEFINE GUID_IID_IAssemblyCacheItem <0x9e3aaeb4,0xd1cd,0x11d2,<0xba,0xb9,0x00,0xc0,0x4f,0x8e,0xce,0xae>>

IAssemblyCacheItem STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	CreateStream PTR
	Commit PTR
	AbortItem PTR
ENDS

#DEFINE GUID_IID_IAssemblyCache <0xe707dcde,0xd1cd,0x11d2,<0xba,0xb9,0x00,0xc0,0x4f,0x8e,0xce,0xae>>

IAssemblyCache STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	UninstallAssembly PTR
	QueryAssemblyInfo PTR
	CreateAssemblyCacheItem PTR
	CreateAssemblyScavenger PTR
	InstallAssembly PTR
ENDS

CANOF_PARSE_DISPLAY_NAME	= 0x1
CANOF_SET_DEFAULT_VALUES	= 0x2

#endif



