#ifndef WINSMCRD_H
#define WINSMCRD_H

/* Windows SmartCard IOCTL definitions */

#IFNDEF FILE_DEVICE_SMARTCARD
	#define FILE_DEVICE_SMARTCARD  0x00000031
#ENDIF

#IFDEF LINKFILES
	#dynamiclinkfile Winscard.dll
#ENDIF

#define SCARD_ATR_LENGTH  33

#define SCARD_PROTOCOL_UNDEFINED 0x00000000
#define SCARD_PROTOCOL_T0  0x00000001
#define SCARD_PROTOCOL_T1  0x00000002
#define SCARD_PROTOCOL_RAW  0x00010000
#define SCARD_PROTOCOL_Tx  (SCARD_PROTOCOL_T0|SCARD_PROTOCOL_T1)
#define SCARD_PROTOCOL_DEFAULT  0x80000000
#define SCARD_PROTOCOL_OPTIMAL  0x00000000

#define SCARD_POWER_DOWN  0
#define SCARD_COLD_RESET  1
#define SCARD_WARM_RESET  2

/*
#define SCARD_CTL_CODE(code)  CTL_CODE(FILE_DEVICE_SMARTCARD,(code),METHOD_BUFFERED,FILE_ANY_ACCESS)
*/

#define IOCTL_SMARTCARD_POWER  (FILE_DEVICE_SMARTCARD<<16)|(1<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_GET_ATTRIBUTE  (FILE_DEVICE_SMARTCARD<<16)|(2<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_SET_ATTRIBUTE  (FILE_DEVICE_SMARTCARD<<16)|(3<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_CONFISCATE  (FILE_DEVICE_SMARTCARD<<16)|(4<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_TRANSMIT  (FILE_DEVICE_SMARTCARD<<16)|(5<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_EJECT  (FILE_DEVICE_SMARTCARD<<16)|(6<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_SWALLOW  (FILE_DEVICE_SMARTCARD<<16)|(7<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_IS_PRESENT  (FILE_DEVICE_SMARTCARD<<16)|(10<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_IS_ABSENT  (FILE_DEVICE_SMARTCARD<<16)|(11<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_SET_PROTOCOL  (FILE_DEVICE_SMARTCARD<<16)|(12<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_GET_STATE  (FILE_DEVICE_SMARTCARD<<16)|(14<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_GET_LAST_ERROR  (FILE_DEVICE_SMARTCARD<<16)|(15<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SMARTCARD_GET_PERF_CNTR  (FILE_DEVICE_SMARTCARD<<16)|(16<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)


#define MAXIMUM_ATTR_STRING_LENGTH  32
#define MAXIMUM_SMARTCARD_READERS  10

;#define SCARD_ATTR_VALUE(Class,Tag)  ((((ULONG)(Class))<<16)|((ULONG)(Tag)))

#define SCARD_CLASS_VENDOR_INFO  1
#define SCARD_CLASS_COMMUNICATIONS  2
#define SCARD_CLASS_PROTOCOL  3
#define SCARD_CLASS_POWER_MGMT  4
#define SCARD_CLASS_SECURITY  5
#define SCARD_CLASS_MECHANICAL  6
#define SCARD_CLASS_VENDOR_DEFINED  7
#define SCARD_CLASS_IFD_PROTOCOL  8
#define SCARD_CLASS_ICC_STATE  9
#define SCARD_CLASS_PERF  0x7FFE
#define SCARD_CLASS_SYSTEM  0x7FFF

#define SCARD_ATTR_VENDOR_NAME  (SCARD_CLASS_VENDOR_INFO<<16)|(0x0100)
#define SCARD_ATTR_VENDOR_IFD_TYPE  (SCARD_CLASS_VENDOR_INFO<<16)|(0x0101)
#define SCARD_ATTR_VENDOR_IFD_VERSION  (SCARD_CLASS_VENDOR_INFO<<16)|(0x0102)
#define SCARD_ATTR_VENDOR_IFD_SERIAL_NO  (SCARD_CLASS_VENDOR_INFO<<16)|(0x0103)
#define SCARD_ATTR_CHANNEL_ID  (SCARD_CLASS_COMMUNICATIONS<<16)|(0x0110)
#define SCARD_ATTR_PROTOCOL_TYPES  (SCARD_CLASS_PROTOCOL<<16)|(0x0120)
#define SCARD_ATTR_DEFAULT_CLK  (SCARD_CLASS_PROTOCOL<<16)|(0x0121)
#define SCARD_ATTR_MAX_CLK  (SCARD_CLASS_PROTOCOL<<16)|(0x0122)
#define SCARD_ATTR_DEFAULT_DATA_RATE  (SCARD_CLASS_PROTOCOL<<16)|(0x0123)
#define SCARD_ATTR_MAX_DATA_RATE  (SCARD_CLASS_PROTOCOL<<16)|(0x0124)
#define SCARD_ATTR_MAX_IFSD  (SCARD_CLASS_PROTOCOL<<16)|(0x0125)
#define SCARD_ATTR_POWER_MGMT_SUPPORT  (SCARD_CLASS_POWER_MGMT<<16)|(0x0131)
#define SCARD_ATTR_USER_TO_CARD_AUTH_DEVICE  (SCARD_CLASS_SECURITY<<16)|(0x0140)
#define SCARD_ATTR_USER_AUTH_INPUT_DEVICE  (SCARD_CLASS_SECURITY<<16)|(0x0142)
#define SCARD_ATTR_CHARACTERISTICS  (SCARD_CLASS_MECHANICAL<<16)|(0x0150)

#define SCARD_ATTR_CURRENT_PROTOCOL_TYPE  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x0201)
#define SCARD_ATTR_CURRENT_CLK  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x0202)
#define SCARD_ATTR_CURRENT_F  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x0203)
#define SCARD_ATTR_CURRENT_D  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x0204)
#define SCARD_ATTR_CURRENT_N  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x0205)
#define SCARD_ATTR_CURRENT_W  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x0206)
#define SCARD_ATTR_CURRENT_IFSC  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x0207)
#define SCARD_ATTR_CURRENT_IFSD  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x0208)
#define SCARD_ATTR_CURRENT_BWT  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x0209)
#define SCARD_ATTR_CURRENT_CWT  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x020a)
#define SCARD_ATTR_CURRENT_EBC_ENCODING  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x020b)
#define SCARD_ATTR_EXTENDED_BWT  (SCARD_CLASS_IFD_PROTOCOL<<16)|(0x020c)

#define SCARD_ATTR_ICC_PRESENCE  (SCARD_CLASS_ICC_STATE<<16)|(0x0300)
#define SCARD_ATTR_ICC_INTERFACE_STATUS  (SCARD_CLASS_ICC_STATE<<16)|(0x0301)
#define SCARD_ATTR_CURRENT_IO_STATE  (SCARD_CLASS_ICC_STATE<<16)|(0x0302)
#define SCARD_ATTR_ATR_STRING  (SCARD_CLASS_ICC_STATE<<16)|(0x0303)
#define SCARD_ATTR_ICC_TYPE_PER_ATR  (SCARD_CLASS_ICC_STATE<<16)|(0x0304)

#define SCARD_ATTR_ESC_RESET  (SCARD_CLASS_VENDOR_DEFINED<<16)|(0xA000)
#define SCARD_ATTR_ESC_CANCEL  (SCARD_CLASS_VENDOR_DEFINED<<16)|(0xA003)
#define SCARD_ATTR_ESC_AUTHREQUEST  (SCARD_CLASS_VENDOR_DEFINED<<16)|(0xA005)
#define SCARD_ATTR_MAXINPUT  (SCARD_CLASS_VENDOR_DEFINED<<16)|(0xA007)

#define SCARD_ATTR_DEVICE_UNIT  (SCARD_CLASS_SYSTEM<<16)|(0x0001)
#define SCARD_ATTR_DEVICE_IN_USE  (SCARD_CLASS_SYSTEM<<16)|(0x0002)
#define SCARD_ATTR_DEVICE_FRIENDLY_NAME_A  (SCARD_CLASS_SYSTEM<<16)|(0x0003)
#define SCARD_ATTR_DEVICE_SYSTEM_NAME_A  (SCARD_CLASS_SYSTEM<<16)|(0x0004)
#define SCARD_ATTR_DEVICE_FRIENDLY_NAME_W  (SCARD_CLASS_SYSTEM<<16)|(0x0005)
#define SCARD_ATTR_DEVICE_SYSTEM_NAME_W  (SCARD_CLASS_SYSTEM<<16)|(0x0006)
#define SCARD_ATTR_SUPRESS_T1_IFS_REQUEST  (SCARD_CLASS_SYSTEM<<16)|(0x0007)

#define SCARD_PERF_NUM_TRANSMISSIONS  (SCARD_CLASS_PERF<<16)|(0x0001)
#define SCARD_PERF_BYTES_TRANSMITTED  (SCARD_CLASS_PERF<<16)|(0x0002)
#define SCARD_PERF_TRANSMISSION_TIME  (SCARD_CLASS_PERF<<16)|(0x0003)

#define SCARD_T0_HEADER_LENGTH  7
#define SCARD_T0_CMD_LENGTH  5

#define SCARD_T1_PROLOGUE_LENGTH  3
#define SCARD_T1_EPILOGUE_LENGTH  2
#define SCARD_T1_MAX_IFS  254

#define SCARD_UNKNOWN  0
#define SCARD_ABSENT  1
#define SCARD_PRESENT  2
#define SCARD_SWALLOWED  3
#define SCARD_POWERED  4
#define SCARD_NEGOTIABLE  5
#define SCARD_SPECIFIC  6

#define SCARD_READER_SWALLOWS  0x00000001
#define SCARD_READER_EJECTS  0x00000002
#define SCARD_READER_CONFISCATES  0x00000004

#define SCARD_READER_TYPE_SERIAL  0x01
#define SCARD_READER_TYPE_PARALELL  0x02
#define SCARD_READER_TYPE_KEYBOARD  0x04
#define SCARD_READER_TYPE_SCSI  0x08
#define SCARD_READER_TYPE_IDE  0x10
#define SCARD_READER_TYPE_USB  0x20
#define SCARD_READER_TYPE_PCMCIA  0x40
#define SCARD_READER_TYPE_VENDOR  0xF0

SCARD_IO_REQUEST STRUCT
	dwProtocol DD
	cbPciLength DD
ENDS

SCARD_T0_COMMAND STRUCT
	bCla DB
	bIns DB
	bP1 DB
	bP2 DB
	bP3 DB
ENDS

SCARD_T0_REQUEST STRUCT
	ioRequest SCARD_IO_REQUEST <>
	bSw1 DB
	bSw2 DB
    UNION
		CmdBytes SCARD_T0_COMMAND <>
		rgbHeader DB 5 DUP (?)
    ENDUNION
ENDS

SCARD_T1_REQUEST STRUCT
	ioRequest SCARD_IO_REQUEST <>
ENDS

#IFDEF UNICODE
	#define SCARD_ATTR_DEVICE_FRIENDLY_NAME SCARD_ATTR_DEVICE_FRIENDLY_NAME_W
	#define SCARD_ATTR_DEVICE_SYSTEM_NAME SCARD_ATTR_DEVICE_SYSTEM_NAME_W
#else
	#define SCARD_ATTR_DEVICE_FRIENDLY_NAME SCARD_ATTR_DEVICE_FRIENDLY_NAME_A
	#define SCARD_ATTR_DEVICE_SYSTEM_NAME SCARD_ATTR_DEVICE_SYSTEM_NAME_A
#endif

#endif /* _WINSMCRD_H */
