///////////////////////////////////////////////////////////////////////////////
//
// File: WpcEvent.h
//
// Comments:
// This file defines the Windows Parental Controls interfaces and events
//
// Copyright (C) 2005 Microsoft Corporation All Rights Reserved.
//
///////////////////////////////////////////////////////////////////////////////

#IFNDEF WPCEVENT_H
#DEFINE WPCEVENT_H

#IFNDEF EVNTPROV_H
	#include "evntprov.h"
#ENDIF

#IFNDEF EVENT_DESCRIPTOR
	EVENT_DESCRIPTOR STRUCT
		Id SHORT
		Version CHAR
		Channel CHAR
		Level CHAR
		Opcode CHAR
		Task SHORT
		Keyword LONGLONG
	ENDS
#ENDIF

//
// Reasons
//

WPCFLAG_ISBLOCKED_NOTBLOCKED = 0x00000000
WPCFLAG_ISBLOCKED_IMBLOCKED = 0x00000001
WPCFLAG_ISBLOCKED_EMAILBLOCKED = 0x00000002
WPCFLAG_ISBLOCKED_MEDIAPLAYBACKBLOCKED = 0x00000004
WPCFLAG_ISBLOCKED_WEBBLOCKED = 0x00000008
WPCFLAG_ISBLOCKED_GAMESBLOCKED = 0x00000010
WPCFLAG_ISBLOCKED_CONTACTBLOCKED = 0x00000020 
WPCFLAG_ISBLOCKED_FEATUREBLOCKED = 0x00000040 
WPCFLAG_ISBLOCKED_DOWNLOADBLOCKED = 0x00000080 
WPCFLAG_ISBLOCKED_RATINGBLOCKED = 0x00000100 
WPCFLAG_ISBLOCKED_DESCRIPTORBLOCKED = 0x00000200 
WPCFLAG_ISBLOCKED_EXPLICITBLOCK = 0x00000400
WPCFLAG_ISBLOCKED_BADPASS = 0x00000800
WPCFLAG_ISBLOCKED_MAXHOURS = 0x00001000
WPCFLAG_ISBLOCKED_SPECHOURS = 0x00002000

WPCFLAG_ISBLOCKED_SETTINGSCHANGEBLOCKED = 0x00004000

WPCFLAG_ISBLOCKED_ATTACHMENTBLOCKED = 0x00008000
WPCFLAG_ISBLOCKED_SENDERBLOCKED = 0x00010000
WPCFLAG_ISBLOCKED_RECEIVERBLOCKED = 0x00020000
WPCFLAG_ISBLOCKED_NOTEXPLICITLYALLOWED = 0x00040000
WPCFLAG_ISBLOCKED_NOTINLIST = 0x00080000
WPCFLAG_ISBLOCKED_CATEGORYBLOCKED = 0x00100000
WPCFLAG_ISBLOCKED_CATEGORYNOTINLIST = 0x00200000
WPCFLAG_ISBLOCKED_NOTKIDS = 0x00400000
WPCFLAG_ISBLOCKED_UNRATED = 0x00800000
WPCFLAG_ISBLOCKED_NOACCESS = 0x01000000
WPCFLAG_ISBLOCKED_INTERNALERROR = 0xFFFFFFFF

WPCFLAG_LOGOFF_TYPE_LOGOUT = 0x00000000
WPCFLAG_LOGOFF_TYPE_RESTART = 0x00000001
WPCFLAG_LOGOFF_TYPE_SHUTDOWN = 0x00000002
WPCFLAG_LOGOFF_TYPE_FUS = 0x00000004
WPCFLAG_LOGOFF_TYPE_FORCEDFUS = 0x00000008

WPCFLAG_IM_LEAVE_NORMAL = 0x00000000
WPCFLAG_IM_LEAVE_FORCED = 0x00000001
WPCFLAG_IM_LEAVE_CONVERSATION_END = 0x00000002


//Event Data Lengths
//System

#define ARRAY_SEP_CHAR 0x9

// WPC_ARGS_SETTINGSCHANGEEVENT

	WPC_ARGS_SETTINGSCHANGEEVENT_CLASS = 0
	WPC_ARGS_SETTINGSCHANGEEVENT_SETTING = 1
	WPC_ARGS_SETTINGSCHANGEEVENT_OWNER = 2
	WPC_ARGS_SETTINGSCHANGEEVENT_OLDVAL = 3
	WPC_ARGS_SETTINGSCHANGEEVENT_NEWVAL = 4
	WPC_ARGS_SETTINGSCHANGEEVENT_REASON = 5
	WPC_ARGS_SETTINGSCHANGEEVENT_OPTIONAL = 6
	WPC_ARGS_SETTINGSCHANGEEVENT_CARGS = 7

// WPC_ARGS_SAFERAPPBLOCKED

	WPC_ARGS_SAFERAPPBLOCKED_TIMESTAMP = 0
	WPC_ARGS_SAFERAPPBLOCKED_USERID = 1
	WPC_ARGS_SAFERAPPBLOCKED_PATH = 2
	WPC_ARGS_SAFERAPPBLOCKED_RULEID = 3
	WPC_ARGS_SAFERAPPBLOCKED_CARGS = 4

//Email
// WPC_ARGS_EMAILRECEIEVEDEVENT

	WPC_ARGS_EMAILRECEIEVEDEVENT_SENDER = 0
	WPC_ARGS_EMAILRECEIEVEDEVENT_APPNAME = 1
	WPC_ARGS_EMAILRECEIEVEDEVENT_APPVERSION = 2
	WPC_ARGS_EMAILRECEIEVEDEVENT_SUBJECT = 3
	WPC_ARGS_EMAILRECEIEVEDEVENT_REASON = 4
	WPC_ARGS_EMAILRECEIEVEDEVENT_RECIPCOUNT = 5
	WPC_ARGS_EMAILRECEIEVEDEVENT_RECIPIENT = 6
	WPC_ARGS_EMAILRECEIEVEDEVENT_ATTACHCOUNT = 7
	WPC_ARGS_EMAILRECEIEVEDEVENT_ATTACHMENTNAME = 8
	WPC_ARGS_EMAILRECEIEVEDEVENT_RECEIVEDTIME = 9
	WPC_ARGS_EMAILRECEIEVEDEVENT_EMAILACCOUNT = 10
	WPC_ARGS_EMAILRECEIEVEDEVENT_CARGS = 11

// WPC_ARGS_EMAILSENTEVENT

	WPC_ARGS_EMAILSENTEVENT_SENDER = 0
	WPC_ARGS_EMAILSENTEVENT_APPNAME = 1
	WPC_ARGS_EMAILSENTEVENT_APPVERSION = 2
	WPC_ARGS_EMAILSENTEVENT_SUBJECT = 3
	WPC_ARGS_EMAILSENTEVENT_REASON = 4
	WPC_ARGS_EMAILSENTEVENT_RECIPCOUNT = 5
	WPC_ARGS_EMAILSENTEVENT_RECIPIENT = 6
	WPC_ARGS_EMAILSENTEVENT_ATTACHCOUNT = 7
	WPC_ARGS_EMAILSENTEVENT_ATTACHMENTNAME = 8
	WPC_ARGS_EMAILSENTEVENT_EMAILACCOUNT = 9
	WPC_ARGS_EMAILSENTEVENT_CARGS = 10

// WPC_ARGS_EMAILCONTACTEVENT

	WPC_ARGS_EMAILCONTACTEVENT_APPNAME = 0
	WPC_ARGS_EMAILCONTACTEVENT_APPVERSION = 1
	WPC_ARGS_EMAILCONTACTEVENT_OLDNAME = 2
	WPC_ARGS_EMAILCONTACTEVENT_OLDID = 3
	WPC_ARGS_EMAILCONTACTEVENT_NEWNAME = 4
	WPC_ARGS_EMAILCONTACTEVENT_NEWID = 5
	WPC_ARGS_EMAILCONTACTEVENT_REASON = 6
	WPC_ARGS_EMAILCONTACTEVENT_EMAILACCOUNT = 7
	WPC_ARGS_EMAILCONTACTEVENT_CARGS = 8

//Media
// WPC_MEDIA_TYPE

	WPC_MEDIA_TYPE_OTHER = 0
	WPC_MEDIA_TYPE_DVD = 1
	WPC_MEDIA_TYPE_RECORDED_TV = 2
	WPC_MEDIA_TYPE_AUDIO_FILE = 3
	WPC_MEDIA_TYPE_CD_AUDIO = 4
	WPC_MEDIA_TYPE_VIDEO_FILE = 5
	WPC_MEDIA_TYPE_PICTURE_FILE = 6
	WPC_MEDIA_TYPE_MAX = 7

// WPC_MEDIA_EXPLICIT_TYPE

	WPC_MEDIA_EXPLICIT_FALSE = 0
	WPC_MEDIA_EXPLICIT_TRUE = 1
	WPC_MEDIA_EXPLICIT_UNKNOWN = 2

// WPC_ARGS_MEDIAPLAYBACKEVENT

	WPC_ARGS_MEDIAPLABACKEVENT_APPNAME = 0
	WPC_ARGS_MEDIAPLAYBACKEVENT_APPVERSION = 1
	WPC_ARGS_MEDIAPLAYBACKEVENT_MEDIATYPE = 2
	WPC_ARGS_MEDIAPLAYBACKEVENT_PATH = 3
	WPC_ARGS_MEDIAPLAYBACKEVENT_TITLE = 4
	WPC_ARGS_MEDIAPLAYBACKEVENT_PML = 5
	WPC_ARGS_MEDIAPLAYBACKEVENT_ALBUM = 6
	WPC_ARGS_MEDIAPLAYBACKEVENT_EXPLICIT = 7
	WPC_ARGS_MEDIAPLAYBACKEVENT_REASON = 8
	WPC_ARGS_MEDIAPLAYBACKEVENT_CARGS = 9

// WPC_ARGS_MEDIADOWNLOADEVENT

	WPC_ARGS_MEDIADOWNLOADEVENT_APPNAME = 0
	WPC_ARGS_MEDIADOWNLOADEVENT_APPVERSION = 1
	WPC_ARGS_MEDIADOWNLOADEVENT_MEDIATYPE = 2
	WPC_ARGS_MEDIADOWNLOADEVENT_PATH = 3
	WPC_ARGS_MEDIADOWNLOADEVENT_TITLE = 4
	WPC_ARGS_MEDIADOWNLOADEVENT_PML = 5
	WPC_ARGS_MEDIADOWNLOADEVENT_ALBUM = 6
	WPC_ARGS_MEDIADOWNLOADEVENT_EXPLICIT = 7
	WPC_ARGS_MEDIADOWNLOADEVENT_REASON = 8
	WPC_ARGS_MEDIADOWNLOADEVENT_CARGS = 9

//IM
// WPC_ARGS_CONVERSATIONINITEVENT

	WPC_ARGS_CONVERSATIONINITEVENT_APPNAME = 0
	WPC_ARGS_CONVERSATIONINITEVENT_APPVERSION = 1
	WPC_ARGS_CONVERSATIONINITEVENT_ACCOUNTNAME = 2
	WPC_ARGS_CONVERSATIONINITEVENT_CONVID = 3
	WPC_ARGS_CONVERSATIONINITEVENT_REQUESTINGIP = 4
	WPC_ARGS_CONVERSATIONINITEVENT_SENDER = 5
	WPC_ARGS_CONVERSATIONINITEVENT_REASON = 6
	WPC_ARGS_CONVERSATIONINITEVENT_RECIPCOUNT = 7
	WPC_ARGS_CONVERSATIONINITEVENT_RECIPIENT = 8
	WPC_ARGS_CONVERSATIONINITEVENT_CARGS = 9

// WPC_ARGS_CONVERSATIONJOINEVENT

	WPC_ARGS_CONVERSATIONJOINEVENT_APPNAME = 0
	WPC_ARGS_CONVERSATIONJOINEVENT_APPVERSION = 1
	WPC_ARGS_CONVERSATIONJOINEVENT_ACCOUNTNAME = 2
	WPC_ARGS_CONVERSATIONJOINEVENT_CONVID = 3
	WPC_ARGS_CONVERSATIONJOINEVENT_JOININGIP = 4
	WPC_ARGS_CONVERSATIONJOINEVENT_JOININGUSER = 5
	WPC_ARGS_CONVERSATIONJOINEVENT_REASON = 6
	WPC_ARGS_CONVERSATIONJOINEVENT_MEMBERCOUNT = 7
	WPC_ARGS_CONVERSATIONJOINEVENT_MEMBER = 8
	WPC_ARGS_CONVERSATIONJOINEVENT_SENDER = 9
	WPC_ARGS_CONVERSATIONJOINEVENT_CARGS = 10

// WPC_ARGS_CONVERSATIONLEAVEEVENT

	WPC_ARGS_CONVERSATIONLEAVEEVENT_APPNAME = 0
	WPC_ARGS_CONVERSATIONLEAVEEVENT_APPVERSION = 1
	WPC_ARGS_CONVERSATIONLEAVEEVENT_ACCOUNTNAME = 2
	WPC_ARGS_CONVERSATIONLEAVEEVENT_CONVID = 3
	WPC_ARGS_CONVERSATIONLEAVEEVENT_LEAVINGIP = 4
	WPC_ARGS_CONVERSATIONLEAVEEVENT_LEAVINGUSER = 5
	WPC_ARGS_CONVERSATIONLEAVEEVENT_REASON = 6
	WPC_ARGS_CONVERSATIONLEAVEEVENT_MEMBERCOUNT = 7
	WPC_ARGS_CONVERSATIONLEAVEEVENT_MEMBER = 8
	WPC_ARGS_CONVERSATIONLEAVEEVENT_FLAGS = 9
	WPC_ARGS_CONVERSATIONLEAVEEVENT_CARGS = 10

// WPCFLAG_IM_FEATURE

	WPCFLAG_IM_FEATURE_NONE = 0x00
	WPCFLAG_IM_FEATURE_VIDEO = 0x01
	WPCFLAG_IM_FEATURE_AUDIO = 0x02
	WPCFLAG_IM_FEATURE_GAME = 0x04
	WPCFLAG_IM_FEATURE_SMS = 0x08
	WPCFLAG_IM_FEATURE_FILESWAP = 0x10
	WPCFLAG_IM_FEATURE_URLSWAP = 0x20
	WPCFLAG_IM_FEATURE_SENDING = 0x80000000 // Top bit means sending or receiving.
	WPCFLAG_IM_FEATURE_ALL = 0xFFFFFFFF

// WPC_ARGS_IMFEATUREEVENT

	WPC_ARGS_IMFEATUREEVENT_APPNAME = 0
	WPC_ARGS_IMFEATUREEVENT_APPVERSION = 1
	WPC_ARGS_IMFEATUREEVENT_ACCOUNTNAME = 2
	WPC_ARGS_IMFEATUREEVENT_CONVID = 3
	WPC_ARGS_IMFEATUREEVENT_MEDIATYPE = 4
	WPC_ARGS_IMFEATUREEVENT_REASON = 5
	WPC_ARGS_IMFEATUREEVENT_RECIPCOUNT = 6
	WPC_ARGS_IMFEATUREEVENT_RECIPIENT = 7
	WPC_ARGS_IMFEATUREEVENT_SENDER = 8
	WPC_ARGS_IMFEATUREEVENT_SENDERIP = 9
	WPC_ARGS_IMFEATUREEVENT_DATA = 10
	WPC_ARGS_IMFEATUREEVENT_CARGS = 11

// WPC_ARGS_IMCONTACTEVENT

	WPC_ARGS_IMCONTACTEVENT_APPNAME = 0
	WPC_ARGS_IMCONTACTEVENT_APPVERSION = 1
	WPC_ARGS_IMCONTACTEVENT_ACCOUNTNAME = 2
	WPC_ARGS_IMCONTACTEVENT_OLDNAME = 3
	WPC_ARGS_IMCONTACTEVENT_OLDID = 4
	WPC_ARGS_IMCONTACTEVENT_NEWNAME = 5
	WPC_ARGS_IMCONTACTEVENT_NEWID = 6
	WPC_ARGS_IMCONTACTEVENT_REASON = 7
	WPC_ARGS_IMCONTACTEVENT_CARGS = 8

//Games
// WPC_ARGS_GAMESTARTEVENT

	WPC_ARGS_GAMESTARTEVENT_APPID = 0
	WPC_ARGS_GAMESTARTEVENT_INSTANCEID = 1
	WPC_ARGS_GAMESTARTEVENT_APPVERSION = 2
	WPC_ARGS_GAMESTARTEVENT_PATH = 3
	WPC_ARGS_GAMESTARTEVENT_RATING = 4
	WPC_ARGS_GAMESTARTEVENT_RATINGSYSTEM = 5
	WPC_ARGS_GAMESTARTEVENT_REASON = 6
	WPC_ARGS_GAMESTARTEVENT_DESCCOUNT = 7
	WPC_ARGS_GAMESTARTEVENT_DESCRIPTOR = 8
	WPC_ARGS_GAMESTARTEVENT_PID = 9
	WPC_ARGS_GAMESTARTEVENT_CARGS = 10

//Web
// WPC_ARGS_FILEDOWNLOADEVENT

	WPC_ARGS_FILEDOWNLOADEVENT_URL = 0
	WPC_ARGS_FILEDOWNLOADEVENT_APPNAME = 1
	WPC_ARGS_FILEDOWNLOADEVENT_VERSION = 2
	WPC_ARGS_FILEDOWNLOADEVENT_BLOCKED = 3
	WPC_ARGS_FILEDOWNLOADEVENT_PATH = 4
	WPC_ARGS_FILEDOWNLOADEVENT_CARGS = 5

// WPC_ARGS_URLVISITEVENT

	WPC_ARGS_URLVISITEVENT_URL = 0
	WPC_ARGS_URLVISITEVENT_APPNAME = 1
	WPC_ARGS_URLVISITEVENT_VERSION = 2
	WPC_ARGS_URLVISITEVENT_REASON = 3
	WPC_ARGS_URLVISITEVENT_RATINGSYSTEMID = 4
	WPC_ARGS_URLVISITEVENT_CATCOUNT = 5
	WPC_ARGS_URLVISITEVENT_CATEGORY = 6
	WPC_ARGS_URLVISITEVENT_CARGS = 7

// WPC_ARGS_CUSTOMEVENT

	WPC_ARGS_CUSTOMEVENT_PUBLISHER = 0
	WPC_ARGS_CUSTOMEVENT_APPNAME = 1
	WPC_ARGS_CUSTOMEVENT_APPVERSION = 2
	WPC_ARGS_CUSTOMEVENT_EVENT = 3
	WPC_ARGS_CUSTOMEVENT_VALUE1 = 4
	WPC_ARGS_CUSTOMEVENT_VALUE2 = 5
	WPC_ARGS_CUSTOMEVENT_VALUE3 = 6
	WPC_ARGS_CUSTOMEVENT_BLOCKED = 7
	WPC_ARGS_CUSTOMEVENT_REASON = 8
	WPC_ARGS_CUSTOMEVENT_CARGS = 9

// WPC_ARGS_WEBOVERRIDEEVENT

	WPC_ARGS_WEBOVERRIDEEVENT_USERID = 0
	WPC_ARGS_WEBOVERRIDEEVENT_URL = 1
	WPC_ARGS_WEBOVERRIDEEVENT_REASON = 2
	WPC_ARGS_WEBOVERRIDEEVENT_CARGS = 3

// WPC_ARGS_APPOVERRIDEEVENT

	WPC_ARGS_APPOVERRIDEEVENT_USERID = 0
	WPC_ARGS_APPOVERRIDEEVENT_PATH = 1
	WPC_ARGS_APPOVERRIDEEVENT_REASON = 2
	WPC_ARGS_APPOVERRIDEEVENT_CARGS = 3


// WPC_SETTINGS

	WPC_SETTINGS_WPC_EXTENSION_PATH = 0
	WPC_SETTINGS_WPC_EXTENSION_SILO = 1
	WPC_SETTINGS_WPC_EXTENSION_IMAGE_PATH = 2
	WPC_SETTINGS_WPC_EXTENSION_DISABLEDIMAGE_PATH = 3
	WPC_SETTINGS_WPC_EXTENSION_NAME = 4
	WPC_SETTINGS_WPC_EXTENSION_SUB_TITLE = 5
	WPC_SETTINGS_SYSTEM_CURRENT_RATING_SYSTEM = 6
	WPC_SETTINGS_SYSTEM_LAST_LOG_VIEW = 7
	WPC_SETTINGS_SYSTEM_LOG_VIEW_REMINDER_INTERVAL = 8
	WPC_SETTINGS_SYSTEM_HTTP_EXEMPTION_LIST = 9
	WPC_SETTINGS_SYSTEM_URL_EXEMPTION_LIST = 10
	WPC_SETTINGS_SYSTEM_FILTER_ID = 11
	WPC_SETTINGS_SYSTEM_FILTER_NAME = 12
	WPC_SETTINGS_SYSTEM_LOCALE = 13
	WPC_SETTINGS_ALLOW_BLOCK = 14
	WPC_SETTINGS_GAME_BLOCKED = 15
	WPC_SETTINGS_GAME_ALLOW_UNRATED = 16
	WPC_SETTINGS_GAME_MAX_ALLOWED = 17
	WPC_SETTINGS_GAME_DENIED_DESCRIPTORS = 18
	WPC_SETTINGS_USER_WPC_ENABLED = 19
	WPC_SETTINGS_USER_LOGGING_REQUIRED = 20
	WPC_SETTINGS_USER_HOURLY_RESTRICTIONS = 21
	WPC_SETTINGS_USER_OVERRRIDE_REQUESTS = 22
	WPC_SETTINGS_USER_LOGON_HOURS = 23
	WPC_SETTINGS_USER_APP_RESTRICTIONS = 24
	WPC_SETTINGS_WEB_FILTER_ON = 25
	WPC_SETTINGS_WEB_DOWNLOAD_BLOCKED = 26
	WPC_SETTINGS_WEB_FILTER_LEVEL = 27
	WPC_SETTINGS_WEB_BLOCKED_CATEGORY_LIST = 28
	WPC_SETTINGS_WEB_BLOCK_UNRATED = 29
	WPC_SETTINGS_WPC_ENABLED = 30
	WPC_SETTINGS_WPC_LOGGING_REQUIRED = 31
	WPC_SETTINGS_RATING_SYSTEM_PATH = 32
	WPC_SETTINGS_WPC_PROVIDER_CURRENT = 33
	WPC_SETTING_COUNT = 34

#DEFINE GUID_WPCPROV <0x01090065, 0xb467, 0x4503, <0x9b, 0x28, 0x53, 0x37, 0x66, 0x76, 0x10, 0x87>>

//
// Channel
//
#define WPCCHANNEL 0x10

//
// Opcodes
//
#define WPC_SETTINGS_LOCATE 0x14
#define WPC_SETTINGS_MODIFY 0x15
#define WPC_APP_LAUNCH 0x16
#define WPC_SYSTEM 0x17
#define WPC_WEB 0x18

//
// Tasks
//
#define WPCPROV_TASK_SettingChange 0x1
#define WPCPROV_TASK_GameStart 0x2
#define WPCPROV_TASK_UrlVisit 0x3
#define WPCPROV_TASK_EmailReceived 0x4
#define WPCPROV_TASK_EmailSent 0x5
#define WPCPROV_TASK_MediaPlayback 0x6
#define WPCPROV_TASK_IMInvitation 0x7
#define WPCPROV_TASK_IMJoin 0x8
#define WPCPROV_TASK_IMLeave 0x9
#define WPCPROV_TASK_FileDownload 0xa
#define WPCPROV_TASK_IMFeature 0xb
#define WPCPROV_TASK_Custom 0xd
#define WPCPROV_TASK_EmailContact 0xe
#define WPCPROV_TASK_IMContact 0xf
#define WPCPROV_TASK_AppBlocked 0x10
#define WPCPROV_TASK_AppOverride 0x11
#define WPCPROV_TASK_WebOverride 0x12

//
// Keyword
//
#define WPCPROV_KEYWORD_WPC 0x10
#define WPCPROV_KEYWORD_ThirdParty 0x20

//
// Event Descriptors
//
#DEFINE WPCEVENT_SYS_SETTINGCHANGE <0x1, 0x0, 0x10, 0x4, 0x15, 0x1, 0x8000000000000010>
#define WPCEVENT_SYS_SETTINGCHANGE_value 0x1

#DEFINE WPCEVENT_GAME_START <0x2, 0x0, 0x10, 0x4, 0x16, 0x2, 0x8000000000000030>
#define WPCEVENT_GAME_START_value 0x2

#DEFINE WPCEVENT_WEB_URLVISIT <0x3, 0x0, 0x10, 0x4, 0x18, 0x3, 0x8000000000000010>
#define WPCEVENT_WEB_URLVISIT_value 0x3

#DEFINE WPCEVENT_EMAIL_RECEIVED <0x4, 0x0, 0x10, 0x4, 0x16, 0x4, 0x8000000000000030>
#define WPCEVENT_EMAIL_RECEIVED_value 0x4

#DEFINE WPCEVENT_EMAIL_SENT <0x5, 0x0, 0x10, 0x4, 0x16, 0x5, 0x8000000000000030>
#define WPCEVENT_EMAIL_SENT_value 0x5

#DEFINE WPCEVENT_MEDIA_PLAYBACK <0x6, 0x0, 0x10, 0x4, 0x16, 0x6, 0x8000000000000030>
#define WPCEVENT_MEDIA_PLAYBACK_value 0x6

#DEFINE WPCEVENT_IM_INVITATION <0x7, 0x0, 0x10, 0x4, 0x16, 0x7, 0x8000000000000030>
#define WPCEVENT_IM_INVITATION_value 0x7

#DEFINE WPCEVENT_IM_JOIN <0x8, 0x0, 0x10, 0x4, 0x16, 0x8, 0x8000000000000030>
#define WPCEVENT_IM_JOIN_value 0x8

#DEFINE WPCEVENT_IM_LEAVE <0x9, 0x0, 0x10, 0x4, 0x16, 0x9, 0x8000000000000030>
#define WPCEVENT_IM_LEAVE_value 0x9

#DEFINE WPCEVENT_WEB_FILEDOWNLOAD <0xa, 0x0, 0x10, 0x4, 0x18, 0xa, 0x8000000000000030>
#define WPCEVENT_WEB_FILEDOWNLOAD_value 0xa

#DEFINE WPCEVENT_IM_FEATURE <0xb, 0x0, 0x10, 0x4, 0x16, 0xb, 0x8000000000000030>
#define WPCEVENT_IM_FEATURE_value 0xb

#DEFINE WPCEVENT_CUSTOM <0xd, 0x0, 0x10, 0x4, 0x17, 0xd, 0x8000000000000030>
#define WPCEVENT_CUSTOM_value 0xd

#DEFINE WPCEVENT_EMAIL_CONTACT <0xe, 0x0, 0x10, 0x4, 0x16, 0xe, 0x8000000000000030>
#define WPCEVENT_EMAIL_CONTACT_value 0xe

#DEFINE WPCEVENT_IM_CONTACT <0xf, 0x0, 0x10, 0x4, 0x16, 0xf, 0x8000000000000030>
#define WPCEVENT_IM_CONTACT_value 0xf

#DEFINE WPCEVENT_SYSTEM_APPBLOCKED <0x10, 0x0, 0x10, 0x4, 0x16, 0x10, 0x8000000000000010>
#define WPCEVENT_SYSTEM_APPBLOCKED_value 0x10

#DEFINE WPCEVENT_APPOVERRIDE <0x11, 0x0, 0x10, 0x4, 0x16, 0x11, 0x8000000000000010>
#define WPCEVENT_APPOVERRIDE_value 0x11

#DEFINE WPCEVENT_WEBOVERRIDE <0x12, 0x0, 0x10, 0x4, 0x16, 0x12, 0x8000000000000010>
#define WPCEVENT_WEBOVERRIDE_value 0x12

#define MSG_Keyword_WPC 0x10000005
#define MSG_Keyword_ThirdParty 0x10000006
#define MSG_Opcode_Locate 0x30000014
#define MSG_Opcode_Modify 0x30000015
#define MSG_Opcode_Launch 0x30000016
#define MSG_Opcode_System 0x30000017
#define MSG_Opcode_Web 0x30000018
#define MSG_Task_SettingChange 0x70000001
#define MSG_Task_GameStart 0x70000002
#define MSG_Task_UrlVisit 0x70000003
#define MSG_Task_EmailReceived 0x70000004
#define MSG_Task_EmailSent 0x70000005
#define MSG_Task_MediaPlayback 0x70000006
#define MSG_Task_IMInvitation 0x70000007
#define MSG_Task_IMJoin 0x70000008
#define MSG_Task_IMLeave 0x70000009
#define MSG_Task_FileDownload 0x7000000A
#define MSG_Task_IMFeature 0x7000000B
#define MSG_Task_Custom 0x7000000D
#define MSG_Task_EmailContact 0x7000000E
#define MSG_Task_IMContact 0x7000000F
#define MSG_Task_AppBlocked 0x70000010
#define MSG_Task_AppOverride 0x70000011
#define MSG_Task_WebOverride 0x70000012
#define MSG_Publisher_Name 0x90000001
#define MSG_Event_SettingChange 0xB0000001
#define MSG_Event_GameStart 0xB0000002
#define MSG_Event_UrlVisit 0xB0000003
#define MSG_Event_EmailReceived 0xB0000004
#define MSG_Event_EmailSent 0xB0000005
#define MSG_Event_MediaPlayback 0xB0000006
#define MSG_Event_IMInvitation 0xB0000007
#define MSG_Event_IMJoin 0xB0000008
#define MSG_Event_IMLeave 0xB0000009
#define MSG_Event_FileDownload 0xB000000A
#define MSG_Event_IMFeature 0xB000000B
#define MSG_Event_Custom 0xB000000D
#define MSG_Event_EmailContact 0xB000000E
#define MSG_Event_IMContact 0xB000000F
#define MSG_Event_AppBlocked 0xB0000010
#define MSG_Event_AppOverride 0xB0000011
#define MSG_Event_WebOverride 0xB0000012

#ENDIF