#ifndef WTYPES_H
#define WTYPES_H

#DEFINE WTYPES_H_REQVER 100

/* Windows Remotable data types definition */

#IFNDEF RPC_H
	#include "rpc.h" // WIN3264
#ENDIF

#IFNDEF RPCNDR_H
	#include "rpcndr.h" // WIN3264
#ENDIF

#define WDT_INPROC_CALL  0x48746457
#define WDT_REMOTE_CALL  0x52746457
#define WDT_INPROC64_CALL  0x50746457

RemHGLOBAL STRUCT
	fNullHGlobal DD
	cbData DD
	data DB
ENDS

RemHMETAFILEPICT STRUCT
	mm DD
	xExt DD
	yExt DD
	cbData DD
	data DB
ENDS

RemHENHMETAFILE STRUCT
	cbData DD
	data DB
ENDS

RemHBITMAP STRUCT
	cbData DD
	data DB
ENDS

RemHPALETTE STRUCT
	cbData DD
	data DB
ENDS

RemBRUSH STRUCT
	cbData DD
	data DB
ENDS

#IFNDEF PALETTEENTRY
	PALETTEENTRY STRUCT
		peRed DB
		peGreen DB
		peBlue DB
		peFlags DB
	ENDS
#ENDIF

#IFNDEF LOGPALETTE
	LOGPALETTE STRUCT
		palVersion DW
		palNumEntries DW
		palPalEntry PALETTEENTRY
	ENDS
#ENDIF

#IFNDEF RECT
	RECT STRUCT
		left DD
		top DD
		right DD
		bottom DD
	ENDS
#ENDIF

#IFNDEF FILETIME
	FILETIME STRUCT
		dwLowDateTime DD
		dwHighDateTime DD
	ENDS
#ENDIF

#IFNDEF SYSTEMTIME
	SYSTEMTIME STRUCT
		wYear DW
		wMonth DW
		wDayOfWeek DW
		wDay DW
		wHour DW
		wMinute DW
		wSecond DW
		wMilliseconds DW
	ENDS
#ENDIF

COAUTHIDENTITY STRUCT
	User PTR
	UserLength DD
	Domain PTR
	DomainLength DD
	Password PTR
	PasswordLength DD
	Flags DD
ENDS

COAUTHINFO STRUCT
	dwAuthnSvc DD
	dwAuthzSvc DD
	pwszServerPrincName DD
	dwAuthnLevel DD
	dwImpersonationLevel DD
	pAuthIdentityData PTR
	dwCapabilities DD
ENDS


#IFNDEF OBJECTID
	OBJECTID STRUCT
		Lineage GUID
		Uniquifier DD
	ENDS
#ENDIF

#DEFINE MEMCTX_TASK 1
#DEFINE MEMCTX_SHARED 2
#DEFINE MEMCTX_MACSYSTEM 3
#DEFINE MEMCTX_UNKNOWN -1
#DEFINE MEMCTX_SAME -2

#define ROTFLAGS_REGISTRATIONKEEPSALIVE  1
#define ROTFLAGS_ALLOWANYCLIENT  2

#define ROT_COMPARE_MAX  2048

#DEFINE CLSCTX_INPROC_SERVER 0x1
#DEFINE CLSCTX_INPROC_HANDLER 0x2
#DEFINE CLSCTX_LOCAL_SERVER 0x4
#DEFINE CLSCTX_INPROC_SERVER16 0x8
#DEFINE CLSCTX_REMOTE_SERVER 0x10
#DEFINE CLSCTX_INPROC_HANDLER16 0x20
#DEFINE CLSCTX_INPROC_SERVERX86 0x40
#DEFINE CLSCTX_INPROC_HANDLERX86 0x80
#DEFINE CLSCTX_ESERVER_HANDLER 0x100
#DEFINE CLSCTX_RESERVED 0x200
#DEFINE CLSCTX_NO_CODE_DOWNLOAD 0x400
#DEFINE CLSCTX_NO_WX86_TRANSLATION 0x800
#DEFINE CLSCTX_NO_CUSTOM_MARSHAL 0x1000
#DEFINE CLSCTX_ENABLE_CODE_DOWNLOAD 0x2000
#DEFINE CLSCTX_NO_FAILURE_LOG 0x4000

#DEFINE MSHLFLAGS_NORMAL 0
#DEFINE MSHLFLAGS_TABLESTRONG 1
#DEFINE MSHLFLAGS_TABLEWEAK 2
#DEFINE MSHLFLAGS_NOPING 4
#DEFINE MSHLFLAGS_RESERVED1 8
#DEFINE MSHLFLAGS_RESERVED2 16
#DEFINE MSHLFLAGS_RESERVED3 32
#DEFINE MSHLFLAGS_RESERVED4 64

#DEFINE MSHCTX_LOCAL 0
#DEFINE MSHCTX_NOSHAREDMEM 1
#DEFINE MSHCTX_DIFFERENTMACHINE 2
#DEFINE MSHCTX_INPROC 3
#DEFINE MSHCTX_CROSSCTX 4

#DEFINE DVASPECT_CONTENT 1
#DEFINE DVASPECT_THUMBNAIL 2
#DEFINE DVASPECT_ICON 4
#DEFINE DVASPECT_DOCPRINT 8

#DEFINE STGC_DEFAULT 0
#DEFINE STGC_OVERWRITE 1
#DEFINE STGC_ONLYIFCURRENT 2
#DEFINE STGC_DANGEROUSLYCOMMITMERELYTODISKCACHE 4
#DEFINE STGC_CONSOLIDATE 8

#DEFINE STGMOVE_MOVE 0
#DEFINE STGMOVE_COPY 1
#DEFINE STGMOVE_SHALLOWCOPY 2

#DEFINE STATFLAG_DEFAULT 0
#DEFINE STATFLAG_NONAME 1
#DEFINE STATFLAG_NOOPEN 2


BYTE_BLOB STRUCT
	clSize DD
	abData DB
ENDS

WORD_BLOB STRUCT
	clSize DD
	asData DW
ENDS

DWORD_BLOB STRUCT
	clSize DD
	alData DD
ENDS

FLAGGED_BYTE_BLOB STRUCT
	fFlags DD
	clSize DD
	abData DB
ENDS

FLAGGED_WORD_BLOB STRUCT
	fFlags DD
	clSize DD
	asData DW
ENDS

BYTE_SIZEDARR STRUCT
	clSize DD
	pData PTR
ENDS

SHORT_SIZEDARR STRUCT
	clSize DD
	pData PTR
ENDS

LONG_SIZEDARR STRUCT
	clSize DD
	pData PTR
ENDS

HYPER_SIZEDARR STRUCT
	clSize DD
	pData PTR
ENDS

userCLIPFORMAT STRUCT
	fContext DD
	UNION
		dwValue DD
		pwszName PTR
	ENDUNION
ENDS

GDI_NONREMOTE STRUCT
	fContext DD
	UNION
		hInproc HANDLE
		hRemote HANDLE
	ENDUNION
ENDS

userHGLOBAL STRUCT
	fContext DD
	UNION
		hInproc HANDLE
		hRemote HANDLE
		hInproc64 HANDLE
	ENDUNION
ENDS

userHMETAFILE STRUCT
	fContext DD
	UNION
		hInproc HANDLE
		hRemote HANDLE
	ENDUNION
ENDS

remoteMETAFILEPICT STRUCT
	mm DD
	xExt DD
	yExt DD
	hMF HANDLE
ENDS

userHMETAFILEPICT STRUCT
	fContext DD
	UNION
		hInproc HANDLE
		hRemote HANDLE
	ENDUNION
ENDS

userHENHMETAFILE STRUCT
	fContext DD
	UNION
		hInproc HANDLE
		hRemote HANDLE
	ENDUNION
ENDS

userBITMAP STRUCT
	bmType DD
	bmWidth DD
	bmHeight DD
	bmWidthBytes DD
	bmPlanes DW
	bmBitsPixel DW
	cbSize DD
	pBuffer PTR
ENDS

userHBITMAP STRUCT
	fContext DD
	UNION
		hInproc HANDLE
		hRemote HANDLE
	ENDUNION
ENDS

userHPALETTE STRUCT
	fContext DD
	UNION
		hInproc HANDLE
		hRemote HANDLE
	ENDUNION
ENDS

RemotableHandle STRUCT
	fContext DD
	UNION
		hInproc HANDLE
		hRemote HANDLE
	ENDUNION
ENDS

#IFNDEF TEXTMETRICW
	TEXTMETRICW STRUCT
		tmHeight DD
		tmAscent DD
		tmDescent DD
		tmInternalLeading DD
		tmExternalLeading DD
		tmAveCharWidth DD
		tmMaxCharWidth DD
		tmWeight DD
		tmOverhang DD
		tmDigitizedAspectX DD
		tmDigitizedAspectY DD
		tmFirstChar DW
		tmLastChar DW
		tmDefaultChar DW
		tmBreakChar DW
		tmItalic DB
		tmUnderlined DB
		tmStruckOut DB
		tmPitchAndFamily DB
		tmCharSet DB
	ENDS
#ENDIF

DECIMAL STRUCT
	wReserved DW
    UNION
		signscalestr STRUCT
			scale DB
			sign DB
		ENDS
		signscale DW
    ENDUNION
	Hi32 DD
    UNION
		lomid STRUCT
			Lo32 DD
			Mid32 DD
		ENDS
		Lo64 DQ
    ENDUNION
ENDS

#define DECIMAL_NEG 0x80

#IFNDEF BSTRBLOB
	BSTRBLOB STRUCT
		cbSize DD
		pData PTR
	ENDS
#ENDIF

#define VARIANT_TRUE  0xFFFF
#define VARIANT_FALSE 0

#IFNDEF BLOB
	BLOB STRUCT
		cbSize DD
		pBlobData PTR
	ENDS
#ENDIF

CLIPDATA STRUCT
	cbSize DD
	ulClipFmt DD
	pClipData DD
ENDS

#DEFINE VT_EMPTY 0
#DEFINE VT_NULL 1
#DEFINE VT_I2 2
#DEFINE VT_I4 3
#DEFINE VT_R4 4
#DEFINE VT_R8 5
#DEFINE VT_CY 6
#DEFINE VT_DATE 7
#DEFINE VT_BSTR 8
#DEFINE VT_DISPATCH 9
#DEFINE VT_ERROR 10
#DEFINE VT_BOOL 11
#DEFINE VT_VARIANT 12
#DEFINE VT_UNKNOWN 13
#DEFINE VT_DECIMAL 14
#DEFINE VT_I1 16
#DEFINE VT_UI1 17
#DEFINE VT_UI2 18
#DEFINE VT_UI4 19
#DEFINE VT_I8 20
#DEFINE VT_UI8 21
#DEFINE VT_INT 22
#DEFINE VT_UINT 23
#DEFINE VT_VOID 24
#DEFINE VT_HRESULT 25
#DEFINE VT_PTR 26
#DEFINE VT_SAFEARRAY 27
#DEFINE VT_CARRAY 28
#DEFINE VT_USERDEFINED 29
#DEFINE VT_LPSTR 30
#DEFINE VT_LPWSTR 31
#DEFINE VT_RECORD 36
#DEFINE VT_FILETIME 64
#DEFINE VT_BLOB 65
#DEFINE VT_STREAM 66
#DEFINE VT_STORAGE 67
#DEFINE VT_STREAMED_OBJECT 68
#DEFINE VT_STORED_OBJECT 69
#DEFINE VT_BLOB_OBJECT 70
#DEFINE VT_CF 71
#DEFINE VT_CLSID 72
#DEFINE VT_VERSIONED_STREAM 73
#DEFINE VT_BSTR_BLOB 0xfff
#DEFINE VT_VECTOR 0x1000
#DEFINE VT_ARRAY 0x2000
#DEFINE VT_BYREF 0x4000
#DEFINE VT_RESERVED 0x8000
#DEFINE VT_ILLEGAL 0xffff
#DEFINE VT_ILLEGALMASKED 0xfff
#DEFINE VT_TYPEMASK 0xfff

#ifndef SID_IDENTIFIER_AUTHORITY
	SID_IDENTIFIER_AUTHORITY STRUCT
		Value DB 6 DUP
	ENDS
#endif

#ifndef SID
	SID STRUCT
		Revision DB
		SubAuthorityCount DB
		IdentifierAuthority SID_IDENTIFIER_AUTHORITY
		SubAuthority DD
	ENDS
	
	SID_AND_ATTRIBUTES STRUCT
		Sid PTR
		Attributes DD
	ENDS
#endif

CSPLATFORM STRUCT
	dwPlatformId DD
	dwVersionHi DD
	dwVersionLo DD
	dwProcessorArch DD
ENDS

QUERYCONTEXT STRUCT
	dwContext DD
	Platform CSPLATFORM
	Locale DD
	dwVersionHi DD
	dwVersionLo DD
ENDS

#DEFINE TYSPEC_CLSID 0
#DEFINE TYSPEC_FILEEXT TYSPEC_CLSID+1
#DEFINE TYSPEC_MIMETYPE TYSPEC_FILEEXT+1
#DEFINE TYSPEC_FILENAME TYSPEC_MIMETYPE+1
#DEFINE TYSPEC_PROGID TYSPEC_FILENAME+1
#DEFINE TYSPEC_PACKAGENAME TYSPEC_PROGID+1
#DEFINE TYSPEC_OBJECTID TYSPEC_PACKAGENAME+1

#endif /* WTYPES_H */

