#ifndef CCHANNEL_H
#define CCHANNEL_H

/* Virtual Channel Client API definitions */

#IFNDEF PCHANNEL_H
	#include pchannel.h
#ENDIF

#define CHANNEL_EVENT_INITIALIZED  0
#define CHANNEL_EVENT_CONNECTED  1
#define CHANNEL_EVENT_V1_CONNECTED  2
#define CHANNEL_EVENT_DISCONNECTED  3
#define CHANNEL_EVENT_TERMINATED  4

#define CHANNEL_EVENT_DATA_RECEIVED  10
#define CHANNEL_EVENT_WRITE_COMPLETE  11
#define CHANNEL_EVENT_WRITE_CANCELLED  12

#define CHANNEL_RC_OK  0
#define CHANNEL_RC_ALREADY_INITIALIZED  1
#define CHANNEL_RC_NOT_INITIALIZED  2
#define CHANNEL_RC_ALREADY_CONNECTED  3
#define CHANNEL_RC_NOT_CONNECTED  4
#define CHANNEL_RC_TOO_MANY_CHANNELS  5
#define CHANNEL_RC_BAD_CHANNEL  6
#define CHANNEL_RC_BAD_CHANNEL_HANDLE  7
#define CHANNEL_RC_NO_BUFFER  8
#define CHANNEL_RC_BAD_INIT_HANDLE  9
#define CHANNEL_RC_NOT_OPEN  10
#define CHANNEL_RC_BAD_PROC  11
#define CHANNEL_RC_NO_MEMORY  12
#define CHANNEL_RC_UNKNOWN_CHANNEL_NAME  13
#define CHANNEL_RC_ALREADY_OPEN  14
#define CHANNEL_RC_NOT_IN_VIRTUALCHANNELENTRY  15
#define CHANNEL_RC_NULL_DATA  16
#define CHANNEL_RC_ZERO_LENGTH  17

#define VIRTUAL_CHANNEL_VERSION_WIN2000  1

CHANNEL_ENTRY_POINTS STRUCT
	cbSize DD
	protocolVersion DD
	pVirtualChannelInit PTR
	pVirtualChannelOpen PTR
	pVirtualChannelClose PTR
	pVirtualChannelWrite PTR
ENDS

#endif /* _CCHANNEL_H */
