#ifndef DPLAY8_H
#define DPLAY8_H

/* DirectPlay8 definitions */

#IFNDEF OLE2_H
	#include "ole2.h"
#ENDIF

#IFNDEF DPADDR_H
	#include "dpaddr.h"
#ENDIF

#IFNDEF BASECOM_H
	#include "BaseCOM.h"
#ENDIF

#IFNDEF WINERROR_H
	#include winerror.h
#ENDIF

#DEFINE GUID_CLSID_DirectPlay8Client <0x743f1dc6,0x5aba,0x429f,<0x8b,0xdf,0xc5,0x4d,0x3,0x25,0x3d,0xc2>>
#DEFINE GUID_CLSID_DirectPlay8Peer <0x286f484d,0x375e,0x4458,<0xa2,0x72,0xb1,0x38,0xe2,0xf8,0xa,0x6a>>
#DEFINE GUID_CLSID_DirectPlay8Server <0xda825e1b,0x6830,0x43d7,<0x83,0x5d,0xb,0x5a,0xd8,0x29,0x56,0xa2>>

#DEFINE GUID_IID_IDirectPlay8Client <0x5102dacd,0x241b,0x11d3,<0xae,0xa7,0x0,0x60,0x97,0xb0,0x14,0x11>>
#DEFINE GUID_IID_IDirectPlay8Peer <0x5102dacf,0x241b,0x11d3,<0xae,0xa7,0x0,0x60,0x97,0xb0,0x14,0x11>>
#DEFINE GUID_IID_IDirectPlay8Server <0x5102dace,0x241b,0x11d3,<0xae,0xa7,0x0,0x60,0x97,0xb0,0x14,0x11>>

#DEFINE GUID_CLSID_DP8SP_IPX <0x53934290,0x628d,0x11d2,<0xae,0xf,0x0,0x60,0x97,0xb0,0x14,0x11>>
#DEFINE GUID_CLSID_DP8SP_MODEM <0x6d4a3650,0x628d,0x11d2,<0xae,0xf,0x0,0x60,0x97,0xb0,0x14,0x11>>
#DEFINE GUID_CLSID_DP8SP_SERIAL <0x743b5d60,0x628d,0x11d2,<0xae,0xf,0x0,0x60,0x97,0xb0,0x14,0x11>>
#DEFINE GUID_CLSID_DP8SP_TCPIP <0xebfe7ba0,0x628d,0x11d2,<0xae,0xf,0x0,0x60,0x97,0xb0,0x14,0x11>>

#define DPN_MSGID_OFFSET  0xFFFF0000
#define DPN_MSGID_ADD_PLAYER_TO_GROUP  (DPN_MSGID_OFFSET|0x0001)
#define DPN_MSGID_APPLICATION_DESC  (DPN_MSGID_OFFSET|0x0002)
#define DPN_MSGID_ASYNC_OP_COMPLETE  (DPN_MSGID_OFFSET|0x0003)
#define DPN_MSGID_CLIENT_INFO  (DPN_MSGID_OFFSET|0x0004)
#define DPN_MSGID_CONNECT_COMPLETE  (DPN_MSGID_OFFSET|0x0005)
#define DPN_MSGID_CREATE_GROUP  (DPN_MSGID_OFFSET|0x0006)
#define DPN_MSGID_CREATE_PLAYER  (DPN_MSGID_OFFSET|0x0007)
#define DPN_MSGID_DESTROY_GROUP  (DPN_MSGID_OFFSET|0x0008)
#define DPN_MSGID_DESTROY_PLAYER  (DPN_MSGID_OFFSET|0x0009)
#define DPN_MSGID_ENUM_HOSTS_QUERY  (DPN_MSGID_OFFSET|0x000a)
#define DPN_MSGID_ENUM_HOSTS_RESPONSE  (DPN_MSGID_OFFSET|0x000b)
#define DPN_MSGID_GROUP_INFO  (DPN_MSGID_OFFSET|0x000c)
#define DPN_MSGID_HOST_MIGRATE  (DPN_MSGID_OFFSET|0x000d)
#define DPN_MSGID_INDICATE_CONNECT  (DPN_MSGID_OFFSET|0x000e)
#define DPN_MSGID_INDICATED_CONNECT_ABORTED  (DPN_MSGID_OFFSET|0x000f)
#define DPN_MSGID_PEER_INFO  (DPN_MSGID_OFFSET|0x0010)
#define DPN_MSGID_RECEIVE  (DPN_MSGID_OFFSET|0x0011)
#define DPN_MSGID_REMOVE_PLAYER_FROM_GROUP  (DPN_MSGID_OFFSET|0x0012)
#define DPN_MSGID_RETURN_BUFFER  (DPN_MSGID_OFFSET|0x0013)
#define DPN_MSGID_SEND_COMPLETE  (DPN_MSGID_OFFSET|0x0014)
#define DPN_MSGID_SERVER_INFO  (DPN_MSGID_OFFSET|0x0015)
#define DPN_MSGID_TERMINATE_SESSION  (DPN_MSGID_OFFSET|0x0016)

#define DPNID_ALL_PLAYERS_GROUP  0

#define DPNDESTROYGROUPREASON_NORMAL  0x0001
#define DPNDESTROYGROUPREASON_AUTODESTRUCTED  0x0002
#define DPNDESTROYGROUPREASON_SESSIONTERMINATED  0x0003

#define DPNDESTROYPLAYERREASON_NORMAL  0x0001
#define DPNDESTROYPLAYERREASON_CONNECTIONLOST  0x0002
#define DPNDESTROYPLAYERREASON_SESSIONTERMINATED  0x0003
#define DPNDESTROYPLAYERREASON_HOSTDESTROYEDPLAYER  0x0004

#define DPNOP_SYNC  0x80000000

#define DPNADDPLAYERTOGROUP_SYNC  DPNOP_SYNC

#define DPNCANCEL_CONNECT  0x0001
#define DPNCANCEL_ENUM  0x0002
#define DPNCANCEL_SEND  0x0004
#define DPNCANCEL_ALL_OPERATIONS  0x8000

#define DPNCONNECT_SYNC  DPNOP_SYNC
#define DPNCONNECT_OKTOQUERYFORADDRESSING  0x0001

#define DPNCREATEGROUP_SYNC  DPNOP_SYNC
#define DPNDESTROYGROUP_SYNC  DPNOP_SYNC

#define DPNENUM_PLAYERS  0x0001
#define DPNENUM_GROUPS  0x0010

#define DPNENUMHOSTS_SYNC  DPNOP_SYNC
#define DPNENUMHOSTS_OKTOQUERYFORADDRESSING  0x0001
#define DPNENUMHOSTS_NOBROADCASTFALLBACK  0x0002

#define DPNENUMSERVICEPROVIDERS_ALL  0x0001

#define DPNGETSENDQUEUEINFO_PRIORITY_NORMAL  0x0001
#define DPNGETSENDQUEUEINFO_PRIORITY_HIGH  0x0002
#define DPNGETSENDQUEUEINFO_PRIORITY_LOW  0x0004

#define DPNGROUP_AUTODESTRUCT  0x0001

#define DPNHOST_OKTOQUERYFORADDRESSING  0x0001

#define DPNINFO_NAME  0x0001
#define DPNINFO_DATA  0x0002

#define DPNINITIALIZE_DISABLEPARAMVAL  0x0001

#define DPNLOBBY_REGISTER  0x0001
#define DPNLOBBY_UNREGISTER  0x0002

#define DPNPLAYER_LOCAL  0x0002
#define DPNPLAYER_HOST  0x0004

#define DPNREMOVEPLAYERFROMGROUP_SYNC  DPNOP_SYNC

#define DPNSEND_SYNC  DPNOP_SYNC
#define DPNSEND_NOCOPY  0x0001
#define DPNSEND_NOCOMPLETE  0x0002
#define DPNSEND_COMPLETEONPROCESS  0x0004
#define DPNSEND_GUARANTEED  0x0008
#define DPNSEND_NONSEQUENTIAL  0x0010
#define DPNSEND_NOLOOPBACK  0x0020
#define DPNSEND_PRIORITY_LOW  0x0040
#define DPNSEND_PRIORITY_HIGH  0x0080

#define DPNSESSION_CLIENT_SERVER  0x0001
#define DPNSESSION_MIGRATE_HOST  0x0004
#define DPNSESSION_NODPNSVR  0x0040
#define DPNSESSION_REQUIREPASSWORD  0x0080

#define DPNSETCLIENTINFO_SYNC  DPNOP_SYNC

#define DPNSETGROUPINFO_SYNC  DPNOP_SYNC

#define DPNSETPEERINFO_SYNC  DPNOP_SYNC

#define DPNSETSERVERINFO_SYNC  DPNOP_SYNC

#define DPNSPCAPS_SUPPORTSDPNSRV  0x0001
#define DPNSPCAPS_SUPPORTSBROADCAST  0x0002
#define DPNSPCAPS_SUPPORTSALLADAPTERS  0x0004

#define _DPN_FACILITY_CODE  0x015
#define _DPNHRESULT_BASE  0x8000

#define DPN_OK  S_OK

#define DPNSUCCESS_EQUAL  (_DPN_FACILITY_CODE<<16|(0x5+_DPNHRESULT_BASE))
#define DPNSUCCESS_NOTEQUAL (_DPN_FACILITY_CODE<<16|(0x0a+_DPNHRESULT_BASE))
#define DPNSUCCESS_PENDING  (_DPN_FACILITY_CODE<<16|(0x0e+_DPNHRESULT_BASE))

#define DPNERR_ABORTED  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x30))
#define DPNERR_ADDRESSING  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x40))
#define DPNERR_ALREADYCLOSING  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x50))
#define DPNERR_ALREADYCONNECTED  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x60))
#define DPNERR_ALREADYDISCONNECTING  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x70))
#define DPNERR_ALREADYINITIALIZED  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x80))
#define DPNERR_ALREADYREGISTERED  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x90))
#define DPNERR_BUFFERTOOSMALL  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x100))
#define DPNERR_CANNOTCANCEL  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x110))
#define DPNERR_CANTCREATEGROUP  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x120))
#define DPNERR_CANTCREATEPLAYER  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x130))
#define DPNERR_CANTLAUNCHAPPLICATION  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x140))
#define DPNERR_CONNECTING  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x150))
#define DPNERR_CONNECTIONLOST  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x160))
#define DPNERR_CONVERSION  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x170))
#define DPNERR_DATATOOLARGE  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x175))
#define DPNERR_DOESNOTEXIST  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x180))
#define DPNERR_DUPLICATECOMMAND  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x190))
#define DPNERR_ENDPOINTNOTRECEIVING  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x200))
#define DPNERR_ENUMQUERYTOOLARGE  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x210))
#define DPNERR_ENUMRESPONSETOOLARGE  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x220))
#define DPNERR_EXCEPTION  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x230))
#define DPNERR_GENERIC  E_FAIL
#define DPNERR_GROUPNOTEMPTY  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x240))
#define DPNERR_HOSTING  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x250))
#define DPNERR_HOSTREJECTEDCONNECTION  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x260))
#define DPNERR_HOSTTERMINATEDSESSION  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x270))
#define DPNERR_INCOMPLETEADDRESS  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x280))
#define DPNERR_INVALIDADDRESSFORMAT  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x290))
#define DPNERR_INVALIDAPPLICATION  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x300))
#define DPNERR_INVALIDCOMMAND  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x310))
#define DPNERR_INVALIDDEVICEADDRESS  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x320))
#define DPNERR_INVALIDENDPOINT  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x330))
#define DPNERR_INVALIDFLAGS  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x340))
#define DPNERR_INVALIDGROUP  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x350))
#define DPNERR_INVALIDHANDLE  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x360))
#define DPNERR_INVALIDHOSTADDRESS  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x370))
#define DPNERR_INVALIDINSTANCE  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x380))
#define DPNERR_INVALIDINTERFACE  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x390))
#define DPNERR_INVALIDOBJECT  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x400))
#define DPNERR_INVALIDPARAM  E_INVALIDARG
#define DPNERR_INVALIDPASSWORD  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x410))
#define DPNERR_INVALIDPLAYER  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x420))
#define DPNERR_INVALIDPOINTER  E_POINTER
#define DPNERR_INVALIDPRIORITY  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x430))
#define DPNERR_INVALIDSTRING  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x440))
#define DPNERR_INVALIDURL  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x450))
#define DPNERR_INVALIDVERSION  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x460))
#define DPNERR_NOCAPS  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x470))
#define DPNERR_NOCONNECTION  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x480))
#define DPNERR_NOHOSTPLAYER  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x490))
#define DPNERR_NOINTERFACE  E_NOINTERFACE
#define DPNERR_NOMOREADDRESSCOMPONENTS  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x500))
#define DPNERR_NORESPONSE  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x510))
#define DPNERR_NOTALLOWED  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x520))
#define DPNERR_NOTHOST  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x530))
#define DPNERR_NOTREADY  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x540))
#define DPNERR_NOTREGISTERED  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x550))
#define DPNERR_OUTOFMEMORY  E_OUTOFMEMORY
#define DPNERR_PENDING  DPNSUCCESS_PENDING
#define DPNERR_PLAYERALREADYINGROUP  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x560))
#define DPNERR_PLAYERLOST  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x570))
#define DPNERR_PLAYERNOTINGROUP  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x580))
#define DPNERR_PLAYERNOTREACHABLE  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x590))
#define DPNERR_SENDTOOLARGE  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x600))
#define DPNERR_SESSIONFULL  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x610))
#define DPNERR_TABLEFULL  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x620))
#define DPNERR_TIMEDOUT  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x630))
#define DPNERR_UNINITIALIZED  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x640))
#define DPNERR_UNSUPPORTED  E_NOTIMPL
#define DPNERR_USERCANCEL  (1<<31|_DPN_FACILITY_CODE<<16|(_DPNHRESULT_BASE+0x650))

DPN_APPLICATION_DESC STRUCT
	dwSize DD
	dwFlags DD
	guidInstance GUID
	guidApplication GUID
	dwMaxPlayers DD
	dwCurrentPlayers DD
	pwszSessionName  PTR
	pwszPassword PTR
	pvReservedData PTR
	dwReservedDataSize DD
	pvApplicationReservedData PTR
	dwApplicationReservedDataSize DD
ENDS

BUFFERDESC STRUCT
	dwBufferSize DD
	pBufferData PTR
ENDS

DPN_CAPS STRUCT
	dwSize DD
	dwFlags DD
	dwConnectTimeout DD
	dwConnectRetries DD
	dwTimeoutUntilKeepAlive DD
ENDS

DPN_CONNECTION_INFO STRUCT
	dwSize DD
	dwRoundTripLatencyMS DD
	dwThroughputBPS DD
	dwPeakThroughputBPS DD
	dwBytesSentGuaranteed DD
	dwPacketsSentGuaranteed DD
	dwBytesSentNonGuaranteed DD
	dwPacketsSentNonGuaranteed DD
	dwBytesRetried DD
	dwPacketsRetried DD
	dwBytesDropped DD
	dwPacketsDropped DD
	dwMessagesTransmittedHighPriority DD
	dwMessagesTimedOutHighPriority DD
	dwMessagesTransmittedNormalPriority DD
	dwMessagesTimedOutNormalPriority DD
	dwMessagesTransmittedLowPriority DD
	dwMessagesTimedOutLowPriority DD
	dwBytesReceivedGuaranteed DD
	dwPacketsReceivedGuaranteed DD
	dwBytesReceivedNonGuaranteed DD
	dwPacketsReceivedNonGuaranteed DD
	dwMessagesReceived DD
ENDS

DPN_GROUP_INFO STRUCT
	dwSize DD
	dwInfoFlags DD
	pwszName PTR
	pvData PTR
	dwDataSize DD
	dwGroupFlags DD
ENDS

DPN_PLAYER_INFO STRUCT
	dwSize DD
	dwInfoFlags DD
	pwszName PTR
	pvData PTR
	dwDataSize DD
	dwPlayerFlags DD
ENDS

DPN_SERVICE_PROVIDER_INFO STRUCT
	dwFlags DD
	guid GUID
	pwszName PTR
	pvReserved PTR
	dwReserved DD
ENDS

DPN_SP_CAPS STRUCT
	dwSize DD
	dwFlags DD
	dwNumThreads DD
	dwDefaultEnumCount DD
	dwDefaultEnumRetryInterval DD
	dwDefaultEnumTimeout DD
	dwMaxEnumPayloadSize DD
	dwBuffersPerThread DD
	dwSystemBufferSize DD
ENDS

DPNMSG_ADD_PLAYER_TO_GROUP STRUCT
	dwSize DD
	dpnidGroup DD
	pvGroupContext PTR
	dpnidPlayer DD
	pvPlayerContext PTR
ENDS

DPNMSG_ASYNC_OP_COMPLETE STRUCT
	dwSize DD
	hAsyncOp HANDLE
	pvUserContext PTR
	hResultCode HANDLE
ENDS

DPNMSG_CLIENT_INFO STRUCT
	dwSize DD
	dpnidClient DD
	pvPlayerContext PTR
ENDS

DPNMSG_CONNECT_COMPLETE STRUCT
	dwSize DD
	hAsyncOp HANDLE
	pvUserContext PTR
	hResultCode HANDLE
	pvApplicationReplyData PTR
	dwApplicationReplyDataSize DD
ENDS

DPNMSG_CREATE_GROUP STRUCT
	dwSize DD
	dpnidGroup DD
	dpnidOwner DD
	pvGroupContext PTR
ENDS

DPNMSG_CREATE_PLAYER STRUCT
	dwSize DD
	dpnidPlayer DD
	pvPlayerContext PTR
ENDS

DPNMSG_DESTROY_GROUP STRUCT
	dwSize DD
	dpnidGroup DD
	pvGroupContext PTR
	dwReason DD
ENDS

DPNMSG_DESTROY_PLAYER STRUCT
	dwSize DD
	dpnidPlayer DD
	pvPlayerContext PTR
	dwReason DD
ENDS

DPNMSG_ENUM_HOSTS_QUERY STRUCT
	dwSize DD
	pAddressSender PTR
	pAddressDevice PTR
	pvReceivedData PTR
	dwReceivedDataSize DD
	dwMaxResponseDataSize DD
	pvResponseData PTR
	dwResponseDataSize DD
	pvResponseContext PTR
ENDS

DPNMSG_ENUM_HOSTS_RESPONSE STRUCT
	dwSize DD
	pAddressSender PTR
	pAddressDevice PTR
	pApplicationDescription PTR
	pvResponseData PTR
	dwResponseDataSize DD
	pvUserContext PTR
	dwRoundTripLatencyMS DD
ENDS

DPNMSG_GROUP_INFO STRUCT
	dwSize DD
	dpnidGroup DD
	pvGroupContext PTR
ENDS

DPNMSG_HOST_MIGRATE STRUCT
	dwSize DD
	dpnidNewHost DD
	pvPlayerContext PTR
ENDS

DPNMSG_INDICATE_CONNECT STRUCT
	dwSize DD
	pvUserConnectData PTR
	dwUserConnectDataSize DD
	pvReplyData PTR
	dwReplyDataSize DD
	pvReplyContext PTR
	pvPlayerContext PTR
	pAddressPlayer PTR
	pAddressDevice PTR
ENDS

DPNMSG_INDICATED_CONNECT_ABORTED STRUCT
	dwSize DD
	pvPlayerContext PTR
ENDS

DPNMSG_PEER_INFO STRUCT
	dwSize DD
	dpnidPeer DD
	pvPlayerContext PTR
ENDS

DPNMSG_RECEIVE STRUCT
	dwSize DD
	dpnidSender DD
	pvPlayerContext PTR
	pReceiveData PTR
	dwReceiveDataSize DD
	hBufferHandle HANDLE
ENDS

DPNMSG_REMOVE_PLAYER_FROM_GROUP STRUCT
	dwSize DD
	dpnidGroup DD
	pvGroupContext PTR
	dpnidPlayer DD
	pvPlayerContext PTR
ENDS

DPNMSG_RETURN_BUFFER STRUCT
	dwSize DD
	hResultCode HANDLE
	pvBuffer PTR
	pvUserContext PTR
ENDS

DPNMSG_SEND_COMPLETE STRUCT
	dwSize DD
	hAsyncOp HANDLE
	pvUserContext PTR
	hResultCode HANDLE
	dwSendTime DD
ENDS

DPNMSG_SERVER_INFO STRUCT
	dwSize DD
	dpnidServer DD
	pvPlayerContext PTR
ENDS

DPNMSG_TERMINATE_SESSION STRUCT
	dwSize DD
	hResultCode HANDLE
	pvTerminateData PTR
	dwTerminateDataSize DD
ENDS

IDirectPlay8Client STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Initialize PTR
	EnumServiceProviders  PTR
	EnumHosts PTR
	CancelAsyncOperation PTR
	Connect PTR
	Send PTR
	GetSendQueueInfo PTR
	GetApplicationDesc PTR
	SetClientInfo PTR
	GetServerInfo PTR
	GetServerAddress PTR
	Close PTR
	ReturnBuffer PTR
	GetCaps PTR
	SetCaps PTR
	SetSPCaps PTR
	GetSPCaps PTR
	GetConnectionInfo PTR
	RegisterLobby PTR
ENDS

IDirectPlay8Server STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Initialize PTR
	EnumServiceProviders PTR
	CancelAsyncOperation PTR
	GetSendQueueInfo PTR
	GetApplicationDesc PTR
	SetServerInfo PTR
	GetClientInfo PTR
	GetClientAddress PTR
	GetLocalHostAddresses PTR
	SetApplicationDesc PTR
	Host PTR
	SendTo PTR
	CreateGroup PTR
	DestroyGroup PTR
	AddPlayerToGroup PTR
	RemovePlayerFromGroup PTR
	SetGroupInfo PTR
	GetGroupInfo PTR
	EnumPlayersAndGroups PTR
	EnumGroupMembers PTR
	Close PTR
	DestroyClient PTR
	ReturnBuffer PTR
	GetPlayerContext PTR
	GetGroupContext PTR
	GetCaps PTR
	SetCaps PTR
	SetSPCaps PTR
	GetSPCaps PTR
	GetConnectionInfo PTR
	RegisterLobby PTR
ENDS

IDirectPlay8Peer STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Initialize PTR
	EnumServiceProviders PTR
	CancelAsyncOperation PTR
	Connect PTR
	SendTo PTR
	GetSendQueueInfo PTR
	Host PTR
	GetApplicationDesc PTR
	SetApplicationDesc PTR
	CreateGroup PTR
	DestroyGroup PTR
	AddPlayerToGroup PTR
	RemovePlayerFromGroup PTR
	SetGroupInfo PTR
	GetGroupInfo PTR
	EnumPlayersAndGroups PTR
	EnumGroupMembers PTR
	SetPeerInfo PTR
	GetPeerInfo PTR
	GetPeerAddress PTR
	GetLocalHostAddresses PTR
	Close PTR
	EnumHosts PTR
	DestroyPeer PTR
	ReturnBuffer PTR
	GetPlayerContext PTR
	GetGroupContext PTR
	GetCaps PTR
	SetCaps PTR
	SetSPCaps PTR
	GetSPCaps PTR
	GetConnectionInfo PTR
	RegisterLobby PTR
	TerminateSession PTR
ENDS

#endif /* DPLAY8_H */
