#ifndef LMACCESS_H
#define LMACCESS_H

/* NetUser, NetUserModals, NetGroup, NetAccess, and NetLogon API definitions */

#IFNDEF LMCONS_H
	#include lmcons.h
#ENDIF

#define GROUP_SPECIALGRP_USERS  L"USERS"
#define GROUP_SPECIALGRP_ADMINS  L"ADMINS"
#define GROUP_SPECIALGRP_GUESTS  L"GUESTS"
#define GROUP_SPECIALGRP_LOCAL  L"LOCAL"

#define ACCESS_LETTERS  "RWCXDAP "

#define UF_SCRIPT  0x0001
#define UF_ACCOUNTDISABLE  0x0002
#define UF_HOMEDIR_REQUIRED  0x0008
#define UF_LOCKOUT  0x0010
#define UF_PASSWD_NOTREQD  0x0020
#define UF_PASSWD_CANT_CHANGE  0x0040

#define UF_TEMP_DUPLICATE_ACCOUNT  0x0100
#define UF_NORMAL_ACCOUNT  0x0200
#define UF_INTERDOMAIN_TRUST_ACCOUNT  0x0800
#define UF_WORKSTATION_TRUST_ACCOUNT  0x1000
#define UF_SERVER_TRUST_ACCOUNT  0x2000

#define UF_MACHINE_ACCOUNT_MASK  (UF_INTERDOMAIN_TRUST_ACCOUNT|UF_WORKSTATION_TRUST_ACCOUNT|UF_SERVER_TRUST_ACCOUNT)
#define UF_ACCOUNT_TYPE_MASK  (UF_TEMP_DUPLICATE_ACCOUNT|UF_NORMAL_ACCOUNT|UF_INTERDOMAIN_TRUST_ACCOUNT|UF_WORKSTATION_TRUST_ACCOUNT|UF_SERVER_TRUST_ACCOUNT)

#define UF_DONT_EXPIRE_PASSWD  0x10000
#define UF_MNS_LOGON_ACCOUNT  0x20000
#define UF_SMARTCARD_REQUIRED  0x40000
#define UF_TRUSTED_FOR_DELEGATION  0x80000
#define UF_NOT_DELEGATED  0x100000
#define UF_USE_DES_KEY_ONLY  0x200000
#define UF_DONT_REQUIRE_PREAUTH  0x400000

#define UF_SETTABLE_BITS  (UF_SCRIPT|UF_ACCOUNTDISABLE|UF_LOCKOUT|UF_HOMEDIR_REQUIRED|UF_PASSWD_NOTREQD|UF_PASSWD_CANT_CHANGE|UF_ACCOUNT_TYPE_MASK|UF_DONT_EXPIRE_PASSWD|UF_MNS_LOGON_ACCOUNT|UF_ENCRYPTED_TEXT_PASSWORD_ALLOWED|UF_SMARTCARD_REQUIRED|UF_TRUSTED_FOR_DELEGATION|UF_NOT_DELEGATED|UF_USE_DES_KEY_ONLY|UF_DONT_REQUIRE_PREAUTH)

#define FILTER_TEMP_DUPLICATE_ACCOUNT  0x0001
#define FILTER_NORMAL_ACCOUNT  0x0002
#define FILTER_INTERDOMAIN_TRUST_ACCOUNT  0x0008
#define FILTER_WORKSTATION_TRUST_ACCOUNT  0x0010
#define FILTER_SERVER_TRUST_ACCOUNT  0x0020

#define LG_INCLUDE_INDIRECT  1

#define AF_OP_PRINT  0x1
#define AF_OP_COMM  0x2
#define AF_OP_SERVER  0x4
#define AF_OP_ACCOUNTS  0x8
#define AF_SETTABLE_BITS  (AF_OP_PRINT|AF_OP_COMM|AF_OP_SERVER|AF_OP_ACCOUNTS)

#define UAS_ROLE_STANDALONE  0
#define UAS_ROLE_MEMBER  1
#define UAS_ROLE_BACKUP  2
#define UAS_ROLE_PRIMARY  3

#define USER_NAME_PARMNUM  1
#define USER_PASSWORD_PARMNUM  3
#define USER_PASSWORD_AGE_PARMNUM  4
#define USER_PRIV_PARMNUM  5
#define USER_HOME_DIR_PARMNUM  6
#define USER_COMMENT_PARMNUM  7
#define USER_FLAGS_PARMNUM  8
#define USER_SCRIPT_PATH_PARMNUM  9
#define USER_AUTH_FLAGS_PARMNUM  10
#define USER_FULL_NAME_PARMNUM  11
#define USER_USR_COMMENT_PARMNUM  12
#define USER_PARMS_PARMNUM  13
#define USER_WORKSTATIONS_PARMNUM  14
#define USER_LAST_LOGON_PARMNUM  15
#define USER_LAST_LOGOFF_PARMNUM  16
#define USER_ACCT_EXPIRES_PARMNUM  17
#define USER_MAX_STORAGE_PARMNUM  18
#define USER_UNITS_PER_WEEK_PARMNUM  19
#define USER_LOGON_HOURS_PARMNUM  20
#define USER_PAD_PW_COUNT_PARMNUM  21
#define USER_NUM_LOGONS_PARMNUM  22
#define USER_LOGON_SERVER_PARMNUM  23
#define USER_COUNTRY_CODE_PARMNUM  24
#define USER_CODE_PAGE_PARMNUM  25
#define USER_PRIMARY_GROUP_PARMNUM  51
#define USER_PROFILE  52
#define USER_PROFILE_PARMNUM  52
#define USER_HOME_DIR_DRIVE_PARMNUM  53

#define USER_NAME_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_NAME_PARMNUM)
#define USER_PASSWORD_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_PASSWORD_PARMNUM)
#define USER_PASSWORD_AGE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_PASSWORD_AGE_PARMNUM)
#define USER_PRIV_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_PRIV_PARMNUM)
#define USER_HOME_DIR_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_HOME_DIR_PARMNUM)
#define USER_COMMENT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_COMMENT_PARMNUM)
#define USER_FLAGS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_FLAGS_PARMNUM)
#define USER_SCRIPT_PATH_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_SCRIPT_PATH_PARMNUM)
#define USER_AUTH_FLAGS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_AUTH_FLAGS_PARMNUM)
#define USER_FULL_NAME_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_FULL_NAME_PARMNUM)
#define USER_USR_COMMENT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_USR_COMMENT_PARMNUM)
#define USER_PARMS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_PARMS_PARMNUM)
#define USER_WORKSTATIONS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_WORKSTATIONS_PARMNUM)
#define USER_LAST_LOGON_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_LAST_LOGON_PARMNUM)
#define USER_LAST_LOGOFF_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_LAST_LOGOFF_PARMNUM)
#define USER_ACCT_EXPIRES_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_ACCT_EXPIRES_PARMNUM)
#define USER_MAX_STORAGE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_MAX_STORAGE_PARMNUM)
#define USER_UNITS_PER_WEEK_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_UNITS_PER_WEEK_PARMNUM)
#define USER_LOGON_HOURS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_LOGON_HOURS_PARMNUM)
#define USER_PAD_PW_COUNT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_PAD_PW_COUNT_PARMNUM)
#define USER_NUM_LOGONS_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_NUM_LOGONS_PARMNUM)
#define USER_LOGON_SERVER_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_LOGON_SERVER_PARMNUM)
#define USER_COUNTRY_CODE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_COUNTRY_CODE_PARMNUM)
#define USER_CODE_PAGE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_CODE_PAGE_PARMNUM)
#define USER_PRIMARY_GROUP_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_PRIMARY_GROUP_PARMNUM)
#define USER_POSIX_ID_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_POSIX_ID_PARMNUM)
#define USER_HOME_DIR_DRIVE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+USER_HOME_DIR_DRIVE_PARMNUM)

#define NULL_USERSETINFO_PASSWD  "              "

#define TIMEQ_FOREVER  -1
#define USER_MAXSTORAGE_UNLIMITED  -1
#define USER_NO_LOGOFF  -1
#define UNITS_PER_DAY  24
#define UNITS_PER_WEEK   168

#define USER_PRIV_MASK  3
#define USER_PRIV_GUEST  0
#define USER_PRIV_USER  1
#define USER_PRIV_ADMIN  2

#define MAX_PASSWD_LEN  PWLEN
#define DEF_MIN_PWLEN  6
#define DEF_PWUNIQUENESS  5
#define DEF_MAX_PWHIST  8

#define DEF_MAX_PWAGE  TIMEQ_FOREVER
#define DEF_MIN_PWAGE  0
#define DEF_FORCE_LOGOFF  0xFFFFFFFF
#define DEF_MAX_BADPW  0
#define ONE_DAY  86400

#define VALIDATED_LOGON  0
#define PASSWORD_EXPIRED  2
#define NON_VALIDATED_LOGON  3

#define VALID_LOGOFF  1

#define MODALS_MIN_PASSWD_LEN_PARMNUM  1
#define MODALS_MAX_PASSWD_AGE_PARMNUM  2
#define MODALS_MIN_PASSWD_AGE_PARMNUM  3
#define MODALS_FORCE_LOGOFF_PARMNUM  4
#define MODALS_PASSWD_HIST_LEN_PARMNUM  5
#define MODALS_ROLE_PARMNUM  6
#define MODALS_PRIMARY_PARMNUM  7
#define MODALS_DOMAIN_NAME_PARMNUM  8
#define MODALS_DOMAIN_ID_PARMNUM  9
#define MODALS_LOCKOUT_DURATION_PARMNUM  10
#define MODALS_LOCKOUT_OBSERVATION_WINDOW_PARMNUM  11
#define MODALS_LOCKOUT_THRESHOLD_PARMNUM  12

#define MODALS_MIN_PASSWD_LEN_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+MODALS_MIN_PASSWD_LEN_PARMNUM)
#define MODALS_MAX_PASSWD_AGE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+MODALS_MAX_PASSWD_AGE_PARMNUM)
#define MODALS_MIN_PASSWD_AGE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+MODALS_MIN_PASSWD_AGE_PARMNUM)
#define MODALS_FORCE_LOGOFF_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+MODALS_FORCE_LOGOFF_PARMNUM)
#define MODALS_PASSWD_HIST_LEN_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+MODALS_PASSWD_HIST_LEN_PARMNUM)
#define MODALS_ROLE_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+MODALS_ROLE_PARMNUM)
#define MODALS_PRIMARY_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+MODALS_PRIMARY_PARMNUM)
#define MODALS_DOMAIN_NAME_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+MODALS_DOMAIN_NAME_PARMNUM)
#define MODALS_DOMAIN_ID_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+MODALS_DOMAIN_ID_PARMNUM)

#define GROUPIDMASK  0x8000

#define GROUP_ALL_PARMNUM  0
#define GROUP_NAME_PARMNUM  1
#define GROUP_COMMENT_PARMNUM  2
#define GROUP_ATTRIBUTES_PARMNUM  3

#define GROUP_ALL_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+GROUP_ALL_PARMNUM)
#define GROUP_NAME_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+GROUP_NAME_PARMNUM)
#define GROUP_COMMENT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+GROUP_COMMENT_PARMNUM)
#define GROUP_ATTRIBUTES_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+GROUP_ATTRIBUTES_PARMNUM)
#define GROUP_POSIX_ID_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+GROUP_POSIX_ID_PARMNUM)

#define LOCALGROUP_NAME_PARMNUM  1
#define LOCALGROUP_COMMENT_PARMNUM  2

#define MAXPERMENTRIES  64

#define ACCESS_NONE  0
#define ACCESS_ALL  (ACCESS_READ|ACCESS_WRITE|ACCESS_CREATE|ACCESS_EXEC|ACCESS_DELETE|ACCESS_ATRIB|ACCESS_PERM)
#define ACCESS_READ  0x01
#define ACCESS_WRITE  0x02
#define ACCESS_CREATE  0x04
#define ACCESS_EXEC  0x08
#define ACCESS_DELETE  0x10
#define ACCESS_ATRIB  0x20
#define ACCESS_PERM  0x40

#define ACCESS_GROUP  0x8000

#define ACCESS_AUDIT  1

#define ACCESS_SUCCESS_OPEN  0x10
#define ACCESS_SUCCESS_WRITE  0x20
#define ACCESS_SUCCESS_DELETE  0x40
#define ACCESS_SUCCESS_ACL  0x80
#define ACCESS_SUCCESS_MASK  0xF0

#define ACCESS_FAIL_OPEN  0x100
#define ACCESS_FAIL_WRITE  0x200
#define ACCESS_FAIL_DELETE  0x400
#define ACCESS_FAIL_ACL  0x800
#define ACCESS_FAIL_MASK  0xF00

#define ACCESS_FAIL_SHIFT  4

#define ACCESS_RESOURCE_NAME_PARMNUM  1
#define ACCESS_ATTR_PARMNUM  2
#define ACCESS_COUNT_PARMNUM  3
#define ACCESS_ACCESS_LIST_PARMNUM  4

#define ACCESS_RESOURCE_NAME_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+ACCESS_RESOURCE_NAME_PARMNUM)
#define ACCESS_ATTR_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+ACCESS_ATTR_PARMNUM)
#define ACCESS_COUNT_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+ACCESS_COUNT_PARMNUM)
#define ACCESS_ACCESS_LIST_INFOLEVEL  (PARMNUM_BASE_INFOLEVEL+ACCESS_ACCESS_LIST_PARMNUM)

#define NETLOGON_CONTROL_QUERY  1
#define NETLOGON_CONTROL_REPLICATE  2
#define NETLOGON_CONTROL_SYNCHRONIZE  3
#define NETLOGON_CONTROL_PDC_REPLICATE  4
#define NETLOGON_CONTROL_REDISCOVER  5
#define NETLOGON_CONTROL_TC_QUERY  6
#define NETLOGON_CONTROL_TRANSPORT_NOTIFY  7
#define NETLOGON_CONTROL_FIND_USER  8
#define NETLOGON_CONTROL_CHANGE_PASSWORD  9

#define NETLOGON_CONTROL_UNLOAD_NETLOGON_DLL  0xFFFB
#define NETLOGON_CONTROL_BACKUP_CHANGE_LOG  0xFFFC
#define NETLOGON_CONTROL_TRUNCATE_LOG  0xFFFD
#define NETLOGON_CONTROL_SET_DBFLAG  0xFFFE
#define NETLOGON_CONTROL_BREAKPOINT  0xFFFF

#define NETLOGON_REPLICATION_NEEDED  0x01
#define NETLOGON_REPLICATION_IN_PROGRESS  0x02
#define NETLOGON_FULL_SYNC_REPLICATION  0x04
#define NETLOGON_REDO_NEEDED  0x08
#define NETLOGON_HAS_IP  0x10
#define NETLOGON_HAS_TIMESERV  0x20

USER_INFO_0 STRUCT
	usri0_name PTR
ENDS

USER_INFO_1 STRUCT
	usri1_name PTR
	usri1_password PTR
	usri1_password_age DD
	usri1_priv DD
	usri1_home_dir PTR
	usri1_comment PTR
	usri1_flags DD
	usri1_script_path PTR
ENDS

USER_INFO_2 STRUCT
	usri2_name PTR
	usri2_password PTR
	usri2_password_age DD
	usri2_priv DD
	usri2_home_dir PTR
	usri2_comment PTR
	usri2_flags DD
	usri2_script_path PTR
	usri2_auth_flags DD
	usri2_full_name PTR
	usri2_usr_comment PTR
	usri2_parms PTR
	usri2_workstations PTR
	usri2_last_logon DD
	usri2_last_logoff DD
	usri2_acct_expires DD
	usri2_max_storage DD
	usri2_units_per_week DD
	usri2_logon_hours PTR
	usri2_bad_pw_count DD
	usri2_num_logons DD
	usri2_logon_server PTR
	usri2_country_code DD
	usri2_code_page DD
ENDS

USER_INFO_3 STRUCT
	usri3_name PTR
	usri3_password PTR
	usri3_password_age DD
	usri3_priv DD
	usri3_home_dir PTR
	usri3_comment PTR
	usri3_flags DD
	usri3_script_path PTR
	usri3_auth_flags DD
	usri3_full_name PTR
	usri3_usr_comment PTR
	usri3_parms PTR
	usri3_workstations PTR
	usri3_last_logon DD
	usri3_last_logoff DD
	usri3_acct_expires DD
	usri3_max_storage DD
	usri3_units_per_week DD
	usri3_logon_hours PTR
	usri3_bad_pw_count DD
	usri3_num_logons DD
	usri3_logon_server PTR
	usri3_country_code DD
	usri3_code_page DD
	usri3_user_id DD
	usri3_primary_group_id DD
	usri3_profile PTR
	usri3_home_dir_drive PTR
	usri3_password_expired DD
ENDS

USER_INFO_4 STRUCT
	usri4_name PTR
	usri4_password PTR
	usri4_password_age DD
	usri4_priv DD
	usri4_home_dir PTR
	usri4_comment PTR
	usri4_flags DD
	usri4_script_path PTR
	usri4_auth_flags DD
	usri4_full_name PTR
	usri4_usr_comment PTR
	usri4_parms PTR
	usri4_workstations PTR
	usri4_last_logon DD
	usri4_last_logoff DD
	usri4_acct_expires DD
	usri4_max_storage DD
	usri4_units_per_week DD
	usri4_logon_hours PTR
	usri4_bad_pw_count DD
	usri4_num_logons DD
	usri4_logon_server PTR
	usri4_country_code DD
	usri4_code_page DD
	usri4_user_sid PTR
	usri4_primary_group_id DD
	usri4_profile PTR
	usri4_home_dir_drive PTR
	usri4_password_expired DD
ENDS

USER_INFO_10 STRUCT
	usri10_name PTR
	usri10_comment PTR
	usri10_usr_comment PTR
	usri10_full_name PTR
ENDS

USER_INFO_11 STRUCT
	usri11_name PTR
	usri11_comment PTR
	usri11_usr_comment PTR
	usri11_full_name PTR
	usri11_priv DD
	usri11_auth_flags DD
	usri11_password_age DD
	usri11_home_dir PTR
	usri11_parms PTR
	usri11_last_logon DD
	usri11_last_logoff DD
	usri11_bad_pw_count DD
	usri11_num_logons DD
	usri11_logon_server PTR
	usri11_country_code DD
	usri11_workstations PTR
	usri11_max_storage DD
	usri11_units_per_week DD
	usri11_logon_hours PTR
	usri11_code_page DD
ENDS

USER_INFO_20 STRUCT
	usri20_name PTR
	usri20_full_name PTR
	usri20_comment PTR
	usri20_flags DD
	usri20_user_id DD
ENDS

USER_INFO_21 STRUCT
	useri21_password DB ENCRYPTED_PWLEN DUP
ENDS

USER_INFO_22 STRUCT
	usri22_name PTR
	usri22_password DB ENCRYPTED_PWLEN DUP
	usri22_password_age DD
	usri22_priv DD
	usri22_home_dir PTR
	usri22_comment PTR
	usri22_flags DD
	usri22_script_path PTR
	usri22_auth_flags DD
	usri22_full_name PTR
	usri22_usr_comment PTR
	usri22_parms PTR
	usri22_workstations PTR
	usri22_last_logon DD
	usri22_last_logoff DD
	usri22_acct_expires DD
	usri22_max_storage DD
	usri22_units_per_week DD
	usri22_logon_hours PTR
	usri22_bad_pw_count DD
	usri22_num_logons DD
	usri22_logon_server PTR
	usri22_country_code DD
	usri22_code_page DD
ENDS

USER_INFO_23 STRUCT
	usri23_name PTR
	usri23_full_name PTR
	usri23_comment PTR
	usri23_flags DD
	usri23_user_sid PTR
ENDS

USER_INFO_1003 STRUCT
	usri1003_password PTR
ENDS

USER_INFO_1005 STRUCT
	usri1005_priv DD
ENDS

USER_INFO_1006 STRUCT
	usri1006_home_dir PTR
ENDS

USER_INFO_1007 STRUCT
	usri1007_comment PTR
ENDS

USER_INFO_1008 STRUCT
	usri1008_flags DD
ENDS

USER_INFO_1009 STRUCT
	usri1009_script_path PTR
ENDS

USER_INFO_1010 STRUCT
	usri1010_auth_flags DD
ENDS

USER_INFO_1011 STRUCT
	usri1011_full_name PTR
ENDS

USER_INFO_1012 STRUCT
	usri1012_usr_comment PTR
ENDS

USER_INFO_1013 STRUCT
	usri1013_parms PTR
ENDS

USER_INFO_1014 STRUCT
	usri1014_workstations PTR
ENDS

USER_INFO_1017 STRUCT
	usri1017_acct_expires DD
ENDS

USER_INFO_1018 STRUCT
	usri1018_max_storage DD
ENDS

USER_INFO_1020 STRUCT
	usri1020_units_per_week DD
	usri1020_logon_hours PTR
ENDS

USER_INFO_1023 STRUCT
	usri1023_logon_server PTR
ENDS

USER_INFO_1024 STRUCT
	usri1024_country_code DD
ENDS

USER_INFO_1025 STRUCT
	usri1025_code_page DD
ENDS

USER_INFO_1051 STRUCT
	usri1051_primary_group_id DD
ENDS

USER_INFO_1052 STRUCT
	usri1052_profile PTR
ENDS

USER_INFO_1053 STRUCT
	usri1053_home_dir_drive PTR
ENDS

USER_MODALS_INFO_0 STRUCT
	usrmod0_min_passwd_len DD
	usrmod0_max_passwd_age DD
	usrmod0_min_passwd_age DD
	usrmod0_force_logoff DD
	usrmod0_password_hist_len DD
ENDS

USER_MODALS_INFO_1 STRUCT
	usrmod1_role DD
	usrmod1_primary PTR
ENDS

USER_MODALS_INFO_2 STRUCT
	usrmod2_domain_name PTR
	usrmod2_domain_id PTR
ENDS

USER_MODALS_INFO_3 STRUCT
	usrmod3_lockout_duration DD
	usrmod3_lockout_observation_window DD
	usrmod3_lockout_threshold DD
ENDS

USER_MODALS_INFO_1001 STRUCT
	usrmod1001_min_passwd_len DD
ENDS

USER_MODALS_INFO_1002 STRUCT
	usrmod1002_max_passwd_age DD
ENDS

USER_MODALS_INFO_1003 STRUCT
	usrmod1003_min_passwd_age DD
ENDS

USER_MODALS_INFO_1004 STRUCT
	usrmod1004_force_logoff DD
ENDS

USER_MODALS_INFO_1005 STRUCT
	usrmod1005_password_hist_len DD
ENDS

USER_MODALS_INFO_1006 STRUCT
	usrmod1006_role DD
ENDS

USER_MODALS_INFO_1007 STRUCT
	usrmod1007_primary PTR
ENDS

GROUP_INFO_0 STRUCT
	grpi0_name PTR
ENDS

GROUP_INFO_1 STRUCT
	grpi1_name PTR
	grpi1_comment PTR
ENDS

GROUP_INFO_2 STRUCT
	grpi2_name PTR
	grpi2_comment PTR
	grpi2_group_id DD
	grpi2_attributes DD
ENDS

GROUP_INFO_3 STRUCT
	grpi3_name PTR
	grpi3_comment PTR
	grpi3_group_sid PTR
	grpi3_attributes DD
ENDS

GROUP_INFO_1002 STRUCT
	grpi1002_comment PTR
ENDS

GROUP_INFO_1005 STRUCT
	grpi1005_attributes DD
ENDS

GROUP_USERS_INFO_0 STRUCT
	grui0_name PTR
ENDS

GROUP_USERS_INFO_1 STRUCT
	grui1_name PTR
	grui1_attributes DD
ENDS

LOCALGROUP_INFO_0 STRUCT
	lgrpi0_name PTR
ENDS

LOCALGROUP_INFO_1 STRUCT
	lgrpi1_name PTR
	lgrpi1_comment PTR
ENDS

LOCALGROUP_INFO_1002 STRUCT
	lgrpi1002_comment PTR
ENDS

LOCALGROUP_MEMBERS_INFO_0 STRUCT
	lgrmi0_sid PTR
ENDS

LOCALGROUP_MEMBERS_INFO_1 STRUCT
	lgrmi1_sid DD
	lgrmi1_sidusage SID_NAME_USE
	lgrmi1_name PTR
ENDS

LOCALGROUP_MEMBERS_INFO_2 STRUCT
	lgrmi2_sid PTR
	lgrmi2_sidusage SID_NAME_USE
	lgrmi2_domainandname PTR
ENDS

LOCALGROUP_MEMBERS_INFO_3 STRUCT
	lgrmi3_domainandname PTR
ENDS

LOCALGROUP_USERS_INFO_0 STRUCT
	lgrui0_name PTR
ENDS

NET_DISPLAY_USER STRUCT
	usri1_name PTR
	usri1_comment PTR
	usri1_flags DD
	usri1_full_name PTR
	usri1_user_id DD
	usri1_next_index DD
ENDS

NET_DISPLAY_MACHINE STRUCT
	usri2_name PTR
	usri2_comment PTR
	usri2_flags DD
	usri2_user_id DD
	usri2_next_index DD
ENDS

NET_DISPLAY_GROUP STRUCT
	grpi3_name PTR
	grpi3_comment PTR
	grpi3_group_id DD
	grpi3_attributes DD
	grpi3_next_index DD
ENDS

ACCESS_INFO_0 STRUCT
	acc0_resource_name PTR
ENDS

ACCESS_INFO_1 STRUCT
	acc1_resource_name PTR
	acc1_attr DD
	acc1_count DD
ENDS

ACCESS_INFO_1002 STRUCT
	acc1002_attr DD
ENDS

ACCESS_LIST STRUCT
	acl_ugname PTR
	acl_access DD
ENDS

NETLOGON_INFO_1 STRUCT
	netlog1_flags DD
	netlog1_pdc_connection_status DD
ENDS

NETLOGON_INFO_2 STRUCT
	netlog2_flags DD
	netlog2_pdc_connection_status
	netlog2_trusted_dc_name PTR
	netlog2_tc_connection_status
ENDS

NETLOGON_INFO_3 STRUCT
	netlog3_flags DD
	netlog3_logon_attempts DD
	netlog3_reserved1 DD
	netlog3_reserved2 DD
	netlog3_reserved3 DD
	netlog3_reserved4 DD
	netlog3_reserved5 DD
ENDS

NETLOGON_INFO_4 STRUCT
	netlog4_trusted_dc_name PTR
	netlog4_trusted_domain_name PTR
ENDS

#define NetAccessAdd RxNetAccessAdd
#define NetAccessEnum RxNetAccessEnum
#define NetAccessGetInfo RxNetAccessGetInfo
#define NetAccessSetInfo RxNetAccessSetInfo
#define NetAccessDel RxNetAccessDel
#define NetAccessGetUserPerms RxNetAccessGetUserPerms

#endif /* _LMACCESS_H */
