#ifndef NMEVENT_H
#define NMEVENT_H

/* Microsoft Network Monitor Events definitions */

#IFNDEF NPPTYPES_H
	#include "npptypes.h"
#ENDIF

#define NMEVENTFLAG_MONITOR  0x00000000
#define NMEVENTFLAG_EXPERT  0x00000001

#define NMEVENTFLAG_DO_NOT_DISPLAY_SEVERITY  0x80000000
#define NMEVENTFLAG_DO_NOT_DISPLAY_SOURCE  0x40000000
#define NMEVENTFLAG_DO_NOT_DISPLAY_EVENT_NAME  0x20000000
#define NMEVENTFLAG_DO_NOT_DISPLAY_DESCRIPTION  0x10000000
#define NMEVENTFLAG_DO_NOT_DISPLAY_MACHINE  0x08000000
#define NMEVENTFLAG_DO_NOT_DISPLAY_TIME  0x04000000
#define NMEVENTFLAG_DO_NOT_DISPLAY_DATE  0x02000000
#define NMEVENTFLAG_DO_NOT_DISPLAY_FIXED_COLUMNS 0xFE000000

NMCOLUMNTYPE_UINT8 = 0
NMCOLUMNTYPE_SINT8 = 1 
NMCOLUMNTYPE_UINT16 = 2
NMCOLUMNTYPE_SINT16 = 3
NMCOLUMNTYPE_UINT32 = 4
NMCOLUMNTYPE_SINT32 = 5
NMCOLUMNTYPE_FLOAT64 = 6
NMCOLUMNTYPE_FRAME = 7
NMCOLUMNTYPE_YESNO = 8
NMCOLUMNTYPE_ONOFF = 9
NMCOLUMNTYPE_TRUEFALSE = 10
NMCOLUMNTYPE_MACADDR = 11
NMCOLUMNTYPE_IPXADDR= 12
NMCOLUMNTYPE_IPADDR = 13
NMCOLUMNTYPE_VARTIME 14
NMCOLUMNTYPE_STRING = 15

NMCOLUMNVARIANT  STRUCT
	Type DD
	UNION
		Uint8Val DB
		Sint8Val DB
		Uint16Val DW
		Sint16Val DW
		Uint32Val DD
		Sint32Val DD
		Float64Val DQ
		FrameVal DD
		YesNoVal DD
		OnOffVal DD
		TrueFalseVal DD
		MACAddrVal DB MAC_ADDRESS_SIZE DUP
		IPXAddrVal IPX_ADDRESS
		IPAddrVal DD
		VarTimeVal DQ
		pStringVal PTR
	ENDUNION
ENDS

NMCOLUMNINFO STRUCT
	szColumnName PTR
	VariantData NMCOLUMNVARIANT
ENDS

NMEVENTDATA STRUCT
;	pszReserved DD
	Version DB
	EventIdent DD
	Flags DD
	Severity DD
	NumColumns DB
	szSourceName PTR
	szEventName PTR
	szDescription PTR
	szMachine PTR
	Justification DD
	szUrl PTR
	SysTime SYSTEMTIME
	Column NMCOLUMNINFO
ENDS

NMEVENT_SEVERITY_INFORMATIONAL = 0
NMEVENT_SEVERITY_WARNING = 1
NMEVENT_SEVERITY_STRONG_WARNING = 2
NMEVENT_SEVERITY_ERROR = 3
NMEVENT_SEVERITY_SEVERE_ERROR = 4
NMEVENT_SEVERITY_CRITICAL_ERROR = 5

#endif /* _NMEVENT_H */
