
#ifndef NTDDSTOR_H
#define NTDDSTOR_H

#define METHOD_BUFFERED  0
#define METHOD_IN_DIRECT  1
#define METHOD_OUT_DIRECT  2
#define METHOD_NEITHER  3

#define FILE_ANY_ACCESS  0
#define FILE_SPECIAL_ACCESS  (FILE_ANY_ACCESS)
#define FILE_READ_ACCESS  0x0001
#define FILE_WRITE_ACCESS  0x0002

#define IOCTL_STORAGE_BASE FILE_DEVICE_MASS_STORAGE
#define IOCTL_STORAGE_CHECK_VERIFY  (IOCTL_STORAGE_BASE<<16)|(0x0200<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_CHECK_VERIFY2  (IOCTL_STORAGE_BASE<<16)|(0x0200<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_MEDIA_REMOVAL  (IOCTL_STORAGE_BASE<<16)|(0x0201<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_EJECT_MEDIA  (IOCTL_STORAGE_BASE<<16)|(0x0202<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_LOAD_MEDIA  (IOCTL_STORAGE_BASE<<16)|(0x0203<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_LOAD_MEDIA2  (IOCTL_STORAGE_BASE<<16)|(0x0203<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_RESERVE  (IOCTL_STORAGE_BASE<<16)|(0x0204<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_RELEASE  (IOCTL_STORAGE_BASE<<16)|(0x0205<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_FIND_NEW_DEVICES  (IOCTL_STORAGE_BASE<<16)|(0x0206<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_EJECTION_CONTROL  (IOCTL_STORAGE_BASE<<16)|(0x0250<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_MCN_CONTROL  (IOCTL_STORAGE_BASE<<16)|(0x0251<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_GET_MEDIA_TYPES  (IOCTL_STORAGE_BASE<<16)|(0x0300<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_GET_MEDIA_TYPES_EX  (IOCTL_STORAGE_BASE<<16)|(0x0301<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_RESET_BUS  (IOCTL_STORAGE_BASE<<16)|(0x0400<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_RESET_DEVICE  (IOCTL_STORAGE_BASE<<16)|(0x0401<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_GET_DEVICE_NUMBER  (IOCTL_STORAGE_BASE<<16)|(0x0420<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_PREDICT_FAILURE  (IOCTL_STORAGE_BASE<<16)|(0x0440<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_BREAK_RESERVATION (IOCTL_STORAGE_BASE<<16)|(0x0405<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_STORAGE_PERSISTENT_RESERVE_IN (IOCTL_STORAGE_BASE<<16)|(0x0406<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_STORAGE_PERSISTENT_RESERVE_OUT (IOCTL_STORAGE_BASE<<16)|(0x0407<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_STORAGE_READ_CAPACITY (IOCTL_STORAGE_BASE<<16)|(0x0450<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_QUERY_PROPERTY   CTL_CODE(IOCTL_STORAGE_BASE, 0x0500, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STORAGE_GET_BC_PROPERTIES (IOCTL_STORAGE_BASE<<16)|(0x0600<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_ALLOCATE_BC_STREAM (IOCTL_STORAGE_BASE<<16)|(0x0601<<2)|METHOD_BUFFERED|((FILE_READ_ACCESS | FILE_WRITE_ACCESS)<<14)
#define IOCTL_STORAGE_FREE_BC_STREAM  (IOCTL_STORAGE_BASE<<16)|(0x0602<<2)|METHOD_BUFFERED|((FILE_READ_ACCESS | FILE_WRITE_ACCESS)<<14)
#define IOCTL_STORAGE_CHECK_PRIORITY_HINT_SUPPORT (IOCTL_STORAGE_BASE<<16)|(0x0620<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)

#DEFINE GUID_DEVINTERFACE_DISK <0x53f56307, 0xb6bf, 0x11d0, <0x94, 0xf2, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>
#DEFINE GUID_DEVINTERFACE_CDROM <0x53f56308, 0xb6bf, 0x11d0, <0x94, 0xf2, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>
#DEFINE GUID_DEVINTERFACE_PARTITION <0x53f5630a, 0xb6bf, 0x11d0, <0x94, 0xf2, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>
#DEFINE GUID_DEVINTERFACE_TAPE <0x53f5630b, 0xb6bf, 0x11d0, <0x94, 0xf2, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>
#DEFINE GUID_DEVINTERFACE_WRITEONCEDISK <0x53f5630c, 0xb6bf, 0x11d0, <0x94, 0xf2, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>
#DEFINE GUID_DEVINTERFACE_VOLUME <0x53f5630d, 0xb6bf, 0x11d0, <0x94, 0xf2, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>
#DEFINE GUID_DEVINTERFACE_MEDIUMCHANGER <0x53f56310, 0xb6bf, 0x11d0, <0x94, 0xf2, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>
#DEFINE GUID_DEVINTERFACE_FLOPPY <0x53f56311, 0xb6bf, 0x11d0, <0x94, 0xf2, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>
#DEFINE GUID_DEVINTERFACE_CDCHANGER <0x53f56312, 0xb6bf, 0x11d0, <0x94, 0xf2, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>
#DEFINE GUID_DEVINTERFACE_STORAGEPORT <0x2accfe60, 0xc130, 0x11d2, <0xb0, 0x82, 0x00, 0xa0, 0xc9, 0x1e, 0xfb, 0x8b>>

#DEFINE STORAGE_MEDIA_TYPE DD
#DEFINE STORAGE_BUS_TYPE DD

DDS_4mm = 32
MiniQic = 33
Travan = 34
QIC = 35
MP_8mm = 36
AME_8mm = 37
AIT1_8mm = 38
DLT = 39
NCTP = 40
IBM_3480 = 41
IBM_3490E = 42
IBM_Magstar_3590 = 43
IBM_Magstar_MP = 44
STK_DATA_D3 = 45
SONY_DTF = 46
DV_6mm = 47
DMI = 48
SONY_D2 = 49
CLEANER_CARTRIDGE = 50
CD_ROM = 51
CD_R = 52
CD_RW = 53
DVD_ROM = 54
DVD_R = 55
DVD_RW = 56
MO_3_RW = 57
MO_5_WO = 58
MO_5_RW = 59
MO_5_LIMDOW = 60
PC_5_WO = 61
PC_5_RW = 62
PD_5_RW = 63
ABL_5_WO = 64
PINNACLE_APEX_5_RW = 65
SONY_12_WO = 66
PHILIPS_12_WO = 67
HITACHI_12_WO = 68
CYGNET_12_WO = 69
KODAK_14_WO = 70
MO_NFR_525 = 71
NIKON_12_RW = 72
IOMEGA_ZIP = 73
IOMEGA_JAZ = 74
SYQUEST_EZ135 = 75
SYQUEST_EZFLYER = 76
SYQUEST_SYJET = 77
AVATAR_F2 = 78
MP2_8mm = 79
DST_S = 80
DST_M = 81
DST_L = 82
VXATape_1 = 83
VXATape_2 = 84
STK_9840 = 85
STK_EAGLE = 85
LTO_Ultrium = 86
LTO_Accelis = 87
DVD_RAM = 88
AIT_8mm = 89
ADR_1 = 90
ADR_2 = 91
STK_9940 = 92
SAIT = 93
VXATape = 94

// Not sure what size this enum should be
#DEFINE STORAGE_BUS_TYPE DB

BusTypeUnknown = 0
BusTypeScsi = 1
BusTypeAtapi = 2
BusTypeAta = 3
BusType1394 = 4
BusTypeSsa = 5
BusTypeFibre = 6
BusTypeUsb = 7
BusTypeRAID = 8
BusTypeiScsi = 9
BusTypeSas = 10
BusTypeSata = 11
BusTypeSd = 12
BusTypeMmc = 13
BusTypeMax = 14
BusTypeMaxReserved = 0x7F

/* DEVICE_MEDIA_INFO.DeviceSpecific.DiskInfo.MediaCharacteristics constants */
#define MEDIA_ERASEABLE                   0x00000001
#define MEDIA_WRITE_ONCE                  0x00000002
#define MEDIA_READ_ONLY                   0x00000004
#define MEDIA_READ_WRITE                  0x00000008
#define MEDIA_WRITE_PROTECTED             0x00000100
#define MEDIA_CURRENTLY_MOUNTED           0x80000000

DEVICE_MEDIA_INFO STRUCT
	UNION
		DiskInfo STRUCT
			Cylinders LARGE_INTEGER
			MediaType DD
			TracksPerCylinder DD
			SectorsPerTrack DD
			BytesPerSector DD
			NumberMediaSides DD
			MediaCharacteristics DD
		ENDS
		RemovableDiskInfo STRUCT
			Cylinders LARGE_INTEGER
			MediaType DD
			TracksPerCylinder DD
			SectorsPerTrack DD
			BytesPerSector DD
			NumberMediaSides DD
			MediaCharacteristics DD
		ENDS
		TapeInfo STRUCT
			MediaType DD
			MediaCharacteristics DD
			CurrentBlockSize DD
			BusType DD
			ScsiInformation STRUCT
				MediumType DB
				DensityCode DB
			ENDS
		ENDS
	ENDUNION
ENDS

GET_MEDIA_TYPES STRUCT
	DeviceType DD
	MediaInfoCount DD
	MediaInfo DEVICE_MEDIA_INFO <>
ENDS

STORAGE_PREDICT_FAILURE STRUCT
	PredictFailure DD
	VendorSpecific DB 512 DUP (?)
ENDS

STORAGE_ADAPTER_DESCRIPTOR STRUCT
	Version DD
	Size DD
	MaximumTransferLength DD
	MaximumPhysicalPages DD
	AlignmentMask DD
	AdapterUsesPio BOOLEAN
	AdapterScansDown BOOLEAN
	CommandQueueing BOOLEAN
	AcceleratedTransfer BOOLEAN
	BusType STORAGE_BUS_TYPE
	BusMajorVersion DW
	BusMinorVersion DW
ENDS

STORAGE_ACCESS_ALIGNMENT_DESCRIPTOR STRUCT
	Version DD
	Size DD
	BytesPerCacheLine DD
	BytesOffsetForCacheAlignment DD
	BytesPerLogicalSector DD
	BytesPerPhysicalSector DD
	BytesOffsetForSectorAlignment DD
ENDS

STORAGE_BUS_RESET_REQUEST STRUCT
	PathId DB
ENDS

STORAGE_DESCRIPTOR_HEADER STRUCT
	Version DD
	Size DD
ENDS

STORAGE_DEVICE_DESCRIPTOR STRUCT
	Version DD
	Size DD
	DeviceType DB
	DeviceTypeModifier DB
	RemovableMedia BOOLEAN
	CommandQueueing BOOLEAN
	VendorIdOffset DD
	ProductIdOffset DD
	ProductRevisionOffset DD
	SerialNumberOffset DD
	BusType STORAGE_BUS_TYPE
	RawPropertiesLength DD
	RawDeviceProperties DB
ENDS

STORAGE_DEVICE_ID_DESCRIPTOR STRUCT
	Version DD
	Size DD
	NumberOfIdentifiers DD
	Identifiers DB
ENDS

STORAGE_DEVICE_NUMBER STRUCT
	DeviceType DD
	DeviceNumber DD
	PartitionNumber DD
ENDS

StorageDeviceProperty = 0
StorageAdapterProperty = 1
StorageDeviceIdProperty = 2

PropertyStandardQuery = 0
PropertyExistsQuery = 1
PropertyMaskQuery = 2
PropertyQueryMaxDefined = 3

STORAGE_PROPERTY_QUERY STRUCT
	PropertyId DD
	QueryType DD
	AdditionalParameters DB
ENDS

#endif /* __NTDDSTOR_H */
