#ifndef URLMON_H
#define URLMON_H

#IFDEF LINKFILES
	#dynamiclinkfile urlmon.dll
#ENDIF

#IFNDEF RPC_H
	#include "rpc.h"
#ENDIF

#IFNDEF RPCNDR_H
	#include "rpcndr.h"
#ENDIF

#ifndef COM_NO_WINDOWS_H
	#IFNDEF WINDOWS_H
		#include "windows.h"
	#ENDIF
	#IFNDEF OLE2_H
		#include "ole2.h"
	#ENDIF
#endif /* COM_NO_WINDOWS_H */

#ifndef OBJIDL_H
	#include "objidl.h"
#ENDIF

#ifndef OLEIDL_H
	#include "oleidl.h"
#ENDIF

#IFNDEF SERVPROV_H
	#include "servprov.h"
#ENDIF

#IFNDEF MSXML_H
	#include "msxml.h"
#ENDIF

#IFNDEF BASECOM_H
	#include "BaseCOM.h"
#ENDIF

#define BINDF_DONTUSECACHE  BINDF_GETNEWESTVERSION
#define BINDF_DONTPUTINCACHE  BINDF_NOWRITECACHE
#define BINDF_NOCOPYDATA  BINDF_PULLDATA
#define PI_DOCFILECLSIDLOOKUP  PI_CLSIDLOOKUP

#define SZ_URLCONTEXT  "URL Context"
#define SZ_ASYNC_CALLEE  "AsyncCallee"
#define MKSYS_URLMONIKER  6

#define FIEF_FLAG_FORCE_JITUI  0x1
#define FIEF_FLAG_PEEK  0x2
#define FIEF_FLAG_SKIP_INSTALLED_VERSION_CHECK  0x4

#define FMFD_DEFAULT  0x00000000
#define FMFD_URLASFILENAME  0x00000001

#define URLMON_OPTION_USERAGENT  0x10000001
#define URLMON_OPTION_USERAGENT_REFRESH 0x10000002
#define URLMON_OPTION_URL_ENCODING  0x10000004

#define CF_NULL  0

#define CFSTR_MIME_NULL  NULL
#define CFSTR_MIME_TEXT  "text/plain"
#define CFSTR_MIME_RICHTEXT  "text/richtext"
#define CFSTR_MIME_X_BITMAP  "image/x-xbitmap"
#define CFSTR_MIME_POSTSCRIPT  "application/postscript"
#define CFSTR_MIME_AIFF  "audio/aiff"
#define CFSTR_MIME_BASICAUDIO  "audio/basic"
#define CFSTR_MIME_WAV  "audio/wav"
#define CFSTR_MIME_X_WAV  "audio/x-wav"
#define CFSTR_MIME_GIF  "image/gif"
#define CFSTR_MIME_PJPEG  "image/pjpeg"
#define CFSTR_MIME_JPEG  "image/jpeg"
#define CFSTR_MIME_TIFF  "image/tiff"
#define CFSTR_MIME_X_PNG  "image/x-png"
#define CFSTR_MIME_BMP  "image/bmp"
#define CFSTR_MIME_X_ART  "image/x-jg"
#define CFSTR_MIME_X_EMF  "image/x-emf"
#define CFSTR_MIME_X_WMF  "image/x-wmf"
#define CFSTR_MIME_AVI  "video/avi"
#define CFSTR_MIME_MPEG  "video/mpeg"
#define CFSTR_MIME_FRACTALS  "application/fractals"
#define CFSTR_MIME_RAWDATA  "application/octet-stream"
#define CFSTR_MIME_RAWDATASTRM  "application/octet-stream"
#define CFSTR_MIME_PDF  "application/pdf"
#define CFSTR_MIME_X_AIFF  "audio/x-aiff"
#define CFSTR_MIME_X_REALAUDIO  "audio/x-pn-realaudio"
#define CFSTR_MIME_XBM  "image/xbm"
#define CFSTR_MIME_QUICKTIME  "video/quicktime"
#define CFSTR_MIME_X_MSVIDEO  "video/x-msvideo"
#define CFSTR_MIME_X_SGI_MOVIE  "video/x-sgi-movie"
#define CFSTR_MIME_HTML  "text/html"

#define MK_S_ASYNCHRONOUS 0x000401E8

#ifndef S_ASYNCHRONOUS
	#define S_ASYNCHRONOUS  MK_S_ASYNCHRONOUS
#endif

#ifndef E_PENDING
	#define E_PENDING 0x8000000A
#endif

#define INET_E_INVALID_URL  0x800C0002
#define INET_E_NO_SESSION  0x800C0003
#define INET_E_CANNOT_CONNECT  0x800C0004
#define INET_E_RESOURCE_NOT_FOUND  0x800C0005
#define INET_E_OBJECT_NOT_FOUND  0x800C0006
#define INET_E_DATA_NOT_AVAILABLE  0x800C0007
#define INET_E_DOWNLOAD_FAILURE  0x800C0008
#define INET_E_AUTHENTICATION_REQUIRED  0x800C0009
#define INET_E_NO_VALID_MEDIA  0x800C000A
#define INET_E_CONNECTION_TIMEOUT  0x800C000B
#define INET_E_INVALID_REQUEST  0x800C000C
#define INET_E_UNKNOWN_PROTOCOL  0x800C000D
#define INET_E_SECURITY_PROBLEM  0x800C000E
#define INET_E_CANNOT_LOAD_DATA  0x800C000F
#define INET_E_CANNOT_INSTANTIATE_OBJECT  0x800C0010
#define INET_E_REDIRECT_FAILED  0x800C0014
#define INET_E_REDIRECT_TO_DIR  0x800C0015
#define INET_E_CANNOT_LOCK_REQUEST  0x800C0016
#define INET_E_USE_EXTEND_BINDING  0x800C0017
#define INET_E_ERROR_FIRST  0x800C0002
#define INET_E_ERROR_LAST  INET_E_USE_EXTEND_BINDING
#define INET_E_CODE_DOWNLOAD_DECLINED  0x800C0100
#define INET_E_RESULT_DISPATCHED  0x800C0200
#define INET_E_CANNOT_REPLACE_SFP_FILE  0x800C0300

#define GUID_IID_IPersistMoniker <0x79eac9c9,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IPersistMoniker STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetClassID PTR
	IsDirty PTR
	Load PTR
	Save PTR
	SaveCompleted PTR
	GetCurMoniker PTR
ENDS

#define GUID_IID_IBindProtocol <0x79eac9cd,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IBindProtocol STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	CreateBinding PTR
ENDS

BINDVERB_GET = 0
BINDVERB_POST = 0x1
BINDVERB_PUT = 0x2
BINDVERB_CUSTOM = 0x3

BINDINFOF_URLENCODESTGMEDDATA = 0x1
BINDINFOF_URLENCODEDEXTRAINFO = 0x2

BINDF_ASYNCHRONOUS = 0x1
BINDF_ASYNCSTORAGE = 0x2
BINDF_NOPROGRESSIVERENDERING = 0x4
BINDF_OFFLINEOPERATION = 0x8
BINDF_GETNEWESTVERSION = 0x10
BINDF_NOWRITECACHE = 0x20
BINDF_NEEDFILE = 0x40
BINDF_PULLDATA = 0x80
BINDF_IGNORESECURITYPROBLEM = 0x100
BINDF_RESYNCHRONIZE = 0x200
BINDF_HYPERLINK = 0x400
BINDF_NO_UI = 0x800
BINDF_SILENTOPERATION = 0x1000
BINDF_PRAGMA_NO_CACHE = 0x2000
BINDF_GETCLASSOBJECT = 0x4000
BINDF_RESERVED_1 = 0x8000
BINDF_FREE_THREADED = 0x10000
BINDF_DIRECT_READ = 0x20000
BINDF_FORMS_SUBMIT = 0x40000
BINDF_GETFROMCACHE_IF_NET_FAIL = 0x80000
BINDF_FROMURLMON = 0x100000
BINDF_FWD_BACK = 0x200000
BINDF_RESERVED_2 = 0x400000
BINDF_RESERVED_3 = 0x800000

URL_ENCODING_NONE = 0
URL_ENCODING_ENABLE_UTF8 = 0x10000000
URL_ENCODING_DISABLE_UTF8 = 0x20000000

BINDINFO STRUCT
	cbSize DD
	szExtraInfo PTR
	stgmedData STGMEDIUM
	grfBindInfoF DD
	dwBindVerb DD
	szCustomVerb PTR
	cbstgmedData DD
	dwOptions DD
	dwOptionsFlags DD
	dwCodePage DD
	securityAttributes SECURITY_ATTRIBUTES
	iid GUID
	pUnk PTR
	dwReserved DD
ENDS

REMSECURITY_ATTRIBUTES STRUCT
	nLength DD
	lpSecurityDescriptor PTR
	bInheritHandle DD
ENDS

REMBINDINFO STRUCT
	cbSize DD
	szExtraInfo PTR
	grfBindInfoF DD
	dwBindVerb DD
	szCustomVerb PTR
	cbstgmedData DD
	dwOptions DD
	dwOptionsFlags DD
	dwCodePage DD
	securityAttributes REMSECURITY_ATTRIBUTES
	iid GUID
	pUnk PTR
	dwReserved DD
ENDS

REMFORMATETC STRUCT
	cfFormat DD
	ptd PTR
	dwAspect DD
	lindex DD
	tymed DD
ENDS

BINDINFO_OPTIONS_WININETFLAG = 0x10000
BINDINFO_OPTIONS_ENABLE_UTF8 = 0x20000
BINDINFO_OPTIONS_DISABLE_UTF8 = 0x40000
BINDINFO_OPTIONS_USE_IE_ENCODING = 0x80000
BINDINFO_OPTIONS_BINDTOOBJECT = 0x100000

BSCF_FIRSTDATANOTIFICATION = 0x1
BSCF_INTERMEDIATEDATANOTIFICATION = 0x2
BSCF_LASTDATANOTIFICATION = 0x4
BSCF_DATAFULLYAVAILABLE = 0x8
BSCF_AVAILABLEDATASIZEUNKNOWN = 0x10

BINDSTATUS_FINDINGRESOURCE = 1
BINDSTATUS_CONNECTING = BINDSTATUS_FINDINGRESOURCE+1
BINDSTATUS_REDIRECTING = BINDSTATUS_FINDINGRESOURCE+2
BINDSTATUS_BEGINDOWNLOADDATA = BINDSTATUS_FINDINGRESOURCE+3
BINDSTATUS_DOWNLOADINGDATA = BINDSTATUS_FINDINGRESOURCE+4
BINDSTATUS_ENDDOWNLOADDATA = BINDSTATUS_FINDINGRESOURCE+5
BINDSTATUS_BEGINDOWNLOADCOMPONENTS = BINDSTATUS_FINDINGRESOURCE+6
BINDSTATUS_INSTALLINGCOMPONENTS = BINDSTATUS_FINDINGRESOURCE+7
BINDSTATUS_ENDDOWNLOADCOMPONENTS = BINDSTATUS_FINDINGRESOURCE+8
BINDSTATUS_USINGCACHEDCOPY = BINDSTATUS_FINDINGRESOURCE+9
BINDSTATUS_SENDINGREQUEST = BINDSTATUS_FINDINGRESOURCE+10
BINDSTATUS_CLASSIDAVAILABLE = BINDSTATUS_FINDINGRESOURCE+11
BINDSTATUS_MIMETYPEAVAILABLE = BINDSTATUS_FINDINGRESOURCE+12
BINDSTATUS_CACHEFILENAMEAVAILABLE = BINDSTATUS_FINDINGRESOURCE+13
BINDSTATUS_BEGINSYNCOPERATION = BINDSTATUS_FINDINGRESOURCE+14
BINDSTATUS_ENDSYNCOPERATION = BINDSTATUS_FINDINGRESOURCE+15
BINDSTATUS_BEGINUPLOADDATA = BINDSTATUS_FINDINGRESOURCE+16
BINDSTATUS_UPLOADINGDATA = BINDSTATUS_FINDINGRESOURCE+17
BINDSTATUS_ENDUPLOADDATA = BINDSTATUS_FINDINGRESOURCE+18
BINDSTATUS_PROTOCOLCLASSID = BINDSTATUS_FINDINGRESOURCE+19
BINDSTATUS_ENCODING = BINDSTATUS_FINDINGRESOURCE+20
BINDSTATUS_VERIFIEDMIMETYPEAVAILABLE = BINDSTATUS_FINDINGRESOURCE+21
BINDSTATUS_CLASSINSTALLLOCATION = BINDSTATUS_FINDINGRESOURCE+22
BINDSTATUS_DECODING = BINDSTATUS_FINDINGRESOURCE+23
BINDSTATUS_LOADINGMIMEHANDLER = BINDSTATUS_FINDINGRESOURCE+24
BINDSTATUS_CONTENTDISPOSITIONATTACH = BINDSTATUS_FINDINGRESOURCE+25
BINDSTATUS_FILTERREPORTMIMETYPE = BINDSTATUS_FINDINGRESOURCE+26
BINDSTATUS_CLSIDCANINSTANTIATE = BINDSTATUS_FINDINGRESOURCE+27
BINDSTATUS_IUNKNOWNAVAILABLE = BINDSTATUS_FINDINGRESOURCE+28
BINDSTATUS_DIRECTBIND = BINDSTATUS_FINDINGRESOURCE+29
BINDSTATUS_RAWMIMETYPE = BINDSTATUS_FINDINGRESOURCE+30
BINDSTATUS_PROXYDETECTING = BINDSTATUS_FINDINGRESOURCE+31
BINDSTATUS_ACCEPTRANGES = BINDSTATUS_FINDINGRESOURCE+32

#define GUID_IID_IBindStatusCallback <0x79eac9c1,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IBindStatusCallback STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	OnStartBinding PTR
	GetPriority PTR
	OnLowResource PTR
	OnProgress PTR
	OnStopBinding PTR
	GetBindInfo PTR
	OnDataAvailable PTR
	OnObjectAvailable PTR
ENDS

#define GUID_IID_IAuthenticate <0x79eac9d0,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IAuthenticate STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Authenticate PTR
ENDS

#define GUID_IID_IHttpNegotiate <0x79eac9d2,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IHttpNegotiate STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	BeginningTransaction PTR
	OnResponse PTR
ENDS

#define GUID_IID_IWindowForBindingUI <0x79eac9d5,0xbafa,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IWindowForBindingUI STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetWindow PTR
ENDS

CIP_DISK_FULL = 0
CIP_ACCESS_DENIED = CIP_DISK_FULL+1
CIP_NEWER_VERSION_EXISTS = CIP_DISK_FULL+2
CIP_OLDER_VERSION_EXISTS = CIP_DISK_FULL+3
CIP_NAME_CONFLICT = CIP_DISK_FULL+4
CIP_TRUST_VERIFICATION_COMPONENT_MISSING = CIP_DISK_FULL+5
CIP_EXE_SELF_REGISTERATION_TIMEOUT = CIP_DISK_FULL+6
CIP_UNSAFE_TO_ABORT = CIP_DISK_FULL+7
CIP_NEED_REBOOT = CIP_DISK_FULL+8

#define GUID_IID_ICodeInstall <0x79eac9d1,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
ICodeInstall STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetWindow PTR
	OnCodeInstallProblem PTR
ENDS

#define GUID_IID_IWinInetInfo <0x79eac9d6,0xbafa,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IWinInetInfo STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	QueryOption PTR
ENDS

#define WININETINFO_OPTION_LOCK_HANDLE  65534

#define GUID_IID_IHttpSecurity <0x79eac9d7,0xbafa,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IHttpSecurity STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetWindow PTR
	OnSecurityProblem PTR
ENDS

#define GUID_IID_IWinInetHttpInfo <0x79eac9d8,0xbafa,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IWinInetHttpInfo STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	QueryOption PTR
	QueryInfo PTR
ENDS

#define GUID_IID_IBindHost <0xfc4801a1,0x2ba9,0x11cf,<0xa2,0x29,0x00,0xaa,0x00,0x3d,0x73,0x52>>
IBindHost STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	CreateMoniker PTR
	MonikerBindToStorage PTR
	MonikerBindToObject PTR
ENDS

#define URLOSTRM_USECACHEDCOPY_ONLY 0x1
#define URLOSTRM_USECACHEDCOPY  0x2
#define URLOSTRM_GETNEWESTVERSION  0x3

#IFDEF UNICODE
	#define URLOpenStream  URLOpenStreamW
	#define URLOpenPullStream  URLOpenPullStreamW
	#define URLDownloadToFile  URLDownloadToFileW
	#define URLDownloadToCacheFile  URLDownloadToCacheFileW
	#define URLOpenBlockingStream  URLOpenBlockingStreamW
#else
	#define URLOpenStream  URLOpenStreamA
	#define URLOpenPullStream  URLOpenPullStreamA
	#define URLDownloadToFile  URLDownloadToFileA
	#define URLDownloadToCacheFile  URLDownloadToCacheFileA
	#define URLOpenBlockingStream  URLOpenBlockingStreamA
#endif /* !UNICODE */

#define GUID_IID_IInternet <0x79eac9e0,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternet STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
ENDS

BINDSTRING_HEADERS = 1
BINDSTRING_ACCEPT_MIMES = BINDSTRING_HEADERS+1
BINDSTRING_EXTRA_URL = BINDSTRING_HEADERS+2
BINDSTRING_LANGUAGE = BINDSTRING_HEADERS+3
BINDSTRING_USERNAME = BINDSTRING_HEADERS+4
BINDSTRING_PASSWORD = BINDSTRING_HEADERS+5
BINDSTRING_UA_PIXELS = BINDSTRING_HEADERS+6
BINDSTRING_UA_COLOR = BINDSTRING_HEADERS+7
BINDSTRING_OS = BINDSTRING_HEADERS+8
BINDSTRING_USER_AGENT = BINDSTRING_HEADERS+9
BINDSTRING_ACCEPT_ENCODINGS = BINDSTRING_HEADERS+10
BINDSTRING_POST_COOKIE = BINDSTRING_HEADERS+11
BINDSTRING_POST_DATA_MIME = BINDSTRING_HEADERS+12
BINDSTRING_URL = BINDSTRING_HEADERS+13
BINDSTRING_IID = BINDSTRING_HEADERS+14
BINDSTRING_FLAG_BIND_TO_OBJECT = BINDSTRING_HEADERS+15
BINDSTRING_PTR_BIND_CONTEXT = BINDSTRING_HEADERS+16

#define GUID_IID_IInternetBindInfo <0x79eac9e1,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetBindInfo STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetBindInfo DD
	GetBindString DD
ENDS

PI_PARSE_URL = 0x1
PI_FILTER_MODE = 0x2
PI_FORCE_ASYNC = 0x4
PI_USE_WORKERTHREAD = 0x8
PI_MIMEVERIFICATION = 0x10
PI_CLSIDLOOKUP = 0x20
PI_DATAPROGRESS = 0x40
PI_SYNCHRONOUS = 0x80
PI_APARTMENTTHREADED = 0x100
PI_CLASSINSTALL = 0x200
PI_PASSONBINDCTX = 0x2000
PI_NOMIMEHANDLER = 0x8000
PI_LOADAPPDIRECT = 0x4000
PD_FORCE_SWITCH = 0x10000

PROTOCOLDATA STRUCT
	grfFlags DD
	dwState DD
	pData PTR
	cbData DD
ENDS

StartParam STRUCT
	iid GUID
	pIBindCtx PTR
	pItf PTR
ENDS

#define GUID_IID_IInternetProtocolRoot <0x79eac9e3,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetProtocolRoot STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Start PTR
	Continue PTR
	Abort PTR
	Terminate PTR
	Suspend PTR
	Resume PTR
ENDS

#define GUID_IID_IInternetProtocol <0x79eac9e4,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetProtocol STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Start PTR
	Continue PTR
	Abort PTR
	Terminate PTR
	Suspend PTR
	Resume PTR
	Read PTR
	Seek PTR
	LockRequest PTR
	UnlockRequest PTR
ENDS

#define GUID_IID_IInternetProtocolSink <0x79eac9e5,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetProtocolSink STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Switch PTR
	ReportProgress PTR
	ReportData PTR
	ReportResult PTR
ENDS

#define GUID_IID_IInternetProtocolSinkStackable <0x79eac9f0,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetProtocolSinkStackable STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	SwitchSink PTR
	CommitSwitch PTR
	RollbackSwitch PTR
ENDS

OIBDG_APARTMENTTHREADED = 0x100
OIBDG_DATAONLY = 0x1000

#define GUID_IID_IInternetSession <0x79eac9e7,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetSession STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	RegisterNameSpace PTR
	UnregisterNameSpace PTR
	RegisterMimeFilter PTR
	UnregisterMimeFilter PTR
	CreateBinding PTR
	SetSessionOption PTR
	GetSessionOption PTR
ENDS

#define GUID_IID_IInternetThreadSwitch <0x79eac9e8,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetThreadSwitch STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Prepare PTR
	Continue PTR
ENDS

#define GUID_IID_IInternetPriority <0x79eac9eb,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetPriority STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	SetPriority PTR
	GetPriority PTR
ENDS

PARSE_CANONICALIZE = 1
PARSE_FRIENDLY = PARSE_CANONICALIZE+1
PARSE_SECURITY_URL = PARSE_CANONICALIZE+2
PARSE_ROOTDOCUMENT = PARSE_CANONICALIZE+3
PARSE_DOCUMENT = PARSE_CANONICALIZE+4
PARSE_ANCHOR = PARSE_CANONICALIZE+5
PARSE_ENCODE = PARSE_CANONICALIZE+6
PARSE_DECODE = PARSE_CANONICALIZE+7
PARSE_PATH_FROM_URL = PARSE_CANONICALIZE+8
PARSE_URL_FROM_PATH = PARSE_CANONICALIZE+9
PARSE_MIME = PARSE_CANONICALIZE+10
PARSE_SERVER = PARSE_CANONICALIZE+11
PARSE_SCHEMA = PARSE_CANONICALIZE+12
PARSE_SITE = PARSE_CANONICALIZE+13
PARSE_DOMAIN = PARSE_CANONICALIZE+14
PARSE_LOCATION = PARSE_CANONICALIZE+15
PARSE_SECURITY_DOMAIN = PARSE_CANONICALIZE+16
PARSE_ESCAPE = PARSE_CANONICALIZE+16
PARSE_UNESCAPE = PARSE_CANONICALIZE+18

PSU_DEFAULT = 1,
PSU_SECURITY_URL_ONLY = PSU_DEFAULT+1

QUERY_EXPIRATION_DATE = 1
QUERY_TIME_OF_LAST_CHANGE = QUERY_EXPIRATION_DATE+1
QUERY_CONTENT_ENCODING = QUERY_EXPIRATION_DATE+2
QUERY_CONTENT_TYPE = QUERY_EXPIRATION_DATE+3
QUERY_REFRESH = QUERY_EXPIRATION_DATE+4
QUERY_RECOMBINE = QUERY_EXPIRATION_DATE+5
QUERY_CAN_NAVIGATE = QUERY_EXPIRATION_DATE+6
QUERY_USES_NETWORK = QUERY_EXPIRATION_DATE+7
QUERY_IS_CACHED = QUERY_EXPIRATION_DATE+8
QUERY_IS_INSTALLEDENTRY = QUERY_EXPIRATION_DATE+9
QUERY_IS_CACHED_OR_MAPPED = QUERY_EXPIRATION_DATE+10
QUERY_USES_CACHE = QUERY_EXPIRATION_DATE+11
QUERY_IS_SECURE = QUERY_EXPIRATION_DATE+12
QUERY_IS_SAFE = QUERY_EXPIRATION_DATE+13


#define GUID_IID_IInternetProtocolInfo <0x79eac9ec,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetProtocolInfo STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	ParseUrl PTR
	CombineUrl PTR
	CompareUrl PTR
	QueryInfo PTR
ENDS

#define INET_E_USE_DEFAULT_PROTOCOLHANDLER  0x800C0011
#define INET_E_USE_DEFAULT_SETTING  0x800C0012
#define INET_E_DEFAULT_ACTION  INET_E_USE_DEFAULT_PROTOCOLHANDLER
#define INET_E_QUERYOPTION_UNKNOWN  0x800C0013
#define INET_E_REDIRECTING  0x800C0014
#define OInetParseUrl  CoInternetParseUrl
#define OInetCombineUrl  CoInternetCombineUrl
#define OInetCompareUrl  CoInternetCompareUrl
#define OInetQueryInfo  CoInternetQueryInfo
#define OInetGetSession  CoInternetGetSession

#define PROTOCOLFLAG_NO_PICS_CHECK  0x00000001

#define GUID_IID_IInternetSecurityMgrSite <0x79eac9ed,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetSecurityMgrSite STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetWindow PTR
	EnableModeless PTR
ENDS

#define MUTZ_NOSAVEDFILECHECK  0x00000001
#define MAX_SIZE_SECURITY_ID  512

PUAF_DEFAULT = 0
PUAF_NOUI = 0x1
PUAF_ISFILE = 0x2
PUAF_WARN_IF_DENIED = 0x4
PUAF_FORCEUI_FOREGROUND = 0x8
PUAF_CHECK_TIFS = 0x10
PUAF_DONTCHECKBOXINDIALOG = 0x20
PUAF_TRUSTED = 0x40
PUAF_ACCEPT_WILDCARD_SCHEME = 0x80

SZM_CREATE = 0
SZM_DELETE = 0x1

#define GUID_IID_IInternetSecurityManager <0x79eac9ee,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetSecurityManager STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	SetSecuritySite PTR
	GetSecuritySite PTR
	MapUrlToZone PTR
	GetSecurityId PTR
	ProcessUrlAction PTR
	QueryCustomPolicy PTR
	SetZoneMapping PTR
	GetZoneMappings PTR
ENDS

#define GUID_IID_IInternetHostSecurityManager <0x3af280b6,0xcb3f,0x11d0,<0x89,0x1e,0x00,0xc0,0x4f,0xb6,0xbf,0xc4>>
IInternetHostSecurityManager STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetSecurityId PTR
	ProcessUrlAction PTR
	QueryCustomPolicy PTR
ENDS

#define URLACTION_MIN  0x00001000
#define URLACTION_DOWNLOAD_MIN  0x00001000
#define URLACTION_DOWNLOAD_SIGNED_ACTIVEX  0x00001001
#define URLACTION_DOWNLOAD_UNSIGNED_ACTIVEX  0x00001004
#define URLACTION_DOWNLOAD_CURR_MAX  0x00001004
#define URLACTION_DOWNLOAD_MAX  0x000011FF
#define URLACTION_ACTIVEX_MIN  0x00001200
#define URLACTION_ACTIVEX_RUN  0x00001200
#define URLPOLICY_ACTIVEX_CHECK_LIST  0x00010000
#define URLACTION_ACTIVEX_OVERRIDE_OBJECT_SAFETY  0x00001201
#define URLACTION_ACTIVEX_OVERRIDE_DATA_SAFETY  0x00001202
#define URLACTION_ACTIVEX_OVERRIDE_SCRIPT_SAFETY  0x00001203
#define URLACTION_SCRIPT_OVERRIDE_SAFETY  0x00001401
#define URLACTION_ACTIVEX_CONFIRM_NOOBJECTSAFETY  0x00001204
#define URLACTION_ACTIVEX_TREATASUNTRUSTED  0x00001205
#define URLACTION_ACTIVEX_CURR_MAX  0x00001205
#define URLACTION_ACTIVEX_MAX  0x000013ff
#define URLACTION_SCRIPT_MIN  0x00001400
#define URLACTION_SCRIPT_RUN  0x00001400
#define URLACTION_SCRIPT_JAVA_USE  0x00001402
#define URLACTION_SCRIPT_SAFE_ACTIVEX  0x00001405
#define URLACTION_CROSS_DOMAIN_DATA  0x00001406
#define URLACTION_SCRIPT_PASTE  0x00001407
#define URLACTION_SCRIPT_CURR_MAX  0x00001407
#define URLACTION_SCRIPT_MAX  0x000015ff
#define URLACTION_HTML_MIN  0x00001600
#define URLACTION_HTML_SUBMIT_FORMS  0x00001601
#define URLACTION_HTML_SUBMIT_FORMS_FROM  0x00001602
#define URLACTION_HTML_SUBMIT_FORMS_TO  0x00001603
#define URLACTION_HTML_FONT_DOWNLOAD  0x00001604
#define URLACTION_HTML_JAVA_RUN  0x00001605
#define URLACTION_HTML_USERDATA_SAVE  0x00001606
#define URLACTION_HTML_SUBFRAME_NAVIGATE  0x00001607
#define URLACTION_HTML_CURR_MAX  0x00001607
#define URLACTION_HTML_MAX  0x000017ff
#define URLACTION_SHELL_MIN  0x00001800
#define URLACTION_SHELL_INSTALL_DTITEMS  0x00001800
#define URLACTION_SHELL_MOVE_OR_COPY  0x00001802
#define URLACTION_SHELL_FILE_DOWNLOAD  0x00001803
#define URLACTION_SHELL_VERB  0x00001804
#define URLACTION_SHELL_WEBVIEW_VERB  0x00001805
#define URLACTION_SHELL_CURR_MAX  0x00001805
#define URLACTION_SHELL_MAX  0x000019ff
#define URLACTION_NETWORK_MIN  0x00001A00
#define URLACTION_CREDENTIALS_USE  0x00001A00
#define URLPOLICY_CREDENTIALS_SILENT_LOGON_OK  0x00000000
#define URLPOLICY_CREDENTIALS_MUST_PROMPT_USER  0x00010000
#define URLPOLICY_CREDENTIALS_CONDITIONAL_PROMPT  0x00020000
#define URLPOLICY_CREDENTIALS_ANONYMOUS_ONLY  0x00030000
#define URLACTION_AUTHENTICATE_CLIENT  0x00001A01
#define URLPOLICY_AUTHENTICATE_CLEARTEXT_OK  0x00000000
#define URLPOLICY_AUTHENTICATE_CHALLENGE_RESPONSE  0x00010000
#define URLPOLICY_AUTHENTICATE_MUTUAL_ONLY  0x00030000
#define URLACTION_COOKIES  0x00001A02
#define URLACTION_COOKIES_SESSION  0x00001A03
#define URLACTION_NETWORK_CURR_MAX  0x00001A03
#define URLACTION_NETWORK_MAX  0x00001Bff
#define URLACTION_JAVA_MIN  0x00001C00
#define URLACTION_JAVA_PERMISSIONS  0x00001C00
#define URLPOLICY_JAVA_PROHIBIT  0x00000000
#define URLPOLICY_JAVA_HIGH  0x00010000
#define URLPOLICY_JAVA_MEDIUM  0x00020000
#define URLPOLICY_JAVA_LOW  0x00030000
#define URLPOLICY_JAVA_CUSTOM  0x00800000
#define URLACTION_JAVA_CURR_MAX  0x00001C00
#define URLACTION_JAVA_MAX  0x00001Cff
#define URLACTION_INFODELIVERY_MIN  0x00001D00
#define URLACTION_INFODELIVERY_NO_ADDING_CHANNELS  0x00001D00
#define URLACTION_INFODELIVERY_NO_EDITING_CHANNELS  0x00001D01
#define URLACTION_INFODELIVERY_NO_REMOVING_CHANNELS  0x00001D02
#define URLACTION_INFODELIVERY_NO_ADDING_SUBSCRIPTIONS  0x00001D03
#define URLACTION_INFODELIVERY_NO_EDITING_SUBSCRIPTIONS  0x00001D04
#define URLACTION_INFODELIVERY_NO_REMOVING_SUBSCRIPTIONS  0x00001D05
#define URLACTION_INFODELIVERY_NO_CHANNEL_LOGGING  0x00001D06
#define URLACTION_INFODELIVERY_CURR_MAX  0x00001D06
#define URLACTION_INFODELIVERY_MAX  0x00001Dff
#define URLACTION_CHANNEL_SOFTDIST_MIN  0x00001E00
#define URLACTION_CHANNEL_SOFTDIST_PERMISSIONS  0x00001E05
#define URLPOLICY_CHANNEL_SOFTDIST_PROHIBIT  0x00010000
#define URLPOLICY_CHANNEL_SOFTDIST_PRECACHE  0x00020000
#define URLPOLICY_CHANNEL_SOFTDIST_AUTOINSTALL  0x00030000
#define URLACTION_CHANNEL_SOFTDIST_MAX  0x00001Eff
#define URLPOLICY_ALLOW  0x00
#define URLPOLICY_QUERY  0x01
#define URLPOLICY_DISALLOW  0x03
#define URLPOLICY_NOTIFY_ON_ALLOW  0x10
#define URLPOLICY_NOTIFY_ON_DISALLOW  0x20
#define URLPOLICY_LOG_ON_ALLOW  0x40
#define URLPOLICY_LOG_ON_DISALLOW  0x80
#define URLPOLICY_MASK_PERMISSIONS  0x0f
#define URLPOLICY_DONTCHECKDLGBOX  0x100

URLZONE_PREDEFINED_MIN = 0
URLZONE_LOCAL_MACHINE = 0
URLZONE_INTRANET = URLZONE_LOCAL_MACHINE+1
URLZONE_TRUSTED = URLZONE_LOCAL_MACHINE+2
URLZONE_INTERNET = URLZONE_LOCAL_MACHINE+3
URLZONE_UNTRUSTED = URLZONE_LOCAL_MACHINE+4
URLZONE_PREDEFINED_MAX = 999
URLZONE_USER_MIN = 1000
URLZONE_USER_MAX = 10000

URLTEMPLATE_CUSTOM = 0
URLTEMPLATE_PREDEFINED_MIN = 0x10000
URLTEMPLATE_LOW = 0x10000
URLTEMPLATE_MEDLOW = 0x10500
URLTEMPLATE_MEDIUM = 0x11000
URLTEMPLATE_HIGH = 0x12000
URLTEMPLATE_PREDEFINED_MAX = 0x20000

MAX_ZONE_PATH = 260
MAX_ZONE_DESCRIPTION = 200

ZAFLAGS_CUSTOM_EDIT = 0x1
ZAFLAGS_ADD_SITES = 0x2
ZAFLAGS_REQUIRE_VERIFICATION = 0x4
ZAFLAGS_INCLUDE_PROXY_OVERRIDE = 0x8
ZAFLAGS_INCLUDE_INTRANET_SITES = 0x10
ZAFLAGS_NO_UI = 0x20
ZAFLAGS_SUPPORTS_VERIFICATION = 0x40
ZAFLAGS_UNC_AS_INTRANET = 0x80

ZONEATTRIBUTES STRUCT
	cbSize DD
	szDisplayName DW 260 DUP (?)
	szDescription DW 200 DUP (?)
	szIconPath DW 260 DUP (?)
	dwTemplateMinLevel DD
	dwTemplateRecommended DD
	dwTemplateCurrentLevel DD
	dwFlags DD
ENDS

URLZONEREG_DEFAULT = 0
URLZONEREG_HKLM = URLZONEREG_DEFAULT+1
URLZONEREG_HKCU = URLZONEREG_DEFAULT+2

#define GUID_IID_IInternetZoneManager <0x79eac9ef,0xbaf9,0x11ce,<0x8c,0x82,0x00,0xaa,0x00,0x4b,0xa9,0x0b>>
IInternetZoneManager STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetZoneAttributes PTR
	SetZoneAttributes PTR
	GetZoneCustomPolicy PTR
	SetZoneCustomPolicy PTR
	GetZoneActionPolicy PTR
	SetZoneActionPolicy PTR
	PromptAction PTR
	LogAction PTR
	CreateZoneEnumerator PTR
	GetZoneAt PTR
	DestroyZoneEnumerator PTR
	CopyTemplatePoliciesToZone PTR
ENDS

#define SOFTDIST_FLAG_USAGE_EMAIL  0x00000001
#define SOFTDIST_FLAG_USAGE_PRECACHE  0x00000002
#define SOFTDIST_FLAG_USAGE_AUTOINSTALL  0x00000004
#define SOFTDIST_FLAG_DELETE_SUBSCRIPTION  0x00000008
#define SOFTDIST_ADSTATE_NONE  0x00000000
#define SOFTDIST_ADSTATE_AVAILABLE  0x00000001
#define SOFTDIST_ADSTATE_DOWNLOADED  0x00000002
#define SOFTDIST_ADSTATE_INSTALLED  0x00000003

CODEBASEHOLD STRUCT
	cbSize DD
	szDistUnit PTR
	szCodeBase PTR
	dwVersionMS DD
	dwVersionLS DD
	dwStyle DD
ENDS

SOFTDISTINFO STRUCT
	cbSize DD
	dwFlags DD
	dwAdState DD
	szTitle PTR
	szAbstract PTR
	szHREF PTR
	dwInstalledVersionMS DD
	dwInstalledVersionLS DD
	dwUpdateVersionMS DD
	dwUpdateVersionLS DD
	dwAdvertisedVersionMS DD
	dwAdvertisedVersionLS DD
	dwReserved DD
ENDS

#define GUID_IID_ISoftDistExt <0xB15B8DC1,0xC7E1,0x11d0,<0x86,0x80,0x00,0xAA,0x00,0xBD,0xCB,0x71>>
ISoftDistExt STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	ProcessSoftDist PTR
	GetFirstCodeBase PTR
	GetNextCodeBase PTR
	AsyncInstallDistributionUnit PTR
ENDS

#define GUID_IID_ICatalogFileInfo <0x711C7600,0x6B48,0x11d1,<0xB4,0x03,0x00,0xAA,0x00,0xB9,0x2A,0xF1>>
ICatalogFileInfo STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetCatalogFile PTR
	GetJavaTrust PTR
ENDS

#define GUID_IID_IDataFilter <0x69d14c80,0xc18e,0x11d0,<0xa9,0xce,0x00,0x60,0x97,0x94,0x23,0x11>>
IDataFilter STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	DoEncode PTR
	DoDecode PTR
	SetEncodingLevel PTR
ENDS

PROTOCOLFILTERDATA STRUCT
	cbSize DD
	pProtocolSink PTR
	pProtocol PTR
	pUnk PTR
	dwFilterFlags DD
ENDS

DATAINFO STRUCT
	ulTotalSize DD
	ulavrPacketSize DD
	ulConnectSpeed DD
	ulProcessorSpeed DD
ENDS

#define GUID_IID_IEncodingFilterFactory <0x70bdde00,0xc18e,0x11d0,<0xa9,0xce,0x00,0x60,0x97,0x94,0x23,0x11>>
IEncodingFilterFactory STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	FindBestFilter PTR
	GetDefaultFilter PTR
ENDS

#IFDEF UNICODE
	#define IsLoggingEnabled  IsLoggingEnabledW
#else
	#define IsLoggingEnabled  IsLoggingEnabledA
#endif /* !UNICODE */

HIT_LOGGING_INFO STRUCT
	dwStructSize DD
	lpszLoggedUrlName PTR
	StartTime SYSTEMTIME
	EndTime SYSTEMTIME
	lpszExtendedInfo PTR
ENDS

#define CONFIRMSAFETYACTION_LOADOBJECT  0x00000001

CONFIRMSAFETY STRUCT
	clsid GUID
	pUnk PTR
	dwFlags DD
ENDS


#endif /* _URLMON_H */
