#ifndef WINIOCTL_H
#define WINIOCTL_H

#IFDEF LINKFILES
	#dynamiclinkfile Kernel32.dll
#ENDIF

#DEFINE WINIOCTL_H_REQVER 100

#define GUID_DiskClassGuid <0x53f56307,0xb6bf,0x11d0,<0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>
#define GUID_CdRomClassGuid <0x53f56308,0xb6bf,0x11d0,<0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>
#define GUID_PartitionClassGuid <0x53f5630a,0xb6bf,0x11d0,<0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>
#define GUID_TapeClassGuid <0x53f5630b,0xb6bf,0x11d0,<0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>
#define GUID_WriteOnceDiskClassGuid <0x53f5630c,0xb6bf,0x11d0,<0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>
#define GUID_VolumeClassGuid <0x53f5630d,0xb6bf,0x11d0,<0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>
#define GUID_MediumChangerClassGuid <0x53f56310,0xb6bf,0x11d0,<0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>
#define GUID_FloppyClassGuid <0x53f56311,0xb6bf,0x11d0,<0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>
#define GUID_CdChangerClassGuid <0x53f56312,0xb6bf,0x11d0,<0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>
#define GUID_StoragePortClassGuid <0x2accfe60,0xc130,0x11d2,<0xb0,0x82,0x00,0xa0,0xc9,0x1e,0xfb,0x8b>>

#define GUID_GUID_CLASS_COMPORT <0x86e0d1e0,0x8089,0x11d0,<0x9c,0xe4,0x08,0x00,0x3e,0x30,0x1f,0x73>>
#define GUID_GUID_SERENUM_BUS_ENUMERATOR <0x4D36E978,0xE325,0x11CE,<0xBF,0xC1,0x08,0x00,0x2B,0xE1,0x03,0x18>>

/* Windows Device I/O control definitions */
#IFNDEF FILE_DEVICE_BEEP
#define FILE_DEVICE_BEEP  0x00000001
#define FILE_DEVICE_CD_ROM  0x00000002
#define FILE_DEVICE_CD_ROM_FILE_SYSTEM  0x00000003
#define FILE_DEVICE_CONTROLLER  0x00000004
#define FILE_DEVICE_DATALINK  0x00000005
#define FILE_DEVICE_DFS  0x00000006
#define FILE_DEVICE_DISK  0x00000007
#define FILE_DEVICE_DISK_FILE_SYSTEM  0x00000008
#define FILE_DEVICE_FILE_SYSTEM  0x00000009
#define FILE_DEVICE_INPORT_PORT  0x0000000A
#define FILE_DEVICE_KEYBOARD  0x0000000B
#define FILE_DEVICE_MAILSLOT  0x0000000C
#define FILE_DEVICE_MIDI_IN  0x0000000D
#define FILE_DEVICE_MIDI_OUT  0x0000000E
#define FILE_DEVICE_MOUSE  0x0000000F
#define FILE_DEVICE_MULTI_UNC_PROVIDER  0x00000010
#define FILE_DEVICE_NAMED_PIPE  0x00000011
#define FILE_DEVICE_NETWORK  0x00000012
#define FILE_DEVICE_NETWORK_BROWSER  0x00000013
#define FILE_DEVICE_NETWORK_FILE_SYSTEM  0x00000014
#define FILE_DEVICE_NULL  0x00000015
#define FILE_DEVICE_PARALLEL_PORT  0x00000016
#define FILE_DEVICE_PHYSICAL_NETCARD  0x00000017
#define FILE_DEVICE_PRINTER  0x00000018
#define FILE_DEVICE_SCANNER  0x00000019
#define FILE_DEVICE_SERIAL_MOUSE_PORT  0x0000001A
#define FILE_DEVICE_SERIAL_PORT  0x0000001B
#define FILE_DEVICE_SCREEN  0x0000001C
#define FILE_DEVICE_SOUND  0x0000001D
#define FILE_DEVICE_STREAMS  0x0000001E
#define FILE_DEVICE_TAPE  0x0000001F
#define FILE_DEVICE_TAPE_FILE_SYSTEM  0x00000020
#define FILE_DEVICE_TRANSPORT  0x00000021
#define FILE_DEVICE_UNKNOWN  0x00000022
#define FILE_DEVICE_VIDEO  0x00000023
#define FILE_DEVICE_VIRTUAL_DISK  0x00000024
#define FILE_DEVICE_WAVE_IN  0x00000025
#define FILE_DEVICE_WAVE_OUT  0x00000026
#define FILE_DEVICE_8042_PORT  0x00000027
#define FILE_DEVICE_NETWORK_REDIRECTOR  0x00000028
#define FILE_DEVICE_BATTERY  0x00000029
#define FILE_DEVICE_BUS_EXTENDER  0x0000002A
#define FILE_DEVICE_MODEM  0x0000002B
#define FILE_DEVICE_VDM  0x0000002C
#define FILE_DEVICE_MASS_STORAGE  0x0000002D
#define FILE_DEVICE_SMB  0x0000002E
#define FILE_DEVICE_KS  0x0000002F
#define FILE_DEVICE_CHANGER  0x00000030
#IFNDEF FILE_DEVICE_SMARTCARD
	#define FILE_DEVICE_SMARTCARD  0x00000031
#ENDIF
#define FILE_DEVICE_ACPI  0x00000032
#define FILE_DEVICE_DVD  0x00000033
#define FILE_DEVICE_FULLSCREEN_VIDEO  0x00000034
#define FILE_DEVICE_DFS_FILE_SYSTEM  0x00000035
#define FILE_DEVICE_DFS_VOLUME  0x00000036
#define FILE_DEVICE_SERENUM  0x00000037
#define FILE_DEVICE_TERMSRV  0x00000038
#define FILE_DEVICE_KSEC  0x00000039
#define FILE_DEVICE_FIPS                0x0000003A
#define FILE_DEVICE_INFINIBAND          0x0000003B
#define FILE_DEVICE_VMBUS               0x0000003E
#define FILE_DEVICE_CRYPT_PROVIDER      0x0000003F
#define FILE_DEVICE_WPD                 0x00000040
#define FILE_DEVICE_BLUETOOTH           0x00000041
#define FILE_DEVICE_MT_COMPOSITE        0x00000042
#define FILE_DEVICE_MT_TRANSPORT        0x00000043
#define FILE_DEVICE_BIOMETRIC		0x00000044
#define FILE_DEVICE_PMI                 0x00000045
#ENDIF

#define METHOD_BUFFERED  0
#define METHOD_IN_DIRECT  1
#define METHOD_OUT_DIRECT  2
#define METHOD_NEITHER  3

#define FILE_ANY_ACCESS  0
#define FILE_SPECIAL_ACCESS  (FILE_ANY_ACCESS)
#define FILE_READ_ACCESS  0x0001
#define FILE_WRITE_ACCESS  0x0002

#define IOCTL_STORAGE_BASE FILE_DEVICE_MASS_STORAGE
#define IOCTL_STORAGE_CHECK_VERIFY  (IOCTL_STORAGE_BASE<<16)|(0x0200<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_CHECK_VERIFY2  (IOCTL_STORAGE_BASE<<16)|(0x0200<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_MEDIA_REMOVAL  (IOCTL_STORAGE_BASE<<16)|(0x0201<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_EJECT_MEDIA  (IOCTL_STORAGE_BASE<<16)|(0x0202<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_LOAD_MEDIA  (IOCTL_STORAGE_BASE<<16)|(0x0203<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_LOAD_MEDIA2  (IOCTL_STORAGE_BASE<<16)|(0x0203<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_RESERVE  (IOCTL_STORAGE_BASE<<16)|(0x0204<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_RELEASE  (IOCTL_STORAGE_BASE<<16)|(0x0205<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_FIND_NEW_DEVICES  (IOCTL_STORAGE_BASE<<16)|(0x0206<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_EJECTION_CONTROL  (IOCTL_STORAGE_BASE<<16)|(0x0250<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_MCN_CONTROL  (IOCTL_STORAGE_BASE<<16)|(0x0251<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_GET_MEDIA_TYPES  (IOCTL_STORAGE_BASE<<16)|(0x0300<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_GET_MEDIA_TYPES_EX  (IOCTL_STORAGE_BASE<<16)|(0x0301<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_RESET_BUS  (IOCTL_STORAGE_BASE<<16)|(0x0400<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_RESET_DEVICE  (IOCTL_STORAGE_BASE<<16)|(0x0401<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_GET_DEVICE_NUMBER  (IOCTL_STORAGE_BASE<<16)|(0x0420<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_PREDICT_FAILURE  (IOCTL_STORAGE_BASE<<16)|(0x0440<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_BREAK_RESERVATION (IOCTL_STORAGE_BASE<<16)|(0x0405<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_STORAGE_PERSISTENT_RESERVE_IN (IOCTL_STORAGE_BASE<<16)|(0x0406<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_STORAGE_PERSISTENT_RESERVE_OUT (IOCTL_STORAGE_BASE<<16)|(0x0407<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_STORAGE_READ_CAPACITY (IOCTL_STORAGE_BASE<<16)|(0x0450<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_QUERY_PROPERTY   (IOCTL_STORAGE_BASE<<16)|(0x0500<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_STORAGE_GET_BC_PROPERTIES (IOCTL_STORAGE_BASE<<16)|(0x0600<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_STORAGE_ALLOCATE_BC_STREAM (IOCTL_STORAGE_BASE<<16)|(0x0601<<2)|METHOD_BUFFERED|((FILE_READ_ACCESS | FILE_WRITE_ACCESS)<<14)
#define IOCTL_STORAGE_FREE_BC_STREAM  (IOCTL_STORAGE_BASE<<16)|(0x0602<<2)|METHOD_BUFFERED|((FILE_READ_ACCESS | FILE_WRITE_ACCESS)<<14)
#define IOCTL_STORAGE_CHECK_PRIORITY_HINT_SUPPORT (IOCTL_STORAGE_BASE<<16)|(0x0620<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)

#define OBSOLETE_IOCTL_STORAGE_RESET_BUS  (IOCTL_STORAGE_BASE<<16)|(0x0400<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define OBSOLETE_IOCTL_STORAGE_RESET_DEVICE  (IOCTL_STORAGE_BASE<<16)|(0x0401<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)

#define IOCTL_DISK_BASE  FILE_DEVICE_DISK
#define IOCTL_DISK_GET_DRIVE_GEOMETRY  (IOCTL_DISK_BASE<<16)|(0x0000<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_GET_PARTITION_INFO  (IOCTL_DISK_BASE<<16)|(0x0001<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_SET_PARTITION_INFO  (IOCTL_DISK_BASE<<16)|(0x0002<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_GET_DRIVE_LAYOUT  (IOCTL_DISK_BASE<<16)|(0x0003<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_SET_DRIVE_LAYOUT  (IOCTL_DISK_BASE<<16)|(0x0004<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_VERIFY  (IOCTL_DISK_BASE<<16)|(0x0005<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_FORMAT_TRACKS  (IOCTL_DISK_BASE<<16)|(0x0006<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_REASSIGN_BLOCKS  (IOCTL_DISK_BASE<<16)|(0x0007<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_PERFORMANCE  (IOCTL_DISK_BASE<<16)|(0x0008<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_IS_WRITABLE  (IOCTL_DISK_BASE<<16)|(0x0009<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_LOGGING  (IOCTL_DISK_BASE<<16)|(0x000a<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_FORMAT_TRACKS_EX  (IOCTL_DISK_BASE<<16)|(0x000b<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_HISTOGRAM_STRUCTURE  (IOCTL_DISK_BASE<<16)|(0x000c<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_HISTOGRAM_DATA  (IOCTL_DISK_BASE<<16)|(0x000d<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_HISTOGRAM_RESET  (IOCTL_DISK_BASE<<16)|(0x000e<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_REQUEST_STRUCTURE  (IOCTL_DISK_BASE<<16)|(0x000f<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_REQUEST_DATA  (IOCTL_DISK_BASE<<16)|(0x0010<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_CONTROLLER_NUMBER  (IOCTL_DISK_BASE<<16)|(0x0011<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define SMART_GET_VERSION  (IOCTL_DISK_BASE<<16)|(0x0020<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define SMART_SEND_DRIVE_COMMAND  (IOCTL_DISK_BASE<<16)|(0x0021<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define SMART_RCV_DRIVE_DATA  (IOCTL_DISK_BASE<<16)|(0x0022<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_UPDATE_DRIVE_SIZE  (IOCTL_DISK_BASE<<16)|(0x0032<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_GROW_PARTITION  (IOCTL_DISK_BASE<<16)|(0x0034<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_GET_CACHE_INFORMATION  (IOCTL_DISK_BASE<<16)|(0x0035<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_SET_CACHE_INFORMATION  (IOCTL_DISK_BASE<<16)|(0x0036<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_DELETE_DRIVE_LAYOUT  (IOCTL_DISK_BASE<<16)|(0x0040<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_FORMAT_DRIVE  (IOCTL_DISK_BASE<<16)|(0x00f3<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_DISK_SENSE_DEVICE  (IOCTL_DISK_BASE<<16)|(0x00f8<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_CHECK_VERIFY  (IOCTL_DISK_BASE<<16)|(0x0200<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_MEDIA_REMOVAL  (IOCTL_DISK_BASE<<16)|(0x0201<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_EJECT_MEDIA  (IOCTL_DISK_BASE<<16)|(0x0202<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_LOAD_MEDIA  (IOCTL_DISK_BASE<<16)|(0x0203<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_RESERVE  (IOCTL_DISK_BASE<<16)|(0x0204<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_RELEASE  (IOCTL_DISK_BASE<<16)|(0x0205<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_FIND_NEW_DEVICES  (IOCTL_DISK_BASE<<16)|(0x0206<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_DISK_GET_MEDIA_TYPES  (IOCTL_DISK_BASE<<16)|(0x0300<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_DISK_GET_WRITE_CACHE_STATE (IOCTL_DISK_BASE<<16)|(0x0037<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define OBSOLETE_DISK_GET_WRITE_CACHE_STATE (IOCTL_DISK_BASE<<16)|(0x0037<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)


#define IOCTL_CHANGER_BASE  FILE_DEVICE_CHANGER
#define IOCTL_CHANGER_GET_PARAMETERS  (IOCTL_CHANGER_BASE<<16)|(0x0000<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_CHANGER_GET_STATUS  (IOCTL_CHANGER_BASE<<16)|(0x0001<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_CHANGER_GET_PRODUCT_DATA  (IOCTL_CHANGER_BASE<<16)|(0x0002<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_CHANGER_SET_ACCESS  (IOCTL_CHANGER_BASE<<16)|(0x0004<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_CHANGER_GET_ELEMENT_STATUS  (IOCTL_CHANGER_BASE<<16)|(0x0005<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_CHANGER_INITIALIZE_ELEMENT_STATUS  (IOCTL_CHANGER_BASE<<16)|(0x0006<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_CHANGER_SET_POSITION  (IOCTL_CHANGER_BASE<<16)|(0x0007<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_CHANGER_EXCHANGE_MEDIUM  (IOCTL_CHANGER_BASE<<16)|(0x0008<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_CHANGER_MOVE_MEDIUM  (IOCTL_CHANGER_BASE<<16)|(0x0009<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_CHANGER_REINITIALIZE_TRANSPORT  (IOCTL_CHANGER_BASE<<16)|(0x000A<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)
#define IOCTL_CHANGER_QUERY_VOLUME_TAGS  (IOCTL_CHANGER_BASE<<16)|(0x000B<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define IOCTL_VOLUME_IS_CLUSTERED (IOCTL_VOLUME_BASE<<16)|(12<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)

#define RECOVERED_WRITES_VALID  0x00000001
#define UNRECOVERED_WRITES_VALID  0x00000002
#define RECOVERED_READS_VALID  0x00000004
#define UNRECOVERED_READS_VALID  0x00000008
#define WRITE_COMPRESSION_INFO_VALID  0x00000010
#define READ_COMPRESSION_INFO_VALID  0x00000020

#define TAPE_RETURN_STATISTICS  0
#define TAPE_RETURN_ENV_INFO  1
#define TAPE_RESET_STATISTICS  2

#define MEDIA_ERASEABLE  0x00000001
#define MEDIA_WRITE_ONCE  0x00000002
#define MEDIA_READ_ONLY  0x00000004
#define MEDIA_READ_WRITE  0x00000008

#define MEDIA_WRITE_PROTECTED  0x00000100
#define MEDIA_CURRENTLY_MOUNTED  0x80000000

STORAGE_DEVICE_NUMBER STRUCT
	DeviceType DD
	DeviceNumber DD
	PartitionNumber DD
ENDS

STORAGE_BUS_RESET_REQUEST STRUCT
	PathId DB
ENDS

PREVENT_MEDIA_REMOVAL STRUCT
	PreventMediaRemoval DD
ENDS

TAPE_STATISTICS STRUCT
	Version DD
	iFlags DD
	RecoveredWrites LARGE_INTEGER
	UnrecoveredWrites LARGE_INTEGER
	RecoveredReads LARGE_INTEGER
	UnrecoveredReads LARGE_INTEGER
	CompressionRatioReads DB
	CompressionRatioWrites DB
ENDS

TAPE_GET_STATISTICS STRUCT
	Operation DD
ENDS

DDS_4mm = 32
MiniQic = 33
Travan = 34
QIC = 35
MP_8mm = 36
AME_8mm = 37
AIT1_8mm = 38
DLT = 39
NCTP = 40
IBM_3480 = 41
IBM_3490E = 42
IBM_Magstar_3590 = 43
IBM_Magstar_MP = 44
STK_DATA_D3 = 45
SONY_DTF = 46
DV_6mm = 47
DMI = 48
SONY_D2 = 49
CLEANER_CARTRIDGE = 50
CD_ROM = 51
CD_R = 52
CD_RW = 53
DVD_ROM = 54
DVD_R = 55
DVD_RW = 56
MO_3_RW = 57
MO_5_WO = 58
MO_5_RW = 59
MO_5_LIMDOW = 60
PC_5_WO = 61
PC_5_RW = 62
PD_5_RW = 63
ABL_5_WO = 64
PINNACLE_APEX_5_RW = 65
SONY_12_WO = 66
PHILIPS_12_WO = 67
HITACHI_12_WO = 68
CYGNET_12_WO = 69
KODAK_14_WO = 70
MO_NFR_525 = 71
NIKON_12_RW = 72
IOMEGA_ZIP = 73
IOMEGA_JAZ = 74
SYQUEST_EZ135 = 75
SYQUEST_EZFLYER = 76
SYQUEST_SYJET = 77
AVATAR_F2 = 78
MP2_8mm = 79
DST_S = 80
DST_M = 81
DST_L = 82
VXATape_1 = 83
VXATape_2 = 84
STK_9840 = 85
STK_EAGLE = 85
LTO_Ultrium = 86
LTO_Accelis = 87
DVD_RAM = 88
AIT_8mm = 89
ADR_1 = 90
ADR_2 = 91
STK_9940 = 92
SAIT = 93
VXATape = 94

BusTypeUnknown = 0
BusTypeScsi = 1
BusTypeAtapi = 2
BusTypeAta = 3
BusType1394 = 4
BusTypeSsa = 5
BusTypeFibre = 6
BusTypeUsb = 7
BusTypeRAID = 8
BusTypeiScsi = 9
BusTypeSas = 10
BusTypeSata = 11
BusTypeSd = 12
BusTypeMmc = 13
BusTypeMax = 14
BusTypeMaxReserved = 0x7F

DEVICE_MEDIA_INFO STRUCT
	UNION
		DiskInfo STRUCT
			Cylinders LARGE_INTEGER
			MediaType DD
			TracksPerCylinder DD
			SectorsPerTrack DD
			BytesPerSector DD
			NumberMediaSides DD
			MediaCharacteristics DD
		ENDS
		RemovableDiskInfo STRUCT
			Cylinders LARGE_INTEGER
			MediaType DD
			TracksPerCylinder DD
			SectorsPerTrack DD
			BytesPerSector DD
			NumberMediaSides DD
			MediaCharacteristics DD
		ENDS
		TapeInfo STRUCT
			MediaType DD
			MediaCharacteristics DD
			CurrentBlockSize DD
			BusType DD
			ScsiInformation STRUCT
				MediumType DB
				DensityCode DB
			ENDS
		ENDS
	ENDUNION
ENDS

GET_MEDIA_TYPES STRUCT
	DeviceType DD
	MediaInfoCount DD
	MediaInfo DEVICE_MEDIA_INFO <>
ENDS

STORAGE_PREDICT_FAILURE STRUCT
	PredictFailure DD
	VendorSpecific DB 512 DUP (?)
ENDS

#define PARTITION_ENTRY_UNUSED  0x00
#define PARTITION_FAT_12  0x01
#define PARTITION_XENIX_1  0x02
#define PARTITION_XENIX_2  0x03
#define PARTITION_FAT_16  0x04
#define PARTITION_EXTENDED  0x05
#define PARTITION_HUGE  0x06
#define PARTITION_IFS  0x07
#define PARTITION_FAT32  0x0B
#define PARTITION_FAT32_XINT13  0x0C
#define PARTITION_XINT13  0x0E
#define PARTITION_XINT13_EXTENDED  0x0F
#define PARTITION_PREP  0x41
#define PARTITION_LDM  0x42
#define PARTITION_UNIX  0x63
#define PARTITION_NTFT  0x80
#define VALID_NTFT  0xC0

#define HIST_NO_OF_BUCKETS  24

#define HISTOGRAM_BUCKET_SIZE  sizeof(HISTOGRAM_BUCKET)
#define DISK_HISTOGRAM_SIZE  sizeof(DISK_HISTOGRAM)

#define DISK_LOGGING_START  0
#define DISK_LOGGING_STOP  1
#define DISK_LOGGING_DUMP  2
#define DISK_BINNING  3

#IFNDEF STORAGE_ADAPTER_DESCRIPTOR
STORAGE_ADAPTER_DESCRIPTOR STRUCT
	Version DD
	Size DD
	MaximumTransferLength DD
	MaximumPhysicalPages DD
	AlignmentMask DD
	AdapterUsesPio BOOLEAN
	AdapterScansDown BOOLEAN
	CommandQueueing BOOLEAN
	AcceleratedTransfer BOOLEAN
	BusType DB
	BusMajorVersion DW
	BusMinorVersion DW
ENDS
#ENDIF

STORAGE_ACCESS_ALIGNMENT_DESCRIPTOR STRUCT
	Version DD
	Size DD
	BytesPerCacheLine DD
	BytesOffsetForCacheAlignment DD
	BytesPerLogicalSector DD
	BytesPerPhysicalSector DD
	BytesOffsetForSectorAlignment DD
ENDS

StoragePortCodeSetReserved = 0
StoragePortCodeSetStorport = 1
StoragePortCodeSetSCSIport = 2

STORAGE_MINIPORT_DESCRIPTOR STRUCT
	Version DD
	Size DD
	Portdriver DD
	LUNResetSupported DB
	TargetResetSupported DB
ENDS

StorageIdCodeSetReserved = 0
StorageIdCodeSetBinary = 1
StorageIdCodeSetAscii = 2
StorageIdCodeSetUtf8 = 3

StorageIdTypeVendorSpecific = 0
StorageIdTypeVendorId = 1
StorageIdTypeEUI64 = 2
StorageIdTypeFCPHName = 3
StorageIdTypePortRelative = 4
StorageIdTypeTargetPortGroup = 5
StorageIdTypeLogicalUnitGroup = 6
StorageIdTypeMD5LogicalUnitIdentifier = 7
StorageIdTypeScsiNameString = 8

// Mislabeled above but need to keep it for backwards compatibility
#define StorageIdTypeNAA StorageIdTypeFCPHName

StorageIdNAAFormatIEEEExtended = 2
StorageIdNAAFormatIEEERegistered = 3
StorageIdNAAFormatIEEEERegisteredExtended = 5

StorageIdAssocDevice = 0
StorageIdAssocPort = 1
StorageIdAssocTarget = 2

STORAGE_IDENTIFIER STRUCT
	CodeSet DD
	Type DD
	IdentifierSize DW
	NextOffset DW
	Association DD
	Identifier DB
ENDS

STORAGE_DEVICE_ID_DESCRIPTOR STRUCT
	Version DD
	Size DD
	NumberOfIdentifiers DD
	Identifiers DB
ENDS

STORAGE_GET_BC_PROPERTIES_OUTPUT STRUCT
	MaximumRequestsPerPeriod DD
	MinimumPeriod DD
	MaximumRequestSize DQ
	EstimatedTimePerRequest DD
	NumOutStandingRequests DD
	RequestSize DQ
ENDS

STORAGE_ALLOCATE_BC_STREAM_INPUT STRUCT
	Version DD
	RequestsPerPeriod DD
	Period DD
	RetryFailures DB
	Discardable DB
	Reserved1 DB 2 DUP
	AccessType DD
	AccessMode DD
ENDS

STORAGE_ALLOCATE_BC_STREAM_OUTPUT STRUCT
	RequestSize DQ
	NumOutStandingRequests DD
ENDS

#define STORAGE_PRIORITY_HINT_SUPPORTED     0x0001

STORAGE_PRIORITY_HINT_SUPPORT STRUCT
	SupportFlags DD
ENDS

STORAGE_MEDIA_SERIAL_NUMBER_DATA STRUCT
	Reserved DW
	SerialNumberLength DW
	SerialNumber DB
ENDS

STORAGE_READ_CAPACITY STRUCT
	Version DD
	Size DD
	BlockLength DD
	NumberOfBlocks LARGE_INTEGER
	DiskLength LARGE_INTEGER
ENDS

WriteCacheTypeUnknown = 0
WriteCacheTypeNone = 1
WriteCacheTypeWriteBack = 2
WriteCacheTypeWriteThrough = 3

WriteCacheEnableUnknown = 0
WriteCacheDisabled = 1
WriteCacheEnabled = 2

WriteCacheChangeUnknown = 0
WriteCacheNotChangeable = 1
WriteCacheChangeable = 2

WriteThroughUnknown = 0
WriteThroughNotSupported = 1
WriteThroughSupported = 2

STORAGE_WRITE_CACHE_PROPERTY STRUCT
	Version DD
	Size DD
	WriteCacheType DD
	WriteCacheEnabled DD
	WriteCacheChangeable DD
	WriteThroughSupported DD
	FlushCacheSupported DB
	UserDefinedPowerProtection DB
	NVCacheEnabled DB
ENDS

PERSISTENT_RESERVE_COMMAND STRUCT
	Version DD
	Size DD
	UNION
		PR_IN STRUCT
			ServiceAction DB
			Reserved1 DB
			AllocationLength DW
		ENDS
		PR_OUT STRUCT
			ServiceAction DB
			Type DB
			Scope DB
			ParameterList DB
		ENDS
	ENDUNION
ENDS

;#define IsRecognizedPartition(PartitionType )(  \
;    ((PartitionType & PARTITION_NTFT) && ((PartitionType & ~0xC0) == PARTITION_FAT_12)) || \
;    ((PartitionType & PARTITION_NTFT) && ((PartitionType & ~0xC0) == PARTITION_FAT_16)) || \
;    ((PartitionType & PARTITION_NTFT) && ((PartitionType & ~0xC0) == PARTITION_IFS)) || \
;    ((PartitionType & PARTITION_NTFT) && ((PartitionType & ~0xC0) == PARTITION_HUGE)) || \
;    ((PartitionType & PARTITION_NTFT) && ((PartitionType & ~0xC0) == PARTITION_FAT32)) || \
;    ((PartitionType & PARTITION_NTFT) && ((PartitionType & ~0xC0) == PARTITION_FAT32_XINT13)) || \
;    ((PartitionType & PARTITION_NTFT) && ((PartitionType & ~0xC0) == PARTITION_XINT13)) || \
;    ((PartitionType & ~PARTITION_NTFT) == PARTITION_FAT_12) || \
;    ((PartitionType & ~PARTITION_NTFT) == PARTITION_FAT_16) || \
;    ((PartitionType & ~PARTITION_NTFT) == PARTITION_IFS) || \
;    ((PartitionType & ~PARTITION_NTFT) == PARTITION_HUGE) || \
;    ((PartitionType & ~PARTITION_NTFT) == PARTITION_FAT32) || \
;    ((PartitionType & ~PARTITION_NTFT) == PARTITION_FAT32_XINT13) || \
;    ((PartitionType & ~PARTITION_NTFT) == PARTITION_XINT13))

;#define IsContainerPartition(PartitionType) \
;    ((PartitionType == PARTITION_EXTENDED) || (PartitionType == PARTITION_XINT13_EXTENDED))

;ENUM MEDIA_TYPE
// Unknown = 0
F5_1Pt2_512 = 1
F3_1Pt44_512 = 2
F3_2Pt88_512 = 3
F3_20Pt8_512 = 4
F3_720_512 = 5
F5_360_512 = 6
F5_320_512 = 7
F5_320_1024 = 8
F5_180_512 = 9
F5_160_512 = 10
RemovableMedia = 11
FixedMedia = 12
F3_120M_512 = 13
F3_640_512 = 14
F5_640_512 = 15
F5_720_512 = 16
F3_1Pt2_512 = 17
F3_1Pt23_1024 = 18
F5_1Pt23_1024 = 19
F3_128Mb_512 = 20
F3_230Mb_512 = 21
F8_256_128 = 22
F3_200Mb_512 = 23
F3_240M_512 = 24
F3_32M_512 = 25

FORMAT_PARAMETERS STRUCT
	MediaType DD
	StartCylinderNumber DD
	EndCylinderNumber DD
	StartHeadNumber DD
	EndHeadNumber DD
ENDS

FORMAT_EX_PARAMETERS STRUCT
	MediaType DD
	StartCylinderNumber DD
	EndCylinderNumber DD
	StartHeadNumber DD
	EndHeadNumber DD
	FormatGapLength DW
	SectorsPerTrack DW
	SectorNumber DW
ENDS

DISK_GEOMETRY STRUCT
	Cylinders DQ
	MediaType DD
	TracksPerCylinder DD
	SectorsPerTrack DD
	BytesPerSector DD
ENDS

#define WMI_DISK_GEOMETRY_GUID  <0x25007f51,0x57c2,0x11d1,<0xa5,0x28,0x0,0xa0,0xc9,0x6,0x29,0x10>>

PARTITION_INFORMATION STRUCT
	StartingOffset DQ
	PartitionLength DQ
	HiddenSectors DD
	PartitionNumber DD
	PartitionType DB
	BootIndicator DD
	RecognizedPartition DD
	RewritePartition DD
ENDS

SET_PARTITION_INFORMATION STRUCT
	PartitionType DB
ENDS

DRIVE_LAYOUT_INFORMATION STRUCT
	PartitionCount DD
	Signature DD
	PartitionEntry PARTITION_INFORMATION <>
ENDS

VERIFY_INFORMATION STRUCT
	StartingOffset DQ
	Length DD
ENDS

REASSIGN_BLOCKS STRUCT
	Reserved DW
	Count DW
	BlockNumber DD
ENDS

DISK_CONTROLLER_NUMBER STRUCT
	ControllerNumber DD
	DiskNumber DD
ENDS

VOLUME_COMPRESSION_STATE STRUCT
	CompressNewFiles DD
ENDS

PARTITION_STYLE_MBR = 0
PARTITION_STYLE_GPT = 1
PARTITION_STYLE_RAW = 2

PARTITION_INFORMATION_GPT STRUCT
	PartitionType GUID
	PartitionId GUID
	Attributes DQ
	Name DW 36 DUP
ENDS

#define GPT_ATTRIBUTE_PLATFORM_REQUIRED             0x0000000000000001
#define GPT_BASIC_DATA_ATTRIBUTE_NO_DRIVE_LETTER    0x8000000000000000
#define GPT_BASIC_DATA_ATTRIBUTE_HIDDEN             0x4000000000000000
#define GPT_BASIC_DATA_ATTRIBUTE_SHADOW_COPY        0x2000000000000000
#define GPT_BASIC_DATA_ATTRIBUTE_READ_ONLY          0x1000000000000000

PARTITION_INFORMATION_MBR STRUCT
	PartitionType DB
	BootIndicator DB
	RecognizedPartition DB
	HiddenSectors DD
ENDS

SET_PARTITION_INFORMATION_EX STRUCT
    PARTITION_STYLE PartitionStyle DD
	UNION
		Mbr SET_PARTITION_INFORMATION_MBR
		Gpt SET_PARTITION_INFORMATION_GPT
	ENDUNION
ENDS

CREATE_DISK_GPT STRUCT
	DiskId GUID
	MaxPartitionCount DD
ENDS

CREATE_DISK_MBR STRUCT
	Signature DD
ENDS

CREATE_DISK STRUCT
    PARTITION_STYLE PartitionStyle DD
	UNION
		Mbr CREATE_DISK_MBR
		Gpt CREATE_DISK_GPT
	ENDUNION
ENDS

GET_LENGTH_INFORMATION STRUCT
	Length LARGE_INTEGER
ENDS

PARTITION_INFORMATION_EX STRUCT
	PartitionStyle DD
	StartingOffset LARGE_INTEGER
	PartitionLength LARGE_INTEGER
	PartitionNumber DD
	RewritePartition DB
	UNION
		Mbr PARTITION_INFORMATION_MBR
		Gpt PARTITION_INFORMATION_GPT
	ENDUNION
ENDS

DRIVE_LAYOUT_INFORMATION_GPT STRUCT
	DiskId GUID
	StartingUsableOffset LARGE_INTEGER
	UsableLength LARGE_INTEGER
	MaxPartitionCount DD
ENDS

DRIVE_LAYOUT_INFORMATION_MBR STRUCT
	Signature DD
ENDS

DRIVE_LAYOUT_INFORMATION_EX STRUCT
	PartitionStyle DD
	PartitionCount DD
	UNION
		Mbr PARTITION_INFORMATION_MBR
		Gpt PARTITION_INFORMATION_GPT
	ENDUNION
	PartitionEntry PARTITION_INFORMATION_EX
ENDS

DetectNone = 0
DetectInt13 = 1
DetectExInt13 = 2

DISK_INT13_INFO STRUCT
	DriveSelect DW
	MaxCylinders DD
	SectorsPerTrack DW
	MaxHeads DW
	NumberDrives DW
ENDS

DISK_EX_INT13_INFO STRUCT
	ExBufferSize DW
	ExFlags DW
	ExCylinders DD
	ExHeads DD
	ExSectorsPerTrack DD
	ExSectorsPerDrive DQ
	ExSectorSize DW
	ExReserved DW
ENDS

DISK_DETECTION_INFO STRUCT
	SizeOfDetectInfo DD
	DetectionType DD
	UNION
		STRUCT
			Int13 DISK_INT13_INFO
			ExInt13 DISK_EX_INT13_INFO
		ENDS
	ENDUNION
ENDS

DISK_PARTITION_INFO STRUCT
	SizeOfPartitionInfo DD
	PartitionStyle DD
	UNION
		Mbr STRUCT
			Signature DD
			CheckSum DD
		ENDS
		Gpt STRUCT
			DiskId GUID
		ENDS
	ENDUNION
ENDS

DISK_GEOMETRY_EX STRUCT
	Geometry DISK_GEOMETRY
	DiskSize LARGE_INTEGER
	Data DB
ENDS

DISK_CONTROLLER_NUMBER STRUCT
	ControllerNumber DD
	DiskNumber DD
ENDS

#define EqualPriority 0
#define KeepPrefetchedData 1
#define KeepReadData 2

DiskWriteCacheNormal = 0
DiskWriteCacheForceDisable = 1
DiskWriteCacheDisableNotSupported = 2

DISK_CACHE_INFORMATION STRUCT
	ParametersSavable DD
	ReadCacheEnabled DD
	WriteCacheEnabled DD
	ReadRetentionPriority DD
	WriteRetentionPriority DD
	DisablePrefetchTransferLength DW
	PrefetchScalar DD
    UNION
		ScalarPrefetch STRUCT
			Minimum DW
			Maximum DW
			MaximumBlocks DW
		ENDS
		BlockPrefetch STRUCT
			Minimum DW
			Maximum DW
		ENDS
	ENDUNION
ENDS

DISK_GROW_PARTITION STRUCT
	PartitionNumber DD
	BytesToGrow DQ
ENDS

HISTOGRAM_BUCKET STRUCT
	Reads DD
	Writes DD
ENDS

DISK_HISTOGRAM STRUCT
	DiskSize DQ
	Start DQ
	End DQ
	Average DQ
	AverageRead DQ
	AverageWrite DQ
	Granularity DD
	Size DD
	ReadCount DD
	WriteCount DD
	Histogram DD
ENDS

DISK_PERFORMANCE STRUCT
	BytesRead DQ
	BytesWritten DQ
	ReadTime DQ
	WriteTime DQ
	IdleTime DQ
	ReadCount DD
	WriteCount DD
	QueueDepth DD
	SplitCount DD
	QueryTime DQ
	StorageDeviceNumber DD
	StorageManagerName DW 8 DUP (?)
ENDS

DISK_RECORD STRUCT
	ByteOffset DQ
	StartTime DQ
	EndTime DQ
	VirtualAddress DD
	NumberOfBytes DD
	DeviceNumber DB
	ReadRequest DD
ENDS

DISK_LOGGING STRUCT
	Function DB
	BufferAddress DD
	BufferSize DD
ENDS

ENUM_BIN_TYPES STRUCT
    RequestSize DB
    RequestLocation DB
ENDS

BIN_RANGE STRUCT
	StartValue DQ
	Length DQ
ENDS

PERF_BIN STRUCT
	NumberOfBins DD
	TypeOfBin DD
	BinsRanges BIN_RANGE <>
ENDS

BIN_COUNT STRUCT
	BinRange BIN_RANGE <>
	BinCount DD
ENDS

BIN_RESULTS STRUCT
	NumberOfBins DD
	BinCounts BIN_RANGE <>
ENDS

GETVERSIONINPARAMS STRUCT
	bVersion DB
	bRevision DB
	bReserved DB
	bIDEDeviceMap DB
	fCapabilities DD
	dwReserved DD 4 DUP ?
ENDS

#define CAP_ATA_ID_CMD  1
#define CAP_ATAPI_ID_CMD  2
#define CAP_SMART_CMD  4

IDEREGS STRUCT
	bFeaturesReg DB
	bSectorCountReg DB
	bSectorNumberReg DB
	bCylLowReg DB
	bCylHighReg DB
	bDriveHeadReg DB
	bCommandReg DB
	bReserved DB
ENDS

#define ATAPI_ID_CMD  0xA1
#define ID_CMD  0xEC
#define SMART_CMD  0xB0

#define SMART_CYL_LOW  0x4F
#define SMART_CYL_HI  0xC2

SENDCMDINPARAMS STRUCT
	cBufferSize DD
	irDriveRegs IDEREGS <>
	bDriveNumber DB
	bReserved DB 3 DUP (?)
	dwReserved DD 4 DUP (?)
	bBuffer DB
ENDS

DRIVERSTATUS STRUCT
	bDriverError DB
	bIDEError DB
	bReserved DB 2 DUP (?)
	dwReserved DD 2 DUP (?)
ENDS

#define SMART_NO_ERROR  0
#define SMART_IDE_ERROR  1
#define SMART_INVALID_FLAG  2
#define SMART_INVALID_COMMAND  3
#define SMART_INVALID_BUFFER  4
#define SMART_INVALID_DRIVE  5
#define SMART_INVALID_IOCTL  6
#define SMART_ERROR_NO_MEM  7
#define SMART_INVALID_REGISTER  8
#define SMART_NOT_SUPPORTED  9
#define SMART_NO_IDE_DEVICE  10

SENDCMDOUTPARAMS STRUCT
	cBufferSize DD
	DriverStatus DRIVERSTATUS <>
	bBuffer DB
ENDS

#define READ_ATTRIBUTE_BUFFER_SIZE  512
#define IDENTIFY_BUFFER_SIZE  512
#define READ_THRESHOLD_BUFFER_SIZE  512

#define READ_ATTRIBUTES  0xD0
#define READ_THRESHOLDS  0xD1
#define ENABLE_DISABLE_AUTOSAVE  0xD2
#define SAVE_ATTRIBUTE_VALUES  0xD3
#define EXECUTE_OFFLINE_DIAGS  0xD4
#define ENABLE_SMART  0xD8
#define DISABLE_SMART  0xD9
#define RETURN_SMART_STATUS  0xDA
#define ENABLE_DISABLE_AUTO_OFFLINE  0xDB

#define MAX_VOLUME_ID_SIZE  36
#define MAX_VOLUME_TEMPLATE_SIZE  40

#define VENDOR_ID_LENGTH  8
#define PRODUCT_ID_LENGTH  16
#define REVISION_LENGTH  4
#define SERIAL_NUMBER_LENGTH  32

#define AllElements 0
#define ChangerTransport 1
#define ChangerSlot 2
#define ChangerIEPort 3
#define ChangerDrive 4
#define ChangerDoor 5
#define ChangerKeypad 6
#define ChangerMaxElement 7

CHANGER_ELEMENT STRUCT
	ElementType DD
	ElementAddress DD
ENDS

CHANGER_ELEMENT_LIST STRUCT
	Element CHANGER_ELEMENT <>
	NumberOfElements DD
ENDS

#define CHANGER_BAR_CODE_SCANNER_INSTALLED  0x00000001
#define CHANGER_INIT_ELEM_STAT_WITH_RANGE  0x00000002
#define CHANGER_CLOSE_IEPORT  0x00000004
#define CHANGER_OPEN_IEPORT  0x00000008
#define CHANGER_STATUS_NON_VOLATILE  0x00000010
#define CHANGER_EXCHANGE_MEDIA  0x00000020
#define CHANGER_CLEANER_SLOT  0x00000040
#define CHANGER_LOCK_UNLOCK  0x00000080
#define CHANGER_CARTRIDGE_MAGAZINE  0x00000100
#define CHANGER_MEDIUM_FLIP  0x00000200
#define CHANGER_POSITION_TO_ELEMENT  0x00000400
#define CHANGER_REPORT_IEPORT_STATE  0x00000800
#define CHANGER_STORAGE_DRIVE  0x00001000
#define CHANGER_STORAGE_IEPORT  0x00002000
#define CHANGER_STORAGE_SLOT  0x00004000
#define CHANGER_STORAGE_TRANSPORT  0x00008000
#define CHANGER_DRIVE_CLEANING_REQUIRED  0x00010000
#define CHANGER_PREDISMOUNT_EJECT_REQUIRED  0x00020000
#define CHANGER_CLEANER_ACCESS_NOT_VALID  0x00040000
#define CHANGER_PREMOUNT_EJECT_REQUIRED  0x00080000
#define CHANGER_VOLUME_IDENTIFICATION  0x00100000
#define CHANGER_VOLUME_SEARCH  0x00200000
#define CHANGER_VOLUME_ASSERT  0x00400000
#define CHANGER_VOLUME_REPLACE  0x00800000
#define CHANGER_VOLUME_UNDEFINE  0x01000000
#define CHANGER_SERIAL_NUMBER_VALID  0x04000000
#define CHANGER_DEVICE_REINITIALIZE_CAPABLE 0x08000000
#define CHANGER_KEYPAD_ENABLE_DISABLE  0x10000000
#define CHANGER_DRIVE_EMPTY_ON_DOOR_ACCESS  0x20000000
#define CHANGER_RESERVED_BIT  0x80000000
#define CHANGER_PREDISMOUNT_ALIGN_TO_SLOT  0x80000001
#define CHANGER_PREDISMOUNT_ALIGN_TO_DRIVE  0x80000002
#define CHANGER_CLEANER_AUTODISMOUNT  0x80000004
#define CHANGER_TRUE_EXCHANGE_CAPABLE  0x80000008
#define CHANGER_SLOTS_USE_TRAYS  0x80000010
#define CHANGER_RTN_MEDIA_TO_ORIGINAL_ADDR  0x80000020
#define CHANGER_CLEANER_OPS_NOT_SUPPORTED  0x80000040
#define CHANGER_IEPORT_USER_CONTROL_OPEN  0x80000080
#define CHANGER_IEPORT_USER_CONTROL_CLOSE  0x80000100
#define CHANGER_MOVE_EXTENDS_IEPORT  0x80000200
#define CHANGER_MOVE_RETRACTS_IEPORT  0x80000400

#define CHANGER_TO_TRANSPORT  0x01
#define CHANGER_TO_SLOT  0x02
#define CHANGER_TO_IEPORT  0x04
#define CHANGER_TO_DRIVE  0x08

#define LOCK_UNLOCK_IEPORT  0x01
#define LOCK_UNLOCK_DOOR  0x02
#define LOCK_UNLOCK_KEYPAD  0x04

GET_CHANGER_PARAMETERS STRUCT
	Size DD
	NumberTransportElements DW
	NumberStorageElements DW
	NumberCleanerSlots DW
	NumberIEElements DW
	NumberDataTransferElements DW
	NumberOfDoors DW
	FirstSlotNumber DW
	FirstDriveNumber DW
	FirstTransportNumber DW
	FirstIEPortNumber DW
	FirstCleanerSlotAddress DW
	MagazineSize DW
	DriveCleanTimeout DD
	Features0 DD
	Features1 DD
	MoveFromTransport DB
	MoveFromSlot DB
	MoveFromIePort DB
	MoveFromDrive DB
	ExchangeFromTransport DB
	ExchangeFromSlot DB
	ExchangeFromIePort DB
	ExchangeFromDrive DB
	LockUnlockCapabilities DB
	PositionCapabilities DB
	Reserved1 DB 2 DUP (?)
	Reserved2 DD 2 DUP (?)
ENDS

CHANGER_PRODUCT_DATA STRUCT
	VendorId DB VENDOR_ID_LENGTH DUP (?)
	ProductId DB PRODUCT_ID_LENGTH DUP (?)
	Revision DB REVISION_LENGTH  DUP (?)
	SerialNumber DB SERIAL_NUMBER_LENGTH DUP (?)
	DeviceType DB
ENDS

#define LOCK_ELEMENT  0
#define UNLOCK_ELEMENT  1
#define EXTEND_IEPORT  2
#define RETRACT_IEPORT  3

CHANGER_SET_ACCESS STRUCT
	Element CHANGER_ELEMENT <>
	Control DD
ENDS

CHANGER_READ_ELEMENT_STATUS STRUCT
	ElementList CHANGER_ELEMENT_LIST <>
	VolumeTagInfo DD
ENDS

CHANGER_ELEMENT_STATUS STRUCT
	Element CHANGER_ELEMENT <>
	SrcElementAddress CHANGER_ELEMENT <>
	Flags DD
	ExceptionCode DD
	TargetId DB
	Lun DB
	Reserved DW
	PrimaryVolumeID DB MAX_VOLUME_ID_SIZE DUP (?)
	AlternateVolumeID DB MAX_VOLUME_ID_SIZE DUP (?)
ENDS

#define ELEMENT_STATUS_FULL  0x00000001
#define ELEMENT_STATUS_IMPEXP  0x00000002
#define ELEMENT_STATUS_EXCEPT  0x00000004
#define ELEMENT_STATUS_ACCESS  0x00000008
#define ELEMENT_STATUS_EXENAB  0x00000010
#define ELEMENT_STATUS_INENAB  0x00000020

#define ELEMENT_STATUS_LUN_VALID 0x00001000
#define ELEMENT_STATUS_ID_VALID  0x00002000
#define ELEMENT_STATUS_NOT_BUS  0x00008000
#define ELEMENT_STATUS_INVERT  0x00400000
#define ELEMENT_STATUS_SVALID  0x00800000

#define ELEMENT_STATUS_PVOLTAG  0x10000000
#define ELEMENT_STATUS_AVOLTAG  0x20000000

#define ERROR_LABEL_UNREADABLE  0x00000001
#define ERROR_LABEL_QUESTIONABLE  0x00000002
#define ERROR_SLOT_NOT_PRESENT  0x00000004
#define ERROR_DRIVE_NOT_INSTALLED 0x00000008
#define ERROR_TRAY_MALFUNCTION  0x00000010
#define ERROR_INIT_STATUS_NEEDED  0x00000011
#define ERROR_UNHANDLED_ERROR  0xFFFFFFFF

CHANGER_INITIALIZE_ELEMENT_STATUS STRUCT
	ElementList CHANGER_ELEMENT_LIST <>
	BarCodeScan DD
ENDS

CHANGER_SET_POSITION STRUCT
	Transport CHANGER_ELEMENT <>
	Destination CHANGER_ELEMENT <>
	Flip DD
ENDS

CHANGER_EXCHANGE_MEDIUM STRUCT
	Transport CHANGER_ELEMENT <>
	Source CHANGER_ELEMENT <>
	Destination1 CHANGER_ELEMENT <>
	Destination2 CHANGER_ELEMENT <>
	Flip1 DD
	Flip2 DD
ENDS

CHANGER_MOVE_MEDIUM STRUCT
	Transport CHANGER_ELEMENT <>
	Source CHANGER_ELEMENT <>
	Destination CHANGER_ELEMENT <>
	Flip DD
ENDS

CHANGER_SEND_VOLUME_TAG_INFORMATION STRUCT
	StartingElement CHANGER_ELEMENT <>
	ActionCode DD
	VolumeIDTemplate DB MAX_VOLUME_TEMPLATE_SIZE DUP (?)
ENDS

READ_ELEMENT_ADDRESS_INFO STRUCT
	NumberOfElements DD
	ElementStatus CHANGER_ELEMENT_STATUS <>
ENDS

#define SEARCH_ALL  0x0
#define SEARCH_PRIMARY  0x1
#define SEARCH_ALTERNATE  0x2
#define SEARCH_ALL_NO_SEQ  0x4
#define SEARCH_PRI_NO_SEQ  0x5
#define SEARCH_ALT_NO_SEQ  0x6

#define ASSERT_PRIMARY  0x8
#define ASSERT_ALTERNATE  0x9

#define REPLACE_PRIMARY  0xA
#define REPLACE_ALTERNATE  0xB

#define UNDEFINE_PRIMARY  0xC
#define UNDEFINE_ALTERNATE  0xD

DeviceProblemNone = 0
DeviceProblemHardware = 1
DeviceProblemCHMError = 2
DeviceProblemDoorOpen = 3
DeviceProblemCalibrationError = 4
DeviceProblemTargetFailure = 5
DeviceProblemCHMMoveError = 6
DeviceProblemCHMZeroError = 7
DeviceProblemCartridgeInsertError = 8
DeviceProblemPositionError = 9
DeviceProblemSensorError = 10
DeviceProblemCartridgeEjectError = 11
DeviceProblemGripperError = 12
DeviceProblemDriveError = 13

// Nobody seems to have the def for FILE_DEVICE_AVIO, Tim Roberts set it to 0x99 but
// admits he pulled the number out of thin air.
// http://www.osronline.com/ShowThread.cfm?link=121697
#define FILE_DEVICE_AVIO 0x99

#define IOCTL_AVIO_ALLOCATE_STREAM (FILE_DEVICE_AVIO<<16)|(1<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)
#define IOCTL_AVIO_FREE_STREAM (FILE_DEVICE_AVIO<<16)|(2<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)
#define IOCTL_AVIO_MODIFY_STREAM (FILE_DEVICE_AVIO<<16)|(3<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)

#define IOCTL_SERIAL_LSRMST_INSERT  (FILE_DEVICE_SERIAL_PORT<<16)|(31<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SERENUM_EXPOSE_HARDWARE  (FILE_DEVICE_SERENUM<<16)|(128<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SERENUM_REMOVE_HARDWARE  (FILE_DEVICE_SERENUM<<16)|(129<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SERENUM_PORT_DESC  (FILE_DEVICE_SERENUM<<16)|(130<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define IOCTL_SERENUM_GET_PORT_NAME  (FILE_DEVICE_SERENUM<<16)|(131<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)

#define SERIAL_LSRMST_ESCAPE 0
#define SERIAL_LSRMST_LSR_DATA  1
#define SERIAL_LSRMST_LSR_NODATA  2
#define SERIAL_LSRMST_MST  3

#define SERIAL_IOC_FCR_FIFO_ENABLE  0x00000001
#define SERIAL_IOC_FCR_RCVR_RESET  0x00000002
#define SERIAL_IOC_FCR_XMIT_RESET  0x00000004
#define SERIAL_IOC_FCR_DMA_MODE  0x00000008
#define SERIAL_IOC_FCR_RES1  0x00000010
#define SERIAL_IOC_FCR_RES2  0x00000020
#define SERIAL_IOC_FCR_RCVR_TRIGGER_LSB  0x00000040
#define SERIAL_IOC_FCR_RCVR_TRIGGER_MSB  0x00000080

#define SERIAL_IOC_MCR_DTR  0x00000001
#define SERIAL_IOC_MCR_RTS  0x00000002
#define SERIAL_IOC_MCR_OUT1  0x00000004
#define SERIAL_IOC_MCR_OUT2  0x00000008
#define SERIAL_IOC_MCR_LOOP  0x00000010

#define FSCTL_REQUEST_OPLOCK_LEVEL_1  (FILE_DEVICE_FILE_SYSTEM<<16)|(0<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_REQUEST_OPLOCK_LEVEL_2  (FILE_DEVICE_FILE_SYSTEM<<16)|(1<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_REQUEST_BATCH_OPLOCK  (FILE_DEVICE_FILE_SYSTEM<<16)|(2<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_OPLOCK_BREAK_ACKNOWLEDGE  (FILE_DEVICE_FILE_SYSTEM<<16)|(3<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_OPBATCH_ACK_CLOSE_PENDING  (FILE_DEVICE_FILE_SYSTEM<<16)|(4<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_OPLOCK_BREAK_NOTIFY  (FILE_DEVICE_FILE_SYSTEM<<16)|(5<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_LOCK_VOLUME  (FILE_DEVICE_FILE_SYSTEM<<16)|(6<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_UNLOCK_VOLUME  (FILE_DEVICE_FILE_SYSTEM<<16)|(7<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_DISMOUNT_VOLUME  (FILE_DEVICE_FILE_SYSTEM<<16)|(8<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_IS_VOLUME_MOUNTED  (FILE_DEVICE_FILE_SYSTEM<<16)|(10<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_IS_PATHNAME_VALID  (FILE_DEVICE_FILE_SYSTEM<<16)|(11<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_MARK_VOLUME_DIRTY  (FILE_DEVICE_FILE_SYSTEM<<16)|(12<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_QUERY_RETRIEVAL_POINTERS  (FILE_DEVICE_FILE_SYSTEM<<16)|(14<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_GET_COMPRESSION  (FILE_DEVICE_FILE_SYSTEM<<16)|(15<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_SET_COMPRESSION  (FILE_DEVICE_FILE_SYSTEM<<16)|(16<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define FSCTL_MARK_AS_SYSTEM_HIVE  (FILE_DEVICE_FILE_SYSTEM<<16)|(19<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_OPLOCK_BREAK_ACK_NO_2  (FILE_DEVICE_FILE_SYSTEM<<16)|(20<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_INVALIDATE_VOLUMES  (FILE_DEVICE_FILE_SYSTEM<<16)|(21<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_QUERY_FAT_BPB  (FILE_DEVICE_FILE_SYSTEM<<16)|(22<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_REQUEST_FILTER_OPLOCK  (FILE_DEVICE_FILE_SYSTEM<<16)|(23<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_FILESYSTEM_GET_STATISTICS  (FILE_DEVICE_FILE_SYSTEM<<16)|(24<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_GET_NTFS_VOLUME_DATA  (FILE_DEVICE_FILE_SYSTEM<<16)|(25<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_GET_NTFS_FILE_RECORD  (FILE_DEVICE_FILE_SYSTEM<<16)|(26<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_GET_VOLUME_BITMAP  (FILE_DEVICE_FILE_SYSTEM<<16)|(27<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_GET_RETRIEVAL_POINTERS  (FILE_DEVICE_FILE_SYSTEM<<16)|(28<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_MOVE_FILE  (FILE_DEVICE_FILE_SYSTEM<<16)|(29<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)
#define FSCTL_IS_VOLUME_DIRTY  (FILE_DEVICE_FILE_SYSTEM<<16)|(30<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_GET_HFS_INFORMATION  (FILE_DEVICE_FILE_SYSTEM<<16)|(31<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_ALLOW_EXTENDED_DASD_IO  (FILE_DEVICE_FILE_SYSTEM<<16)|(32<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_READ_PROPERTY_DATA  (FILE_DEVICE_FILE_SYSTEM<<16)|(33<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_WRITE_PROPERTY_DATA  (FILE_DEVICE_FILE_SYSTEM<<16)|(34<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_FIND_FILES_BY_SID  (FILE_DEVICE_FILE_SYSTEM<<16)|(35<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_DUMP_PROPERTY_DATA  (FILE_DEVICE_FILE_SYSTEM<<16)|(37<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_SET_OBJECT_ID  (FILE_DEVICE_FILE_SYSTEM<<16)|(38<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)
#define FSCTL_GET_OBJECT_ID  (FILE_DEVICE_FILE_SYSTEM<<16)|(39<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_DELETE_OBJECT_ID  (FILE_DEVICE_FILE_SYSTEM<<16)|(40<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)
#define FSCTL_SET_REPARSE_POINT  (FILE_DEVICE_FILE_SYSTEM<<16)|(41<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)
#define FSCTL_GET_REPARSE_POINT  (FILE_DEVICE_FILE_SYSTEM<<16)|(42<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_DELETE_REPARSE_POINT  (FILE_DEVICE_FILE_SYSTEM<<16)|(43<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)
#define FSCTL_ENUM_USN_DATA  (FILE_DEVICE_FILE_SYSTEM<<16)|(44<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_SECURITY_ID_CHECK  (FILE_DEVICE_FILE_SYSTEM<<16)|(45<<2)|METHOD_NEITHER|(FILE_READ_ACCESS<<14)
#define FSCTL_READ_USN_JOURNAL  (FILE_DEVICE_FILE_SYSTEM<<16)|(46<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_SET_OBJECT_ID_EXTENDED  (FILE_DEVICE_FILE_SYSTEM<<16)|(47<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)
#define FSCTL_CREATE_OR_GET_OBJECT_ID  (FILE_DEVICE_FILE_SYSTEM<<16)|(48<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_SET_SPARSE  (FILE_DEVICE_FILE_SYSTEM<<16)|(49<<2)|METHOD_BUFFERED|(FILE_SPECIAL_ACCESS<<14)
#define FSCTL_SET_ZERO_DATA  (FILE_DEVICE_FILE_SYSTEM<<16)|(50<<2)|METHOD_BUFFERED|(FILE_WRITE_ACCESS<<14)
#define FSCTL_QUERY_ALLOCATED_RANGES  (FILE_DEVICE_FILE_SYSTEM<<16)|(51<<2)|METHOD_NEITHER|(FILE_READ_ACCESS<<14)
#define FSCTL_ENABLE_UPGRADE  (FILE_DEVICE_FILE_SYSTEM<<16)|(52<<2)|METHOD_BUFFERED|(FILE_WRITE_ACCESS<<14)
#define FSCTL_SET_ENCRYPTION  (FILE_DEVICE_FILE_SYSTEM<<16)|(53<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_ENCRYPTION_FSCTL_IO  (FILE_DEVICE_FILE_SYSTEM<<16)|(54<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_WRITE_RAW_ENCRYPTED  (FILE_DEVICE_FILE_SYSTEM<<16)|(55<<2)|METHOD_NEITHER|(FILE_SPECIAL_ACCESS<<14)
#define FSCTL_READ_RAW_ENCRYPTED  (FILE_DEVICE_FILE_SYSTEM<<16)|(56<<2)|METHOD_NEITHER|(FILE_SPECIAL_ACCESS<<14)
#define FSCTL_CREATE_USN_JOURNAL  (FILE_DEVICE_FILE_SYSTEM<<16)|(57<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_READ_FILE_USN_DATA  (FILE_DEVICE_FILE_SYSTEM<<16)|(58<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_WRITE_USN_CLOSE_RECORD  (FILE_DEVICE_FILE_SYSTEM<<16)|(59<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_EXTEND_VOLUME  (FILE_DEVICE_FILE_SYSTEM<<16)|(60<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_QUERY_USN_JOURNAL  (FILE_DEVICE_FILE_SYSTEM<<16)|(61<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_DELETE_USN_JOURNAL  (FILE_DEVICE_FILE_SYSTEM<<16)|(62<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_MARK_HANDLE  (FILE_DEVICE_FILE_SYSTEM<<16)|(63<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_SIS_COPYFILE  (FILE_DEVICE_FILE_SYSTEM<<16)|(64<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)
#define FSCTL_SIS_LINK_FILES  (FILE_DEVICE_FILE_SYSTEM<<16)|(65<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define FSCTL_HSM_MSG  (FILE_DEVICE_FILE_SYSTEM<<16)|(66<<2)|METHOD_BUFFERED|(FILE_READWRITE_ACCESS<<14)
#define FSCTL_NSS_CONTROL  (FILE_DEVICE_FILE_SYSTEM<<16)|(67<<2)|METHOD_BUFFERED|(FILE_WRITE_ACCESS<<14)
#define FSCTL_HSM_DATA  (FILE_DEVICE_FILE_SYSTEM<<16)|(68<<2)|METHOD_NEITHER|(FILE_READWRITE_ACCESS<<14)
#define FSCTL_RECALL_FILE  (FILE_DEVICE_FILE_SYSTEM<<16)|(69<<2)|METHOD_NEITHER|(FILE_ANY_ACCESS<<14)
#define FSCTL_NSS_RCONTROL  (FILE_DEVICE_FILE_SYSTEM<<16)|(70<<2)|METHOD_BUFFERED|(FILE_READ_ACCESS<<14)

PATHNAME_BUFFER STRUCT
	PathNameLength DD
	Name DW
ENDS

FSCTL_QUERY_FAT_BPB_BUFFER STRUCT
	First0x24BytesOfBootSector DB 024h DUP (?)
ENDS

NTFS_VOLUME_DATA_BUFFER STRUCT
	VolumeSerialNumber DQ
	NumberSectors DQ
	TotalClusters DQ
	FreeClusters DQ
	TotalReserved DQ
	BytesPerSector DD
	BytesPerCluster DD
	BytesPerFileRecordSegment DD
	ClustersPerFileRecordSegment DD
	MftValidDataLength DQ
	MftStartLcn DQ
	Mft2StartLcn DQ
	MftZoneStart DQ
	MftZoneEnd DQ
ENDS

NTFS_EXTENDED_VOLUME_DATA STRUCT
	ByteCount DD
	MajorVersion DW
	MinorVersion DW
ENDS

STARTING_LCN_INPUT_BUFFER STRUCT
	StartingLcn DQ
ENDS

VOLUME_BITMAP_BUFFER STRUCT
	StartingLcn DQ
	BitmapSize DQ
	Buffer DB
ENDS

STARTING_VCN_INPUT_BUFFER STRUCT
	StartingVcn DQ
ENDS

RETRIEVAL_POINTERS_BUFFER STRUCT
	ExtentCount DD
	StartingVcn DQ
	Extents STRUCT
		NextVcn DQ
		Lcn DQ
	ENDS
ENDS

NTFS_FILE_RECORD_INPUT_BUFFER STRUCT
	FileReferenceNumber DQ
ENDS

NTFS_FILE_RECORD_OUTPUT_BUFFER STRUCT
	FileReferenceNumber DQ
	FileRecordLength DD
	FileRecordBuffer DB
ENDS

MOVE_FILE_DATA STRUCT
	FileHandle DD
	StartingVcn DQ
	StartingLcn DQ
	ClusterCount DD
ENDS

#IFDEF WIN64

MOVE_FILE_DATA32 STRUCT
	FileHandle DD
	StartingVcn DQ
	StartingLcn DQ
	ClusterCount DD
ENDS

MARK_HANDLE_INFO32 STRUCT
	UsnSourceInfo DD
	VolumeHandle DD
	HandleInfo DD
ENDS

#ENDIF

HFS_INFORMATION_BUFFER STRUCT
	FinderInfo DB 32 DUP (?)
ENDS

FIND_BY_SID_DATA STRUCT
	Restart DD
	Sid SID <>
ENDS

MFT_ENUM_DATA STRUCT
	StartFileReferenceNumber DQ
	LowUsn DQ
	HighUsn DQ
ENDS

CREATE_USN_JOURNAL_DATA STRUCT
	MaximumSize DQ
	AllocationDelta DQ
ENDS

READ_USN_JOURNAL_DATA STRUCT
	StartUsn DQ
	ReasonMask DD
	ReturnOnlyOnClose DD
	Timeout DQ
	BytesToWaitFor DQ
	UsnJournalID DQ
ENDS

USN_RECORD STRUCT
	RecordLength DD
	MajorVersion DW
	MinorVersion DW
	FileReferenceNumber DQ
	ParentFileReferenceNumber DQ
	Usn DQ
	TimeStamp DQ
	Reason DD
	SourceInfo DD
	SecurityId DD
	FileAttributes DD
	FileNameLength DQ
	FileNameOffset DW
	FileName DW
ENDS

#define USN_PAGE_SIZE  (0x1000)

#define USN_REASON_DATA_OVERWRITE  (0x00000001)
#define USN_REASON_DATA_EXTEND  (0x00000002)
#define USN_REASON_DATA_TRUNCATION  (0x00000004)
#define USN_REASON_NAMED_DATA_OVERWRITE  (0x00000010)
#define USN_REASON_NAMED_DATA_EXTEND  (0x00000020)
#define USN_REASON_NAMED_DATA_TRUNCATION  (0x00000040)
#define USN_REASON_FILE_CREATE  (0x00000100)
#define USN_REASON_FILE_DELETE  (0x00000200)
#define USN_REASON_EA_CHANGE  (0x00000400)
#define USN_REASON_SECURITY_CHANGE  (0x00000800)
#define USN_REASON_RENAME_OLD_NAME  (0x00001000)
#define USN_REASON_RENAME_NEW_NAME  (0x00002000)
#define USN_REASON_INDEXABLE_CHANGE  (0x00004000)
#define USN_REASON_BASIC_INFO_CHANGE  (0x00008000)
#define USN_REASON_HARD_LINK_CHANGE  (0x00010000)
#define USN_REASON_COMPRESSION_CHANGE  (0x00020000)
#define USN_REASON_ENCRYPTION_CHANGE  (0x00040000)
#define USN_REASON_OBJECT_ID_CHANGE  (0x00080000)
#define USN_REASON_REPARSE_POINT_CHANGE  (0x00100000)
#define USN_REASON_STREAM_CHANGE  (0x00200000)
#define USN_REASON_CLOSE  (0x80000000)

USN_JOURNAL_DATA STRUCT
	UsnJournalID DQ
	FirstUsn DQ
	NextUsn DQ
	LowestValidUsn DQ
	MaxUsn DQ
	MaximumSize DQ
	AllocationDelta DQ
ENDS

DELETE_USN_JOURNAL_DATA STRUCT
	UsnJournalID DQ
	DeleteFlags DD
ENDS

#define USN_DELETE_FLAG_DELETE  (0x00000001)
#define USN_DELETE_FLAG_NOTIFY  (0x00000002)
#define USN_DELETE_VALID_FLAGS  (0x00000003)

MARK_HANDLE_INFO STRUCT
	UsnSourceInfo DD
	VolumeHandle DD
	HandleInfo DD
ENDS

#define USN_SOURCE_DATA_MANAGEMENT  (0x00000001)
#define USN_SOURCE_AUXILIARY_DATA  (0x00000002)
#define USN_SOURCE_REPLICATION_MANAGEMENT  (0x00000004)


BULK_SECURITY_TEST_DATA STRUCT
	DesiredAccess DD
	SecurityIds DD
ENDS

#define VOLUME_IS_DIRTY  (0x00000001)
#define VOLUME_UPGRADE_SCHEDULED  (0x00000002)

FILESYSTEM_STATISTICS STRUCT
	FileSystemType DW
	Version DW
	SizeOfCompleteStructure DD
	UserFileReads DD
	UserFileReadBytes DD
	UserDiskReads DD
	UserFileWrites DD
	UserFileWriteBytes DD
	UserDiskWrites DD
	MetaDataReads DD
	MetaDataReadBytes DD
	MetaDataDiskReads DD
	MetaDataWrites DD
	MetaDataWriteBytes DD
	MetaDataDiskWrites DD
ENDS

#define FILESYSTEM_STATISTICS_TYPE_NTFS  1
#define FILESYSTEM_STATISTICS_TYPE_FAT  2

FAT_STATISTICS STRUCT
	CreateHits DD
	SuccessfulCreates DD
	FailedCreates DD
	NonCachedReads DD
	NonCachedReadBytes DD
	NonCachedWrites DD
	NonCachedWriteBytes DD
	NonCachedDiskReads DD
	NonCachedDiskWrites DD
ENDS

EXFAT_STATISTICS STRUCT
	CreateHits DD
	SuccessfulCreates DD
	FailedCreates DD
	NonCachedReads DD
	NonCachedReadBytes DD
	NonCachedWrites DD
	NonCachedWriteBytes DD
	NonCachedDiskReads DD
	NonCachedDiskWrites DD
ENDS

NTFS_STATISTICS STRUCT
	LogFileFullExceptions DD
	OtherExceptions DD
	MftReads DD
	MftReadBytes DD
	MftWrites DD
	MftWriteBytes DD
	MftWritesUserLevel struct
		Write DW
		Create DW
		SetInfo DW
		Flush DW
	ENDS

	MftWritesFlushForLogFileFull DW
	MftWritesLazyWriter DW
	MftWritesUserRequest DW

	Mft2Writes DD
	Mft2WriteBytes DD
	Mft2WritesUserLevel struct
		Write DW
		Create DW
		SetInfo DW
		Flush DW
	ENDS

	Mft2WritesFlushForLogFileFull DW
	Mft2WritesLazyWriter DW
	Mft2WritesUserRequest DW

	RootIndexReads DD
	RootIndexReadBytes DD
	RootIndexWrites DD
	RootIndexWriteBytes DD

	BitmapReads DD
	BitmapReadBytes DD
	BitmapWrites DD
	BitmapWriteBytes DD

	BitmapWritesFlushForLogFileFull DW
	BitmapWritesLazyWriter DW
	BitmapWritesUserRequest DW

	BitmapWritesUserLevel struct
		Write DW
		Create DW
		SetInfo DW
	ENDS

	MftBitmapReads DD
	MftBitmapReadBytes DD
	MftBitmapWrites DD
	MftBitmapWriteBytes DD

	MftBitmapWritesFlushForLogFileFull DW
	MftBitmapWritesLazyWriter DW
	MftBitmapWritesUserRequest DW

	MftBitmapWritesUserLevel struct
		Write DW
		Create DW
		SetInfo DW
		Flush DW
	ENDS

	UserIndexReads DD
	UserIndexReadBytes DD
	UserIndexWrites DD
	UserIndexWriteBytes DD

    //
    // Additions for NT 5.0
    //

	LogFileReads DD
	LogFileReadBytes DD
	LogFileWrites DD
	LogFileWriteBytes DD

	Allocate STRUCT
		Calls DD                // number of individual calls to allocate clusters
		Clusters DD             // number of clusters allocated
		Hints DD                // number of times a hint was specified

		RunsReturned DD         // number of runs used to satisify all the requests

		HintsHonored DD         // number of times the hint was useful
		HintsClusters DD        // number of clusters allocated via the hint
		Cache DD                // number of times the cache was useful other than the hint
		CacheClusters DD        // number of clusters allocated via the cache other than the hint
		CacheMiss DD            // number of times the cache wasn't useful
		CacheMissClusters DD    // number of clusters allocated without the cache
	ENDS

ENDS

FILE_OBJECTID_BUFFER STRUCT
	ObjectId DB 16 DUP (?)
	UNION
        ExtendedInfostruct STRUCT
			BirthVolumeId DB 16 DUP (?)
			BirthObjectId DB 16 DUP (?)
			DomainId DB 16 DUP (?)
		ENDS
		ExtendedInfo DB 48 DUP (?)
	ENDUNION
ENDS

FILE_SET_SPARSE_BUFFER STRUCT
	SetSparse DD
ENDS

FILE_ZERO_DATA_INFORMATION STRUCT
	FileOffset DQ
	BeyondFinalZero DQ
ENDS

FILE_ALLOCATED_RANGE_BUFFER STRUCT
	FileOffset DQ
	Length DQ
ENDS

ENCRYPTION_BUFFER STRUCT
	EncryptionOperation DD
	Private DB
ENDS

#define FILE_SET_ENCRYPTION  0x00000001
#define FILE_CLEAR_ENCRYPTION  0x00000002
#define STREAM_SET_ENCRYPTION  0x00000003
#define STREAM_CLEAR_ENCRYPTION  0x00000004

#define MAXIMUM_ENCRYPTION_VALUE  0x00000004

DECRYPTION_STATUS_BUFFER STRUCT
	NoEncryptedStreams DD
ENDS

#define ENCRYPTION_FORMAT_DEFAULT  0x01
#define COMPRESSION_FORMAT_SPARSE  0x4000

REQUEST_RAW_ENCRYPTED_DATA STRUCT
	FileOffset DQ
	Length DD
ENDS

ENCRYPTED_DATA_INFO STRUCT
	StartingFileOffset DQ
	OutputBufferOffset DD
	BytesWithinFileSize DD
	BytesWithinValidDataLength DD
	CompressionFormat DW
	DataUnitShift DB
	ChunkShift DB
	ClusterShift DB
	EncryptionFormat DB
	NumberOfDataBlocks DW
	DataBlockSize DD
ENDS

SI_COPYFILE STRUCT
	SourceFileNameLength DD
	DestinationFileNameLength DD
	Flags DD
	FileNameBuffer DW
ENDS

#define COPYFILE_SIS_LINK  0x0001
#define COPYFILE_SIS_REPLACE  0x0002
#define COPYFILE_SIS_FLAGS  0x0003

NSS_CONTROL STRUCT
	code DD
	param DD
ENDS

#define NSS_CONTROL_MARK  1
#define NSS_CONTROL_UNMARK  2
#define NSS_CONTROL_ISNSSFILE  4

#define IOCTL_VOLUME_BASE  A'V'
#define IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS  (IOCTL_VOLUME_BASE<<16)|(0<<2)|METHOD_BUFFERED|(FILE_ANY_ACCESS<<14)

DISK_EXTENT STRUCT
	DiskNumber DD
	StartingOffset DQ
	ExtentLength DQ
ENDS

VOLUME_DISK_EXTENTS STRUCT
	NumberOfDiskExtents DD
	Extents DISK_EXTENT <>
ENDS

#endif /* _WINIOCTL_H */

