#ifndef WINSVC_H
#define WINSVC_H

#define WINSVC_H_REQVER 100

#IFDEF LINKFILES
	#dynamiclinkfile Advapi32.dll
#ENDIF

/* Windows Service Control Manager definitions */

#define SERVICES_ACTIVE_DATABASEW  L"ServicesActive"
#define SERVICES_FAILED_DATABASEW  L"ServicesFailed"
#define SERVICES_ACTIVE_DATABASEA  A"ServicesActive"
#define SERVICES_FAILED_DATABASEA  A"ServicesFailed"

#define SC_GROUP_IDENTIFIERW  L'+'
#define SC_GROUP_IDENTIFIERA  A'+'

#IFDEF UNICODE
	#define SERVICES_ACTIVE_DATABASE  SERVICES_ACTIVE_DATABASEW
	#define SERVICES_FAILED_DATABASE  SERVICES_FAILED_DATABASEW
	#define SC_GROUP_IDENTIFIER  SC_GROUP_IDENTIFIERW
#else
	#define SERVICES_ACTIVE_DATABASE  SERVICES_ACTIVE_DATABASEA
	#define SERVICES_FAILED_DATABASE  SERVICES_FAILED_DATABASEA
	#define SC_GROUP_IDENTIFIER  SC_GROUP_IDENTIFIERA
#endif

#define SERVICE_NO_CHANGE  0xFFFFFFFF

#define SERVICE_ACTIVE  0x00000001
#define SERVICE_INACTIVE  0x00000002
#define SERVICE_STATE_ALL  (SERVICE_ACTIVE|SERVICE_INACTIVE)

#define SERVICE_CONTROL_STOP  0x00000001
#define SERVICE_CONTROL_PAUSE  0x00000002
#define SERVICE_CONTROL_CONTINUE  0x00000003
#define SERVICE_CONTROL_INTERROGATE  0x00000004
#define SERVICE_CONTROL_SHUTDOWN  0x00000005
#define SERVICE_CONTROL_PARAMCHANGE  0x00000006
#define SERVICE_CONTROL_NETBINDADD  0x00000007
#define SERVICE_CONTROL_NETBINDREMOVE  0x00000008
#define SERVICE_CONTROL_NETBINDENABLE  0x00000009
#define SERVICE_CONTROL_NETBINDDISABLE  0x0000000A
#define SERVICE_CONTROL_DEVICEEVENT  0x0000000B
#define SERVICE_CONTROL_HARDWAREPROFILECHANGE  0x0000000C
#define SERVICE_CONTROL_POWEREVENT  0x0000000D

#define SERVICE_STOPPED  0x00000001
#define SERVICE_START_PENDING  0x00000002
#define SERVICE_STOP_PENDING  0x00000003
#define SERVICE_RUNNING  0x00000004
#define SERVICE_CONTINUE_PENDING  0x00000005
#define SERVICE_PAUSE_PENDING  0x00000006
#define SERVICE_PAUSED  0x00000007

#define SERVICE_ACCEPT_STOP  0x00000001
#define SERVICE_ACCEPT_PAUSE_CONTINUE  0x00000002
#define SERVICE_ACCEPT_SHUTDOWN  0x00000004
#define SERVICE_ACCEPT_PARAMCHANGE  0x00000008
#define SERVICE_ACCEPT_NETBINDCHANGE  0x00000010
#define SERVICE_ACCEPT_HARDWAREPROFILECHANGE  0x00000020
#define SERVICE_ACCEPT_POWEREVENT  0x00000040

#define SC_MANAGER_CONNECT  0x0001
#define SC_MANAGER_CREATE_SERVICE  0x0002
#define SC_MANAGER_ENUMERATE_SERVICE  0x0004
#define SC_MANAGER_LOCK  0x0008
#define SC_MANAGER_QUERY_LOCK_STATUS  0x0010
#define SC_MANAGER_MODIFY_BOOT_CONFIG  0x0020
#define SC_MANAGER_ALL_ACCESS  (STANDARD_RIGHTS_REQUIRED|SC_MANAGER_CONNECT|SC_MANAGER_CREATE_SERVICE|SC_MANAGER_ENUMERATE_SERVICE|SC_MANAGER_LOCK|SC_MANAGER_QUERY_LOCK_STATUS|SC_MANAGER_MODIFY_BOOT_CONFIG)

#define SERVICE_QUERY_CONFIG  0x0001
#define SERVICE_CHANGE_CONFIG  0x0002
#define SERVICE_QUERY_STATUS  0x0004
#define SERVICE_ENUMERATE_DEPENDENTS  0x0008
#define SERVICE_START  0x0010
#define SERVICE_STOP  0x0020
#define SERVICE_PAUSE_CONTINUE  0x0040
#define SERVICE_INTERROGATE  0x0080
#define SERVICE_USER_DEFINED_CONTROL  0x0100
#define SERVICE_ALL_ACCESS  (STANDARD_RIGHTS_REQUIRED|SERVICE_QUERY_CONFIG|SERVICE_CHANGE_CONFIG|SERVICE_QUERY_STATUS|SERVICE_ENUMERATE_DEPENDENTS|SERVICE_START|SERVICE_STOP|SERVICE_PAUSE_CONTINUE|SERVICE_INTERROGATE|SERVICE_USER_DEFINED_CONTROL)

#define SERVICE_RUNS_IN_SYSTEM_PROCESS  0x00000001

#define SERVICE_CONFIG_DESCRIPTION  1
#define SERVICE_CONFIG_FAILURE_ACTIONS  2

SERVICE_DESCRIPTIONA STRUCT
	lpDescription PTR
ENDS

SERVICE_DESCRIPTIONW STRUCT
	lpDescription PTR
ENDS

SC_ACTION_NONE=0
SC_ACTION_RESTART=1
SC_ACTION_REBOOT=2
SC_ACTION_RUN_COMMAND=3

SC_ACTION STRUCT
	Type DD
	Delay DD
ENDS

SERVICE_FAILURE_ACTIONSA STRUCT
	dwResetPeriod DD
	lpRebootMsg PTR
	lpCommand PTR
	cActions DD
	lpsaActions PTR
ENDS

SERVICE_FAILURE_ACTIONSW STRUCT
	dwResetPeriod DD
	lpRebootMsg PTR
	lpCommand PTR
	cActions DD
	lpsaActions PTR
ENDS

SC_STATUS_PROCESS_INFO=0
SC_ENUM_PROCESS_INFO=0

SERVICE_STATUS STRUCT
	dwServiceType DD
	dwCurrentState DD
	dwControlsAccepted DD
	dwWin32ExitCode DD
	dwServiceSpecificExitCode DD
	dwCheckPoint DD
	dwWaitHint DD
ENDS

SERVICE_STATUS_PROCESS STRUCT
	dwServiceType DD
	dwCurrentState DD
	dwControlsAccepted DD
	dwWin32ExitCode DD
	dwServiceSpecificExitCode DD
	dwCheckPoint DD
	dwWaitHint DD
	dwProcessId DD
	dwServiceFlags DD
ENDS

ENUM_SERVICE_STATUSA STRUCT
	lpServiceName PTR
	lpDisplayName PTR
	ServiceStatus SERVICE_STATUS <>
ENDS

ENUM_SERVICE_STATUSW STRUCT
	lpServiceName PTR
	lpDisplayName PTR
	ServiceStatus SERVICE_STATUS <>
ENDS

ENUM_SERVICE_STATUS_PROCESSA STRUCT
	lpServiceName PTR
	lpDisplayName PTR
	ServiceStatusProcess SERVICE_STATUS_PROCESS <>
ENDS

ENUM_SERVICE_STATUS_PROCESSW STRUCT
	lpServiceName PTR
	lpDisplayName PTR
	ServiceStatusProcess SERVICE_STATUS_PROCESS <>
ENDS

QUERY_SERVICE_LOCK_STATUSA STRUCT
	fIsLocked DD
	lpLockOwner PTR
	dwLockDuration DD
ENDS

QUERY_SERVICE_LOCK_STATUSW STRUCT
	fIsLocked DD
	lpLockOwner PTR
	dwLockDuration DD
ENDS

QUERY_SERVICE_CONFIGA STRUCT
	dwServiceType DD
	dwStartType DD
	dwErrorControl DD
	lpBinaryPathName PTR
	lpLoadOrderGroup PTR
	dwTagId DD
	lpDependencies PTR
	lpServiceStartName PTR
	lpDisplayName PTR
ENDS

QUERY_SERVICE_CONFIGW STRUCT
	dwServiceType DD
	dwStartType DD
	dwErrorControl DD
	lpBinaryPathName PTR
	lpLoadOrderGroup PTR
	dwTagId DD
	lpDependencies PTR
	lpServiceStartName PTR
	lpDisplayName PTR
ENDS

SERVICE_TABLE_ENTRYA STRUCT
	lpServiceName PTR
	lpServiceProc PTR
ENDS

SERVICE_TABLE_ENTRYW STRUCT
	lpServiceName PTR
	lpServiceProc PTR
ENDS

#IFDEF UNICODE
	#DEFINE SERVICE_DESCRIPTION SERVICE_DESCRIPTIONW
	#DEFINE SERVICE_FAILURE_ACTIONS SERVICE_FAILURE_ACTIONSW
	#DEFINE ENUM_SERVICE_STATUS ENUM_SERVICE_STATUSW
	#DEFINE ENUM_SERVICE_STATUS_PROCESS ENUM_SERVICE_STATUS_PROCESSW
	#DEFINE QUERY_SERVICE_LOCK_STATUS QUERY_SERVICE_LOCK_STATUSW
	#DEFINE QUERY_SERVICE_CONFIG QUERY_SERVICE_CONFIGW
	#DEFINE SERVICE_TABLE_ENTRY SERVICE_TABLE_ENTRYW
	#define ChangeServiceConfig ChangeServiceConfigW
	#define ChangeServiceConfig2 ChangeServiceConfig2W
	#define CreateService CreateServiceW
	#define EnumDependentServices EnumDependentServicesW
	#define EnumServicesStatus EnumServicesStatusW
	#define EnumServicesStatusEx EnumServicesStatusExW
	#define GetServiceKeyName GetServiceKeyNameW
	#define GetServiceDisplayName GetServiceDisplayNameW
	#define OpenSCManager OpenSCManagerW
	#define OpenService OpenServiceW
	#define QueryServiceConfig QueryServiceConfigW
	#define QueryServiceConfig2 QueryServiceConfig2W
	#define QueryServiceLockStatus QueryServiceLockStatusW
	#define RegisterServiceCtrlHandler RegisterServiceCtrlHandlerW
	#define RegisterServiceCtrlHandlerEx RegisterServiceCtrlHandlerExW
	#define StartServiceCtrlDispatcher StartServiceCtrlDispatcherW
	#define StartService StartServiceW
#else
	#DEFINE SERVICE_DESCRIPTION SERVICE_DESCRIPTIONA
	#DEFINE SERVICE_FAILURE_ACTIONS SERVICE_FAILURE_ACTIONSA
	#DEFINE ENUM_SERVICE_STATUS ENUM_SERVICE_STATUSA
	#DEFINE ENUM_SERVICE_STATUS_PROCESS ENUM_SERVICE_STATUS_PROCESSA
	#DEFINE QUERY_SERVICE_LOCK_STATUS QUERY_SERVICE_LOCK_STATUSA
	#DEFINE QUERY_SERVICE_CONFIG QUERY_SERVICE_CONFIGA
	#DEFINE SERVICE_TABLE_ENTRY SERVICE_TABLE_ENTRYA
	#define ChangeServiceConfig ChangeServiceConfigA
	#define ChangeServiceConfig2 ChangeServiceConfig2A
	#define CreateService CreateServiceA
	#define EnumDependentServices EnumDependentServicesA
	#define EnumServicesStatus EnumServicesStatusA
	#define EnumServicesStatusEx EnumServicesStatusExA
	#define GetServiceKeyName GetServiceKeyNameA
	#define GetServiceDisplayName GetServiceDisplayNameA
	#define OpenSCManager OpenSCManagerA
	#define OpenService OpenServiceA
	#define QueryServiceConfig QueryServiceConfigA
	#define QueryServiceConfig2 QueryServiceConfig2A
	#define QueryServiceLockStatus QueryServiceLockStatusA
	#define RegisterServiceCtrlHandler RegisterServiceCtrlHandlerA
	#define RegisterServiceCtrlHandlerEx RegisterServiceCtrlHandlerExA
	#define StartServiceCtrlDispatcher StartServiceCtrlDispatcherA
	#define StartService StartServiceA
#endif /* UNICODE */

#endif /* _WINSVC_H */
