#ifndef WINTRUST_H
#define WINTRUST_H

/* Windows Internet Security Trust Provider Model definitions */
#IFNDEF WINCRYPT_H
	#include wincrypt.h
#ENDIF

#IFDEF LINKFILES
	#dynamiclinkfile Wintrust.dll
#ENDIF

#define WINTRUST_CONFIG_REGPATH L"Software\\Microsoft\\Cryptography\\Wintrust\\Config"
#define WINTRUST_MAX_HEADER_BYTES_TO_MAP_VALUE_NAME     L"MaxHeaderBytesToMap"
#define WINTRUST_MAX_HEADER_BYTES_TO_MAP_DEFAULT        0x00A00000
#define WINTRUST_MAX_HASH_BYTES_TO_MAP_VALUE_NAME       L"MaxHashBytesToMap"
#define WINTRUST_MAX_HASH_BYTES_TO_MAP_DEFAULT          0x00100000

#define WTD_UI_ALL  1
#define WTD_UI_NONE  2
#define WTD_UI_NOBAD  3
#define WTD_UI_NOGOOD  4
#define WTD_REVOKE_NONE  0x00000000
#define WTD_REVOKE_WHOLECHAIN  0x00000001
#define WTD_CHOICE_FILE  1
#define WTD_CHOICE_CATALOG  2
#define WTD_CHOICE_BLOB  3
#define WTD_CHOICE_SIGNER  4
#define WTD_CHOICE_CERT  5
#define WTD_STATEACTION_IGNORE  0x00000000
#define WTD_STATEACTION_VERIFY  0x00000001
#define WTD_STATEACTION_CLOSE  0x00000002
#define WTD_STATEACTION_AUTO_CACHE  0x00000003
#define WTD_STATEACTION_AUTO_CACHE_FLUSH  0x00000004
#define WTD_PROV_FLAGS_MASK  0x0000FFFF
#define WTD_USE_IE4_TRUST_FLAG  0x00000001
#define WTD_NO_IE4_CHAIN_FLAG  0x00000002
#define WTD_NO_POLICY_USAGE_FLAG  0x00000004
#define WTD_REVOCATION_CHECK_NONE  0x00000010
#define WTD_REVOCATION_CHECK_END_CERT  0x00000020
#define WTD_REVOCATION_CHECK_CHAIN  0x00000040
#define WTD_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT  0x00000080
#define WTD_SAFER_FLAG 0x00000100
#define WTD_HASH_ONLY_FLAG 0x00000200
#define WTD_USE_DEFAULT_OSVER_CHECK 0x00000400
#define WTD_LIFETIME_SIGNING_FLAG 0x00000800
#define WTD_CACHE_ONLY_URL_RETRIEVAL 0x00001000

#define WTD_UICONTEXT_EXECUTE 0
#define WTD_UICONTEXT_INSTALL 1

#define WTCI_DONT_OPEN_STORES  0x00000001
#define WTCI_OPEN_ONLY_ROOT  0x00000002
#define WTCI_USE_LOCAL_MACHINE  0x00000004

#define WTPF_TRUSTTEST  0x00000020
#define WTPF_TESTCANBEVALID  0x00000080
#define WTPF_IGNOREEXPIRATION  0x00000100
#define WTPF_IGNOREREVOKATION  0x00000200
#define WTPF_OFFLINEOK_IND  0x00000400
#define WTPF_OFFLINEOK_COM  0x00000800
#define WTPF_OFFLINEOKNBU_IND  0x00001000
#define WTPF_OFFLINEOKNBU_COM  0x00002000
#define WTPF_VERIFY_V1_OFF  0x00010000
#define WTPF_IGNOREREVOCATIONONTS  0x00020000
#define WTPF_ALLOWONLYPERTRUST  0x00040000

#define TRUSTERROR_STEP_WVTPARAMS  0
#define TRUSTERROR_STEP_FILEIO  2
#define TRUSTERROR_STEP_SIP  3
#define TRUSTERROR_STEP_SIPSUBJINFO  5
#define TRUSTERROR_STEP_CATALOGFILE  6
#define TRUSTERROR_STEP_CERTSTORE  7
#define TRUSTERROR_STEP_MESSAGE  8
#define TRUSTERROR_STEP_MSG_SIGNERCOUNT  9
#define TRUSTERROR_STEP_MSG_INNERCNTTYPE  10
#define TRUSTERROR_STEP_MSG_INNERCNT  11
#define TRUSTERROR_STEP_MSG_STORE  12
#define TRUSTERROR_STEP_MSG_SIGNERINFO  13
#define TRUSTERROR_STEP_MSG_SIGNERCERT  14
#define TRUSTERROR_STEP_MSG_CERTCHAIN  15
#define TRUSTERROR_STEP_MSG_COUNTERSIGINFO  16
#define TRUSTERROR_STEP_MSG_COUNTERSIGCERT  17
#define TRUSTERROR_STEP_VERIFY_MSGHASH  18
#define TRUSTERROR_STEP_VERIFY_MSGINDIRECTDATA  19
#define TRUSTERROR_STEP_FINAL_WVTINIT  30
#define TRUSTERROR_STEP_FINAL_INITPROV  31
#define TRUSTERROR_STEP_FINAL_OBJPROV  32
#define TRUSTERROR_STEP_FINAL_SIGPROV  33
#define TRUSTERROR_STEP_FINAL_CERTPROV  34
#define TRUSTERROR_STEP_FINAL_CERTCHKPROV  35
#define TRUSTERROR_STEP_FINAL_POLICYPROV  36
#define TRUSTERROR_STEP_FINAL_UIPROV  37
#define TRUSTERROR_MAX_STEPS  38

#define CPD_CHOICE_SIP  1

#define CPD_USE_NT5_CHAIN_FLAG  0x80000000
#define CPD_REVOCATION_CHECK_NONE  0x00010000
#define CPD_REVOCATION_CHECK_END_CERT  0x00020000
#define CPD_REVOCATION_CHECK_CHAIN  0x00040000
#define CPD_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT  0x00080000

#define CPD_UISTATE_MODE_PROMPT 0x00000000
#define CPD_UISTATE_MODE_BLOCK 0x00000001
#define CPD_UISTATE_MODE_ALLOW 0x00000002
#define CPD_UISTATE_MODE_MASK 0x00000003

#define SGNR_TYPE_TIMESTAMP  0x00000010

#define CERT_CONFIDENCE_SIG  0x10000000
#define CERT_CONFIDENCE_TIME  0x01000000
#define CERT_CONFIDENCE_TIMENEST  0x00100000
#define CERT_CONFIDENCE_AUTHIDEXT  0x00010000
#define CERT_CONFIDENCE_HYGIENE  0x00001000
#define CERT_CONFIDENCE_HIGHEST  0x11111000

#define WT_CURRENT_VERSION  0x00000200

#define WT_PROVIDER_DLL_NAME  L"WINTRUST.DLL"
#define WT_PROVIDER_CERTTRUST_FUNCTION  L"WintrustCertificateTrust"

#define WT_ADD_ACTION_ID_RET_RESULT_FLAG    0x1

#define DWACTION_ALLOCANDFILL  1
#define DWACTION_FREE  2

#define szOID_TRUSTED_CODESIGNING_CA_LIST  "1.3.6.1.4.1.311.2.2.1"
#define szOID_TRUSTED_CLIENT_AUTH_CA_LIST  "1.3.6.1.4.1.311.2.2.2"
#define szOID_TRUSTED_SERVER_AUTH_CA_LIST  "1.3.6.1.4.1.311.2.2.3"

#define SPC_COMMON_NAME_OBJID  szOID_COMMON_NAME
#define SPC_TIME_STAMP_REQUEST_OBJID  "1.3.6.1.4.1.311.3.2.1"
#define SPC_INDIRECT_DATA_OBJID  "1.3.6.1.4.1.311.2.1.4"
#define SPC_SP_AGENCY_INFO_OBJID  "1.3.6.1.4.1.311.2.1.10"
#define SPC_STATEMENT_TYPE_OBJID  "1.3.6.1.4.1.311.2.1.11"
#define SPC_SP_OPUS_INFO_OBJID  "1.3.6.1.4.1.311.2.1.12"
#define SPC_CERT_EXTENSIONS_OBJID  "1.3.6.1.4.1.311.2.1.14"
#define SPC_PE_IMAGE_DATA_OBJID  "1.3.6.1.4.1.311.2.1.15"
#define SPC_RAW_FILE_DATA_OBJID  "1.3.6.1.4.1.311.2.1.18"
#define SPC_STRUCTURED_STORAGE_DATA_OBJID  "1.3.6.1.4.1.311.2.1.19"
#define SPC_JAVA_CLASS_DATA_OBJID  "1.3.6.1.4.1.311.2.1.20"
#define SPC_INDIVIDUAL_SP_KEY_PURPOSE_OBJID "1.3.6.1.4.1.311.2.1.21"
#define SPC_COMMERCIAL_SP_KEY_PURPOSE_OBJID "1.3.6.1.4.1.311.2.1.22"
#define SPC_CAB_DATA_OBJID  "1.3.6.1.4.1.311.2.1.25"
#define SPC_GLUE_RDN_OBJID  "1.3.6.1.4.1.311.2.1.25"
#define SPC_MINIMAL_CRITERIA_OBJID  "1.3.6.1.4.1.311.2.1.26"
#define SPC_FINANCIAL_CRITERIA_OBJID  "1.3.6.1.4.1.311.2.1.27"
#define SPC_LINK_OBJID  "1.3.6.1.4.1.311.2.1.28"
#define SPC_SIGINFO_OBJID  "1.3.6.1.4.1.311.2.1.30"

#define SPC_PE_IMAGE_PAGE_HASHES_V1_OBJID   "1.3.6.1.4.1.311.2.3.1"     // V1
#define SPC_PE_IMAGE_PAGE_HASHES_V2_OBJID   "1.3.6.1.4.1.311.2.3.2"     // V2

#define CAT_NAMEVALUE_OBJID  "1.3.6.1.4.1.311.12.2.1"
#define CAT_MEMBERINFO_OBJID  "1.3.6.1.4.1.311.12.2.2"

#define SpcSerializedObjectAttributesClassId <0xA6, 0xB5, 0x86, 0xD5, 0xB4, 0xA1, 0x24, 0x66, 0xAE, 0x05, 0xA2, 0x17, 0xDA, 0x8E, 0x60, 0xD6>

#define SPC_SP_AGENCY_INFO_STRUCT  2000
#define SPC_MINIMAL_CRITERIA_STRUCT  2001
#define SPC_FINANCIAL_CRITERIA_STRUCT  2002
#define SPC_INDIRECT_DATA_CONTENT_STRUCT  2003
#define SPC_PE_IMAGE_DATA_STRUCT  2004
#define SPC_LINK_STRUCT  2005
#define SPC_STATEMENT_TYPE_STRUCT  2006
#define SPC_SP_OPUS_INFO_STRUCT  2007
#define SPC_CAB_DATA_STRUCT  2008
#define SPC_JAVA_CLASS_DATA_STRUCT  2009
#define SPC_SIGINFO_STRUCT  2130
#define CAT_NAMEVALUE_STRUCT  2221
#define CAT_MEMBERINFO_STRUCT  2222

#define SPC_URL_LINK_CHOICE  1
#define SPC_MONIKER_LINK_CHOICE  2
#define SPC_FILE_LINK_CHOICE  3

WINTRUST_DATA STRUCT
	cbStruct DD
	pPolicyCallbackData PTR
	pSIPClientData PTR
	dwUIChoice DD
	fdwRevocationChecks DD
	dwUnionChoice DD
	UNION
		pFile PTR
		pCatalog PTR
		pBlob PTR
		pSgnr PTR
		pCert PTR
	ENDUNION
	dwStateAction DD
	hWVTStateData HANDLE
	pwszURLReference PTR
	dwProvFlags DD
	dwUIContext DD
ENDS

WINTRUST_FILE_INFO STRUCT
	cbStruct DD
	pcwszFilePath PTR
	hFile HANDLE
	pgKnownSubject PTR
ENDS

WINTRUST_CATALOG_INFO STRUCT
	cbStruct DD
	dwCatalogVersion DD
	pcwszCatalogFilePath PTR
	pcwszMemberTag PTR
	pcwszMemberFilePath PTR
	hMemberFile HANDLE
	pbCalculatedFileHash PTR
	cbCalculatedFileHash DD
	pcCatalogContext PTR
ENDS

WINTRUST_BLOB_INFO STRUCT
	cbStruct DD
	gSubject GUID
	pcwszDisplayName PTR
	cbMem DD
	pbMem PTR
	cbMemSignedMsg DD
	pbMemSignedMsg PTR
ENDS

WINTRUST_SGNR_INFO STRUCT
	cbStruct DD
	pcwszDisplayName PTR
	psSignerInfo PTR
	chStores DD
	pahStores PTR
ENDS

WINTRUST_CERT_INFO STRUCT
	cbStruct DD
	pcwszDisplayName PTR
	psCertContext PTR
	chStores DD
	pahStores PTR
	dwFlags DD
	psftVerifyAsOf PTR
ENDS


CRYPT_PROVIDER_DATA STRUCT
	cbStruct DD
	pWintrustData PTR
	fOpenedFile DD
	hWndParent HANDLE
	pgActionID DD
	hProv HANDLE
	dwError DD
	dwRegSecuritySettings DD
	dwRegPolicySettings DD
	psPfns PTR
	cdwTrustStepErrors DD
	padwTrustStepErrors PTR
	chStores DD
	pahStores PTR
	dwEncoding DD
	hMsg HANDLE
	csSigners DD
	pasSigners PTR
	csProvPrivData DD
	pasProvPrivData PTR
	dwSubjectChoice DD
	pPDSip PTR
	pszUsageOID PTR
	fRecallWithState DD
	sftSystemTime FILETIME
	pszCTLSignerUsageOID PTR
	dwProvFlags DD
	dwFinalError DD
	pRequestUsage PTR
ENDS

CRYPT_PROVIDER_FUNCTIONS STRUCT
	cbStruct DD
	pfnAlloc PTR
	pfnFree PTR
	pfnAddStore2Chain PTR
	pfnAddSgnr2Chain PTR
	pfnAddCert2Chain PTR
	pfnAddPrivData2Chain PTR
	pfnInitialize PTR
	pfnObjectTrust PTR
	pfnSignatureTrust PTR
	pfnCertificateTrust PTR
	pfnFinalPolicy PTR
	pfnCertCheckPolicy PTR
	pfnTestFinalPolicy PTR
	psUIpfns PTR
	pfnCleanupPolicy PTR
ENDS

CRYPT_PROVUI_FUNCS STRUCT
	cbStruct DD
	psUIData PTR
	pfnOnMoreInfoClick PTR
	pfnOnMoreInfoClickDefault PTR
	pfnOnAdvancedClick PTR
	pfnOnAdvancedClickDefault PTR
ENDS

CRYPT_PROVUI_DATA STRUCT
	cbStruct DD
	dwFinalError DD
	pYesButtonText PTR
	pNoButtonText PTR
	pMoreInfoButtonText PTR
	pAdvancedLinkText PTR
	pCopyActionText PTR
	pCopyActionTextNoTS PTR
	pCopyActionTextNotSigned PTR
ENDS

CRYPT_PROVIDER_SGNR STRUCT
	cbStruct DD
	sftVerifyAsOf FILETIME
	csCertChain DD
	pasCertChain PTR
	dwSignerType DD
	psSigner PTR
	dwError DD
	csCounterSigners DD
	pasCounterSigners PTR
	pChainContext PTR
ENDS

CRYPT_PROVIDER_CERT STRUCT
	cbStruct DD
	pCert PTR
	fCommercial DD
	fTrustedRoot DD
	fSelfSigned DD
	fTestCert DD
	dwRevokedReason DD
	dwConfidence DD
	dwError DD
	pTrustListContext PTR
	fTrustListSignerCert DD
	pCtlContext PTR
	dwCtlError DD
	fIsCyclic DD
ENDS

CRYPT_PROVIDER_PRIVDATA STRUCT
	cbStruct DD
	gProviderID GUID
	cbProvData DD
	pvProvData PTR
ENDS

PROVDATA_SIP STRUCT
	cbStruct DD
	gSubject GUID
	pSip PTR
	pCATSip PTR
	psSipSubjectInfo PTR
	psSipCATSubjectInfo PTR
	psIndirectData PTR
ENDS

CRYPT_TRUST_REG_ENTRY STRUCT
	cbStruct DD
	pwszDLLName PTR
	pwszFunctionName PTR
ENDS

CRYPT_REGISTER_ACTIONID STRUCT
	cbStruct DD
	sInitProvider CRYPT_TRUST_REG_ENTRY
	sObjectProvider CRYPT_TRUST_REG_ENTRY
	sSignatureProvider CRYPT_TRUST_REG_ENTRY
	sCertificateProvider CRYPT_TRUST_REG_ENTRY
	sCertificatePolicyProvider CRYPT_TRUST_REG_ENTRY
	sFinalPolicyProvider CRYPT_TRUST_REG_ENTRY
	sTestPolicyProvider CRYPT_TRUST_REG_ENTRY
	sCleanupProvider CRYPT_TRUST_REG_ENTRY
ENDS

CRYPT_PROVIDER_REGDEFUSAGE STRUCT
	cbStruct DD
	pgActionID PTR
	pwszDllName PTR
	pwszLoadCallbackDataFunctionName PTR
	pwszFreeCallbackDataFunctionName PTR
ENDS

CRYPT_PROVIDER_DEFUSAGE STRUCT
	cbStruct DD
	gActionID GUID
	pDefPolicyCallbackData PTR
	pDefSIPClientData PTR
ENDS

#define SPC_UUID_LENGTH  16

SPC_SERIALIZED_OBJECT STRUCT
	ClassId DB SPC_UUID_LENGTH DUP
	SerializedData CRYPT_DATA_BLOB
ENDS

SPC_SIGINFO STRUCT
	dwSipVersion DD
	gSIPGuid GUID
	dwReserved1 DD
	dwReserved2 DD
	dwReserved3 DD
	dwReserved4 DD
	dwReserved5 DD
ENDS

SPC_LINK STRUCT
	dwLinkChoice DD
	UNION
		pwszUrl PTR
		Moniker SPC_SERIALIZED_OBJECT
		pwszFile PTR
	ENDUNION
ENDS

SPC_PE_IMAGE_DATA STRUCT
	Flags CRYPT_BIT_BLOB
	pFile PTR
ENDS

SPC_INDIRECT_DATA_CONTENT STRUCT
	Data CRYPT_ATTRIBUTE_TYPE_VALUE
	DigestAlgorithm CRYPT_ALGORITHM_IDENTIFIER
	Digest CRYPT_HASH_BLOB
ENDS

SPC_FINANCIAL_CRITERIA STRUCT
	fFinancialInfoAvailable DD
	fMeetsCriteria DD
ENDS

SPC_IMAGE STRUCT
	pImageLink PTR
	Bitmap CRYPT_DATA_BLOB
	Metafile CRYPT_DATA_BLOB
	EnhancedMetafile CRYPT_DATA_BLOB
	GifFile CRYPT_DATA_BLOB
ENDS

SPC_SP_AGENCY_INFO STRUCT
	pPolicyInformation PTR
	pwszPolicyDisplayText PTR
	pLogoImage PTR
	pLogoLink PTR
ENDS

SPC_STATEMENT_TYPE STRUCT
	cKeyPurposeId DD
	rgpszKeyPurposeId DD
ENDS

SPC_SP_OPUS_INFO STRUCT
	pwszProgramName PTR
	pMoreInfo PTR
	pPublisherInfo PTR
ENDS

CAT_NAMEVALUE STRUCT
	pwszTag PTR
	fdwFlags DD
	Value CRYPT_DATA_BLOB
ENDS

CAT_MEMBERINFO STRUCT
	pwszSubjGuid PTR
	dwCertVersion DD
ENDS

#define WIN_CERT_REVISION_1_0  0x0100
#define WIN_CERT_REVISION_2_0  0x0200
#define WIN_CERT_TYPE_X509  0x0001
#define WIN_CERT_TYPE_PKCS_SIGNED_DATA  0x0002
#define WIN_CERT_TYPE_RESERVED_1  0x0003
#define WIN_CERT_TYPE_TS_STACK_SIGNED  0x0004

#define WIN_TRUST_SUBJTYPE_RAW_FILE  <0x959dc450,0x8d9e,0x11cf,0x87,0x36,0x00,0xaa,0x00,0xa4,0x85,0xeb>
#define WIN_TRUST_SUBJTYPE_PE_IMAGE  <0x43c9a1e0,0x8da0,0x11cf,0x87,0x36,0x00,0xaa,0x00,0xa4,0x85,0xeb>
#define WIN_TRUST_SUBJTYPE_JAVA_CLASS  <0x08ad3990,0x8da1,0x11cf,0x87,0x36,0x00,0xaa,0x00,0xa4,0x85,0xeb>
#define WIN_TRUST_SUBJTYPE_CABINET  <0xd17c5374,0xa392,0x11cf,0x9d,0xf5,0x0,0xaa,0x0,0xc1,0x84,0xe0>
#define WIN_TRUST_SUBJTYPE_RAW_FILEEX  <0x6f458110,0xc2f1,0x11cf,0x8a,0x69,0x0,0xaa,0x0,0x6c,0x37,0x6>
#define WIN_TRUST_SUBJTYPE_PE_IMAGEEX  <0x6f458111,0xc2f1,0x11cf,0x8a,0x69,0x0,0xaa,0x0,0x6c,0x37,0x6>
#define WIN_TRUST_SUBJTYPE_JAVA_CLASSEX  <0x6f458113,0xc2f1,0x11cf,0x8a,0x69,0x0,0xaa,0x0,0x6c,0x37,0x6>
#define WIN_TRUST_SUBJTYPE_CABINETEX  <0x6f458114,0xc2f1,0x11cf,0x8a,0x69,0x0,0xaa,0x0,0x6c,0x37,0x6>
#define WIN_TRUST_SUBJTYPE_OLE_STORAGE  <0xc257e740,0x8da0,0x11cf,0x87,0x36,0x00,0xaa,0x00,0xa4,0x85,0xeb>
#define WIN_SPUB_ACTION_TRUSTED_PUBLISHER  <0x66426730,0x8da1,0x11cf,0x87,0x36,0x00,0xaa,0x00,0xa4,0x85,0xeb>
#define WIN_SPUB_ACTION_NT_ACTIVATE_IMAGE  <0x8bc96b00,0x8da1,0x11cf,0x87,0x36,0x00,0xaa,0x00,0xa4,0x85,0xeb>
#define WIN_SPUB_ACTION_PUBLISHED_SOFTWARE  <0x64b9d180,0x8da2,0x11cf,0x87,0x36,0x00,0xaa,0x00,0xa4,0x85,0xeb>

WIN_CERTIFICATE STRUCT
	dwLength DD
	wRevision DW
	wCertificateType DW
	bCertificate DB ANYSIZE_ARRAY DUP (?)
ENDS

WIN_TRUST_ACTDATA_CONTEXT_WITH_SUBJECT STRUCT
	hClientToken HANDLE
	SubjectType DD
	Subject PTR
ENDS

WIN_TRUST_ACTDATA_SUBJECT_ONLY STRUCT
	SubjectType DD
	Subject PTR
ENDS

WIN_TRUST_SUBJECT_FILE STRUCT
	hFile HANDLE
	lpPath PTR
ENDS

WIN_TRUST_SUBJECT_FILE_AND_DISPLAY STRUCT
	hFile HANDLE
	lpPath PTR
	lpDisplayName PTR
ENDS

WIN_SPUB_TRUSTED_PUBLISHER_DATA STRUCT
	hClientToken HANDLE
	lpCertificate PTR
ENDS

#define WT_TRUSTDBDIALOG_NO_UI_FLAG             0x00000001
#define WT_TRUSTDBDIALOG_ONLY_PUB_TAB_FLAG      0x00000002
#define WT_TRUSTDBDIALOG_WRITE_LEGACY_REG_FLAG  0x00000100
#define WT_TRUSTDBDIALOG_WRITE_IEAK_STORE_FLAG  0x00000200

#endif
