#IFNDEF WMIUTILS_H
#DEFINE WMIUTILS_H

#IFNDEF RPC_H
	#include "rpc.h"
#ENDIF
#IFNDEF RPCNDR_H
	#include "rpcndr.h"
#ENDIF

#ifndef COM_NO_WINDOWS_H
	#IFNDEF WINDOWS_H
		#include "windows.h"
	#ENDIF
	#IFNDEF OLE2_H
		#include "ole2.h"
	#ENDIF
#endif

#IFNDEF BASECOM_H
	#include "BaseCOM.h"
#ENDIF

WBEMPATH_INFO_ANON_LOCAL_MACHINE	= 0x1
WBEMPATH_INFO_HAS_MACHINE_NAME	= 0x2
WBEMPATH_INFO_IS_CLASS_REF	= 0x4
WBEMPATH_INFO_IS_INST_REF	= 0x8
WBEMPATH_INFO_HAS_SUBSCOPES	= 0x10
WBEMPATH_INFO_IS_COMPOUND	= 0x20
WBEMPATH_INFO_HAS_V2_REF_PATHS	= 0x40
WBEMPATH_INFO_HAS_IMPLIED_KEY	= 0x80
WBEMPATH_INFO_CONTAINS_SINGLETON	= 0x100
WBEMPATH_INFO_V1_COMPLIANT	= 0x200
WBEMPATH_INFO_V2_COMPLIANT	= 0x400
WBEMPATH_INFO_CIM_COMPLIANT	= 0x800
WBEMPATH_INFO_IS_SINGLETON	= 0x1000
WBEMPATH_INFO_IS_PARENT	= 0x2000
WBEMPATH_INFO_SERVER_NAMESPACE_ONLY	= 0x4000
WBEMPATH_INFO_NATIVE_PATH	= 0x8000
WBEMPATH_INFO_WMI_PATH	= 0x10000
WBEMPATH_INFO_PATH_HAD_SERVER	= 0x20000

WBEMPATH_CREATE_ACCEPT_RELATIVE	= 0x1
WBEMPATH_CREATE_ACCEPT_ABSOLUTE	= 0x2
WBEMPATH_CREATE_ACCEPT_ALL	= 0x4
WBEMPATH_TREAT_SINGLE_IDENT_AS_NS	= 0x8

WBEMPATH_COMPRESSED	= 0x1
WBEMPATH_GET_RELATIVE_ONLY	= 0x2
WBEMPATH_GET_SERVER_TOO	= 0x4
WBEMPATH_GET_SERVER_AND_NAMESPACE_ONLY	= 0x8
WBEMPATH_GET_NAMESPACE_ONLY	= 0x10
WBEMPATH_GET_ORIGINAL	= 0x20

WBEMPATH_TEXT	= 0x1
WBEMPATH_QUOTEDTEXT	= 0x2

#DEFINE GUID_IID_IWbemPathKeyList <0x9AE62877,0x7544,0x4bb0,<0xAA,0x26,0xA1,0x38,0x24,0x65,0x9E,0xD6>>

IWbemPathKeyList STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	GetCount PTR
	SetKey PTR
	SetKey2 PTR
	GetKey PTR
	GetKey2 PTR
	RemoveKey PTR
	RemoveAllKeys PTR
	MakeSingleton PTR
	GetInfo PTR
	GetText PTR
ENDS

#DEFINE GUID_IID_IWbemPath <0x3BC15AF2,0x736C,0x477e,<0x9E,0x51,0x23,0x8A,0xF8,0x66,0x7D,0xCC>>

IWbemPath STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	SetText PTR
	GetText PTR
	GetInfo PTR
	SetServer PTR
	GetServer PTR
	GetNamespaceCount PTR
	SetNamespaceAt PTR
	GetNamespaceAt PTR
	RemoveNamespaceAt PTR
	RemoveAllNamespaces PTR
	GetScopeCount PTR
	SetScope PTR
	SetScopeFromText PTR
	GetScope PTR
	GetScopeAsText PTR
	RemoveScope PTR
	RemoveAllScopes PTR
	SetClassName PTR
	GetClassName PTR
	GetKeyList PTR
	CreateClassPart PTR
	DeleteClassPart PTR
	IsRelative PTR
	IsRelativeOrChild PTR
	IsLocal PTR
	IsSameClassName PTR
ENDS

#DEFINE GUID_CLSID_WbemDefPath <0xcf4cc405,0xe2c5,0x4ddd,<0xb3,0xce,0x5e,0x75,0x82,0xd8,0xc9,0xfa>>

#DEFINE GUID_IID_IWbemQuery <0x81166f58,0xdd98,0x11d3,<0xa1,0x20,0x00,0x10,0x5a,0x1f,0x51,0x5a>>

IWbemQuery STRUCT
	UNION
		struct
			QueryInterface		PTR
			AddRef				PTR
			Release				PTR
		ends
		IUnknown Unknown
	ENDUNION
	Empty PTR
	SetLanguageFeatures PTR
	TestLanguageFeatures PTR
	Parse PTR
	GetAnalysis PTR
	FreeMemory PTR
	GetQueryInfo PTR
ENDS

#DEFINE GUID_CLSID_WbemQuery <0xEAC8A024,0x21E2,0x4523,<0xAD,0x73,0xA7,0x1A,0x0A,0xA2,0xF5,0x6A>>

WMIQ_ANALYSIS_RPN_SEQUENCE	= 0x1
WMIQ_ANALYSIS_ASSOC_QUERY	= 0x2
WMIQ_ANALYSIS_PROP_ANALYSIS_MATRIX	= 0x3
WMIQ_ANALYSIS_QUERY_TEXT	= 0x4
WMIQ_ANALYSIS_RESERVED	= 0x8000000

WMIQ_RPN_TOKEN_EXPRESSION	= 1
WMIQ_RPN_TOKEN_AND	= 2
WMIQ_RPN_TOKEN_OR	= 3
WMIQ_RPN_TOKEN_NOT	= 4
WMIQ_RPN_OP_UNDEFINED	= 0
WMIQ_RPN_OP_EQ	= 1
WMIQ_RPN_OP_NE	= 2
WMIQ_RPN_OP_GE	= 3
WMIQ_RPN_OP_LE	= 4
WMIQ_RPN_OP_LT	= 5
WMIQ_RPN_OP_GT	= 6
WMIQ_RPN_OP_LIKE	= 7
WMIQ_RPN_OP_ISA	= 8
WMIQ_RPN_OP_ISNOTA	= 9
WMIQ_RPN_OP_ISNULL	= 10
WMIQ_RPN_OP_ISNOTNULL	= 11
WMIQ_RPN_LEFT_PROPERTY_NAME	= 0x1
WMIQ_RPN_RIGHT_PROPERTY_NAME	= 0x2
WMIQ_RPN_CONST2	= 0x4
WMIQ_RPN_CONST	= 0x8
WMIQ_RPN_RELOP	= 0x10
WMIQ_RPN_LEFT_FUNCTION	= 0x20
WMIQ_RPN_RIGHT_FUNCTION	= 0x40
WMIQ_RPN_GET_TOKEN_TYPE	= 1
WMIQ_RPN_GET_EXPR_SHAPE	= 2
WMIQ_RPN_GET_LEFT_FUNCTION	= 3
WMIQ_RPN_GET_RIGHT_FUNCTION	= 4
WMIQ_RPN_GET_RELOP	= 5
WMIQ_RPN_NEXT_TOKEN	= 1
WMIQ_RPN_FROM_UNARY	= 0x1
WMIQ_RPN_FROM_PATH	= 0x2
WMIQ_RPN_FROM_CLASS_LIST	= 0x4
WMIQ_RPN_FROM_MULTIPLE	= 0x8

WMIQ_ASSOCQ_ASSOCIATORS	= 0x1
WMIQ_ASSOCQ_REFERENCES	= 0x2
WMIQ_ASSOCQ_RESULTCLASS	= 0x4
WMIQ_ASSOCQ_ASSOCCLASS	= 0x8
WMIQ_ASSOCQ_ROLE	= 0x10
WMIQ_ASSOCQ_RESULTROLE	= 0x20
WMIQ_ASSOCQ_REQUIREDQUALIFIER	= 0x40
WMIQ_ASSOCQ_REQUIREDASSOCQUALIFIER	= 0x80
WMIQ_ASSOCQ_CLASSDEFSONLY	= 0x100
WMIQ_ASSOCQ_KEYSONLY	= 0x200
WMIQ_ASSOCQ_SCHEMAONLY	= 0x400
WMIQ_ASSOCQ_CLASSREFSONLY	= 0x800

SWbemQueryQualifiedName stRUCT
	m_uVersion DD
	m_uTokenType DD
	m_uNameListSize DD
	m_ppszNameList PTR
	m_bArraysUsed DD
	m_pbArrayElUsed PTR
	m_puArrayIndex PTR
ENDS

SWbemRpnConst UNION
	m_pszStrVal PTR
	m_bBoolVal DD
	m_lLongVal DD
	m_uLongVal DD
	m_dblVal DOUBLE
	m_lVal64 DQ
	m_uVal64 DQ
ENDUNION

SWbemRpnQueryToken STRUCT
	m_uVersion DD
	m_uTokenType DD
	m_uSubexpressionShape DD
	m_uOperator DD
	m_pRightIdent PTR
	m_pLeftIdent PTR
	m_uConstApparentType DD
    SWbemRpnConst m_Const DD
	m_uConst2ApparentType DD
	m_Const2 DD
	m_pszRightFunc PTR
	m_pszLeftFunc PTR
ENDS

SWbemRpnTokenList STRUCT
	m_uVersion DD
	m_uTokenType DD
	m_uNumTokens DD
ENDS

WMIQ_LF1_BASIC_SELECT	= 1
WMIQ_LF2_CLASS_NAME_IN_QUERY	= 2
WMIQ_LF3_STRING_CASE_FUNCTIONS	= 3
WMIQ_LF4_PROP_TO_PROP_TESTS	= 4
WMIQ_LF5_COUNT_STAR	= 5
WMIQ_LF6_ORDER_BY	= 6
WMIQ_LF7_DISTINCT	= 7
WMIQ_LF8_ISA	= 8
WMIQ_LF9_THIS	= 9
WMIQ_LF10_COMPEX_SUBEXPRESSIONS	= 10
WMIQ_LF11_ALIASING	= 11
WMIQ_LF12_GROUP_BY_HAVING	= 12
WMIQ_LF13_WMI_WITHIN	= 13
WMIQ_LF14_SQL_WRITE_OPERATIONS	= 14
WMIQ_LF15_GO	= 15
WMIQ_LF16_SINGLE_LEVEL_TRANSACTIONS	= 16
WMIQ_LF17_QUALIFIED_NAMES	= 17
WMIQ_LF18_ASSOCIATONS	= 18
WMIQ_LF19_SYSTEM_PROPERTIES	= 19
WMIQ_LF20_EXTENDED_SYSTEM_PROPERTIES	= 20
WMIQ_LF21_SQL89_JOINS	= 21
WMIQ_LF22_SQL92_JOINS	= 22
WMIQ_LF23_SUBSELECTS	= 23
WMIQ_LF24_UMI_EXTENSIONS	= 24
WMIQ_LF25_DATEPART	= 25
WMIQ_LF26_LIKE	= 26
WMIQ_LF27_CIM_TEMPORAL_CONSTRUCTS	= 27
WMIQ_LF28_STANDARD_AGGREGATES	= 28
WMIQ_LF29_MULTI_LEVEL_ORDER_BY	= 29
WMIQ_LF30_WMI_PRAGMAS	= 30
WMIQ_LF31_QUALIFIER_TESTS	= 31
WMIQ_LF32_SP_EXECUTE	= 32
WMIQ_LF33_ARRAY_ACCESS	= 33
WMIQ_LF34_UNION	= 34
WMIQ_LF35_COMPLEX_SELECT_TARGET	= 35
WMIQ_LF36_REFERENCE_TESTS	= 36
WMIQ_LF37_SELECT_INTO	= 37
WMIQ_LF38_BASIC_DATETIME_TESTS	= 38
WMIQ_LF39_COUNT_COLUMN	= 39
WMIQ_LF40_BETWEEN	= 40
WMIQ_LF_LAST	= 40

WMIQ_RPNF_WHERE_CLAUSE_PRESENT	= 0x1
WMIQ_RPNF_QUERY_IS_CONJUNCTIVE	= 0x2
WMIQ_RPNF_QUERY_IS_DISJUNCTIVE	= 0x4
WMIQ_RPNF_PROJECTION	= 0x8
WMIQ_RPNF_FEATURE_SELECT_STAR	= 0x10
WMIQ_RPNF_EQUALITY_TESTS_ONLY	= 0x20
WMIQ_RPNF_COUNT_STAR	= 0x40
WMIQ_RPNF_QUALIFIED_NAMES_USED	= 0x80
WMIQ_RPNF_SYSPROP_CLASS_USED	= 0x100
WMIQ_RPNF_PROP_TO_PROP_TESTS	= 0x200
WMIQ_RPNF_ORDER_BY	= 0x400
WMIQ_RPNF_ISA_USED	= 0x800
WMIQ_RPNF_GROUP_BY_HAVING	= 0x1000
WMIQ_RPNF_ARRAY_ACCESS_USED	= 0x2000

SWbemRpnEncodedQuery STRUCT
	m_uVersion DD
	m_uTokenType DD
	m_uParsedFeatureMask DQ
	m_uDetectedArraySize DD
	m_puDetectedFeatures PTR
	m_uSelectListSize DD
	m_ppSelectList PTR
	m_uFromTargetType DD
	m_pszOptionalFromPath PTR
	m_uFromListSize DD
	m_ppszFromList PTR
	m_uWhereClauseSize DD
	m_ppRpnWhereClause PTR
	m_dblWithinPolling DOUBLE
	m_dblWithinWindow DOUBLE
	m_uOrderByListSize DD
	m_ppszOrderByList PTR
	m_uOrderDirectionEl PTR
ENDS

SWbemAnalysisMatrix STRUCT
	m_uVersion DD
	m_uMatrixType DD
	m_pszProperty PTR
	m_uPropertyType DD
	m_uEntries DD
	m_pValues PTR
	m_pbTruthTable PTR
ENDS

SWbemAnalysisMatrixList STRUCT
	m_uVersion DD
	m_uMatrixType DD
	m_uNumMatrices DD
	m_pMatrices PTR
ENDS

SWbemAssocQueryInf STRUCT
	m_uVersion DD
	m_uAnalysisType DD
	m_uFeatureMask DD
	m_pPath PTR
	m_pszPath PTR
	m_pszQueryText PTR
	m_pszResultClass PTR
	m_pszAssocClass PTR
	m_pszRole PTR
	m_pszResultRole PTR
	m_pszRequiredQualifier PTR
	m_pszRequiredAssocQualifier PTR
ENDS

#endif



