#ifndef WOWNT32_H
#define WOWNT32_H

#IFDEF LINKFILES
	#dynamiclinkfile Wow32.dll
#ENDIF

#define WCB16_MAX_CBARGS 16

#define WCB16_PASCAL 0
#define WCB16_CDECL 1

WOW_TYPE_HWND = 0
WOW_TYPE_HMENU = 1
WOW_TYPE_HDWP = 2
WOW_TYPE_HDROP = 3
WOW_TYPE_HDC = 4
WOW_TYPE_HFONT = 5
WOW_TYPE_HMETAFILE = 6
WOW_TYPE_HRGN = 7
WOW_TYPE_HBITMAP = 8
WOW_TYPE_HBRUSH = 9
WOW_TYPE_HPALETTE = 10
WOW_TYPE_HPEN = 11
WOW_TYPE_HACCEL = 12
WOW_TYPE_HTASK = 13
WOW_TYPE_FULLHWND = 14

#endif /* WOWNT32_H */
